import Link from "next/link";
import NavBar from "@/components/ui/NavBar";
import Footer from "@/components/ui/Footer";

export const metadata = {
  title: "Disclaimers — Abode Cost Segregation",
  description: "Important disclaimers regarding Abode Cost Segregation services.",
};

export default function DisclaimersPage() {
  const effectiveDate = "March 13, 2026";

  return (
    <>
      <NavBar />
      <main
        style={{
          paddingTop: "var(--space-16)",
          paddingBottom: "var(--space-10)",
          background: "var(--bg)",
        }}
      >
        <div className="container" style={{ maxWidth: "780px" }}>
          <div className="eyebrow" style={{ color: "var(--turq)", marginBottom: "var(--space-1)" }}>
            Legal
          </div>
          <h1 className="h1-hero" style={{ marginBottom: "var(--space-2)" }}>
            Disclaimers
          </h1>
          <p className="mono" style={{ color: "var(--dust)", marginBottom: "var(--space-6)" }}>
            Effective Date: {effectiveDate}
          </p>

          <div className="legal-content" style={{ fontSize: "14px", lineHeight: 1.8, color: "var(--ink-mid)" }}>
            {/* Prominent top-level disclaimer */}
            <div
              style={{
                background: "var(--surface)",
                border: "1px solid var(--border)",
                borderLeft: "3px solid var(--turq)",
                borderRadius: "var(--radius-md)",
                padding: "var(--space-4)",
                marginBottom: "var(--space-6)",
              }}
            >
              <p style={{ fontWeight: 600, color: "var(--ink)", marginBottom: "var(--space-2)" }}>
                Important Notice
              </p>
              <p>
                Abode Cost Segregation is a software platform that generates informational
                reports. <strong>We are not a tax advisory firm, accounting firm, engineering
                firm, or law firm. Nothing on this website or in any Abode-generated report
                constitutes tax advice, legal advice, financial advice, or professional
                engineering services.</strong> All estimates, calculations, and study outputs are
                for informational purposes only. Consult a qualified tax professional before
                making any tax-related decisions.
              </p>
            </div>

            <LegalSection title="1. No Tax Advice Disclaimer">
              <p>
                The information provided by Abode, including cost segregation studies, savings
                estimates, depreciation calculations, and all other outputs, is for
                <strong> informational purposes only and does not constitute tax advice</strong>.
                The Service is designed as a tool to assist qualified tax professionals (such as
                CPAs and tax attorneys) in preparing cost segregation analyses.
              </p>
              <p>
                You should not rely on the Service as a substitute for professional tax advice.
                Tax laws are complex, change frequently, and vary by jurisdiction. Always consult
                with a qualified Certified Public Accountant (CPA) or tax attorney before making
                tax decisions based on any information provided by the Service.
              </p>
            </LegalSection>

            <LegalSection title="2. Accuracy and Data Reliance Disclaimer">
              <p>
                <strong>
                  The accuracy of any cost segregation study generated by Abode is entirely
                  dependent on the accuracy and completeness of the information provided by the
                  User.
                </strong>
              </p>
              <p>
                Abode does not independently verify, audit, inspect, or validate any property
                data, financial information, or other details submitted by Users. We do not
                conduct physical property inspections or appraisals. The study output is a
                computational analysis based solely on User-provided inputs.
              </p>
              <p>
                If the information you provide is incomplete, inaccurate, or misleading, the
                resulting study may contain errors. Abode assumes no responsibility for errors
                in study output caused by inaccurate User-provided data.
              </p>
            </LegalSection>

            <LegalSection title="3. No Guarantee of Tax Savings">
              <p>
                <strong>
                  Abode makes no guarantee, representation, or warranty that you will achieve
                  any specific amount of tax savings from using the Service.
                </strong>
              </p>
              <p>
                Savings estimates displayed on our website (including the free estimate quiz,
                marketing materials, and sample studies) are hypothetical projections based on
                generalized assumptions. Actual tax savings depend on many factors beyond the
                scope of the Service, including but not limited to:
              </p>
              <ul>
                <li>Your specific tax situation, income, and filing status;</li>
                <li>Current and future tax laws, rates, and regulations;</li>
                <li>IRS interpretation and enforcement of depreciation rules;</li>
                <li>Bonus depreciation rates, which are subject to legislative change;</li>
                <li>The accuracy of the property data you provided;</li>
                <li>Your CPA&apos;s treatment and filing of the study.</li>
              </ul>
            </LegalSection>

            <LegalSection title="4. IRS Compliance Disclaimer">
              <p>
                While Abode&apos;s methodology is designed to follow the principles outlined in
                the IRS Cost Segregation Audit Techniques Guide (ATG), <strong>we do not
                guarantee that any study will satisfy IRS requirements or withstand an IRS
                audit or examination</strong>.
              </p>
              <p>
                The IRS has the authority to challenge, reject, or reclassify any asset
                categorization in a cost segregation study. Abode is not responsible for any
                adverse outcomes resulting from IRS review of a study generated by the Service.
              </p>
              <p>
                Abode does not provide audit defense or representation before the IRS or any
                taxing authority. If you are audited, you should seek the assistance of a
                qualified tax attorney or CPA.
              </p>
            </LegalSection>

            <LegalSection title="5. AI-Generated Content Disclaimer">
              <p>
                Abode uses artificial intelligence (AI) and machine learning algorithms to
                analyze property data and generate cost segregation classifications.
                <strong> AI-generated outputs may contain errors, omissions, or
                inaccuracies.</strong>
              </p>
              <p>
                While we strive for accuracy, AI technology has inherent limitations. The
                Service&apos;s analysis should be reviewed and validated by a qualified tax
                professional before being used for tax filing purposes. Abode makes no warranty
                regarding the accuracy, completeness, or reliability of AI-generated content.
              </p>
            </LegalSection>

            <LegalSection title="6. Methodology Disclaimer">
              <p>
                Abode&apos;s cost segregation methodology has been developed with reference to
                IRS guidelines and accepted industry practices. Our approach has been reviewed
                for methodological consistency by tax professionals with cost segregation
                experience.
              </p>
              <p>
                This review does not constitute a guarantee, certification, or endorsement by
                any individual CPA, accounting firm, or professional body. It does not guarantee
                the accuracy of any specific study output or its acceptance by the IRS.
              </p>
            </LegalSection>

            <LegalSection title="7. Earnings and Results Disclaimer">
              <p>
                Any examples of tax savings, case studies, testimonials, or projected results
                displayed on this website are illustrative only and should not be interpreted as
                a promise or guarantee of similar results. Individual results vary significantly
                based on property characteristics, tax situation, and other factors.
              </p>
            </LegalSection>

            <LegalSection title="8. Third-Party Disclaimer">
              <p>
                Abode is not affiliated with, endorsed by, or sponsored by the Internal Revenue
                Service (IRS), any state taxing authority, TurboTax, Intuit, or any other
                third-party company referenced on this website unless explicitly stated. Any
                references to third-party products, services, or guidelines are for informational
                purposes only.
              </p>
            </LegalSection>

            <LegalSection title="9. Bonus Depreciation Disclaimer">
              <p>
                Information regarding bonus depreciation rates and rules is based on current
                legislation at the time of publication. Bonus depreciation rates are subject to
                change through federal legislation. Abode is not responsible for changes in tax
                law that affect the applicability of bonus depreciation after a study has been
                generated.
              </p>
              <p>
                Users are advised to verify current bonus depreciation rates and eligibility
                with their tax professional before filing.
              </p>
            </LegalSection>

            <LegalSection title="10. Form 3115 (Change in Accounting Method) Disclaimer">
              <p>
                References to IRS Form 3115 and catch-up deductions on this website are for
                informational purposes only. Filing a change in accounting method is a complex
                tax procedure that should only be performed by or under the guidance of a
                qualified tax professional. Abode does not prepare or file Form 3115 on your
                behalf.
              </p>
            </LegalSection>

            <LegalSection title="11. Contact">
              <p>
                If you have questions about these disclaimers, please contact us at:
              </p>
              <p>
                <strong>Abode Cost Segregation</strong><br />
                Email: legal@abodecostseg.com<br />
                Support: support@abodecostseg.com
              </p>
            </LegalSection>

            <p style={{ marginTop: "var(--space-4)" }}>
              See also our{" "}
              <Link href="/terms" style={{ color: "var(--turq)" }}>Terms of Service</Link> and{" "}
              <Link href="/privacy" style={{ color: "var(--turq)" }}>Privacy Policy</Link>.
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}

function LegalSection({ title, children }) {
  return (
    <div style={{ marginBottom: "var(--space-5)" }}>
      <h2
        style={{
          fontWeight: 600,
          fontSize: "18px",
          color: "var(--ink)",
          marginBottom: "var(--space-2)",
        }}
      >
        {title}
      </h2>
      <div style={{ display: "flex", flexDirection: "column", gap: "var(--space-2)" }}>
        {children}
      </div>
    </div>
  );
}
