// City STR investment guides — Midwest region
// URL pattern: /learn/str-investing-[city]

export const cityArticlesMidwest = [

  // ─── Branson, MO ─────────────────────────────────────────────────────────
  {
    slug: "str-investing-branson-mo",
    title: "Short-Term Rental Investing in Branson, MO: Live Entertainment, Table Rock Lake, and Tax Strategy",
    description: "Branson draws 10+ million visitors annually with live entertainment shows and Table Rock Lake. Here's the complete investor guide: revenue benchmarks, cost segregation, local taxes, and STR licensing.",
    publishedAt: "2026-03-15",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Branson", "Missouri", "Table Rock Lake", "live entertainment", "cost segregation", "STR loophole"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-investing-branson-mo.jpg",
    seo: {
      title: "STR Investing in Branson, MO: Market Guide + Tax Strategy | Abode",
      description: "Branson draws 10M+ visitors for live entertainment and Table Rock Lake recreation. Here's the complete investor guide to Branson STR investing, revenue benchmarks, and cost segregation.",
      canonical: "https://www.abodecostseg.com/learn/str-investing-branson-mo",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Is Branson, MO a good market for STR investing?", acceptedAnswer: { "@type": "Answer", text: "Yes. Branson is one of the most consistent STR markets in the Midwest, driven by 10+ million annual visitors attracted by live entertainment theaters, Table Rock Lake, Silver Dollar City theme park, and the Branson Landing. The market features year-round demand (spring, summer, and fall are strong; winter is slower but Christmas shows draw visitors), low property costs relative to coastal markets, and a loyal repeat visitor base." } },
          { "@type": "Question", name: "What taxes apply to Branson STR rentals?", acceptedAnswer: { "@type": "Answer", text: "Branson STR operators pay Missouri state sales tax of 4.225%, plus Taney County and City of Branson taxes. The total transient tax on Branson STR rentals is approximately 8.475% of gross rental revenue. Missouri also has a 4.95% state income tax on net rental profits, and Missouri conforms to federal bonus depreciation." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Branson STR Quick Facts", text: "10M+ annual visitors | Live entertainment capital of the Midwest | Total lodging tax ~8.475% | Missouri 4.95% state income tax | Conforms to federal bonus depreciation | Table Rock Lake lakefront properties command premium rates" },
      { type: "paragraph", text: "Branson, Missouri is the Midwest's most unique tourism destination — a small Ozarks city that has built an entertainment empire rivaling Gatlinburg in visitor volume. Over 100 live entertainment shows, Silver Dollar City (one of America's top theme parks), Table Rock Lake's 745 miles of shoreline, and the retail/dining experience at Branson Landing attract visitors primarily from a broad Midwest catchment area. The STR market here is robust, with lower entry prices than coastal markets and a demand base that includes a large share of older, affluent Midwestern families." },
      { type: "heading", level: 2, text: "Branson Market Overview", id: "market-overview" },
      { type: "paragraph", text: "Branson's tourism economy is anchored by the entertainment strip (Highway 76) and Table Rock Lake south of town. The market has two distinct sub-markets: entertainment-proximity properties (closer to the shows, Silver Dollar City, and Branson Landing) and Table Rock Lake waterfront and lake-view properties. Lake properties command premium rates and have the best cost segregation profiles due to dock infrastructure." },
      { type: "paragraph", text: "Seasonality is moderate — Branson sees strong demand March through November, with a distinct dip in January–February. The Christmas season (shows run through December) provides a revenue boost not seen in many comparable Midwest markets. The typical booking pattern is 2–4 nights, solidly supporting the STR loophole's 7-day average stay requirement." },
      { type: "heading", level: 2, text: "Revenue Benchmarks by Property Type", id: "revenue-benchmarks" },
      { type: "table", headers: ["Property Type", "Beds/Description", "Annual Gross Revenue Range"],
        rows: [
          ["Downtown/entertainment-area condo", "1–2 BR", "$20,000–$35,000"],
          ["Condo or townhome with pool access", "2–3 BR", "$30,000–$55,000"],
          ["Cabin or house, inland", "3–4 BR with amenities", "$45,000–$80,000"],
          ["Table Rock Lake view property", "3–4 BR, lake view", "$60,000–$100,000"],
          ["Table Rock Lake waterfront with dock", "4–5 BR", "$80,000–$150,000"],
          ["Luxury lakefront estate", "5+ BR, pool, boat dock", "$120,000–$250,000+"],
        ]
      },
      { type: "heading", level: 2, text: "Cost Segregation Profile: Branson Properties", id: "cost-seg-branson" },
      { type: "paragraph", text: "Branson STR properties — particularly Table Rock Lake properties — have strong cost segregation profiles. Key reclassifiable components include: boat docks and covered slips (15-year land improvement), outdoor entertainment areas and decks (15-year), hot tubs (15-year), waterfront seawalls and riprap (15-year), furniture and vacation furnishing packages (5-year), and outdoor lighting and landscaping (15-year). Table Rock lakefront properties typically achieve 22–28% of purchase price in 5-year and 15-year assets." },
      { type: "paragraph", text: "Estimated deduction range: a $500,000 Branson lakefront property might generate $110,000–$140,000 in bonus-eligible deductions. At 37% federal + 4.95% Missouri (Missouri conforms to federal bonus depreciation), the combined first-year tax savings would be approximately $46,000–$58,600 from cost segregation alone." },
      { type: "heading", level: 2, text: "STR Loophole Applicability in Branson", id: "str-loophole" },
      { type: "paragraph", text: "Branson is highly favorable for the STR loophole. The typical guest booking is a 2–4 night entertainment getaway — family reunion, anniversary trip, or group gathering for a Branson show experience. Average stays are consistently below 7 days for well-managed Branson properties. Material participation through active management or documented oversight of day-to-day operations is generally achievable. For investors combining cost segregation deductions with the STR loophole, a Branson property can generate substantial offsetting losses against other income in Year 1." },
      { type: "heading", level: 2, text: "Local Taxes and Licensing in Branson", id: "local-taxes" },
      { type: "paragraph", text: "Branson STR operators must collect and remit Missouri state sales tax (4.225%) plus Taney County and city taxes, bringing the total transient tax to approximately 8.475%. Operators must register with the Missouri Department of Revenue. The City of Branson requires a business license for STR operations. Table Rock Lake properties may be in unincorporated Taney County rather than city limits — confirm the specific jurisdiction for your property." },
      { type: "paragraph", text: "Both Airbnb and VRBO collect and remit Missouri state sales tax on platform bookings. Local taxes are generally also collected by the platforms, but confirm the specific coverage for Taney County. Direct bookings require independent collection and remittance." },
      { type: "faq", question: "What's the best property type for STR investing in Branson?", answer: "Table Rock Lake waterfront properties with boat docks consistently produce the best combination of rental income and cost segregation deductions. The dock infrastructure, outdoor amenities, and lake-view premium create strong ADRs ($250–$600+/night in peak season) while the high personal property ratio from dock and waterfront improvements maximizes first-year deductions. Entertainment-zone condos have lower entry prices but also lower per-unit deductions." },
      { type: "cta", title: "Calculate Your Branson STR Tax Savings", text: "Branson's Table Rock Lake properties have excellent cost segregation profiles. Get your free estimate in under 2 minutes.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Lake of the Ozarks, MO ───────────────────────────────────────────────
  {
    slug: "str-investing-lake-of-the-ozarks-mo",
    title: "Short-Term Rental Investing at Lake of the Ozarks, MO: America's Boating Lake Guide",
    description: "Lake of the Ozarks has 1,150 miles of shoreline and a massive summer boating culture. Here's the complete investor guide for STR investing, revenue benchmarks, cost segregation, and tax strategy.",
    publishedAt: "2026-03-15",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Lake of the Ozarks", "Missouri", "lake cabin", "boating", "cost segregation", "STR loophole"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-investing-lake-of-the-ozarks-mo.jpg",
    seo: {
      title: "STR Investing at Lake of the Ozarks, MO: Market Guide + Tax Strategy | Abode",
      description: "Lake of the Ozarks has 1,150 miles of shoreline and extraordinary summer demand. Here's the complete investor guide: revenue benchmarks, dock-heavy cost seg profiles, and Missouri tax rules.",
      canonical: "https://www.abodecostseg.com/learn/str-investing-lake-of-the-ozarks-mo",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Is Lake of the Ozarks a good STR investment market?", acceptedAnswer: { "@type": "Answer", text: "Yes. Lake of the Ozarks is one of the Midwest's strongest lake STR markets. With 1,150 miles of shoreline — more than California's Pacific coastline — and intense summer boating culture, demand from Kansas City, St. Louis, and surrounding Midwest metros is enormous. Properties with boat docks and deep water access command the highest rates. The market is more affordable than coastal lake markets like Tahoe but generates competitive returns." } },
          { "@type": "Question", name: "What are the lodging taxes at Lake of the Ozarks?", acceptedAnswer: { "@type": "Answer", text: "Lake of the Ozarks straddles multiple counties — primarily Camden, Miller, Morgan, and Benton. Missouri state sales tax is 4.225%, and county/local taxes add 2–3% in most lake communities, bringing total transient taxes to approximately 6.5–7.5% of rental revenue. Missouri conforms to federal bonus depreciation, making cost segregation deductions fully effective at the state level." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Lake of the Ozarks STR Quick Facts", text: "1,150 miles of shoreline (more than California's entire coast) | Intense summer boating culture (Memorial Day–Labor Day peak) | Total transient taxes ~6.5–7.5% | Missouri 4.95% income tax, conforms to federal bonus dep | Dock infrastructure = strong cost seg profiles | Kansas City and St. Louis drive massive weekend demand" },
      { type: "paragraph", text: "Lake of the Ozarks is one of the most unique vacation lake destinations in the United States. Created in 1931 by the damming of the Osage River, the lake's 1,150 miles of irregular, heavily wooded shoreline creates thousands of private coves, deep water channels, and hidden inlets that make waterfront property scarce and highly prized. The lake's vibrant party cove culture, marinas, waterfront restaurants, and proximity to Kansas City (3 hours) and St. Louis (2.5 hours) drive extraordinary Memorial Day through Labor Day demand." },
      { type: "heading", level: 2, text: "Lake of the Ozarks Market Overview", id: "market-overview" },
      { type: "paragraph", text: "The lake has distinct geographic segments: the upper lake (closer to the dam and the amenity-dense Osage Beach/Lake Ozark area), the middle lake (Ha Ha Tonka area), and the lower arms. Properties in the upper lake near the Party Cove (mile marker 1) and the major marina clusters command the highest summertime rates. Deep water dockage is the most critical feature — properties without deep water boat access trade at a meaningful discount." },
      { type: "paragraph", text: "Lake of the Ozarks seasonality is pronounced — winter (November–March) is significantly slower than summer. However, many lake investors generate 70–80% of annual revenue in the 12-week Memorial Day through Labor Day window, with supplemental income from fall fishing weekends and Thanksgiving gatherings. The typical booking is 2–5 nights." },
      { type: "heading", level: 2, text: "Revenue Benchmarks by Property Type", id: "revenue-benchmarks" },
      { type: "table", headers: ["Property Type", "Beds/Description", "Annual Gross Revenue Range"],
        rows: [
          ["Basic lake cabin, no dock", "2–3 BR", "$25,000–$45,000"],
          ["Lake cabin with dock and cove access", "3–4 BR", "$50,000–$80,000"],
          ["Lakefront home with double slip dock", "4 BR, pool or hot tub", "$75,000–$130,000"],
          ["Luxury lakefront home, deep water", "4–5 BR, pool, boat garage", "$100,000–$200,000"],
          ["Estate-class lakefront, party cove adjacent", "5–6+ BR, multiple docks", "$150,000–$350,000+"],
        ]
      },
      { type: "heading", level: 2, text: "Cost Segregation Profile: Dock-Heavy Lake Properties", id: "cost-seg-lake-ozarks" },
      { type: "paragraph", text: "Lake of the Ozarks properties have among the strongest dock and marine infrastructure ratios of any inland lake market in the country. Key reclassifiable components: covered boat slips and dock platforms (15-year land improvement), boat lifts and PWC lifts (15-year), seawalls and riprap shoreline protection (15-year), outdoor decks and entertainment areas (15-year), hot tubs and outdoor pools (15-year), and furnished interior packages (5-year personal property)." },
      { type: "paragraph", text: "A well-equipped lake property at Lake of the Ozarks often achieves 25–32% of purchase price in short-life assets — higher than most inland lake markets because of the extensive boat dock infrastructure. A $600,000 lakefront property might generate $150,000–$192,000 in bonus-eligible deductions. Combined federal + Missouri state savings (Missouri conforms to federal bonus dep): $55,500–$71,000 in Year 1 at 37% federal + 4.95% state." },
      { type: "heading", level: 2, text: "STR Loophole at Lake of the Ozarks", id: "str-loophole" },
      { type: "paragraph", text: "Lake of the Ozarks is an ideal STR loophole market. Average stays are typically 2–5 nights (predominantly weekend and holiday bookings), keeping the average well below the 7-day threshold. Weekend-only bookings are common during peak season, with many guests booking 2-night Friday–Sunday stays. Material participation through active management or documented oversight is achievable. The combination of cost segregation deductions, the STR loophole, and Missouri's bonus depreciation conformity can generate large Year 1 loss deductions." },
      { type: "heading", level: 2, text: "Local Taxes and Licensing", id: "local-taxes" },
      { type: "paragraph", text: "Lake of the Ozarks straddles Camden, Miller, Morgan, and Benton counties, each with slightly different local tax rates. Missouri state sales tax is 4.225%; county taxes add 2–3%, bringing total transient taxes to approximately 6.5–7.5%. STR operators must register with the Missouri Department of Revenue. The county where your property is located may have separate registration requirements. Both Airbnb and VRBO collect and remit state and most local taxes in Missouri." },
      { type: "faq", question: "How important is deep water dock access for Lake of the Ozarks STR revenue?", answer: "Extremely important. Properties with deep water dock access (8+ feet at normal pool) capable of accommodating pontoon boats, ski boats, and jet skis command 30–50% higher rental rates than comparable properties without dock access or with shallow water. Dock size and slip count also matter — a covered double slip dock with PWC lifts justifies a significant rate premium. When evaluating Lake of the Ozarks STR purchases, dock quality and water depth are among the top revenue-determining factors." },
      { type: "cta", title: "Calculate Your Lake of the Ozarks STR Tax Savings", text: "Dock-heavy lake properties + Missouri's full bonus depreciation conformity = exceptional cost seg results. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Traverse City, MI ────────────────────────────────────────────────────
  {
    slug: "str-investing-traverse-city-mi",
    title: "Short-Term Rental Investing in Traverse City, MI: Wine Country, Cherry Orchards, and Lake Michigan",
    description: "Traverse City is Michigan's premier STR market — wine country, Sleeping Bear Dunes, and Grand Traverse Bay. Here's the complete investor guide with revenue benchmarks, cost segregation, and local taxes.",
    publishedAt: "2026-03-16",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Traverse City", "Michigan", "wine country", "Lake Michigan", "Sleeping Bear Dunes", "cost segregation", "STR loophole"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-investing-traverse-city-mi.jpg",
    seo: {
      title: "STR Investing in Traverse City, MI: Wine Country, Lake Michigan Guide | Abode",
      description: "Traverse City is Michigan's top STR market. Here's the investor guide: wine country ADR, Sleeping Bear Dunes demand, cost segregation profiles, and Michigan tax strategy.",
      canonical: "https://www.abodecostseg.com/learn/str-investing-traverse-city-mi",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Is Traverse City a good market for STR investing?", acceptedAnswer: { "@type": "Answer", text: "Yes. Traverse City is consistently ranked among the top 20 STR markets in the United States. The combination of Sleeping Bear Dunes National Lakeshore, Old Mission and Leelanau wine appellations, Grand Traverse Bay, and the National Cherry Festival drives year-round demand. Occupancy rates of 55–70% annually are achievable for well-positioned properties, with peak summer rates of $400–$900+/night for quality lakefront and wine country retreats." } },
          { "@type": "Question", name: "What are the taxes on Traverse City STR rentals?", acceptedAnswer: { "@type": "Answer", text: "Grand Traverse County STR operators pay Michigan's 6% state use tax plus approximately 5% county lodging tax, for a total of approximately 11% on rental revenue. Michigan has a 4.25% flat state income tax on net rental profits. Michigan conforms to federal bonus depreciation, so cost segregation deductions are fully effective at the state level." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Traverse City STR Quick Facts", text: "Avg ADR: $350–$800/night (peak summer) | Annual occupancy: 55–70% for quality properties | Total lodging tax ~11% | Michigan 4.25% flat income tax | Conforms to federal bonus dep | Top amenities: waterfront access, wine country proximity, Sleeping Bear Dunes access" },
      { type: "paragraph", text: "Traverse City occupies one of the most beautiful settings in the Midwest: the tip of the Old Mission Peninsula reaching into Grand Traverse Bay, surrounded by the cherry orchards and vineyards of Michigan's premier wine country. Within 30 minutes, guests can access Sleeping Bear Dunes National Lakeshore, renowned as 'The Most Beautiful Place in America' by Good Morning America viewers in 2011 — a designation that has driven a decade of explosive STR growth in the region." },
      { type: "heading", level: 2, text: "Market Overview: Multi-Season Demand", id: "market-overview" },
      { type: "paragraph", text: "Traverse City benefits from genuinely multi-season demand, which drives above-average annual occupancy compared to single-season markets. Summer (June–August) is peak season — Grand Traverse Bay swimming, Sleeping Bear Dunes hiking, and the National Cherry Festival (July) drive maximum ADRs. Fall (September–October) brings wine harvest season, fall color, and apple picking. Winter has a shoulder season with some cross-country skiing and snowshoeing demand. Spring brings the cherry blossom season (May), photographed and visited widely." },
      { type: "heading", level: 2, text: "Revenue Benchmarks by Property Type", id: "revenue-benchmarks" },
      { type: "table", headers: ["Property Type", "Beds/Description", "Annual Gross Revenue Range"],
        rows: [
          ["Downtown TC condo or apartment", "1–2 BR", "$35,000–$60,000"],
          ["Inland wine country cottage", "2–3 BR", "$50,000–$80,000"],
          ["Lake Leelanau or inland lake cottage", "3 BR with lake access", "$70,000–$110,000"],
          ["Grand Traverse Bay waterfront home", "3–4 BR, bay views", "$90,000–$150,000"],
          ["Old Mission Peninsula luxury estate", "4–5 BR, vineyard views", "$120,000–$200,000+"],
          ["Private beachfront cottage", "4 BR, private beach", "$130,000–$220,000+"],
        ]
      },
      { type: "heading", level: 2, text: "Cost Segregation Profile: Traverse City Properties", id: "cost-seg-traverse-city" },
      { type: "paragraph", text: "Traverse City STR properties have excellent cost segregation profiles, especially waterfront and wine country estate properties. Reclassifiable assets include: dock and pier systems (15-year), lakefront seawalls and landscaping (15-year), outdoor entertainment areas and pergolas (15-year), hot tubs and outdoor pools (15-year), high-end furnished interiors (5-year personal property), premium kitchen packages (5-year), and specialty wine storage and entertaining features in wine country homes." },
      { type: "paragraph", text: "Estimated deduction range: 20–28% of purchase price in short-life assets. A $750,000 Grand Traverse Bay waterfront home might generate $150,000–$210,000 in bonus-eligible deductions. At 37% federal + 4.25% Michigan state (Michigan conforms to federal bonus dep), the combined first-year tax savings would be $61,500–$86,100." },
      { type: "heading", level: 2, text: "STR Loophole in Traverse City", id: "str-loophole" },
      { type: "paragraph", text: "Traverse City's booking patterns strongly support the STR loophole. Typical stays are 3–6 nights for summer vacationers, 2–4 nights for wine country weekenders, and 2–3 nights for fall leaf-peepers. Average stays are comfortably below 7 days across all seasons. Michigan's Public Act 113 of 2023 provides additional regulatory protection for STR operators, helping ensure properties maintain their STR-eligible status." },
      { type: "heading", level: 2, text: "Local Taxes and Licensing", id: "local-taxes" },
      { type: "paragraph", text: "Grand Traverse County STR operators collect Michigan's 6% state use tax plus approximately 5% county lodging tax (total ~11%). The City of Traverse City has a separate STR registration requirement with permit fees. Township properties outside the city limits fall under Grand Traverse County township rules, which vary. Both Airbnb and VRBO collect Michigan state use tax on platform bookings." },
      { type: "faq", question: "What's the best sub-market within the Traverse City area for STR investing?", answer: "The best returns per dollar invested are often found in properties on the Old Mission Peninsula (wine country views + bay access), Leelanau Peninsula waterfront (near Sleeping Bear Dunes), and properties with private beach access on Grand Traverse Bay. Downtown Traverse City condos are lower entry prices but also lower per-night rates. The premium water/wine country combination commands the best ADR and occupancy combination." },
      { type: "cta", title: "Calculate Your Traverse City STR Tax Savings", text: "Traverse City's wine country and waterfront properties have excellent cost seg profiles. Get your free estimate in under 2 minutes.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Door County, WI ──────────────────────────────────────────────────────
  {
    slug: "str-investing-door-county-wi",
    title: "Short-Term Rental Investing in Door County, WI: The Cape Cod of the Midwest",
    description: "Door County is Wisconsin's most beloved vacation destination — 300 miles of Great Lakes shoreline, cherry orchards, and waterfront villages. Here's the complete STR investment guide.",
    publishedAt: "2026-03-17",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Door County", "Wisconsin", "Great Lakes", "Wisconsin coastal", "cost segregation", "STR loophole"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-investing-door-county-wi.jpg",
    seo: {
      title: "STR Investing in Door County, WI: Market Guide + Tax Strategy | Abode",
      description: "Door County is the Cape Cod of the Midwest with 300 miles of Great Lakes shoreline. Here's the investor guide to revenue benchmarks, Wisconsin tax issues, and cost segregation strategy.",
      canonical: "https://www.abodecostseg.com/learn/str-investing-door-county-wi",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Is Door County a good STR investment market?", acceptedAnswer: { "@type": "Answer", text: "Yes. Door County is Wisconsin's most popular tourist destination, drawing 2+ million visitors annually to its 300 miles of shoreline on Green Bay and Lake Michigan. The market has strong summer and fall demand, charming waterfront villages (Fish Creek, Ephraim, Sister Bay, Egg Harbor), and limited STR supply relative to demand. Strong annual occupancy rates of 50–65% are achievable, with peak summer ADRs of $250–$600+ for quality properties." } },
          { "@type": "Question", name: "What are the taxes for Door County STR operators?", acceptedAnswer: { "@type": "Answer", text: "Door County STR operators pay Wisconsin's 5% state sales tax plus Door County's 8% room tax, for a total of approximately 13% on rental revenue — one of the higher combined rates in the Midwest. Wisconsin does not fully conform to federal bonus depreciation, which requires bonus depreciation addback on Wisconsin state returns. Wisconsin's state income tax is 3.54–7.65% (graduated)." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Door County STR Quick Facts", text: "Avg ADR: $250–$600/night (peak summer) | Annual occupancy: 50–65% for quality properties | Total lodging tax ~13% (one of higher Midwest rates) | Wisconsin 3.54–7.65% income tax | Wisconsin does NOT conform to federal bonus dep | Top amenities: waterfront, cherry orchard views, village walkability, kayaking access" },
      { type: "paragraph", text: "Door County occupies the 70-mile-long peninsula between Green Bay and Lake Michigan — a limestone headland shaped by glaciers and etched with sea caves, cliffs, and protected coves. The 'Cape Cod of the Midwest' label is apt: like Cape Cod, Door County is a peninsula destination with charming waterfront villages, artisan culture, maritime history, and fiercely loyal return visitors who have been coming for generations. The STR market here is mature and strong." },
      { type: "heading", level: 2, text: "Door County Market Overview: Seasonal Strength", id: "market-overview" },
      { type: "paragraph", text: "Door County has a defined summer season (June–September) driven by beach and water recreation, plus a strong fall season (October) for cherry harvest, fall foliage, and harvest festivals. Winter is slow (November–March), though some operators find demand for ski-adjacent properties near Peninsula State Park cross-country trails. Spring (April–May) begins to build with flower and cherry blossom tourism." },
      { type: "paragraph", text: "The market draws primarily from Milwaukee (2.5 hours), Chicago (4 hours), and Minneapolis (5 hours). The repeat visitor rate is extraordinarily high for Door County — families return annually for the same cottage experience, creating stable advance booking patterns and high owner confidence in revenue." },
      { type: "heading", level: 2, text: "Revenue Benchmarks by Property Type", id: "revenue-benchmarks" },
      { type: "table", headers: ["Property Type", "Beds/Description", "Annual Gross Revenue Range"],
        rows: [
          ["Inland cottage or farmhouse", "2–3 BR", "$30,000–$55,000"],
          ["Village/walking-distance cottage", "2–3 BR", "$40,000–$70,000"],
          ["Green Bay waterfront cottage", "3 BR, bay views", "$60,000–$100,000"],
          ["Lake Michigan or bluff view property", "3–4 BR", "$70,000–$120,000"],
          ["Waterfront home with dock access", "4 BR, private dock", "$90,000–$160,000"],
          ["Luxury waterfront estate", "5+ BR, pool, private beach", "$140,000–$250,000+"],
        ]
      },
      { type: "heading", level: 2, text: "Cost Segregation in Door County", id: "cost-seg-door-county" },
      { type: "paragraph", text: "Door County properties have solid cost segregation profiles. Key reclassifiable components: waterfront docks and pier systems (15-year), outdoor decks and entertainment areas (15-year), boathouses (15-year), landscaping and shoreline improvements (15-year), furnished interior packages and premium decor (5-year). Properties in Door County typically achieve 18–26% of purchase price in short-life assets." },
      { type: "paragraph", text: "Important Wisconsin tax note: Wisconsin does not conform to federal bonus depreciation. The federal cost segregation deduction is fully intact, but the Wisconsin addback means higher Wisconsin taxable income in Year 1. Work with a Wisconsin CPA to model the multi-year state tax picture. The net present value of cost segregation remains strongly positive — federal savings at 37% dwarf the Wisconsin timing difference." },
      { type: "heading", level: 2, text: "STR Loophole in Door County", id: "str-loophole" },
      { type: "paragraph", text: "Door County's booking patterns are conducive to the STR loophole. Summer bookings are typically 5–7 night weekly rentals (some traditional Door County properties rent by the week), while shoulder season brings shorter 2–4 night stays. Properties with average stays between 2–6 nights qualify cleanly. Some traditional weekly rental properties may need to ensure their overall average remains below 7 days to qualify — calculate carefully if your property has significant weekly bookings." },
      { type: "heading", level: 2, text: "Local Taxes and Licensing", id: "local-taxes" },
      { type: "paragraph", text: "Door County has one of the highest room tax rates in Wisconsin at 8%, bringing total transient taxes to approximately 13% when combined with Wisconsin's 5% state sales tax. STR operators must register with the Wisconsin Department of Revenue and Door County for room tax collection. Door County municipalities (Fish Creek, Ephraim, Sister Bay) may have additional local registration requirements." },
      { type: "faq", question: "Are there STR restrictions in Door County?", answer: "Door County municipalities vary in their STR regulations. Some villages have adopted permit programs with density limits or zoning restrictions. Peninsula State Park area properties in unincorporated county land generally face lighter regulation than village-center properties. Research the specific township and municipality for your target property. Door County has seen some regulatory pressure but remains generally STR-friendly compared to urban markets." },
      { type: "cta", title: "Calculate Your Door County STR Tax Savings", text: "Door County waterfront properties have strong cost seg profiles despite Wisconsin's bonus dep limitation. Get your free federal savings estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Lake Geneva, WI ──────────────────────────────────────────────────────
  {
    slug: "str-investing-lake-geneva-wi",
    title: "Short-Term Rental Investing in Lake Geneva, WI: Chicago's Classic Lake Resort",
    description: "Lake Geneva is Chicago's premier weekend escape — 90 minutes from the city with elegant lakefront properties and high ADR. Here's the complete STR investor guide for this Wisconsin resort community.",
    publishedAt: "2026-03-17",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Lake Geneva", "Wisconsin", "Chicago lakefront", "resort market", "cost segregation", "STR loophole"],
    readTime: "7 min read",
    heroImage: "/images/blog/str-investing-lake-geneva-wi.jpg",
    seo: {
      title: "STR Investing in Lake Geneva, WI: Chicago's Lake Resort Guide | Abode",
      description: "Lake Geneva is 90 minutes from Chicago with high-value lakefront properties and strong year-round demand. Here's the complete STR investor guide for Wisconsin's classic resort community.",
      canonical: "https://www.abodecostseg.com/learn/str-investing-lake-geneva-wi",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Is Lake Geneva, WI a good STR investment market?", acceptedAnswer: { "@type": "Answer", text: "Yes. Lake Geneva has served as Chicago's lake resort since the 1870s, when Gilded Age industrialists built grand summer estates on its shores. Today the market is driven by Chicago metro residents (90 minutes away) seeking lake access, the Geneva Lake shoreline trail, luxury boutique hotels, and upscale dining. High property values ($1M–$5M+ for lakefront) support premium ADRs of $400–$1,500+/night for quality waterfront properties." } },
          { "@type": "Question", name: "What are the taxes for Lake Geneva STR operators?", acceptedAnswer: { "@type": "Answer", text: "Walworth County STR operators pay Wisconsin's 5% state sales tax plus approximately 5.5% county room tax, totaling approximately 10.5% on rental revenue. Wisconsin's graduated income tax (3.54–7.65%) applies to net rental income, and Wisconsin does not fully conform to federal bonus depreciation — an important planning consideration for investors using cost segregation." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Lake Geneva STR Quick Facts", text: "Avg ADR: $300–$1,200/night (peak season) | Year-round demand from Chicago metro (90 min) | Total lodging tax ~10.5% | Wisconsin 3.54–7.65% income tax | Wisconsin bonus dep non-conformity applies | High property values ($800K–$4M+ lakefront) → large cost seg deductions" },
      { type: "paragraph", text: "Lake Geneva (Geneva Lake) is one of Wisconsin's most iconic destinations — a clear, deep glacial lake ringed by the summer estates of Gilded Age fortunes, now transitioning to a premier modern STR market. The 26-mile shoreline trail, upscale restaurants, boutique shopping, and the iconic Geneva Lake water taxis create a distinctive resort atmosphere. The market is anchored by Chicago demand — residents who can't afford a Hamptons house find a compelling Hamptons-style experience 90 minutes from the city." },
      { type: "heading", level: 2, text: "Lake Geneva Market Overview", id: "market-overview" },
      { type: "paragraph", text: "Lake Geneva has genuine year-round demand — a differentiator from seasonal lake markets. Summer is peak season (June–August), but fall brings apple picking and wine tours, winter brings Christmas Market shopping and nearby ski (Alpine Valley, Wilmot Mountain), and spring brings early season boating. This year-round demand profile produces higher annual occupancy than comparable single-season markets." },
      { type: "paragraph", text: "The high property values in Lake Geneva — lakefront homes routinely trade at $1M–$4M+ — create very large cost segregation deduction opportunities even at moderate personal property ratios. A $2M Geneva Lake waterfront home with a 22% personal property ratio generates $440,000 in bonus-eligible deductions — extraordinary first-year federal tax savings." },
      { type: "heading", level: 2, text: "Revenue Benchmarks by Property Type", id: "revenue-benchmarks" },
      { type: "table", headers: ["Property Type", "Beds/Description", "Annual Gross Revenue Range"],
        rows: [
          ["Inland cottage (lake views, no access)", "3 BR", "$40,000–$70,000"],
          ["Lake access neighborhood property", "3–4 BR, shared beach", "$60,000–$100,000"],
          ["Canal or channel property with dock", "3–4 BR", "$75,000–$125,000"],
          ["Geneva Lake frontage, modest", "3–4 BR, private pier", "$120,000–$200,000"],
          ["Geneva Lake luxury waterfront", "5+ BR, pool, boat dock", "$180,000–$350,000+"],
        ]
      },
      { type: "heading", level: 2, text: "Cost Segregation in Lake Geneva", id: "cost-seg-lake-geneva" },
      { type: "paragraph", text: "Lake Geneva's high property values make cost segregation particularly impactful. Even at moderate personal property ratios of 18–24%, the absolute dollar values of deductions are very large. Key reclassifiable components: pier and dock systems (15-year), boat hoists and lifts (15-year), seawalls and riprap (15-year), outdoor decks, patios, and landscaping (15-year), luxury furnished interior packages (5-year), and specialty guest amenities (5-year)." },
      { type: "paragraph", text: "Wisconsin tax note: Wisconsin does not conform to federal bonus depreciation. The federal deduction is fully intact and valuable — a $440,000 federal deduction at 37% saves $162,800 in federal taxes. The Wisconsin addback increases Year 1 Wisconsin income by the excess depreciation, but this is a timing difference that self-corrects over the asset life. Work with a Wisconsin CPA to manage the multi-year state tax calculation." },
      { type: "heading", level: 2, text: "Local Taxes and Licensing", id: "local-taxes" },
      { type: "paragraph", text: "Walworth County charges a 5.5% room tax; combined with Wisconsin's 5% state sales tax, total transient taxes are approximately 10.5%. The City of Lake Geneva and surrounding municipalities have STR permit requirements. The City of Lake Geneva has adopted regulations limiting STRs in certain areas and requiring permits. Lake Geneva Township (unincorporated) has somewhat different rules. Verify the specific municipality for your target property before acquisition." },
      { type: "faq", question: "How does Lake Geneva compare to Galena, IL as a Chicago-area getaway STR market?", answer: "Lake Geneva and Galena both serve the Chicago weekend escape market, but they're distinct. Lake Geneva is primarily a lake/water recreation market with higher property values, more luxury orientation, and stronger year-round demand. Galena is a historic town in rolling hills without a large natural lake, commanding slightly lower property prices but with a strong cultural tourism and antique/arts visitor base. Lake Geneva typically generates higher ADRs but requires larger capital investment for lakefront properties." },
      { type: "cta", title: "Calculate Your Lake Geneva STR Tax Savings", text: "Lake Geneva's high property values create very large cost seg deductions even at moderate ratios. Get your free federal savings estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Boundary Waters area, MN ─────────────────────────────────────────────
  {
    slug: "str-investing-boundary-waters-mn",
    title: "Short-Term Rental Investing in the Boundary Waters Area, MN: Wilderness Cabins and Adventure Tourism",
    description: "The Boundary Waters Canoe Area gateway — centered on Ely, MN — is one of America's most unique STR markets. Here's the complete guide for wilderness cabin investing, revenue benchmarks, and Minnesota tax strategy.",
    publishedAt: "2026-03-18",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Boundary Waters", "BWCA", "Ely Minnesota", "Minnesota", "wilderness cabin", "cost segregation", "adventure tourism"],
    readTime: "7 min read",
    heroImage: "/images/blog/str-investing-boundary-waters-mn.jpg",
    seo: {
      title: "STR Investing in Boundary Waters Area, MN: Wilderness Cabin Guide | Abode",
      description: "The BWCA gateway is America's most unique wilderness STR market. Here's the investor guide to Ely-area cabins, revenue benchmarks, Minnesota tax issues, and cost segregation.",
      canonical: "https://www.abodecostseg.com/learn/str-investing-boundary-waters-mn",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Is the Boundary Waters area a good STR investment market?", acceptedAnswer: { "@type": "Answer", text: "Yes, for the right investor. The BWCA gateway (Ely, MN and surrounding Cook County) is a niche but genuine STR market with distinctive competitive advantages: access to the most visited Wilderness in North America, extraordinary natural beauty, and a loyal adventure tourism visitor base. The season is shorter than most markets (mid-May through September peak), but ADRs for quality wilderness cabin experiences can be strong. Properties serve as base camps for BWCA trips, moose spotting, fishing, and northern Minnesota wilderness experiences." } },
          { "@type": "Question", name: "What are the taxes for Boundary Waters area STR operators?", acceptedAnswer: { "@type": "Answer", text: "Cook County and St. Louis County (where most BWCA gateway properties are located) STR operators pay Minnesota's 6.875% state sales tax plus approximately 3% county lodging tax, totaling approximately 9.875%. Minnesota has the highest income tax rate in the Midwest (up to 9.85%) and does not conform to federal bonus depreciation — two significant planning considerations for BWCA area STR investors." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Boundary Waters Area STR Quick Facts", text: "BWCA is the most visited Wilderness area in North America (150,000+ permits annually) | Intense but short season: peak May–September | Total lodging tax ~9.875% | Minnesota 5.35–9.85% income tax — highest in Midwest | Minnesota does NOT conform to federal bonus dep | Wilderness cabin experiences command premium rates for the right visitor segment" },
      { type: "paragraph", text: "The Boundary Waters Canoe Area Wilderness (BWCA) is the crown jewel of the Superior National Forest in northeastern Minnesota — a million-acre roadless wilderness of 1,200+ interconnected lakes and rivers on the Canadian border. The town of Ely serves as the primary outfitter hub and gateway community. More than 150,000 entry permits are issued annually, with demand far exceeding supply. For STR investors, the BWCA gateway represents a niche but authentic market: visitors who want comfortable base camp accommodations before and after their canoe trips." },
      { type: "heading", level: 2, text: "BWCA Gateway Market Overview", id: "market-overview" },
      { type: "paragraph", text: "The BWCA area STR market is intensely seasonal. Peak season is late May through September, with the absolute prime window being late June through mid-August for canoe trippers and mid-September through early October for the extraordinary fall foliage and moose viewing season. Winter (December–March) brings snowmobiling and ice fishing demand, though at much lower volume than summer." },
      { type: "paragraph", text: "The typical BWCA-area guest spends 1–3 nights before their BWCA trip and 1 night after — a natural booking pattern that averages well under 7 days and perfectly supports the STR loophole. Fishing-focused guests (walleye and smallmouth bass fishing is world-class on the boundary waters) may book 3–7 day stays." },
      { type: "heading", level: 2, text: "Revenue Benchmarks by Property Type", id: "revenue-benchmarks" },
      { type: "table", headers: ["Property Type", "Beds/Description", "Annual Gross Revenue Range"],
        rows: [
          ["Basic cabin, no lake access", "2–3 BR", "$18,000–$35,000"],
          ["Lakefront cabin, entry-level", "2–3 BR, shared dock", "$30,000–$55,000"],
          ["Quality lakefront cabin with canoe access", "3–4 BR, private dock", "$45,000–$80,000"],
          ["Luxury wilderness retreat, BWCA-adjacent", "4 BR, full amenities", "$60,000–$110,000"],
          ["Fishing lodge with multiple cabins", "Multi-unit compound", "$80,000–$200,000+"],
        ]
      },
      { type: "heading", level: 2, text: "Cost Segregation in the Boundary Waters Area", id: "cost-seg-bwca" },
      { type: "paragraph", text: "BWCA-area properties have unique cost segregation profiles centered on wilderness and water access infrastructure. Key reclassifiable components: canoe storage and portage equipment infrastructure (5-year and 15-year), dock and boat launch systems (15-year), generator and off-grid electrical systems (5-year where not structural), sauna buildings (15-year where separate structure), and premium wilderness-theme furnishing packages (5-year)." },
      { type: "paragraph", text: "Minnesota tax note: Minnesota does not conform to federal bonus depreciation. The federal deductions are fully intact, but Minnesota requires an addback of excess bonus depreciation. With Minnesota's high top rate (9.85%), this addback can be significant in Year 1. Work with a Minnesota CPA to model the multi-year state impact. The federal benefit at 37% remains compelling regardless of the Minnesota timing difference." },
      { type: "heading", level: 2, text: "Local Taxes and Licensing", id: "local-taxes" },
      { type: "paragraph", text: "Cook County (Ely gateway area) and St. Louis County (northern reaches) both charge approximately 3% county lodging tax on top of Minnesota's 6.875% state sales tax. STR operators must register with the Minnesota Department of Revenue. Cook County is one of the more rural and regulation-light environments in Minnesota for STR operations, though local municipalities may have registration requirements." },
      { type: "faq", question: "What's the realistic return on a BWCA-area STR investment?", answer: "The BWCA market is niche and requires realistic expectations. Entry-level lakefront properties at $300,000–$500,000 might generate $45,000–$80,000 in gross annual revenue in good years, with strong years above that. The short season concentrates risk — a wet summer or challenging access conditions can significantly impact bookings. The appeal is not just financial: many BWCA-area STR owners have personal attachment to the wilderness and use the property themselves in shoulder season. Best suited for investors who also value personal use in one of America's most spectacular natural settings." },
      { type: "cta", title: "Estimate Your Boundary Waters Area STR Tax Savings", text: "BWCA wilderness properties have unique cost seg components. Get your free federal savings estimate despite Minnesota's bonus dep non-conformity.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Put-in-Bay, OH ───────────────────────────────────────────────────────
  {
    slug: "str-investing-put-in-bay-oh",
    title: "Short-Term Rental Investing in Put-in-Bay, OH: Lake Erie's Island Market Guide",
    description: "Put-in-Bay on South Bass Island is one of Ohio's most unique STR markets — an island accessible only by ferry with intense summer demand. Here's the complete investor guide.",
    publishedAt: "2026-03-19",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Put-in-Bay", "Ohio", "Lake Erie", "island STR", "South Bass Island", "cost segregation", "STR loophole"],
    readTime: "7 min read",
    heroImage: "/images/blog/str-investing-put-in-bay-oh.jpg",
    seo: {
      title: "STR Investing in Put-in-Bay, OH: Lake Erie Island Market Guide | Abode",
      description: "Put-in-Bay on South Bass Island is Ohio's most unique STR market. Here's the investor guide to island rental property investing, revenue benchmarks, and Ohio tax strategy.",
      canonical: "https://www.abodecostseg.com/learn/str-investing-put-in-bay-oh",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Is Put-in-Bay a good STR investment market?", acceptedAnswer: { "@type": "Answer", text: "Put-in-Bay has unique investment characteristics driven by its island status (accessible only by ferry or air, creating natural supply constraints), intense summer demand from Ohio and Midwest vacationers, and a distinctive party/entertainment atmosphere. The season is short (May–October), but peak summer ADRs can be exceptional. Properties with golf cart rental potential add a secondary revenue stream on the car-free island." } },
          { "@type": "Question", name: "What are the taxes for Put-in-Bay STR operators?", acceptedAnswer: { "@type": "Answer", text: "Ottawa County (where South Bass Island/Put-in-Bay is located) STR operators pay Ohio's 5.75% state sales tax plus approximately 5% Ottawa County lodging tax, totaling approximately 10.75% on rental revenue. Ohio has low graduated income taxes (max 3.75%) and conforms to federal bonus depreciation — making it one of the more tax-efficient Midwest states for STR investing." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Put-in-Bay STR Quick Facts", text: "Island accessible only by ferry from Port Clinton and Sandusky | Intense June–August season | Total lodging tax ~10.75% | Ohio max 3.75% income tax — low | Ohio conforms to federal bonus dep | Golf cart rentals provide secondary income | Limited supply due to island geography" },
      { type: "paragraph", text: "South Bass Island and its main community, Put-in-Bay, occupies a unique position in the Ohio STR market. The ferry-only access (15-20 minute ride from Port Clinton) creates natural scarcity — the island has approximately 600 year-round residents but sees tens of thousands of visitors in peak summer weeks. The mix of natural Lake Erie beauty (cave tours, fishing, water sports) and a vibrant entertainment scene (the famous PUT Bar & Grille and other venues) attracts a diverse summer visitor base." },
      { type: "heading", level: 2, text: "Put-in-Bay Market Overview", id: "market-overview" },
      { type: "paragraph", text: "Put-in-Bay's season is intensely concentrated. Memorial Day opens the season, July 4th weekend is the peak of the peak, and Labor Day closes out the high season. October can see some traffic for fall color and a few events, but most properties go quiet by November. The short season creates a unique financial model: investors must generate sufficient annual revenue in a 15–18 week window to justify year-round ownership costs." },
      { type: "paragraph", text: "Golf carts are the primary transportation on the island (no Uber, limited car access), and many STR hosts include golf cart rental in their package or partner with island rental companies. This supplemental revenue stream and guest experience differentiator is unique to island markets like Put-in-Bay." },
      { type: "heading", level: 2, text: "Revenue Benchmarks by Property Type", id: "revenue-benchmarks" },
      { type: "table", headers: ["Property Type", "Beds/Description", "Annual Gross Revenue Range"],
        rows: [
          ["Cottage or bungalow, inland", "2–3 BR", "$20,000–$40,000"],
          ["Village-area cottage", "3 BR, walkable location", "$35,000–$60,000"],
          ["Waterfront cottage, bay views", "3 BR", "$50,000–$85,000"],
          ["Lakefront property with dock", "3–4 BR, boat dock", "$70,000–$120,000"],
          ["Large gathering home", "5+ BR, entertainment area", "$90,000–$160,000"],
        ]
      },
      { type: "heading", level: 2, text: "Cost Segregation in Put-in-Bay", id: "cost-seg-put-in-bay" },
      { type: "paragraph", text: "Put-in-Bay STR properties have solid cost segregation profiles, particularly those with lake access infrastructure. Reclassifiable components include: dock and pier systems (15-year), boat lifts (15-year), outdoor entertainment areas and decks (15-year), golf cart charging and storage infrastructure (5-year), and furnished vacation rental packages (5-year personal property)." },
      { type: "paragraph", text: "Ohio's full bonus depreciation conformity means the federal and state deductions are aligned. A $450,000 South Bass Island waterfront cottage with $100,000 in bonus-eligible deductions saves approximately $37,000 federally (at 37%) plus $3,750 in Ohio state tax savings (at 3.75%) — a combined $40,750 first-year benefit." },
      { type: "heading", level: 2, text: "STR Loophole in Put-in-Bay", id: "str-loophole" },
      { type: "paragraph", text: "Put-in-Bay's booking patterns are highly favorable for the STR loophole. The typical booking is 1–4 nights — day-trippers and weekenders, not week-long vacationers. Average stays are consistently and comfortably below 7 days. The short intense season means most investors are also materially participating in management decisions throughout the busy window." },
      { type: "heading", level: 2, text: "Local Taxes and Licensing", id: "local-taxes" },
      { type: "paragraph", text: "Ottawa County charges approximately 5% lodging tax on STR rental revenue; combined with Ohio's 5.75% state sales tax, total transient taxes are approximately 10.75%. South Bass Island (Put-in-Bay) has its own village regulations for STR operations, including permit requirements. Due to the island's small, tight-knit community, compliance with local rules is particularly important for maintaining positive neighbor relations." },
      { type: "faq", question: "What are the logistics of owning an STR property on South Bass Island?", answer: "Island ownership requires planning for property management, maintenance, and guest logistics. Most owners use local property managers who understand island-specific issues. The ferry schedule (last ferry varies by season) affects check-in timing. Winter property maintenance requires understanding of island-specific utility situations and winterization. The Put-in-Bay Property Owners Association and local realtor community are good resources for island-specific ownership guidance." },
      { type: "cta", title: "Calculate Your Put-in-Bay STR Tax Savings", text: "Ohio's low income tax + full bonus dep conformity = efficient cost segregation returns for Lake Erie island properties. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Brown County, IN ─────────────────────────────────────────────────────
  {
    slug: "str-investing-brown-county-in",
    title: "Short-Term Rental Investing in Brown County, IN: Indiana's Art Colony and Forest Cabin Market",
    description: "Brown County (Nashville, IN) is Indiana's premier STR market — known for fall foliage, art galleries, state forest, and cabin rentals. Here's the complete investor guide.",
    publishedAt: "2026-03-19",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Brown County", "Nashville Indiana", "Indiana", "fall foliage", "cabin rental", "cost segregation", "STR loophole"],
    readTime: "7 min read",
    heroImage: "/images/blog/str-investing-brown-county-in.jpg",
    seo: {
      title: "STR Investing in Brown County, IN: Indiana Art Colony Cabin Guide | Abode",
      description: "Brown County is Indiana's most beloved STR market. Here's the investor guide to Nashville IN cabin investing, fall foliage demand, revenue benchmarks, and Indiana tax strategy.",
      canonical: "https://www.abodecostseg.com/learn/str-investing-brown-county-in",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Is Brown County, Indiana a good STR investment market?", acceptedAnswer: { "@type": "Answer", text: "Yes. Brown County is Indiana's most popular nature tourism destination and the state's most active STR market outside Indianapolis. The combination of Brown County State Forest (Indiana's largest), the artsy town of Nashville IN, historic covered bridges, and the most intense fall foliage in the Midwest drives strong demand from Indianapolis (60 miles), Louisville, Cincinnati, and Columbus. Annual occupancy of 50–65% is achievable for quality properties, with October (peak fall foliage) being the single highest-demand month." } },
          { "@type": "Question", name: "What are the taxes for Brown County STR operators?", acceptedAnswer: { "@type": "Answer", text: "Brown County STR operators pay Indiana's 7% state sales tax plus Brown County's 5% innkeeper's tax, totaling approximately 12% on rental revenue. Indiana has a 3.23% flat state income tax plus county income tax (Brown County residents add approximately 1.35%), and Indiana conforms to federal bonus depreciation." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Brown County STR Quick Facts", text: "Indiana's most popular nature tourism destination | Peak season: October (fall foliage — best in Indiana) | Total lodging tax ~12% | Indiana 3.23% income tax + 1.35% county income tax | Conforms to federal bonus dep | Cabin and tree house rentals with amenities command highest rates" },
      { type: "paragraph", text: "Brown County sits in the gentle hills of south-central Indiana, rising above the flatlands of the state with a topography unusual for the Midwest. The result is Indiana's most spectacular fall foliage, an art scene that has been drawing painters and craftspeople since the 1870s, and a cabin rental market that has expanded dramatically with the rise of Airbnb. Nashville, Indiana (county seat, not to be confused with Tennessee's Nashville) is a charming artisan town with galleries, antique shops, breweries, and restaurants that anchor the tourism economy." },
      { type: "heading", level: 2, text: "Brown County Market Overview", id: "market-overview" },
      { type: "paragraph", text: "Brown County's seasonality is distinctive: October is the crown jewel — fall foliage peaking in mid-to-late October drives the highest ADRs of the year, with properties often booked solid a year in advance for foliage weekend. Spring (April–May) is popular for wildflower season and the opening of outdoor activities. Summer sees steady family vacation demand from the broader Midwest. Winter is slower but some properties find Christmas getaway demand." },
      { type: "paragraph", text: "The typical Brown County booking is a 2–4 night weekend escape from Indianapolis (1 hour), Louisville (2 hours), Cincinnati (2.5 hours), or Columbus (3 hours). The market is overwhelmingly driven by drive-to tourism, not air travel. Average stays well below 7 days support the STR loophole cleanly." },
      { type: "heading", level: 2, text: "Revenue Benchmarks by Property Type", id: "revenue-benchmarks" },
      { type: "table", headers: ["Property Type", "Beds/Description", "Annual Gross Revenue Range"],
        rows: [
          ["Cozy cabin, basic amenities", "1–2 BR", "$20,000–$38,000"],
          ["Mid-range cabin, hot tub", "2–3 BR, hot tub", "$35,000–$60,000"],
          ["Quality cabin with amenities", "3 BR, hot tub, fire pit, views", "$50,000–$85,000"],
          ["Luxury treehouse or unique experience", "2–3 BR, wow factor", "$60,000–$100,000+"],
          ["Large gathering cabin", "4–5 BR, game room, fire pit", "$70,000–$130,000"],
        ]
      },
      { type: "heading", level: 2, text: "Cost Segregation Profile: Brown County Cabins", id: "cost-seg-brown-county" },
      { type: "paragraph", text: "Brown County cabin STR properties have strong cost segregation profiles driven by the high amenity density typical in this market. Key reclassifiable components: hot tubs (15-year land improvement), outdoor fire pits and gathering areas (15-year), covered decks and porches (15-year), game room equipment (5-year), cabin furnishings and decor packages (5-year personal property), and outdoor storage structures (15-year)." },
      { type: "paragraph", text: "Brown County cabins typically achieve 22–30% of purchase price in short-life assets — strong for a market without lakefront dock infrastructure. A $300,000 Brown County cabin with $75,000–$90,000 in bonus-eligible deductions generates $27,750–$33,300 in federal first-year savings at 37%, plus approximately $2,418–$2,902 in Indiana state savings at 3.23%. Indiana's full bonus depreciation conformity means the state deduction exactly mirrors the federal deduction." },
      { type: "heading", level: 2, text: "STR Loophole in Brown County", id: "str-loophole" },
      { type: "paragraph", text: "Brown County's booking patterns are ideal for the STR loophole. The vast majority of bookings are 2–4 night weekend stays. Average stays across the market consistently fall well below 7 days. Indiana's full bonus depreciation conformity means combined federal and state deductions from cost segregation and the STR loophole are clean and calculable without state-level addback complexity." },
      { type: "heading", level: 2, text: "Local Taxes and Licensing", id: "local-taxes" },
      { type: "paragraph", text: "Brown County charges a 5% innkeeper's tax on all STR rentals; combined with Indiana's 7% state sales tax, total transient taxes are approximately 12%. Brown County has STR registration requirements — operators must register with the Brown County Treasurer for innkeeper's tax collection. Both Airbnb and VRBO collect and remit state taxes on Indiana platform bookings; verify county innkeeper's tax coverage for Brown County specifically." },
      { type: "faq", question: "What amenities matter most for Brown County STR revenue?", answer: "Hot tubs are the single highest-impact amenity in Brown County — properties with hot tubs command 20–35% higher ADRs and significantly better occupancy, particularly in shoulder and winter seasons when a hot tub under the stars in the Indiana hills is a compelling draw. Fire pits and covered outdoor gathering areas are the second most important. Unique architectural elements (tree house design, massive stone fireplace, floor-to-ceiling windows with forest views) drive the premium positioning that generates $70,000–$100,000+ in annual revenue." },
      { type: "cta", title: "Calculate Your Brown County STR Tax Savings", text: "Brown County cabins with amenities have strong cost seg profiles and Indiana's full bonus dep conformity. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

];
