// Glossary articles — "What is X?" definitional pages targeting featured-snippet queries
// URL pattern: /learn/what-is-[term]

export const glossaryArticles = [

  // ─── 1. What Is Cost Segregation? ───────────────────────────────────────
  {
    slug: "what-is-cost-segregation-definition",
    title: "What Is Cost Segregation? (Plain-English Definition for Investors)",
    description: "Cost segregation is an IRS-approved tax strategy that reclassifies building components into shorter depreciation lives, accelerating deductions and reducing current-year taxes.",
    publishedAt: "2026-02-05",
    updatedAt: "2026-03-01",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "Fundamentals",
    tags: ["cost segregation", "depreciation", "STR investors", "MACRS", "bonus depreciation", "getting started"],
    readTime: "5 min read",
    heroImage: "/images/blog/what-is-cost-segregation.jpg",
    seo: {
      title: "What Is Cost Segregation? Simple Definition for Property Investors | Abode",
      description: "Cost segregation is an IRS-approved engineering study that reclassifies building components into faster depreciation categories, generating large first-year tax deductions.",
      canonical: "https://www.abodecostseg.com/learn/what-is-cost-segregation-definition",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is cost segregation?", acceptedAnswer: { "@type": "Answer", text: "Cost segregation is an engineering-based tax study that identifies and reclassifies building components from 27.5-year (residential) or 39-year (commercial) depreciation into shorter 5-year, 7-year, or 15-year categories, allowing property owners to take larger tax deductions earlier." } },
          { "@type": "Question", name: "Who benefits most from cost segregation?", acceptedAnswer: { "@type": "Answer", text: "Investors who can immediately use large depreciation deductions against ordinary income benefit most — particularly short-term rental investors using the STR loophole and investors with Real Estate Professional Status." } },
          { "@type": "Question", name: "Is cost segregation legal?", acceptedAnswer: { "@type": "Answer", text: "Yes. Cost segregation is an IRS-approved tax strategy explicitly endorsed in the IRS Audit Techniques Guide (ATG). The strategy has been upheld in numerous Tax Court cases." } },
          { "@type": "Question", name: "How much does a cost segregation study cost?", acceptedAnswer: { "@type": "Answer", text: "Engineering-based studies typically cost $3,500–$15,000 depending on property size and complexity. The ROI is typically 5–10× in year one for investors who can utilize the deductions." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "info", title: "Quick Answer", text: "Cost segregation is an IRS-approved engineering study that reclassifies building components from 27.5-year depreciation into 5-year, 7-year, and 15-year categories. The result: instead of deducting $18,000/year on a $500,000 property, you might deduct $100,000+ in year one." },
      { type: "paragraph", text: "When you buy a rental property, the IRS requires you to depreciate the building over 27.5 years (residential) or 39 years (commercial) using straight-line depreciation. This is the default accounting method — and for most property owners, it's the only method they ever use." },
      { type: "paragraph", text: "Cost segregation challenges that default. A qualified engineer physically analyzes the property — reviewing construction documents, inspection photos, purchase records, and building components — and identifies elements that legally qualify for faster depreciation under MACRS (Modified Accelerated Cost Recovery System)." },
      { type: "heading", level: 2, text: "How Cost Segregation Works", id: "how-it-works" },
      { type: "paragraph", text: "MACRS assigns different depreciation periods to different types of property. Real property (the building structure) depreciates over 27.5 or 39 years. But not everything attached to a building is real property. Personal property — assets that serve the business use of the property rather than its structural function — depreciates over 5 or 7 years. Land improvements (driveways, landscaping, outdoor amenities) depreciate over 15 years." },
      { type: "paragraph", text: "A cost segregation study identifies which components of your property fall into which category. A furnace built into the structure is real property. A portable air conditioning unit is personal property. A deck or hot tub is a 15-year land improvement. The study reclassifies as many components as possible into shorter-life categories — then, with 100% bonus depreciation (permanent under the OBBBA signed July 4, 2025), all 5-year and 7-year assets can be deducted in full in year one." },
      { type: "heading", level: 2, text: "A Simple Example", id: "example" },
      { type: "table", headers: ["Approach", "Year 1 Deduction", "Years 2–27", "Total Deduction"],
        rows: [
          ["Straight-line (no cost seg)", "$16,364", "$16,364/yr × 26.5 yrs", "$450,000"],
          ["With cost segregation + 100% bonus", "$120,000+", "Smaller ongoing deductions", "$450,000"],
        ]
      },
      { type: "paragraph", text: "The total lifetime deduction is the same — cost segregation accelerates it, concentrating deductions in year one when they're worth the most (time value of money). At a 37% tax bracket, $120,000 in year-one deductions generates approximately $44,400 in immediate tax savings." },
      { type: "heading", level: 2, text: "What Gets Reclassified", id: "what-gets-reclassified" },
      { type: "list", style: "bulleted", items: [
        "<strong>5-year property:</strong> Furniture, appliances, carpets, decorative fixtures, electronics, smart home devices",
        "<strong>15-year property:</strong> Driveways, parking areas, landscaping, pools, hot tubs, outdoor kitchens, decks",
        "<strong>27.5-year property (stays):</strong> Foundation, framing, roof, permanent HVAC, plumbing, electrical rough-in",
      ]},
      { type: "heading", level: 2, text: "Who Needs a Cost Segregation Study?", id: "who-needs-it" },
      { type: "paragraph", text: "Cost segregation is most valuable for investors who: (1) own rental property with a purchase price above $250,000, (2) have a tax strategy that allows them to use large depreciation deductions against ordinary income (the STR loophole or REPS), and (3) have a marginal federal tax rate of 24% or higher. The higher the tax rate and the larger the property, the greater the benefit." },
      { type: "heading", level: 2, text: "Frequently Asked Questions", id: "faq" },
      { type: "faq", question: "Is cost segregation the same as accelerated depreciation?", answer: "Cost segregation is the study that identifies which assets qualify for accelerated depreciation. Accelerated depreciation (via MACRS and bonus depreciation) is the tax benefit the study generates. They're related but distinct: cost seg is the means; accelerated depreciation is the result." },
      { type: "faq", question: "Can I do cost segregation on a property I've owned for years?", answer: "Yes. A look-back cost segregation study combined with Form 3115 lets you claim all missed accelerated depreciation from prior years in a single current-year deduction — without amending prior returns." },
      { type: "faq", question: "Does cost segregation trigger a tax audit?", answer: "A properly prepared cost segregation study from a qualified engineer is audit-defensible. The IRS's own Audit Techniques Guide acknowledges cost segregation as legitimate. Poorly prepared studies (software-only, no engineering support) carry more risk." },
      { type: "cta", title: "See What Your Property Could Generate", text: "Get a free cost segregation estimate for your STR in under 2 minutes. No obligation.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── 2. What Is Bonus Depreciation? ─────────────────────────────────────
  {
    slug: "what-is-bonus-depreciation",
    title: "What Is Bonus Depreciation? How It Works for Rental Property Investors",
    description: "Bonus depreciation allows investors to deduct 100% of eligible property costs in the year placed in service instead of spreading deductions over 5–15 years. Here's how it works in 2025–2026.",
    publishedAt: "2026-02-06",
    updatedAt: "2026-03-01",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "Tax Strategy",
    tags: ["bonus depreciation", "MACRS", "cost segregation", "STR investors", "depreciation", "OBBBA", "first-year deduction"],
    readTime: "5 min read",
    heroImage: "/images/blog/what-is-bonus-depreciation.jpg",
    seo: {
      title: "What Is Bonus Depreciation? 2025–2026 Rules for Rental Investors | Abode",
      description: "Bonus depreciation lets investors deduct 100% of eligible rental property components in year one. The OBBBA made 100% bonus permanent starting January 19, 2025.",
      canonical: "https://www.abodecostseg.com/learn/what-is-bonus-depreciation",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Bonus depreciation is a tax provision that allows businesses and investors to immediately deduct a percentage (currently 100%) of the cost of eligible property in the year it's placed in service, rather than depreciating it over its standard MACRS recovery period." } },
          { "@type": "Question", name: "What is the bonus depreciation rate in 2025?", acceptedAnswer: { "@type": "Answer", text: "The rate depends on when property was placed in service. For property acquired and placed in service on or after January 19, 2025 (the OBBBA effective date), the rate is 100%. For property placed in service January 1–18, 2025, the rate is 40% (the TCJA phase-down rate for 2025)." } },
          { "@type": "Question", name: "What property qualifies for bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "5-year personal property (furniture, appliances, equipment) and 15-year land improvements (driveways, landscaping, pools) qualify. Real property (the building structure, 27.5-year or 39-year) generally does not qualify, except for Qualified Improvement Property." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "info", title: "Quick Answer", text: "Bonus depreciation lets you deduct 100% of eligible rental property costs in the year you place them in service. As of January 19, 2025 (OBBBA), this 100% rate is permanent — no more phase-down schedule." },
      { type: "paragraph", text: "Standard MACRS depreciation spreads an asset's cost over its recovery period: 5 years for personal property, 15 years for land improvements. Bonus depreciation overrides that schedule, allowing the entire cost to be deducted in year one instead." },
      { type: "paragraph", text: "For a short-term rental investor, this means the furniture, appliances, carpet, outdoor improvements, and other short-life components identified in a cost segregation study can all be fully expensed in the year of acquisition — generating a deduction that might equal 20–35% of the property's purchase price." },
      { type: "heading", level: 2, text: "The 2025 Rate: Why OBBBA Changed Everything", id: "obbba-rates" },
      { type: "paragraph", text: "The Tax Cuts and Jobs Act (2017) set 100% bonus depreciation through 2022, then scheduled a phase-down: 80% in 2023, 60% in 2024, 40% in 2025, 20% in 2026, and 0% in 2027. For investors acquiring property in 2023 and 2024, this was a significant reduction from the 100% they'd enjoyed previously." },
      { type: "paragraph", text: "The One Big Beautiful Act (OBBBA), signed July 4, 2025, restored and made permanent 100% bonus depreciation. It applies to property placed in service on or after January 19, 2025 (the date of House passage). For property placed in service January 1–18, 2025, the 40% TCJA rate applies. For property placed in service in 2024, the 60% rate applies." },
      { type: "heading", level: 2, text: "What Qualifies for Bonus Depreciation", id: "what-qualifies" },
      { type: "list", style: "bulleted", items: [
        "<strong>5-year MACRS property:</strong> Furniture, appliances, carpets, electronics, decorative fixtures, smart home technology",
        "<strong>15-year MACRS property:</strong> Land improvements — driveways, pools, hot tubs, outdoor kitchens, landscaping, fencing",
        "<strong>Qualified Improvement Property (QIP):</strong> Interior improvements to nonresidential buildings placed in service after the building",
        "<strong>Does NOT qualify:</strong> Real property (the building structure) — 27.5-year residential or 39-year commercial property",
      ]},
      { type: "heading", level: 2, text: "Bonus Depreciation + Cost Segregation = Maximum Year-One Deduction", id: "combined-strategy" },
      { type: "paragraph", text: "Cost segregation identifies which components of your property qualify for bonus depreciation. Without a study, the IRS treats the entire property as 27.5-year real property — ineligible for bonus. With a study, a significant portion (20–35% of purchase price for a typical STR) gets reclassified into bonus-eligible categories." },
      { type: "paragraph", text: "The combination of cost segregation + 100% bonus depreciation is the engine of the STR tax strategy. A $600,000 STR might yield $140,000 in bonus-eligible assets via cost seg. At 100% bonus depreciation, that's $140,000 deducted in year one — vs. $21,818 under straight-line." },
      { type: "heading", level: 2, text: "Frequently Asked Questions", id: "faq" },
      { type: "faq", question: "Do I have to take bonus depreciation?", answer: "No. You can elect out of bonus depreciation on a class-by-class basis. Reasons to elect out: you have low income in year one and want to spread deductions to higher-income years, or you're in a state that doesn't conform to federal bonus depreciation (like California) and want to avoid a state tax difference." },
      { type: "faq", question: "Does bonus depreciation cause recapture when I sell?", answer: "Yes. Personal property (§1245) depreciation recapture is taxed at ordinary income rates when you sell. However, this can be deferred with a 1031 exchange, or eliminated via estate planning (step-up in basis at death). The time-value benefit of taking deductions now typically outweighs the future recapture cost." },
      { type: "faq", question: "Can I use bonus depreciation on a property I bought in a prior year?", answer: "No — bonus depreciation applies to property placed in service in the current year. For prior-year properties, you need a look-back cost segregation study with Form 3115 to capture missed accelerated depreciation via the Section 481(a) catch-up mechanism." },
      { type: "cta", title: "Maximize Your Bonus Depreciation", text: "A cost segregation study identifies all the bonus-eligible assets in your STR. Get your free estimate to see your year-one deduction.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── 3. What Is MACRS Depreciation? ─────────────────────────────────────
  {
    slug: "what-is-macrs-depreciation",
    title: "What Is MACRS Depreciation? The IRS System Explained for Property Owners",
    description: "MACRS is the IRS-required depreciation system for rental property. Learn what it is, how property classes work, and why understanding MACRS is the foundation of every cost segregation study.",
    publishedAt: "2026-02-07",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "Fundamentals",
    tags: ["MACRS", "depreciation", "cost segregation", "asset classification", "5-year property", "27.5-year property"],
    readTime: "5 min read",
    heroImage: "/images/blog/what-is-macrs-depreciation.jpg",
    seo: {
      title: "What Is MACRS Depreciation? IRS Property Depreciation Explained | Abode",
      description: "MACRS (Modified Accelerated Cost Recovery System) is the IRS-required depreciation method for rental property. Here's how it works, what the property classes are, and why it matters for investors.",
      canonical: "https://www.abodecostseg.com/learn/what-is-macrs-depreciation",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is MACRS depreciation?", acceptedAnswer: { "@type": "Answer", text: "MACRS (Modified Accelerated Cost Recovery System) is the IRS-required depreciation method for most tangible property placed in service after 1986. It assigns recovery periods (5-year, 15-year, 27.5-year, etc.) and depreciation methods to different asset types." } },
          { "@type": "Question", name: "How long do you depreciate a rental property under MACRS?", acceptedAnswer: { "@type": "Answer", text: "The building structure of a residential rental property depreciates over 27.5 years using straight-line MACRS. Commercial buildings depreciate over 39 years. However, individual components (furniture, appliances, land improvements) have shorter recovery periods of 5–15 years." } },
          { "@type": "Question", name: "What is the MACRS depreciation rate for rental property?", acceptedAnswer: { "@type": "Answer", text: "For the building structure (27.5-year residential), the annual depreciation rate is approximately 3.636%. But components identified via cost segregation as 5-year property use 200% declining balance, and 15-year land improvements use 150% declining balance — both significantly faster." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "info", title: "Quick Answer", text: "MACRS (Modified Accelerated Cost Recovery System) is the IRS's required method for depreciating property. It assigns every type of asset to a property class with a specific recovery period — 5 years, 15 years, 27.5 years, etc. Cost segregation works by correctly applying MACRS to every component of your rental." },
      { type: "paragraph", text: "Every rental property owner depreciates their property — but most do it the slow way: straight-line over 27.5 years. MACRS is actually a much more nuanced system that allows faster depreciation for many components. Understanding it is the key to understanding why cost segregation generates such large deductions." },
      { type: "heading", level: 2, text: "The MACRS Property Classes", id: "property-classes" },
      { type: "table", headers: ["Class", "Recovery Period", "Depreciation Method", "STR Examples"],
        rows: [
          ["5-year", "5 years", "200% Declining Balance", "Furniture, appliances, carpets, electronics"],
          ["7-year", "7 years", "200% Declining Balance", "Office furniture, certain equipment"],
          ["15-year", "15 years", "150% Declining Balance", "Driveways, landscaping, pools, fences, decks"],
          ["27.5-year", "27.5 years", "Straight-Line", "Residential building structure"],
          ["39-year", "39 years", "Straight-Line", "Commercial building structure"],
        ]
      },
      { type: "paragraph", text: "The key insight: when you buy a rental property, the purchase price includes components from every row of this table. A kitchen contains both real property (the walls, plumbing rough-in) and personal property (the appliances, removable cabinets). MACRS requires each component to be assigned to its correct class — but most property owners never separate them." },
      { type: "heading", level: 2, text: "GDS vs. ADS: Which System Applies?", id: "gds-vs-ads" },
      { type: "paragraph", text: "MACRS has two sub-systems: the General Depreciation System (GDS) and the Alternative Depreciation System (ADS). GDS provides faster deductions and is the default for most rental properties. ADS is required in certain situations (foreign-use property, electing-farm corporations, listed property below 50% business use, and for some qualified business income calculations)." },
      { type: "paragraph", text: "For most STR investors, GDS applies throughout. If you have a mixed-use property (personal + rental), you may need to track GDS vs. ADS separately depending on the percentage of business use." },
      { type: "heading", level: 2, text: "How Cost Segregation Uses MACRS", id: "cost-seg-and-macrs" },
      { type: "paragraph", text: "A cost segregation study is essentially a detailed engineering analysis that applies MACRS correctly to every identifiable component of your property. Instead of treating the entire $600,000 purchase price as 27.5-year real property, the study might identify $120,000 in 5-year personal property, $60,000 in 15-year land improvements, and $420,000 in 27.5-year real property." },
      { type: "paragraph", text: "With 100% bonus depreciation, the $120,000 + $60,000 = $180,000 in shorter-life property is deducted entirely in year one. The $420,000 continues at $15,272/year for 27.5 years. Without cost seg, the entire $600,000 would depreciate at $21,818/year — generating $8+ million less in early-year cash flow at a 37% tax rate." },
      { type: "heading", level: 2, text: "Frequently Asked Questions", id: "faq" },
      { type: "faq", question: "Is MACRS the same as straight-line depreciation?", answer: "No. MACRS includes straight-line depreciation as one method (used for 27.5-year and 39-year real property), but also includes declining balance methods that front-load deductions in early years. The 200% declining balance used for 5-year property is significantly faster than straight-line." },
      { type: "faq", question: "Can I choose a different depreciation method instead of MACRS?", answer: "No — MACRS is required for tangible personal property and real property placed in service after 1986. The Alternative Depreciation System (ADS) is available in some situations but also falls under the MACRS umbrella." },
      { type: "cta", title: "See MACRS Working for You", text: "A cost segregation study applies MACRS correctly to every component of your rental. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── 4. What Is Depreciation Recapture? ─────────────────────────────────
  {
    slug: "what-is-depreciation-recapture",
    title: "What Is Depreciation Recapture? What Rental Investors Owe When They Sell",
    description: "Depreciation recapture is the tax you pay on prior depreciation deductions when you sell a rental property. Here's how §1245 and §1250 recapture work, the tax rates, and how to plan around it.",
    publishedAt: "2026-02-08",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "Tax Strategy",
    tags: ["depreciation recapture", "cost segregation", "depreciation", "rental property sale", "section 1245", "section 1250", "1031 exchange"],
    readTime: "6 min read",
    heroImage: "/images/blog/what-is-depreciation-recapture.jpg",
    seo: {
      title: "What Is Depreciation Recapture? Tax Rates and Planning for Rental Investors | Abode",
      description: "When you sell a rental property, the IRS taxes prior depreciation deductions at higher rates than capital gains. Here's how §1245 and §1250 recapture work and how to minimize it.",
      canonical: "https://www.abodecostseg.com/learn/what-is-depreciation-recapture",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is depreciation recapture?", acceptedAnswer: { "@type": "Answer", text: "Depreciation recapture is a tax provision that requires you to pay tax on depreciation deductions you previously claimed when you sell a property at a gain. The recaptured amount is taxed at higher rates than standard long-term capital gains." } },
          { "@type": "Question", name: "What is the depreciation recapture tax rate?", acceptedAnswer: { "@type": "Answer", text: "Section 1245 personal property depreciation is recaptured at ordinary income rates (up to 37%). Section 1250 real property depreciation is recaptured at a maximum rate of 25% (unrecaptured §1250 gain). These are both higher than the 0–20% long-term capital gains rate on appreciation." } },
          { "@type": "Question", name: "Can you avoid depreciation recapture?", acceptedAnswer: { "@type": "Answer", text: "Yes — the most common strategies are: (1) 1031 exchange into another investment property, deferring recapture indefinitely; (2) holding until death, as a step-up in basis at death eliminates accumulated depreciation; (3) installment sale to spread recapture over multiple years." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "info", title: "Quick Answer", text: "Depreciation recapture is the tax you owe on prior depreciation deductions when you sell a rental property at a gain. Section 1245 personal property is recaptured at ordinary income rates (up to 37%). Section 1250 real property is taxed at a maximum 25% rate. Both are higher than the long-term capital gains rate on appreciation." },
      { type: "paragraph", text: "Depreciation is a tax benefit while you hold a property — it reduces your taxable income annually. But when you sell, the IRS partially \"recaptures\" those deductions by taxing them at higher rates than long-term capital gains on pure appreciation. Understanding recapture is essential for planning your exit strategy." },
      { type: "heading", level: 2, text: "Section 1245 vs. Section 1250 Recapture", id: "1245-vs-1250" },
      { type: "paragraph", text: "The IRS uses two different recapture rules depending on the type of property:" },
      { type: "table", headers: ["Property Type", "Code Section", "Recapture Rate", "Examples"],
        rows: [
          ["Personal property (5/7-yr MACRS)", "§1245", "Ordinary income (up to 37%)", "Furniture, appliances, equipment, carpets"],
          ["Land improvements (15-yr MACRS)", "§1245", "Ordinary income (up to 37%)", "Driveways, pools, landscaping"],
          ["Real property (27.5/39-yr MACRS)", "§1250", "Maximum 25%", "Building structure"],
          ["Appreciation above original cost", "§1231", "Long-term capital gains (0–20%)", "All property types"],
        ]
      },
      { type: "paragraph", text: "For investors who used cost segregation and bonus depreciation, the §1245 recapture on personal property is the most significant: furniture and appliances depreciated at 100% in year one are fully recaptured at ordinary income rates when sold. However, this recapture only applies to the depreciation actually deducted — if you hold the property long enough that the assets are fully depreciated under their MACRS lives anyway, the recapture is the same whether you accelerated or not." },
      { type: "heading", level: 2, text: "How the Numbers Work", id: "how-numbers-work" },
      { type: "paragraph", text: "Suppose you bought a property for $600,000 and took $200,000 in depreciation over several years (including a cost segregation study). You sell for $700,000 — a $100,000 gain over original cost. The IRS does not treat all of this the same way:" },
      { type: "list", style: "numbered", items: [
        "Your adjusted basis is $600,000 − $200,000 depreciation = $400,000",
        "Sale price $700,000 − adjusted basis $400,000 = $300,000 total gain",
        "Of that $300,000: $200,000 is recaptured depreciation (taxed at ordinary or 25% rates), $100,000 is appreciation (taxed at long-term capital gains rates)",
      ]},
      { type: "heading", level: 2, text: "Strategies to Minimize Recapture", id: "minimize-recapture" },
      { type: "list", style: "bulleted", items: [
        "<strong>1031 exchange:</strong> Exchange into another investment property and defer all recapture and gain indefinitely",
        "<strong>Hold until death:</strong> A step-up in basis at death eliminates all accumulated depreciation — recapture never triggers",
        "<strong>Installment sale:</strong> Spread the gain over multiple years to smooth the tax impact",
        "<strong>Opportunity Zone reinvestment:</strong> Roll proceeds into a Qualified Opportunity Fund to defer and potentially reduce gain",
        "<strong>Loss harvesting:</strong> Coordinate the sale year with capital losses elsewhere to offset recapture income",
      ]},
      { type: "heading", level: 2, text: "Does Cost Segregation Make Recapture Worse?", id: "cost-seg-and-recapture" },
      { type: "paragraph", text: "This is the most common objection to cost segregation. The answer depends on your situation. If you plan to hold long-term or 1031 exchange, cost segregation does not increase your lifetime tax burden — it accelerates deductions into earlier years where they compound. If you sell in year 2 without a 1031 exchange, you'll pay ordinary-income-rate recapture on the full bonus depreciation amount taken." },
      { type: "paragraph", text: "For investors with a long hold period and a 1031 exchange strategy, cost segregation is almost always net positive. For investors planning to sell outright within 2 years, the calculation requires more careful analysis." },
      { type: "faq", question: "Is depreciation recapture the same as capital gains tax?", answer: "No. Capital gains tax applies to appreciation above your original cost. Depreciation recapture applies to the portion of your gain that represents previously deducted depreciation. They're calculated separately and at different rates." },
      { type: "cta", title: "Plan Your Cost Segregation Strategy", text: "Understanding recapture is part of a complete cost segregation analysis. Get your free estimate — we'll show you both the upside and the full tax picture.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── 5. What Is Passive Activity Loss? ──────────────────────────────────
  {
    slug: "what-is-passive-activity-loss",
    title: "What Is a Passive Activity Loss? Why It Matters for Rental Investors",
    description: "Passive activity loss rules determine whether you can deduct rental losses against your W-2 income or must carry them forward. Here's how they work and how STR investors get around them.",
    publishedAt: "2026-02-09",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "Fundamentals",
    tags: ["passive activity rules", "passive income", "rental losses", "STR loophole", "REPS", "cost segregation", "material participation"],
    readTime: "5 min read",
    heroImage: "/images/blog/what-is-passive-activity-loss.jpg",
    seo: {
      title: "What Is a Passive Activity Loss? Rental Property Loss Rules Explained | Abode",
      description: "Passive activity loss rules limit when you can deduct rental losses against W-2 income. Here's how the rules work, who they apply to, and how STR investors legally work around them.",
      canonical: "https://www.abodecostseg.com/learn/what-is-passive-activity-loss",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is a passive activity loss?", acceptedAnswer: { "@type": "Answer", text: "A passive activity loss is a loss from a trade or business in which you don't materially participate — including most rental activities by default. Under IRC §469, passive losses can only offset passive income; they cannot reduce wages, salary, or other active income." } },
          { "@type": "Question", name: "Can I deduct rental losses against my W-2 income?", acceptedAnswer: { "@type": "Answer", text: "Not automatically. By default, rental losses are passive and can only offset passive income. However, short-term rental investors who materially participate can use the STR loophole to make losses active. Investors with Real Estate Professional Status can also deduct unlimited rental losses against any income." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "info", title: "Quick Answer", text: "Passive activity loss rules (IRC §469) prevent most rental losses from offsetting W-2 wages or other active income. Rental losses are passive by default — they can only offset passive income or carry forward to future years. STR investors can escape this limitation through the STR loophole or REPS." },
      { type: "paragraph", text: "When a rental property generates a loss — from depreciation, mortgage interest, repairs, and other expenses exceeding rental income — the tax treatment depends entirely on whether that loss is \"passive\" or \"active.\" Most investors assume all rental losses are freely deductible. They're not." },
      { type: "heading", level: 2, text: "The Passive Activity Loss Rules (IRC §469)", id: "pal-rules" },
      { type: "paragraph", text: "Congress enacted the passive activity loss rules in 1986 to prevent high-income taxpayers from using rental real estate losses as a tax shelter against wages. Under §469, a passive activity loss can only offset passive activity income. Passive losses in excess of passive income are suspended — they carry forward to future years until you either generate passive income or sell the property." },
      { type: "paragraph", text: "All rental activities are passive by default under §469(c)(2), regardless of how much time you spend managing them — with two exceptions: the STR tax loophole and Real Estate Professional Status." },
      { type: "heading", level: 2, text: "The $25,000 Rental Loss Allowance", id: "rental-loss-allowance" },
      { type: "paragraph", text: "There is a partial exception for small investors. If you actively participate in a rental activity (a lower standard than material participation — basically just making management decisions), you can deduct up to $25,000 in rental losses against ordinary income. But this allowance phases out at modified AGI between $100,000 and $150,000, and is completely eliminated above $150,000. For most investors pursuing cost segregation, income is too high to benefit from this allowance." },
      { type: "heading", level: 2, text: "Two Ways STR Investors Escape PAL Rules", id: "escaping-pal-rules" },
      { type: "paragraph", text: "<strong>1. The STR Tax Loophole:</strong> Short-term rental properties where the average guest stay is 7 days or fewer are not classified as rental activities under Reg. §1.469-1T(e)(3). They're treated as active trade or business income. When you materially participate, the losses are active — fully deductible against W-2 wages and other income." },
      { type: "paragraph", text: "<strong>2. Real Estate Professional Status (REPS):</strong> Under §469(c)(7), investors who spend 750+ hours in real property trades or businesses — more than half their working time — can make all rental activities non-passive, deducting losses against any income without limit." },
      { type: "heading", level: 2, text: "Why This Matters for Cost Segregation", id: "why-it-matters" },
      { type: "paragraph", text: "Cost segregation generates large depreciation deductions. But those deductions are only immediately valuable if you can use them. An investor subject to PAL rules who generates $150,000 in rental losses from cost segregation sees none of that benefit in year one — the losses simply accumulate as a passive loss carryforward." },
      { type: "paragraph", text: "The STR loophole and REPS are what convert a passive carryforward into an immediate check from the Treasury. This is why the strategic sequence matters: establish your loss-utilization pathway first, then commission the cost segregation study." },
      { type: "faq", question: "What happens to suspended passive losses when I sell?", answer: "When you dispose of the passive activity entirely in a fully taxable sale, all suspended passive losses become deductible in the year of sale — they can offset any income, including ordinary income." },
      { type: "cta", title: "Make Your Depreciation Deductions Work", text: "Cost segregation + the right tax strategy = immediate savings. Get your free estimate and see your numbers.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── 6. What Is REPS? ────────────────────────────────────────────────────
  {
    slug: "what-is-real-estate-professional-status",
    title: "What Is Real Estate Professional Status (REPS)? The Key to Unlimited Rental Loss Deductions",
    description: "Real Estate Professional Status is an IRS designation that allows qualifying investors to deduct unlimited rental losses against any income. Here's what it is, who qualifies, and how to use it.",
    publishedAt: "2026-02-10",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "IRS Compliance",
    tags: ["REPS", "real estate professional", "passive activity", "rental losses", "material participation", "750 hours"],
    readTime: "5 min read",
    heroImage: "/images/blog/what-is-real-estate-professional-status.jpg",
    seo: {
      title: "What Is Real Estate Professional Status (REPS)? | Abode",
      description: "REPS (Real Estate Professional Status) under §469(c)(7) lets qualifying investors deduct unlimited rental losses against any income. Here's the two-part test and who qualifies.",
      canonical: "https://www.abodecostseg.com/learn/what-is-real-estate-professional-status",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is Real Estate Professional Status?", acceptedAnswer: { "@type": "Answer", text: "Real Estate Professional Status (REPS) is an IRS designation under §469(c)(7) that removes the passive activity classification from rental activities for qualifying investors. To qualify, you must spend more than 750 hours in real property trades or businesses in which you materially participate, and those hours must exceed hours spent in all other trades or businesses." } },
          { "@type": "Question", name: "What are the requirements for REPS?", acceptedAnswer: { "@type": "Answer", text: "Two tests: (1) More than 750 hours during the year in real property trades or businesses where you materially participate; (2) Real property hours exceed hours in all other trades or businesses. Both tests must be met every year." } },
          { "@type": "Question", name: "Can my spouse qualify for REPS?", acceptedAnswer: { "@type": "Answer", text: "Yes. On a joint return, if either spouse individually qualifies for REPS, the couple can deduct unlimited rental losses. The qualifying spouse must meet both tests on their own — hours cannot be combined between spouses." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "info", title: "Quick Answer", text: "Real Estate Professional Status (REPS) under IRC §469(c)(7) removes the passive activity classification from rentals for qualifying investors. Requirements: 750+ hours in real estate activities + real estate as your primary occupation by hours. Result: unlimited rental losses deductible against any income, including W-2 wages." },
      { type: "paragraph", text: "By default, all rental income and losses are passive under the tax code. Passive losses can only offset passive income — they cannot reduce your salary or wages. For high-income investors with large depreciation deductions from cost segregation, this means the deductions sit in carryforward, providing no immediate benefit." },
      { type: "paragraph", text: "REPS changes that. When you qualify, your rental activities are reclassified as active trade or business activities. Combined with material participation in each rental, the losses become fully deductible against any income — W-2, business income, interest, anything." },
      { type: "heading", level: 2, text: "The Two-Part REPS Test", id: "two-part-test" },
      { type: "list", style: "numbered", items: [
        "<strong>750-hour test:</strong> You must spend more than 750 hours during the tax year in real property trades or businesses in which you materially participate. Qualifying activities: development, construction, acquisition, conversion, rental, operation, management, leasing, and brokerage of real property.",
        "<strong>Majority-of-services test:</strong> Your real property hours must exceed hours spent in all other trades or businesses during the year. This is what disqualifies most full-time employees — their job hours typically exceed their real estate hours.",
      ]},
      { type: "callout", variant: "warning", title: "Both Tests Required Every Year", text: "REPS is not permanent. You must qualify anew each tax year by meeting both tests. If you fail to qualify in a given year, rental losses revert to passive for that year." },
      { type: "heading", level: 2, text: "REPS vs. the STR Tax Loophole", id: "reps-vs-str" },
      { type: "paragraph", text: "REPS and the STR loophole are two different mechanisms for making rental losses active. REPS works for any rental property including long-term rentals. The STR loophole only works for properties with average stays of 7 days or fewer. REPS requires 750+ hours of real estate activity; the STR loophole typically requires 100–500 hours of self-management per property." },
      { type: "paragraph", text: "For investors with long-term rentals, REPS is the only pathway. For STR investors who can't meet REPS requirements (due to a full-time job), the STR loophole is the more accessible alternative." },
      { type: "heading", level: 2, text: "Documentation Requirements", id: "documentation" },
      { type: "paragraph", text: "REPS is one of the most audited tax positions in real estate. The IRS specifically targets high-income taxpayers claiming REPS because it's a common abuse point. Contemporaneous hour logs — maintained throughout the year, not reconstructed at tax time — are essential. Logs should include specific dates, activities, and hours, corroborated by emails, invoices, and booking records." },
      { type: "faq", question: "Does REPS apply if I use a property manager?", answer: "Using a property manager doesn't automatically disqualify you from REPS, but it makes material participation harder to prove. Hours spent overseeing the property manager, reviewing financials, making strategic decisions, and performing maintenance can count — but passive investment oversight typically doesn't." },
      { type: "cta", title: "Combine REPS with Cost Segregation", text: "REPS makes large depreciation deductions immediately valuable. Get your free estimate to see your year-one savings.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── 7. What Is Material Participation? ─────────────────────────────────
  {
    slug: "what-is-material-participation",
    title: "What Is Material Participation? The 7 IRS Tests Explained",
    description: "Material participation determines whether a rental or business activity is passive or active for tax purposes. Here are the 7 IRS tests and how STR investors typically qualify.",
    publishedAt: "2026-02-11",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "Fundamentals",
    tags: ["material participation", "passive activity rules", "STR loophole", "REPS", "rental losses", "IRS tests"],
    readTime: "5 min read",
    heroImage: "/images/blog/what-is-material-participation.jpg",
    seo: {
      title: "What Is Material Participation? The 7 IRS Tests for Rental Investors | Abode",
      description: "Material participation under IRC §469 determines if rental activity losses are deductible against ordinary income. Here are the 7 tests and which ones STR investors most commonly use.",
      canonical: "https://www.abodecostseg.com/learn/what-is-material-participation",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is material participation?", acceptedAnswer: { "@type": "Answer", text: "Material participation is an IRS standard that determines whether you're actively involved enough in a business or rental activity for its losses to be deductible against ordinary income. Under Reg. §1.469-5T, there are 7 tests — meeting any one of them satisfies material participation for that activity." } },
          { "@type": "Question", name: "How many hours is material participation for a rental?", acceptedAnswer: { "@type": "Answer", text: "The most common test requires more than 500 hours of participation in the activity (Test 1). However, for STR investors, Test 3 is often easier to satisfy: you participate more hours than any other person in the activity. For a self-managed STR with no full-time property manager, 100–200 hours may satisfy this test." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "info", title: "Quick Answer", text: "Material participation means you're actively involved enough in an activity that its losses are treated as active (not passive). The IRS has 7 tests — meeting any one qualifies you. For STR investors, the most commonly used test is Test 3: more hours than any other person in the activity." },
      { type: "paragraph", text: "Material participation is the gatekeeper between passive losses (stuck in carryforward) and active losses (immediately deductible against any income). For STR investors using the STR loophole, material participation is what converts a paper loss from cost segregation into a check from the IRS." },
      { type: "heading", level: 2, text: "The 7 Material Participation Tests (Reg. §1.469-5T)", id: "seven-tests" },
      { type: "table", headers: ["Test", "Requirement", "Best For"],
        rows: [
          ["Test 1", "500+ hours of participation in the activity during the year", "Investors with significant hands-on time"],
          ["Test 2", "Participation constitutes substantially all participation by anyone", "Single-owner properties with no staff"],
          ["Test 3", "100+ hours AND more hours than any other individual", "Self-managed STRs — most common for STR investors"],
          ["Test 4", "Significant participation activity (100–500 hrs) AND all significant participation activities total 500+ hrs", "Investors with multiple activities"],
          ["Test 5", "Material participation in any 5 of the prior 10 years", "Established investors with track record"],
          ["Test 6", "Material participation in any 3 prior years (personal service activity only)", "Rarely applies to rental real estate"],
          ["Test 7", "Based on facts and circumstances — regular, continuous, and substantial involvement", "Last resort; rarely accepted by IRS"],
        ]
      },
      { type: "heading", level: 2, text: "How STR Investors Typically Qualify (Test 3)", id: "test-3" },
      { type: "paragraph", text: "Test 3 is the most accessible for self-managing STR investors: you must participate more than 100 hours in the activity AND more than any other person. For a property managed directly by the owner — where no property manager logs more hours than the owner — 100–200 hours of documented self-management typically satisfies this test." },
      { type: "paragraph", text: "Qualifying activities include: managing guest communications and bookings, overseeing cleaning and maintenance, purchasing supplies, conducting property inspections, handling repairs, managing pricing and listings, and handling financial recordkeeping. Passive oversight (reviewing bank statements, reading reports) typically doesn't count." },
      { type: "callout", variant: "warning", title: "Document Everything Contemporaneously", text: "Material participation must be proven with contemporaneous records maintained throughout the year. Year-end reconstructions from memory have been repeatedly rejected by the Tax Court. Keep a running log with specific dates, activities, and durations." },
      { type: "heading", level: 2, text: "Material Participation vs. REPS", id: "vs-reps" },
      { type: "paragraph", text: "Material participation and REPS are related but distinct. REPS is a threshold qualification — once met, it removes the passive classification from all real property activities. But even REPS investors must materially participate in each rental activity (or make the grouping election) for losses from that activity to be active." },
      { type: "paragraph", text: "For STR investors, REPS isn't required — the STR loophole handles the non-passive classification. Material participation (typically Test 3) is what's needed to activate the loophole." },
      { type: "faq", question: "Does hiring a property manager mean I can't materially participate?", answer: "Not automatically. You can still materially participate even with a property manager, as long as your hours exceed the property manager's hours in the activity. If the property manager works 800 hours/year and you work 200, you don't satisfy Test 3. If you work 600 hours and they work 400, you do." },
      { type: "cta", title: "Qualify + Deduct with Cost Segregation", text: "Material participation turns your cost segregation deductions into real tax savings. Get your free estimate today.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── 8. What Is the STR Tax Loophole? ───────────────────────────────────
  {
    slug: "what-is-the-str-tax-loophole",
    title: "What Is the STR Tax Loophole? The Rule That Makes Short-Term Rentals So Tax-Efficient",
    description: "The STR tax loophole lets short-term rental investors deduct paper losses from cost segregation against their W-2 income. Here's the exact IRS rule, who qualifies, and how to use it.",
    publishedAt: "2026-02-12",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR loophole", "short-term rental", "passive activity rules", "material participation", "cost segregation", "rental losses", "W-2 income"],
    readTime: "5 min read",
    heroImage: "/images/blog/what-is-the-str-tax-loophole.jpg",
    seo: {
      title: "What Is the STR Tax Loophole? How Short-Term Rentals Beat the Passive Activity Rules | Abode",
      description: "The STR tax loophole (Reg. §1.469-1T) lets qualifying short-term rental investors deduct paper losses from depreciation against W-2 income. Here's how it works and who qualifies.",
      canonical: "https://www.abodecostseg.com/learn/what-is-the-str-tax-loophole",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is the STR tax loophole?", acceptedAnswer: { "@type": "Answer", text: "The STR tax loophole refers to Reg. §1.469-1T(e)(3)(ii)(A), which excludes short-term rental properties (average guest stay ≤ 7 days) from the passive activity 'rental activity' classification. When the property qualifies AND you materially participate, losses are active — deductible against W-2 wages without limit." } },
          { "@type": "Question", name: "What are the requirements for the STR tax loophole?", acceptedAnswer: { "@type": "Answer", text: "Two requirements: (1) The average period of customer use is 7 days or fewer (calculated across all rentals in the tax year); (2) You materially participate in the short-term rental activity. Meeting both makes the activity non-passive." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "info", title: "Quick Answer", text: "The STR tax loophole is a provision in IRS Regulation §1.469-1T that excludes short-term rentals (average stay ≤ 7 days) from the passive activity rules when you materially participate. The result: depreciation losses from cost segregation offset your W-2 wages directly, generating five- and six-figure tax savings." },
      { type: "paragraph", text: "Most rental property losses are passive — limited to offsetting other passive income. But short-term rentals with average stays of 7 days or fewer aren't classified as \"rental activities\" under the IRS passive activity regulations. They're treated as active trade or business activities. When you're actively involved in managing the property, any losses (including large paper losses from depreciation) become active and deductible against any income." },
      { type: "heading", level: 2, text: "The Exact IRS Rule", id: "irs-rule" },
      { type: "paragraph", text: "Regulation §1.469-1T(e)(3)(ii)(A) states that an activity is NOT a rental activity if \"the average period of customer use for such property is 7 days or less.\" A rental activity subject to the passive rules is one where customers use property for an average of 8+ days. Fall below that threshold and you're outside the rental activity passive presumption." },
      { type: "paragraph", text: "This is not a loophole in the pejorative sense — it's a deliberate feature of the passive activity regulations that recognizes that short-term hospitality businesses (like hotels) are active businesses, not passive investments. The rule simply classifies your Airbnb or VRBO appropriately." },
      { type: "heading", level: 2, text: "The Two Requirements", id: "requirements" },
      { type: "list", style: "numbered", items: [
        "<strong>Average stay ≤ 7 days:</strong> Calculated as total rental days divided by total number of rentals. A property with 180 rented nights across 40 bookings has a 4.5-day average stay — well below the threshold.",
        "<strong>Material participation:</strong> You must actively participate in the activity. The most common test: you participate more than any other person in the activity (Reg. §1.469-5T(a)(3)). For self-managed properties, 100–300 hours of documented involvement typically satisfies this.",
      ]},
      { type: "heading", level: 2, text: "How Cost Segregation Amplifies the Loophole", id: "with-cost-seg" },
      { type: "paragraph", text: "The STR loophole alone doesn't generate tax savings — it just makes the activity non-passive. The large deductions come from cost segregation. A $600,000 STR with a cost segregation study might generate $130,000+ in year-one depreciation. Without the STR loophole, that's a passive carryforward. With the loophole and material participation, it's a $130,000 deduction against your salary, potentially saving $48,000+ in federal taxes." },
      { type: "heading", level: 2, text: "Common Mistakes", id: "common-mistakes" },
      { type: "list", style: "bulleted", items: [
        "<strong>Relying on a full-service property manager:</strong> If your property manager has more hours in the activity than you do, you fail material participation Test 3",
        "<strong>Long-term rentals mixed in:</strong> Booking a guest for 30 days raises your average stay; know your average stay at all times",
        "<strong>Poor documentation:</strong> The IRS can challenge material participation without contemporaneous records",
        "<strong>Conflating the loophole with REPS:</strong> The STR loophole is a property-level classification; REPS is a taxpayer-level qualification. They work differently",
      ]},
      { type: "faq", question: "Does the STR loophole apply to long-term rentals?", answer: "No. The average stay threshold must be 7 days or fewer. Standard long-term rentals with monthly tenants have average stays of 30+ days — they're rental activities subject to passive rules. Only short-term rentals with average stays ≤ 7 days qualify." },
      { type: "cta", title: "Use the Loophole to Its Full Potential", text: "The STR loophole + cost segregation = the most powerful tax strategy available to rental investors. Get your free savings estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── 9. What Is Form 3115? ───────────────────────────────────────────────
  {
    slug: "what-is-form-3115",
    title: "What Is Form 3115? The IRS Form That Unlocks Catch-Up Depreciation",
    description: "Form 3115 (Application for Change in Accounting Method) allows investors to retroactively reclassify property and claim all missed accelerated depreciation in a single year. Here's how it works.",
    publishedAt: "2026-02-13",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "IRS Compliance",
    tags: ["form 3115", "catch-up depreciation", "cost segregation", "section 481a", "look-back study", "accounting method change"],
    readTime: "5 min read",
    heroImage: "/images/blog/what-is-form-3115.jpg",
    seo: {
      title: "What Is Form 3115? Catch-Up Depreciation and Accounting Method Changes | Abode",
      description: "Form 3115 lets rental investors retroactively claim missed accelerated depreciation from prior years in a single current-year deduction. Here's how the process works.",
      canonical: "https://www.abodecostseg.com/learn/what-is-form-3115",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is Form 3115?", acceptedAnswer: { "@type": "Answer", text: "Form 3115 (Application for Change in Accounting Method) is an IRS form that allows taxpayers to change their depreciation method. When used with a retroactive cost segregation study, it enables investors to claim all missed accelerated depreciation from prior years as a single deduction in the current year — without amending prior returns." } },
          { "@type": "Question", name: "What is the Section 481(a) adjustment?", acceptedAnswer: { "@type": "Answer", text: "The Section 481(a) adjustment is the catch-up amount generated by a Form 3115 accounting method change. It equals the difference between depreciation that should have been taken under the new method versus what was actually taken under the old method. For cost segregation, this is the sum of all missed accelerated depreciation from prior years." } },
          { "@type": "Question", name: "Do I need to amend prior returns to do a look-back cost segregation study?", acceptedAnswer: { "@type": "Answer", text: "No. That's the key advantage of Form 3115. You do not amend prior returns. Instead, the entire catch-up deduction is taken in the current tax year as a single line item on Schedule E (or Form 8825). This is a significant administrative advantage over amended returns." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "info", title: "Quick Answer", text: "Form 3115 lets you retroactively claim all missed cost segregation deductions from prior years in a single current-year deduction — no amended returns required. You file it with your current-year tax return and take a lump-sum Section 481(a) catch-up adjustment." },
      { type: "paragraph", text: "If you bought a rental property in a prior year and never did a cost segregation study, you haven't missed your chance. Form 3115 (Application for Change in Accounting Method) is the IRS's mechanism for retroactively correcting a suboptimal depreciation method — and the result is a single large deduction in the current year." },
      { type: "heading", level: 2, text: "Why You Don't Have to Amend Returns", id: "no-amendments" },
      { type: "paragraph", text: "When you bought your rental property, the IRS assigned you a default depreciation method: straight-line over 27.5 years. Cost segregation is a change from that default to accelerated MACRS depreciation for individual components. The IRS treats this as a change in accounting method, not a correction of an error." },
      { type: "paragraph", text: "Changes in accounting method are handled via Form 3115, not amended returns. The entire cumulative benefit of switching methods — all the depreciation you should have taken in prior years but didn't — flows into your current-year return as a single deduction called the Section 481(a) adjustment." },
      { type: "heading", level: 2, text: "The Look-Back Study Process", id: "look-back-process" },
      { type: "list", style: "numbered", items: [
        "<strong>Commission a retroactive cost segregation study:</strong> An engineer analyzes the property back to its purchase date, reclassifying components and calculating what MACRS depreciation you should have taken each year.",
        "<strong>Calculate the Section 481(a) adjustment:</strong> The engineer computes the difference between depreciation taken (straight-line) and depreciation that should have been taken (MACRS + bonus). This gap is the catch-up amount.",
        "<strong>Prepare Form 3115:</strong> Your CPA completes Form 3115 requesting IRS consent to change accounting method. Most cost segregation changes qualify for automatic consent (no prior IRS approval needed).",
        "<strong>File with current-year return:</strong> Form 3115 attaches to your current-year return; a copy goes directly to the IRS service center. The catch-up deduction appears on Schedule E.",
        "<strong>Take the deduction:</strong> The full Section 481(a) catch-up amount is deductible in the current tax year — even if it represents 5, 10, or more years of missed depreciation.",
      ]},
      { type: "heading", level: 2, text: "Is There a Statute of Limitations?", id: "statute-of-limitations" },
      { type: "paragraph", text: "There is no statute of limitations on cost segregation look-back studies. Whether you bought the property 2 years ago or 15 years ago, you can do a retroactive study and file Form 3115 to claim the catch-up. However, practical considerations matter: properties held very long term may have had significant assets already fully depreciated, reducing the catch-up benefit." },
      { type: "faq", question: "What if my property already has cost seg from a previous study?", answer: "If a prior study missed some assets or used less rigorous methodology, you can do a supplemental study and file Form 3115 for the additional reclassifications. This is less common but valid in situations where the original study was software-only or incomplete." },
      { type: "cta", title: "Claim Missed Depreciation From Prior Years", text: "If you bought your STR without a cost segregation study, a look-back study can recover years of missed deductions. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── 10. What Is Depreciation? ──────────────────────────────────────────
  {
    slug: "what-is-depreciation-rental-property",
    title: "What Is Depreciation on a Rental Property? A Simple Guide for New Investors",
    description: "Depreciation lets rental property investors deduct the cost of the property over time, reducing taxable income annually. Here's how it works, how it's calculated, and why it's the foundation of rental property tax strategy.",
    publishedAt: "2026-02-14",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "Fundamentals",
    tags: ["depreciation", "rental property", "MACRS", "cost segregation", "getting started", "Schedule E", "taxable income"],
    readTime: "5 min read",
    heroImage: "/images/blog/what-is-depreciation-rental-property.jpg",
    seo: {
      title: "What Is Rental Property Depreciation? A Simple Explanation for Investors | Abode",
      description: "Rental property depreciation is an annual tax deduction that reduces your taxable income without requiring cash outlay. Here's how it works, how to calculate it, and how cost segregation accelerates it.",
      canonical: "https://www.abodecostseg.com/learn/what-is-depreciation-rental-property",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is depreciation on a rental property?", acceptedAnswer: { "@type": "Answer", text: "Depreciation is an annual tax deduction that allows rental property owners to recover the cost of the property over its useful life. For a residential rental property, the IRS allows depreciation over 27.5 years. It's a non-cash deduction — it reduces your taxable income without requiring any cash outlay in the year you claim it." } },
          { "@type": "Question", name: "How much depreciation can I take on a rental property?", acceptedAnswer: { "@type": "Answer", text: "For a standard residential rental, annual depreciation = (purchase price − land value) ÷ 27.5 years. For a $500,000 property with $50,000 land value, that's $450,000 ÷ 27.5 = $16,364/year. With cost segregation, a much larger portion can be depreciated in year one." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "info", title: "Quick Answer", text: "Depreciation is an annual tax deduction for the gradual \"wearing out\" of your rental property. For residential rentals, the IRS lets you deduct 1/27.5 of the building value each year — with no cash outlay. It's the single largest recurring deduction most rental investors have." },
      { type: "paragraph", text: "Depreciation is the tax code's recognition that physical assets wear out over time. A building's roof will eventually need replacement. Appliances wear out. Carpets get stained. Rather than waiting until those items actually fail, the IRS lets you deduct a portion of the property's value each year as a \"depreciation\" expense — even if you haven't spent a dollar on repairs." },
      { type: "heading", level: 2, text: "How Rental Property Depreciation Is Calculated", id: "how-calculated" },
      { type: "paragraph", text: "The formula is simple: (Purchase Price − Land Value) ÷ 27.5 years = Annual Depreciation. Land cannot be depreciated because it doesn't wear out. You must allocate a portion of the purchase price to land (typically based on the assessed value ratio on your property tax bill) and depreciate only the building value." },
      { type: "table", headers: ["Property Value", "Land Allocation (15%)", "Depreciable Basis", "Annual Deduction"],
        rows: [
          ["$300,000", "$45,000", "$255,000", "$9,273/yr"],
          ["$500,000", "$75,000", "$425,000", "$15,455/yr"],
          ["$750,000", "$112,500", "$637,500", "$23,182/yr"],
          ["$1,000,000", "$150,000", "$850,000", "$30,909/yr"],
        ]
      },
      { type: "heading", level: 2, text: "Why Depreciation Is So Powerful", id: "why-powerful" },
      { type: "paragraph", text: "Depreciation is a non-cash deduction. You don't write a check for it — it just reduces your taxable income on paper. For a rental property generating $30,000/year in net rental income, $15,000/year in depreciation reduces your taxable rental income by half. At a 32% tax rate, that's $4,800 in taxes you don't pay — every year, for 27.5 years." },
      { type: "paragraph", text: "For properties with enough depreciation to exceed rental income, the excess loss flows through to your tax return (subject to passive activity rules). This is where cost segregation becomes transformative — by accelerating depreciation into year one, a single year's deduction can exceed the property's annual rental income many times over." },
      { type: "heading", level: 2, text: "Where Depreciation Goes on Your Tax Return", id: "on-tax-return" },
      { type: "paragraph", text: "Rental income and expenses — including depreciation — are reported on Schedule E (Supplemental Income and Loss) attached to your Form 1040. Depreciation appears as a line item expense, reducing your net rental income (or increasing your rental loss). The depreciation is calculated on Form 4562 and flows to Schedule E." },
      { type: "heading", level: 2, text: "Cost Segregation: Accelerating Depreciation", id: "cost-seg-acceleration" },
      { type: "paragraph", text: "Standard straight-line depreciation over 27.5 years is just the default. Cost segregation reclassifies components of the property into shorter-life categories (5-year and 15-year) that depreciate faster — and with 100% bonus depreciation, qualify for full first-year deduction. The result: instead of $15,000/year for 27.5 years, you might take $130,000 in year one." },
      { type: "faq", question: "Do I have to take depreciation on my rental property?", answer: "The IRS requires you to reduce your basis by depreciation 'allowed or allowable' — even if you forget to take it. If you sell the property without having claimed depreciation, the IRS still treats that depreciation as if you took it (and taxes you on recapture). Always take your depreciation deductions." },
      { type: "cta", title: "Accelerate Your Depreciation with Cost Segregation", text: "Stop taking $15,000/year when you could take $130,000 in year one. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── 11. What Is a 1031 Exchange? ───────────────────────────────────────
  {
    slug: "what-is-1031-exchange-rental-property",
    title: "What Is a 1031 Exchange? How Rental Investors Defer Taxes at Sale",
    description: "A 1031 exchange lets rental property investors defer all capital gains and depreciation recapture taxes when they sell, by reinvesting into a like-kind property. Here's how it works.",
    publishedAt: "2026-02-15",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "Tax Strategy",
    tags: ["1031 exchange", "depreciation recapture", "cost segregation", "rental property", "capital gains", "tax strategy", "STR investing"],
    readTime: "6 min read",
    heroImage: "/images/blog/what-is-1031-exchange.jpg",
    seo: {
      title: "What Is a 1031 Exchange? How to Defer Taxes When Selling a Rental | Abode",
      description: "A 1031 exchange lets investors defer capital gains and depreciation recapture taxes indefinitely by reinvesting sale proceeds into a like-kind property. Here's the process and rules.",
      canonical: "https://www.abodecostseg.com/learn/what-is-1031-exchange-rental-property",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is a 1031 exchange?", acceptedAnswer: { "@type": "Answer", text: "A 1031 exchange (named after IRC §1031) allows investors to defer capital gains tax and depreciation recapture when selling an investment property by reinvesting the proceeds into a like-kind replacement property. The tax is deferred — not eliminated — until you eventually sell without exchanging." } },
          { "@type": "Question", name: "What are the 1031 exchange deadlines?", acceptedAnswer: { "@type": "Answer", text: "You must identify replacement property within 45 days of closing the relinquished property sale. You must close on the replacement property within 180 days of the sale. Both deadlines are strict — no extensions except in presidentially declared disasters." } },
          { "@type": "Question", name: "Can I 1031 exchange a short-term rental property?", acceptedAnswer: { "@type": "Answer", text: "Yes, with caveats. An STR qualifies as 'held for investment' if it meets IRC §1031 requirements. The IRS has provided safe harbor guidance (Rev. Proc. 2008-16) for vacation rental properties: held at least 24 months, rented at fair market rent for at least 14 days per year, and personal use not exceeding the greater of 14 days or 10% of rental days." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "info", title: "Quick Answer", text: "A 1031 exchange lets you sell a rental property and defer 100% of capital gains and depreciation recapture taxes by reinvesting into a like-kind property. It's the most powerful tax deferral tool for real estate investors — and it's also the primary reason why cost segregation's accelerated depreciation doesn't need to be feared at sale time." },
      { type: "paragraph", text: "When you sell a rental property, two types of tax typically apply: long-term capital gains on appreciation (0–20%), and depreciation recapture on all deductions taken (up to 25% for §1250, up to 37% for §1245). For a property that's been significantly depreciated via cost segregation, this recapture can be substantial." },
      { type: "paragraph", text: "A 1031 exchange defers both taxes entirely — indefinitely, if you keep exchanging. The sale proceeds roll into the new property, your basis carries over (adjusted), and the tax bill keeps getting pushed into the future." },
      { type: "heading", level: 2, text: "The Key Rules", id: "key-rules" },
      { type: "list", style: "bulleted", items: [
        "<strong>Like-kind property:</strong> Any real property held for investment or business use qualifies — you can exchange an STR for a commercial building, apartment complex, or another STR",
        "<strong>45-day identification window:</strong> Must identify potential replacement properties within 45 days of closing the sale",
        "<strong>180-day closing window:</strong> Must close on the replacement property within 180 days of the sale",
        "<strong>Qualified intermediary required:</strong> You cannot touch the proceeds — a QI holds them between transactions",
        "<strong>Equal or greater value:</strong> To defer 100% of gain, the replacement property must be equal to or greater in value than the relinquished property",
      ]},
      { type: "heading", level: 2, text: "1031 Exchange + Cost Segregation: The Strategy", id: "with-cost-seg" },
      { type: "paragraph", text: "The combination of cost segregation and 1031 exchanges is the foundation of the most sophisticated STR tax strategies. It works like this: (1) Buy property, do cost segregation in year one, generate large deductions against current income; (2) Hold the property for several years collecting depreciation benefits; (3) 1031 exchange into a new property, deferring all accumulated recapture; (4) Repeat on the new property." },
      { type: "paragraph", text: "Each exchange resets the clock. Depreciation recapture from aggressive cost segregation on property A transfers to property B's basis — but you've collected years of tax savings in the interim. And if you hold the final property until death, a step-up in basis at death eliminates all accumulated recapture for your heirs." },
      { type: "heading", level: 2, text: "Can You 1031 Exchange an STR?", id: "str-1031" },
      { type: "paragraph", text: "Yes, with planning. IRS Rev. Proc. 2008-16 provides a safe harbor for vacation rental properties: the property must be held for at least 24 months, rented at fair market rate for at least 14 days per year, and personal use limited to the greater of 14 days or 10% of rental days. STRs that meet these criteria are clearly \"held for investment\" and qualify for §1031 exchange treatment." },
      { type: "faq", question: "What happens to my depreciation basis after a 1031 exchange?", answer: "Your carryover basis from the relinquished property transfers to the replacement property. This means you have a lower basis on the new property, and your depreciation deductions are smaller going forward — but a new cost segregation study on the replacement property can accelerate depreciation on the portion of the basis that represents the replacement property value above the carryover." },
      { type: "cta", title: "Build Your Long-Term STR Tax Strategy", text: "Cost segregation and 1031 exchanges work together. Get your free estimate and see what your year-one savings look like.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── 12. What Is the QBI Deduction? ─────────────────────────────────────
  {
    slug: "what-is-qbi-deduction-rental",
    title: "What Is the QBI Deduction for Rental Property? The §199A Deduction Explained",
    description: "The QBI deduction (§199A) may allow STR investors to deduct 20% of their qualified business income from short-term rental activities. Here's how it works and when rental properties qualify.",
    publishedAt: "2026-02-16",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "Tax Strategy",
    tags: ["QBI deduction", "section 199A", "STR investors", "rental property", "tax strategy", "pass-through deduction"],
    readTime: "6 min read",
    heroImage: "/images/blog/what-is-qbi-deduction.jpg",
    seo: {
      title: "QBI Deduction for Rental Property: How §199A Works for STR Investors | Abode",
      description: "The §199A QBI deduction may allow STR investors to deduct 20% of net rental income. Here's when short-term rentals qualify, the income limits, and how to maximize the deduction.",
      canonical: "https://www.abodecostseg.com/learn/what-is-qbi-deduction-rental",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is the QBI deduction for rental property?", acceptedAnswer: { "@type": "Answer", text: "The QBI deduction under §199A allows owners of pass-through businesses to deduct up to 20% of qualified business income. For rental property to qualify, it generally must rise to the level of a trade or business under IRC §162. Short-term rentals that qualify as active trade or business activities (under the STR loophole or via REPS) are more likely to qualify than passive long-term rentals." } },
          { "@type": "Question", name: "Do short-term rentals qualify for the QBI deduction?", acceptedAnswer: { "@type": "Answer", text: "STRs are more likely to qualify than long-term rentals because they're active trade or business activities (not passive rental activities under the passive activity rules). The IRS has not issued definitive guidance specific to STRs, but many practitioners argue — and some IRS guidance suggests — that active STR activities constitute a §162 trade or business." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "info", title: "Quick Answer", text: "The §199A QBI deduction lets owners of pass-through businesses deduct up to 20% of qualified business income. For STR investors whose rental activity qualifies as a trade or business, this is a second major deduction on top of depreciation — but it's subject to income limits and W-2 wage/capital limitations at higher incomes." },
      { type: "paragraph", text: "The Tax Cuts and Jobs Act (2017) created the §199A qualified business income (QBI) deduction for pass-through entities — sole proprietorships, partnerships, S-corps, and LLCs taxed as pass-throughs. The deduction is generally 20% of qualified business income, subject to limitations." },
      { type: "heading", level: 2, text: "Does Rental Income Qualify as QBI?", id: "rental-and-qbi" },
      { type: "paragraph", text: "This is where it gets complicated. The QBI deduction applies to income from a \"qualified trade or business\" under §162. Passive rental activities generally do not constitute a trade or business under §162 — they're investments, not businesses. However, activities that rise to the level of a business (significant services, active management, short-term rentals) may qualify." },
      { type: "paragraph", text: "For STR investors: because the STR tax loophole treats the rental activity as a non-passive trade or business activity, many practitioners argue that it simultaneously qualifies as a §162 trade or business for QBI purposes. There's also IRS Revenue Procedure 2019-38, which provides a safe harbor for certain rental real estate to qualify as a §162 trade or business for QBI deduction purposes." },
      { type: "heading", level: 2, text: "The Income Limitations", id: "income-limits" },
      { type: "paragraph", text: "Below the threshold income ($197,300 single / $394,600 married filing jointly for 2025), the QBI deduction is straightforwardly 20% of QBI. Above these thresholds, the deduction begins to phase in W-2 wage and qualified property limitations that can reduce the deduction significantly for capital-intensive businesses with few employees." },
      { type: "paragraph", text: "For high-income STR investors (above the threshold), the deduction is limited to the greater of: (1) 50% of W-2 wages paid by the business, or (2) 25% of W-2 wages + 2.5% of the unadjusted basis of qualified property. Since most individual STR operators pay no W-2 wages, the qualified property limitation (2.5% of property basis) often applies." },
      { type: "heading", level: 2, text: "Interaction with Cost Segregation", id: "interaction-with-cost-seg" },
      { type: "paragraph", text: "Cost segregation reduces QBI (because depreciation deductions reduce net income). For investors in the phase-in range or who rely on the W-2/property limitation, a large depreciation deduction from cost segregation might reduce QBI to near zero in year one — eliminating the QBI deduction in that year. This is a planning consideration, not a reason to avoid cost segregation: the depreciation savings typically dwarf any QBI deduction lost." },
      { type: "faq", question: "Is the QBI deduction still available in 2025?", answer: "The QBI deduction was extended as part of the OBBBA (signed July 4, 2025). The deduction continues at the 20% rate for qualified business income from pass-through entities and qualifying rental activities." },
      { type: "cta", title: "Maximize All Your Deductions", text: "A good tax strategy captures both cost segregation deductions and the QBI deduction. Get your free estimate to see your complete savings picture.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── 13. What Is Section 179? ────────────────────────────────────────────
  {
    slug: "what-is-section-179-rental-property",
    title: "What Is Section 179? And Why Rental Property Investors Usually Use Bonus Depreciation Instead",
    description: "Section 179 lets businesses immediately expense certain assets instead of depreciating them. But for rental property investors, bonus depreciation is usually more valuable. Here's why.",
    publishedAt: "2026-02-17",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "Fundamentals",
    tags: ["section 179", "bonus depreciation", "MACRS", "cost segregation", "depreciation", "rental property"],
    readTime: "5 min read",
    heroImage: "/images/blog/what-is-section-179.jpg",
    seo: {
      title: "What Is Section 179? Section 179 vs Bonus Depreciation for Rental Property | Abode",
      description: "Section 179 and bonus depreciation both allow immediate expensing of assets. Here's how they differ, the limitations of §179 for rental investors, and why bonus depreciation is usually the better choice.",
      canonical: "https://www.abodecostseg.com/learn/what-is-section-179-rental-property",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is Section 179?", acceptedAnswer: { "@type": "Answer", text: "Section 179 of the tax code allows businesses to immediately expense (deduct in full) the cost of eligible property in the year it's placed in service, subject to annual limits. For 2025, the §179 deduction limit is $1.16 million with a phase-out beginning at $2.9 million in total property acquisitions." } },
          { "@type": "Question", name: "Can I use Section 179 on rental property?", acceptedAnswer: { "@type": "Answer", text: "Section 179 has a key limitation for rental investors: the deduction is limited to taxable income from active trade or business activities. Passive rental income does not count. As a result, §179 typically cannot create or increase a rental loss — limiting its utility compared to bonus depreciation, which has no income limitation." } },
          { "@type": "Question", name: "Is Section 179 or bonus depreciation better for rental property?", acceptedAnswer: { "@type": "Answer", text: "Bonus depreciation is generally better for rental property investors because: (1) it has no income limitation (can create losses), (2) it applies automatically without an election, and (3) it's not limited by active income. Section 179 is more valuable for operating businesses (not rentals) where the income limitation isn't an issue." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "info", title: "Quick Answer", text: "Section 179 allows immediate expensing of eligible business property, but has a critical limitation for rental investors: it can't create a rental loss. Bonus depreciation has no income limitation and can generate large losses. For most STR investors, bonus depreciation via cost segregation is the better tool." },
      { type: "paragraph", text: "Section 179 is often discussed alongside bonus depreciation as a way to accelerate deductions. Both allow immediate expensing of eligible assets. But they work differently — and for rental property investors, the differences usually favor bonus depreciation." },
      { type: "heading", level: 2, text: "Section 179 vs. Bonus Depreciation: Key Differences", id: "179-vs-bonus" },
      { type: "table", headers: ["Feature", "Section 179", "Bonus Depreciation"],
        rows: [
          ["Annual limit (2025)", "$1.16M (phases out above $2.9M)", "No limit"],
          ["Can create a loss?", "No — limited to active business income", "Yes — unlimited loss creation"],
          ["Eligible property", "New and used personal property, QIP", "New and used property (certain categories)"],
          ["Election required?", "Yes — must elect §179", "No — applies automatically unless elected out"],
          ["Carry forward unused amount?", "Yes", "No — must take it or elect out"],
          ["Works with passive rentals?", "No — limited by active income", "Yes — but losses may be passive"],
        ]
      },
      { type: "paragraph", text: "The critical row is 'Can create a loss?' Section 179 deductions are limited to taxable income from active trade or business activities. Rental income — even for STR investors using the STR loophole — may not qualify as the type of active income that supports §179. Bonus depreciation has no such limitation: it can generate large losses that offset any income (if you have the STR loophole or REPS in place)." },
      { type: "heading", level: 2, text: "When Section 179 Is Useful for Rental Investors", id: "when-179-useful" },
      { type: "paragraph", text: "Section 179 can be useful for rental investors who: (1) have an S-corp or other business entity with significant active income, (2) want to expense specific assets like a vehicle used in rental operations, or (3) have rental income exceeding rental losses such that §179's income limitation isn't binding." },
      { type: "paragraph", text: "For most STR investors pursuing the aggressive year-one deduction strategy with cost segregation, bonus depreciation is the right tool. It's automatic, unlimited, and can create offsetting losses against W-2 income." },
      { type: "faq", question: "Can I use both Section 179 and bonus depreciation on the same property?", answer: "Yes, in some situations. You can apply §179 first, then take bonus depreciation on any remaining basis. But for rental investors, this is rarely the optimal approach — bonus depreciation alone typically captures the full benefit more simply." },
      { type: "cta", title: "Maximize Your First-Year Deduction", text: "Cost segregation with bonus depreciation is the standard strategy for STR investors. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── 14. What Is Net Investment Income Tax? ─────────────────────────────
  {
    slug: "what-is-niit-rental-property",
    title: "What Is the Net Investment Income Tax (NIIT)? How It Affects Rental Investors",
    description: "The 3.8% net investment income tax (NIIT) applies to passive rental income for high-income investors. Here's how it works, when it applies, and how STR investors can avoid it.",
    publishedAt: "2026-02-18",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "Tax Strategy",
    tags: ["NIIT", "net investment income tax", "passive income", "STR investors", "rental property", "tax strategy"],
    readTime: "5 min read",
    heroImage: "/images/blog/what-is-niit.jpg",
    seo: {
      title: "What Is the Net Investment Income Tax (NIIT) for Rental Property? | Abode",
      description: "The 3.8% NIIT applies to net investment income including passive rental income for high earners. STR investors who use the STR loophole or REPS can potentially avoid it entirely.",
      canonical: "https://www.abodecostseg.com/learn/what-is-niit-rental-property",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is the net investment income tax?", acceptedAnswer: { "@type": "Answer", text: "The net investment income tax (NIIT) under §1411 is a 3.8% surtax on net investment income for taxpayers with modified AGI above $200,000 (single) or $250,000 (married filing jointly). Passive rental income is included in net investment income; active rental income (STR loophole or REPS) is not." } },
          { "@type": "Question", name: "Does the STR loophole eliminate the NIIT?", acceptedAnswer: { "@type": "Answer", text: "When the STR loophole or REPS makes rental activity non-passive, rental income is active income — not investment income subject to NIIT. This means STR investors who meet material participation requirements potentially avoid the 3.8% NIIT on their rental income, a significant additional benefit beyond the depreciation deductions." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "info", title: "Quick Answer", text: "The NIIT is a 3.8% surtax on net investment income (including passive rental income) for taxpayers with AGI above $200,000 (single) or $250,000 (married). STR investors who use the STR loophole or REPS convert rental income from passive to active — avoiding NIIT entirely on that income." },
      { type: "paragraph", text: "The Affordable Care Act (2010) imposed a 3.8% net investment income tax on high-income taxpayers. For rental property investors, passive rental income falls squarely in the NIIT's crosshairs — adding a 3.8% surcharge on top of ordinary income taxes on net passive rental income." },
      { type: "heading", level: 2, text: "What Income Is Subject to NIIT?", id: "what-is-subject" },
      { type: "paragraph", text: "Net investment income includes: interest, dividends, capital gains, rents from passive activities, and income from passive trade or business activities. The key word: passive. Active income — wages, self-employment income, active business income — is not subject to NIIT." },
      { type: "paragraph", text: "For rental investors, the distinction is critical. Passive rental income (from long-term rentals without REPS) is subject to NIIT. Active rental income (from STRs with material participation, or any rental with REPS) is not." },
      { type: "heading", level: 2, text: "The NIIT Threshold and Calculation", id: "niit-threshold" },
      { type: "table", headers: ["Filing Status", "MAGI Threshold", "Tax Rate", "Applied To"],
        rows: [
          ["Single", "$200,000", "3.8%", "Lesser of NII or MAGI above threshold"],
          ["Married Filing Jointly", "$250,000", "3.8%", "Lesser of NII or MAGI above threshold"],
          ["Married Filing Separately", "$125,000", "3.8%", "Lesser of NII or MAGI above threshold"],
        ]
      },
      { type: "paragraph", text: "Example: A married couple with $300,000 in MAGI ($250,000 in wages + $50,000 in passive rental income) would owe NIIT on the lesser of (a) their NII ($50,000 in passive rent) or (b) $50,000 ($300,000 − $250,000 threshold). The NIIT = $50,000 × 3.8% = $1,900." },
      { type: "heading", level: 2, text: "How the STR Loophole Eliminates NIIT on Rental Income", id: "str-eliminates-niit" },
      { type: "paragraph", text: "When STR rental income is active (non-passive) because of the STR loophole or REPS, it is not included in net investment income. The 3.8% NIIT does not apply. For an investor generating $100,000/year in STR income with an active classification, avoiding NIIT saves $3,800/year — not transformative by itself, but meaningful as part of the overall tax picture." },
      { type: "paragraph", text: "More significantly, cost segregation losses from an active STR reduce active income rather than passive income — potentially reducing MAGI below the NIIT threshold entirely in the year of the study." },
      { type: "faq", question: "Does depreciation from cost segregation reduce NIIT liability?", answer: "For active STR investors, cost segregation losses reduce active income (not NII), so they don't directly offset NIIT on other passive income. However, if cost segregation losses reduce overall MAGI below the threshold, NIIT is eliminated entirely. The interaction depends on your specific income mix." },
      { type: "cta", title: "See Your Complete Tax Savings Picture", text: "NIIT avoidance is one more benefit of the STR loophole + cost segregation strategy. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── 15. What Is a Cost Basis? ──────────────────────────────────────────
  {
    slug: "what-is-cost-basis-rental-property",
    title: "What Is Cost Basis in Real Estate? How It Affects Depreciation and Taxes at Sale",
    description: "Cost basis is the foundation of all rental property tax calculations — depreciation, capital gains, and recapture at sale. Here's what it is, what's included, and how cost segregation affects it.",
    publishedAt: "2026-02-19",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "Fundamentals",
    tags: ["cost basis", "depreciation", "rental property", "capital gains", "depreciation recapture", "cost segregation"],
    readTime: "5 min read",
    heroImage: "/images/blog/what-is-cost-basis.jpg",
    seo: {
      title: "What Is Cost Basis for Rental Property? Tax Implications Explained | Abode",
      description: "Cost basis is the starting point for all rental property tax calculations. Here's what's included in basis, how it's adjusted over time, and how cost segregation affects your depreciation and gain calculations.",
      canonical: "https://www.abodecostseg.com/learn/what-is-cost-basis-rental-property",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is cost basis in real estate?", acceptedAnswer: { "@type": "Answer", text: "Cost basis (or tax basis) in real estate is the total amount you're considered to have invested in a property for tax purposes. It starts with the purchase price, adds acquisition costs and improvements, and is reduced by depreciation taken. Your adjusted basis determines your taxable gain when you sell." } },
          { "@type": "Question", name: "How does depreciation affect cost basis?", acceptedAnswer: { "@type": "Answer", text: "Depreciation reduces your adjusted basis dollar-for-dollar. If you paid $500,000 for a property and have taken $100,000 in depreciation, your adjusted basis is $400,000. If you sell for $600,000, your gain is $200,000 — not $100,000 — because the basis has been reduced by depreciation." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "info", title: "Quick Answer", text: "Cost basis is what you're considered to have paid for a property for tax purposes. It starts with the purchase price + closing costs, increases with capital improvements, and decreases with depreciation deductions. Your adjusted basis is subtracted from the sale price to calculate your taxable gain." },
      { type: "paragraph", text: "Cost basis is the invisible number that determines your tax bill in almost every rental property transaction. Every time you take a depreciation deduction, you lower your basis. Every capital improvement raises it. Get the basis wrong, and you either overpay taxes or underreport income — neither is good." },
      { type: "heading", level: 2, text: "What's Included in Your Initial Basis", id: "initial-basis" },
      { type: "list", style: "bulleted", items: [
        "<strong>Purchase price:</strong> The contract price paid for the property",
        "<strong>Closing costs:</strong> Title insurance, recording fees, attorney fees, transfer taxes paid by the buyer",
        "<strong>Broker commissions:</strong> Commissions paid in connection with the acquisition",
        "<strong>Prepaid items capitalized:</strong> Some prepaid expenses at closing may be added to basis",
        "<strong>NOT included:</strong> Points paid to obtain a mortgage (deductible separately), prorated property taxes (deductible currently), homeowner's insurance",
      ]},
      { type: "heading", level: 2, text: "How Depreciation Reduces Your Basis", id: "depreciation-reduces-basis" },
      { type: "paragraph", text: "Each year you take a depreciation deduction, your adjusted basis decreases by the same amount. After 10 years of $16,000/year in depreciation on a $500,000 property, your adjusted basis is $340,000 ($500,000 − $160,000 depreciation taken). If you sell for $600,000, your gain is $260,000 ($600,000 − $340,000), not $100,000 ($600,000 − $500,000)." },
      { type: "paragraph", text: "Critically, the IRS reduces your basis by depreciation 'allowed or allowable' — meaning they reduce it whether or not you actually claimed the deduction. If you forgot to take depreciation for several years, your basis is still reduced — and you owe recapture tax on deductions you never took. This is why it's always better to take depreciation and file Form 3115 for any missed years." },
      { type: "heading", level: 2, text: "How Cost Segregation Affects Basis", id: "cost-seg-and-basis" },
      { type: "paragraph", text: "Cost segregation accelerates basis reduction. Instead of $16,000/year over 27.5 years, cost seg generates $130,000+ in year one. Your adjusted basis drops $130,000 in year one alone. This is why large cost segregation deductions taken early in ownership create a potentially large recapture liability if you sell shortly after." },
      { type: "paragraph", text: "The solution: hold the property long enough that the time value of the early deductions outweighs any recapture at sale — or use a 1031 exchange to defer recapture indefinitely when you're ready to sell." },
      { type: "faq", question: "Can I add the cost of a cost segregation study to my basis?", answer: "No. The cost of a cost segregation study is a currently deductible professional fee (Section 162 business expense), not a capital cost that adds to basis. It's expensed in the year incurred." },
      { type: "cta", title: "Understand Your Full Tax Picture", text: "Cost segregation accelerates basis reduction to generate immediate savings. Get your free estimate and see the numbers.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

];
