// State-specific STR tax guides
// URL pattern: /learn/str-taxes-[state]

export const stateArticles = [

  // ─── Florida ─────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-florida",
    title: "Short-Term Rental Taxes in Florida: What Investors Need to Know in 2025",
    description: "Florida has no state income tax, but STR investors still face sales tax, county tourist development taxes, and licensing requirements. Here's the complete Florida STR tax guide.",
    publishedAt: "2026-02-20",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Florida", "state taxes", "sales tax", "cost segregation", "bonus depreciation", "no income tax"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-florida.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Florida 2025: Complete Investor Guide | Abode",
      description: "Florida has no income tax but STR investors owe state sales tax + county tourist development tax. Here's what Florida STR investors pay, what they can deduct, and how cost segregation works in Florida.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-florida",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Florida have a state income tax on rental income?", acceptedAnswer: { "@type": "Answer", text: "No. Florida has no state personal income tax, so STR rental income is only taxed federally. This is a significant advantage for Florida STR investors compared to states like California or New York." } },
          { "@type": "Question", name: "What taxes do Florida STR investors pay on rental income?", acceptedAnswer: { "@type": "Answer", text: "Florida STR investors pay: (1) Federal income tax on net rental income; (2) Florida state sales tax of 6% on rental payments; (3) County tourist development tax (1–6% depending on county — Miami-Dade is 6%, Orange County is 6%, Walton County is 5%); and in some counties, additional municipal taxes." } },
          { "@type": "Question", name: "Does Florida conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Florida has no personal income tax, so federal bonus depreciation conformity is moot for individual investors. There is no Florida state income tax return for individuals — you benefit from 100% federal bonus depreciation without any state-level adjustment." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Florida STR Tax Summary", text: "No state income tax | 6% state sales tax on rentals | County tourist development taxes (1–6%) | Must register with Florida Dept. of Revenue | Federal depreciation fully applicable" },
      { type: "paragraph", text: "Florida is the largest short-term rental market in the United States. With over 150,000 active STR listings, markets from the Florida Panhandle to the Florida Keys, and no state personal income tax, Florida is one of the most tax-favorable states for STR investors from a pure income tax standpoint. But that doesn't mean STR taxes are simple here — the combination of state sales tax and county-level tourist development taxes creates a layered compliance obligation." },
      { type: "heading", level: 2, text: "The Big Advantage: No Florida State Income Tax", id: "no-income-tax" },
      { type: "paragraph", text: "Florida's most significant tax advantage for STR investors is the absence of a state personal income tax. While California investors pay up to 13.3% state income tax on top of federal taxes, Florida investors pay only federal. For a high-income investor in the 37% federal bracket with $200,000 in rental income, the absence of state income tax saves $26,000+ compared to a California resident in the same situation." },
      { type: "paragraph", text: "This also means Florida fully benefits from 100% federal bonus depreciation (OBBBA) without any state-level adjustment. California, by contrast, does not conform to federal bonus depreciation for state taxes — Florida investors don't face that complexity." },
      { type: "heading", level: 2, text: "Florida Sales Tax on STR Rentals", id: "florida-sales-tax" },
      { type: "paragraph", text: "Florida imposes a 6% state sales tax on all transient rental accommodations (rentals under 6 months). This applies to both the rental rate and most required cleaning fees charged to guests. Florida STR operators must register with the Florida Department of Revenue and either collect and remit this tax themselves or ensure their booking platform (Airbnb, VRBO) is collecting it." },
      { type: "paragraph", text: "Airbnb has a marketplace facilitator agreement with Florida — meaning Airbnb collects and remits Florida state sales tax on bookings made through their platform. VRBO/Vrbo has similar arrangements in most Florida counties. Direct bookings (your own website) require you to collect and remit independently." },
      { type: "heading", level: 2, text: "County Tourist Development Taxes", id: "county-taxes" },
      { type: "table", headers: ["County / Market", "Tourist Development Tax Rate", "Total Tax (State + County)"],
        rows: [
          ["Miami-Dade", "6%", "12%"],
          ["Orange County (Orlando/Disney)", "6%", "12%"],
          ["Pinellas County (St. Pete/Clearwater)", "6%", "12%"],
          ["Walton County (30A/Destin area)", "5%", "11%"],
          ["Okaloosa County (Destin/Fort Walton)", "5%", "11%"],
          ["Collier County (Naples)", "5%", "11%"],
          ["Sarasota County", "5%", "11%"],
          ["Monroe County (Florida Keys)", "5%", "11%"],
          ["Duval County (Jacksonville)", "2%", "8%"],
        ]
      },
      { type: "heading", level: 2, text: "Florida STR Licensing Requirements", id: "licensing" },
      { type: "paragraph", text: "Florida requires all STR operators to obtain a Vacation Rental License from the Florida Department of Business and Professional Regulation (DBPR). The license must be renewed annually and requires inspection in some cases. Unlicensed operation can result in significant fines ($1,000+ per day in some jurisdictions)." },
      { type: "paragraph", text: "Additionally, many Florida municipalities have added their own short-term rental regulations. Miami Beach has highly restrictive STR rules in some zones. Some counties have adopted registration programs on top of the state license. Check both state and local requirements before operating." },
      { type: "heading", level: 2, text: "Cost Segregation in Florida: What's Different", id: "cost-seg-florida" },
      { type: "paragraph", text: "Florida STR investors benefit from cost segregation in the same way as investors in any other state — the federal tax savings are the same. With no state income tax, there's no state-level complexity around bonus depreciation conformity. A $600,000 Florida beach house or Orlando vacation rental with a cost segregation study might generate $130,000+ in first-year federal depreciation deductions." },
      { type: "paragraph", text: "Florida's top STR markets — Destin/30A, Miami Beach, Orlando/Kissimmee, St. Pete Beach, Naples, and the Florida Keys — all feature high property values that amplify cost segregation benefits. A $900,000 beachfront property in Destin could generate $200,000+ in first-year deductions." },
      { type: "heading", level: 2, text: "Top Florida STR Markets and Tax Profiles", id: "top-markets" },
      { type: "list", style: "bulleted", items: [
        "<strong>Destin/30A/Okaloosa & Walton Counties:</strong> 11% total transient tax; strong rental demand; high property values with excellent cost seg potential",
        "<strong>Orlando/Kissimmee/Orange County:</strong> 12% total transient tax; world's largest STR market by volume; strong average stays support the 7-day loophole",
        "<strong>Florida Keys/Monroe County:</strong> 11% total transient tax; very high property values ($1M+); significant outdoor amenity value for cost seg",
        "<strong>Naples/Collier County:</strong> 11% total transient tax; luxury market; high personal property ratios on furnished vacation homes",
        "<strong>St. Pete/Clearwater/Pinellas:</strong> 12% total transient tax; affordable relative to Naples; strong occupancy rates",
      ]},
      { type: "faq", question: "Do I need to file a Florida tax return as an STR investor?", answer: "No. Florida has no state individual income tax return. You only file federal returns (Form 1040 + Schedule E). You do have sales tax remittance obligations with the Florida Dept. of Revenue, but those are filed separately and are not income tax returns." },
      { type: "cta", title: "Estimate Your Florida STR Tax Savings", text: "Florida's no-income-tax status makes cost segregation even more powerful — 100% of the federal benefit with no state offset. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Tennessee ────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-tennessee",
    title: "Short-Term Rental Taxes in Tennessee: The STR Investor's Complete Guide",
    description: "Tennessee has no wage income tax, strong STR markets in Gatlinburg/Smoky Mountains and Nashville, and conforms fully to federal bonus depreciation. Here's the complete Tennessee STR tax guide.",
    publishedAt: "2026-02-21",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Tennessee", "Gatlinburg", "Nashville", "Smoky Mountains", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-tennessee.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Tennessee 2025: Gatlinburg, Nashville & More | Abode",
      description: "Tennessee has no income tax on wages, fully conforms to federal bonus depreciation, and hosts the Smoky Mountains and Nashville STR markets. Here's what TN STR investors pay and how to maximize deductions.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-tennessee",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Tennessee have a state income tax on rental income?", acceptedAnswer: { "@type": "Answer", text: "Tennessee does not have a traditional state income tax on wages or salaries. The Hall Income Tax (which taxed dividends and interest) was fully repealed effective January 1, 2021. As a result, Tennessee STR investors pay no state income tax on rental income — only federal." } },
          { "@type": "Question", name: "What taxes apply to Tennessee STR rentals?", acceptedAnswer: { "@type": "Answer", text: "Tennessee STR operators collect and remit: (1) Tennessee state sales tax of 7% on rental revenue; (2) Local occupancy taxes varying by jurisdiction (Nashville charges an additional 6%, Gatlinburg/Sevier County charges approximately 3–5%); (3) Some municipalities have additional hotel/motel taxes." } },
          { "@type": "Question", name: "Does Tennessee conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Tennessee has no income tax, so there is no state-level depreciation conformity issue. The full 100% federal bonus depreciation benefit applies without any Tennessee state-level adjustment or clawback." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Tennessee STR Tax Summary", text: "No state income tax | 7% state sales tax on rentals | Local occupancy taxes vary by city | Gatlinburg/Smoky Mountains is the top Tennessee STR market | Full federal bonus depreciation benefit" },
      { type: "paragraph", text: "Tennessee is one of the fastest-growing STR markets in the country, driven by two very different travel demand drivers: the Great Smoky Mountains (the most-visited national park in the U.S.) and Nashville (Music City, with a thriving urban short-term rental market). Both markets generate excellent revenue for STR investors — and the combination of no state income tax and full federal depreciation benefit makes Tennessee a strong tax picture." },
      { type: "heading", level: 2, text: "Tennessee State Tax Landscape", id: "state-tax-landscape" },
      { type: "paragraph", text: "Tennessee eliminated its last remaining individual income tax (the Hall Income Tax on investment income) effective January 1, 2021. Individual Tennessee residents now pay zero state income tax on wages, rental income, business income, or investment income. Federal income taxes apply in full, but the absence of state income tax means Tennessee STR investors are among the best-positioned in the country from a tax efficiency standpoint." },
      { type: "paragraph", text: "Tennessee does have a corporate income/franchise tax for entities, but individual STR investors operating through a disregarded LLC or personal ownership are not subject to corporate taxes on their rental income." },
      { type: "heading", level: 2, text: "Tennessee Sales and Occupancy Taxes on STRs", id: "sales-occupancy-taxes" },
      { type: "paragraph", text: "While there's no income tax, Tennessee STR operators do collect and remit: (1) Tennessee state sales tax of 7% on rental revenue; (2) Local occupancy taxes that vary significantly by jurisdiction." },
      { type: "table", headers: ["Market / County", "Local Occupancy Tax", "Total Tax (7% State + Local)"],
        rows: [
          ["Nashville (Davidson County)", "6%", "13%"],
          ["Sevier County (Gatlinburg/Pigeon Forge)", "3%", "10%"],
          ["Knox County (Knoxville)", "4%", "11%"],
          ["Shelby County (Memphis)", "5.25%", "12.25%"],
          ["Hamilton County (Chattanooga)", "2%", "9%"],
        ]
      },
      { type: "heading", level: 2, text: "The Smoky Mountains STR Market: Gatlinburg and Pigeon Forge", id: "smoky-mountains-market" },
      { type: "paragraph", text: "The Gatlinburg/Pigeon Forge/Sevierville corridor in Sevier County is one of the highest-density STR markets in the United States. Properties in this market feature consistently high occupancy rates (60–80%+ annually), strong average daily rates, and very short average booking windows — typically well under 7 days, which supports the STR tax loophole comfortably." },
      { type: "paragraph", text: "Smoky Mountains STR properties tend to have high personal property ratios: hot tubs, game rooms, home theaters, outdoor decks, and recreational amenities are standard in the market. This means cost segregation studies on Sevier County properties typically identify 25–35% of purchase price in 5-year and 15-year assets — toward the top of the range nationally." },
      { type: "heading", level: 2, text: "Nashville STR Market", id: "nashville-market" },
      { type: "paragraph", text: "Nashville's STR market is predominantly urban condos and apartments catering to bachelorette parties, country music tourists, and convention attendees. Nashville has adopted a permitting system for STRs, limiting them in many residential zones to owner-occupied properties. Non-owner-occupied STRs face restrictions in many areas." },
      { type: "paragraph", text: "Investors acquiring Nashville STR properties should verify current zoning and permit availability before acquisition. The city has periodically tightened regulations. Properties in approved zones can be very lucrative — Nashville commands some of the highest nightly rates in the Southeast." },
      { type: "heading", level: 2, text: "Tennessee STR Licensing", id: "licensing" },
      { type: "paragraph", text: "Tennessee requires STR operators to register with the Tennessee Department of Revenue for sales tax collection. Individual jurisdictions may have separate licensing requirements — Sevier County has its own STR registration, and Nashville requires a specific permit. Check both state and local requirements for your specific property location." },
      { type: "faq", question: "Are Airbnb and VRBO taxes automatically collected in Tennessee?", answer: "Both Airbnb and VRBO act as marketplace facilitators in Tennessee, collecting and remitting state sales tax on bookings made through their platforms. Local occupancy taxes may or may not be collected by the platform depending on the jurisdiction. Verify with your specific county." },
      { type: "cta", title: "Maximize Your Tennessee STR Tax Strategy", text: "Tennessee's no-income-tax environment + cost segregation = exceptional after-tax returns. Get your free estimate for your Smoky Mountains or Nashville property.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Texas ────────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-texas",
    title: "Short-Term Rental Taxes in Texas: What STR Investors Pay (and Don't Pay)",
    description: "Texas has no state income tax and fully conforms to federal bonus depreciation. With major STR markets in Austin, San Antonio, and Hill Country, Texas is a top-tier state for STR investing.",
    publishedAt: "2026-02-22",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Texas", "Austin", "Hill Country", "state taxes", "cost segregation", "no income tax", "bonus depreciation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-texas.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Texas 2025: Austin, Hill Country & More | Abode",
      description: "Texas has no state income tax, making it one of the best states for STR investing. Here's what Texas STR investors pay, local hotel occupancy taxes by market, and how cost segregation works.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-texas",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Texas have a state income tax on rental income?", acceptedAnswer: { "@type": "Answer", text: "No. Texas has no state personal income tax. STR rental income is only taxed at the federal level. This makes Texas one of the most favorable states for STR investors from an income tax perspective." } },
          { "@type": "Question", name: "What taxes do Texas STR investors pay?", acceptedAnswer: { "@type": "Answer", text: "Texas STR operators are subject to: (1) Federal income tax; (2) Texas state hotel occupancy tax of 6% on rental revenue; (3) City hotel occupancy taxes (Austin charges 9%, Houston charges 7%, San Antonio charges 9%). Some counties also have hotel taxes. Total rates typically range from 13–17% depending on location." } },
          { "@type": "Question", name: "Does Texas conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Texas has no personal income tax, so there's no state conformity issue for individual investors. The full 100% federal bonus depreciation benefit applies with no Texas state adjustment. LLCs and entities may have franchise tax (Texas Margin Tax) considerations, but this doesn't affect depreciation deductions on federal returns." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Texas STR Tax Summary", text: "No state income tax | 6% state hotel occupancy tax | City hotel taxes 7–9% | Strong STR markets in Austin, Hill Country, San Antonio | Full federal bonus depreciation benefit" },
      { type: "paragraph", text: "Texas is one of the fastest-growing states in the country and home to several of the most dynamic STR markets: Austin (music festivals, tech industry, SXSW), the Texas Hill Country (wine country, weekend escapes from Houston and Dallas), San Antonio (Alamo, River Walk, tourism), and Fredericksburg (wine region). Combined with no state income tax, Texas offers one of the best income tax environments for STR investing." },
      { type: "heading", level: 2, text: "No Texas State Income Tax", id: "no-income-tax" },
      { type: "paragraph", text: "Texas has no personal income tax — rental income, wages, and investment returns are all income-tax-free at the state level. The full benefit of cost segregation, bonus depreciation, and the STR loophole flows to the federal return without any state-level offset." },
      { type: "paragraph", text: "Texas does have a franchise tax (the Texas Margin Tax) for certain entities, but this applies to business entities with revenues above $1.18 million (2025 threshold) and is calculated differently from income tax. Most individual STR investors operating through a single-member LLC will not be subject to the franchise tax." },
      { type: "heading", level: 2, text: "Texas Hotel Occupancy Tax", id: "hotel-occupancy-tax" },
      { type: "table", headers: ["Market / Jurisdiction", "State HOT (6%)", "City/County HOT", "Total Rate"],
        rows: [
          ["Austin (city limits)", "6%", "9%", "15%"],
          ["San Antonio (city limits)", "6%", "9%", "15%"],
          ["Houston (city limits)", "6%", "7%", "13%"],
          ["Dallas (city limits)", "6%", "7%", "13%"],
          ["Fredericksburg (Gillespie County)", "6%", "7%", "13%"],
          ["New Braunfels (Comal County)", "6%", "7%", "13%"],
          ["Galveston (Galveston County)", "6%", "7%", "13%"],
          ["South Padre Island", "6%", "7%", "13%"],
        ]
      },
      { type: "heading", level: 2, text: "Top Texas STR Markets", id: "top-markets" },
      { type: "paragraph", text: "<strong>Austin:</strong> High nightly rates driven by SXSW, ACL Music Festival, Formula 1 (Circuit of the Americas), and the University of Texas. Austin's STR regulations require registration. Demand consistently keeps average stays well below 7 days, supporting the STR loophole." },
      { type: "paragraph", text: "<strong>Texas Hill Country (Fredericksburg, Wimberley, New Braunfels):</strong> Vineyard retreats, swimming holes, and weekend escapes from San Antonio, Austin, and Houston. Properties tend to be freestanding homes with pools, outdoor entertainment areas, and scenic views — high personal property ratios for cost segregation." },
      { type: "paragraph", text: "<strong>San Antonio:</strong> Tourism-driven by the Alamo, River Walk, and major conventions. Shorter stays typical; strong year-round occupancy. Downtown condos and historic Southtown properties are popular." },
      { type: "heading", level: 2, text: "Texas Property Taxes: The Trade-off", id: "property-taxes" },
      { type: "paragraph", text: "Texas compensates for its lack of income tax with notably high property tax rates — typically 1.5–2.5% of market value annually. For a $500,000 STR, that's $7,500–$12,500/year in property taxes. These are fully deductible as a business expense on your Schedule E, but they represent a significant ongoing cost that investors in lower-property-tax states (Florida, Tennessee) don't face." },
      { type: "faq", question: "Do I need to collect hotel occupancy tax on direct bookings in Texas?", answer: "Yes. If you accept direct bookings (not through Airbnb or VRBO), you are responsible for collecting and remitting both state and applicable local hotel occupancy taxes. Airbnb and VRBO act as marketplace facilitators in Texas and collect on their platform bookings." },
      { type: "cta", title: "Estimate Your Texas STR Tax Savings", text: "No income tax + 100% federal bonus depreciation = exceptional Texas STR returns. Get your free cost segregation estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Colorado ─────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-colorado",
    title: "Short-Term Rental Taxes in Colorado: Ski Markets, State Income Tax, and Cost Segregation",
    description: "Colorado STR investors face a 4.4% flat state income tax and varying local lodging taxes. Here's the complete guide for Breckenridge, Vail, Aspen, and other Colorado STR markets.",
    publishedAt: "2026-02-23",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Colorado", "Breckenridge", "Vail", "Aspen", "ski rental", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-colorado.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Colorado 2025: Ski Markets Guide | Abode",
      description: "Colorado has a 4.4% flat income tax, fully conforms to federal bonus depreciation, and features major STR markets in Breckenridge, Vail, Aspen, and Steamboat Springs. Here's the full tax guide.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-colorado",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is Colorado's state income tax rate for rental income?", acceptedAnswer: { "@type": "Answer", text: "Colorado has a flat 4.4% state income tax rate (reduced from 4.55% effective 2024) on taxable income, including net rental income. Colorado conforms to federal depreciation methods, meaning the full benefit of cost segregation and bonus depreciation applies to both federal and Colorado state returns." } },
          { "@type": "Question", name: "Does Colorado conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. Colorado fully conforms to federal MACRS depreciation and bonus depreciation. The 100% bonus depreciation benefit under the OBBBA applies fully on Colorado state returns — unlike California, which partially decouples from federal bonus depreciation." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Colorado STR Tax Summary", text: "4.4% flat state income tax | Conforms to federal bonus depreciation | Major ski resort STR markets | Local lodging taxes 2–12% | Very high property values → large cost seg deductions" },
      { type: "paragraph", text: "Colorado is home to some of the most valuable short-term rental properties in the United States. Ski resort markets — Vail, Aspen, Breckenridge, Telluride, Steamboat Springs — command property values of $1M–$10M+ for premier units. The combination of very high property values, Colorado's full conformity with federal bonus depreciation, and a moderate 4.4% flat state income tax makes Colorado STR investing a compelling tax picture." },
      { type: "heading", level: 2, text: "Colorado State Income Tax", id: "state-income-tax" },
      { type: "paragraph", text: "Colorado taxes net rental income at its flat 4.4% rate. This applies after all deductions — including depreciation, mortgage interest, property management, maintenance, and all other deductible expenses. For a Colorado STR investor generating $80,000 in net rental income, the Colorado state tax is $3,520 (4.4% × $80,000)." },
      { type: "paragraph", text: "In a year with a major cost segregation study, the large depreciation deduction may reduce or eliminate net rental income — eliminating Colorado state tax for that year as well. A $200,000 cost segregation deduction on a $1M Vail condo can easily wipe out net income for the year, creating a state tax benefit as well as a federal one." },
      { type: "heading", level: 2, text: "Colorado Fully Conforms to Federal Depreciation", id: "depreciation-conformity" },
      { type: "paragraph", text: "Unlike California (which decouples from federal bonus depreciation) and some other states, Colorado fully conforms to federal MACRS depreciation including 100% bonus depreciation. Colorado's tax code follows federal adjusted gross income as a starting point, meaning cost segregation deductions that reduce federal taxable income reduce Colorado taxable income by the same amount." },
      { type: "heading", level: 2, text: "Local Lodging Taxes in Colorado STR Markets", id: "local-taxes" },
      { type: "table", headers: ["Market", "State Sales Tax", "Local Lodging Tax", "Total Approx. Rate"],
        rows: [
          ["Breckenridge (Summit County)", "2.9%", "11.225%", "~14%"],
          ["Vail (Eagle County)", "2.9%", "10%", "~13%"],
          ["Aspen (Pitkin County)", "2.9%", "12%", "~15%"],
          ["Steamboat Springs (Routt County)", "2.9%", "9%", "~12%"],
          ["Telluride (San Miguel County)", "2.9%", "10%", "~13%"],
          ["Estes Park (Larimer County)", "2.9%", "8.5%", "~11%"],
          ["Colorado Springs", "2.9%", "5%", "~8%"],
          ["Denver (city limits)", "2.9%", "10.75%", "~14%"],
        ]
      },
      { type: "heading", level: 2, text: "Colorado SKI Market Cost Segregation: High Values, High Deductions", id: "ski-market-cost-seg" },
      { type: "paragraph", text: "Colorado ski resort properties produce exceptional cost segregation results for two reasons: (1) very high absolute property values ($500K to $5M+) generate proportionally large dollar deductions, and (2) ski properties tend to include significant personal property (premium furnishings, ski equipment storage, outdoor hot tubs, entertainment systems) and land improvements (outdoor spaces, decks, ski equipment areas)." },
      { type: "paragraph", text: "A $1.5M Breckenridge condo with a cost segregation study might identify $300,000–$450,000 in 5-year and 15-year assets eligible for 100% bonus depreciation. At a 37% federal + 4.4% Colorado rate, the incremental deduction vs. straight-line could be worth $100,000+ in first-year tax savings." },
      { type: "heading", level: 2, text: "Colorado STR Regulations", id: "str-regulations" },
      { type: "paragraph", text: "Colorado ski resort municipalities have varying STR regulations. Breckenridge allows STRs with a license and registration. Vail requires an STR license; the town actively manages inventory. Aspen has strict STR regulations and limits in residential zones. Telluride has permit requirements and caps. Always verify current regulations before acquiring a Colorado ski resort property as an STR investment." },
      { type: "faq", question: "Can I use the STR loophole in Colorado ski resort markets?", answer: "Yes, if your property's average rental period is 7 days or fewer. Ski resort STRs typically see short stays (2–7 nights), making it feasible to maintain an average stay below the threshold. Track your average carefully — some luxury properties in these markets take week-long rentals that push averages toward 7 days." },
      { type: "cta", title: "Maximize Your Colorado STR Tax Strategy", text: "High-value Colorado ski properties generate exceptional cost segregation deductions. Get your free estimate for your Vail, Breckenridge, or Aspen property.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── North Carolina ───────────────────────────────────────────────────────
  {
    slug: "str-taxes-north-carolina",
    title: "Short-Term Rental Taxes in North Carolina: Asheville, OBX, and Beyond",
    description: "North Carolina has a 4.5% flat income tax and fully conforms to federal depreciation. Top STR markets include Asheville, the Outer Banks, Lake Norman, and Wrightsville Beach.",
    publishedAt: "2026-02-24",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "North Carolina", "Asheville", "Outer Banks", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "7 min read",
    heroImage: "/images/blog/str-taxes-north-carolina.jpg",
    seo: {
      title: "Short-Term Rental Taxes in North Carolina 2025 | Abode",
      description: "North Carolina's 4.5% flat income tax and full federal depreciation conformity make it favorable for STR investors. Here's the complete NC tax guide for Asheville, OBX, and other markets.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-north-carolina",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is North Carolina's income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "North Carolina has a flat 4.5% individual income tax rate (as of 2024, phasing down further). This applies to net rental income after all deductions including depreciation. North Carolina generally conforms to federal depreciation, so cost segregation deductions reduce both federal and NC taxable income." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "North Carolina STR Tax Summary", text: "4.5% flat state income tax (phasing down) | Conforms to federal bonus depreciation | Top markets: Asheville, Outer Banks, Wilmington/Wrightsville Beach | County and city occupancy taxes apply" },
      { type: "paragraph", text: "North Carolina is home to some of the most diverse STR markets in the Southeast: the mountain retreat culture of Asheville, the iconic beach destinations of the Outer Banks, and the coastal markets around Wilmington. With a flat 4.5% state income tax (phasing down under current law) and full conformity to federal depreciation, North Carolina is a solid STR investing environment." },
      { type: "heading", level: 2, text: "North Carolina State Income Tax", id: "state-income-tax" },
      { type: "paragraph", text: "North Carolina has transitioned to a flat income tax rate, reducing from 5.25% in 2021 to 4.5% in 2024, with further reductions scheduled under the Revenue Laws Study Committee plan. Rental income (net of all deductions) is taxed at this flat rate. North Carolina generally conforms to federal tax law for depreciation purposes, meaning cost segregation deductions flow through to the NC return." },
      { type: "heading", level: 2, text: "Occupancy Tax Rates in Key NC Markets", id: "occupancy-taxes" },
      { type: "table", headers: ["County / Market", "NC Occupancy Tax Rate", "Notes"],
        rows: [
          ["Dare County (Outer Banks)", "6%", "One of highest in NC; major tourism market"],
          ["Buncombe County (Asheville)", "6%", "City of Asheville adds additional 3%"],
          ["Brunswick County (Ocean Isle, Sunset Beach)", "5%", "Popular retirement/vacation area"],
          ["New Hanover County (Wilmington)", "6%", "Plus city tourism tax"],
          ["Mecklenburg County (Charlotte)", "6%", "Charlotte urban STR market"],
          ["Haywood County (Maggie Valley)", "5%", "Mountain market near Asheville"],
          ["Watauga County (Boone/Blowing Rock)", "6%", "Mountain/ski market"],
        ]
      },
      { type: "heading", level: 2, text: "Asheville STR Market", id: "asheville-market" },
      { type: "paragraph", text: "Asheville is consistently ranked among the top STR markets in the Southeast. Known for its arts scene, craft breweries, Blue Ridge Parkway access, and mountain views, Asheville commands strong nightly rates and high occupancy. The city has permitting requirements for STRs; non-owner-occupied STRs require a permit and must comply with zoning restrictions." },
      { type: "paragraph", text: "Asheville mountain cabins and craftsman bungalows have excellent cost segregation profiles: high furniture and fixture loads, outdoor decks, mountain view amenities, and landscaping all contribute to shorter-life asset identification." },
      { type: "heading", level: 2, text: "Outer Banks STR Market", id: "obx-market" },
      { type: "paragraph", text: "The Outer Banks (Dare County) is a large-scale vacation rental market with thousands of properties, primarily freestanding beach homes. OBX properties range from modest cottages to multi-million-dollar oceanfront estates. The market is highly seasonal (summer peak) but can achieve exceptional ADR during peak weeks. Dare County's 6% occupancy tax applies to all STR revenue." },
      { type: "paragraph", text: "OBX beach houses with pools, game rooms, and elevator access (multi-story homes are common) have very strong cost segregation potential. Personal property and land improvement ratios on these properties often exceed 30% of purchase price." },
      { type: "faq", question: "Does North Carolina have any special STR registration requirements?", answer: "North Carolina doesn't have a statewide STR licensing program, but individual municipalities do. Asheville, Charlotte, and some beach towns have registration or permit requirements. Always check with the specific city or county where your property is located." },
      { type: "cta", title: "See Your NC STR Tax Savings", text: "Get a free cost segregation estimate for your Asheville, OBX, or North Carolina coastal property.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── California ───────────────────────────────────────────────────────────
  {
    slug: "str-taxes-california",
    title: "Short-Term Rental Taxes in California: What Investors Need to Know About Bonus Depreciation",
    description: "California has a top income tax rate of 13.3% and does NOT conform to federal bonus depreciation. Here's what that means for CA STR investors and how to optimize your tax strategy.",
    publishedAt: "2026-02-25",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "California", "Palm Springs", "bonus depreciation", "state taxes", "cost segregation", "California conformity"],
    readTime: "9 min read",
    heroImage: "/images/blog/str-taxes-california.jpg",
    seo: {
      title: "Short-Term Rental Taxes in California 2025: Bonus Depreciation Issues Explained | Abode",
      description: "California taxes rental income at up to 13.3% AND doesn't conform to federal bonus depreciation. Here's how California's decoupling affects STR investors and how to still generate strong returns.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-california",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does California conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "No. California does not conform to federal bonus depreciation. While you can take 100% bonus depreciation on your federal return, California requires you to spread that same depreciation over the regular MACRS recovery period on your California state return. This creates a temporary difference that can result in a higher California tax bill in year one." } },
          { "@type": "Question", name: "What is California's income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "California taxes rental income as ordinary income, with rates ranging from 1% to 13.3%. High-income investors (taxable income over $1 million) pay the maximum 13.3% rate (including the 1% mental health services tax). California also has an AMT at 7.25%." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "warning", title: "California Critical Difference", text: "California does NOT conform to federal bonus depreciation. A $150,000 first-year bonus depreciation deduction on your federal return does not reduce your California taxable income by $150,000. California requires you to use regular MACRS depreciation schedules for CA purposes — creating a significant state tax impact in year one." },
      { type: "paragraph", text: "California is both one of the largest STR markets in the United States (Palm Springs, Lake Tahoe, Big Sur, San Diego) and one of the most tax-complex states for real estate investors. The combination of high income tax rates and non-conformity with federal bonus depreciation means California STR investors face a very different tax picture than investors in Florida, Texas, or Tennessee." },
      { type: "heading", level: 2, text: "California's Non-Conformity with Bonus Depreciation", id: "non-conformity" },
      { type: "paragraph", text: "This is the critical issue for California investors. When you take 100% bonus depreciation on 5-year and 15-year property at the federal level, you deduct the full cost in year one on your federal Form 1040. California does not follow this treatment. Instead, California requires you to depreciate those same assets over their regular MACRS lives — 5 years, 15 years, etc. — using straight-line methods." },
      { type: "paragraph", text: "The practical result: if you take a $120,000 bonus depreciation deduction federally, your California taxable income is only reduced by approximately $24,000 (the first-year MACRS amount for 5-year property). You still owe California income tax on the remaining $96,000 that you deducted federally. At the 13.3% rate, that's approximately $12,768 in additional California state tax in year one compared to what you'd pay if California conformed." },
      { type: "heading", level: 2, text: "What California Does Conform To", id: "california-conformity" },
      { type: "paragraph", text: "California does conform to MACRS regular depreciation schedules (just not bonus depreciation). So the cost segregation study is still valuable — you're still identifying 5-year and 15-year assets and getting accelerated (non-bonus) depreciation on those assets over their shorter MACRS lives at the state level. You also still get full federal bonus depreciation." },
      { type: "paragraph", text: "California does conform to Section 179 expensing (up to its own limit of $25,000 for 2025), which is lower than the federal limit. But §179 has income limitations that make it less useful for passive rental investors." },
      { type: "heading", level: 2, text: "California Income Tax Rates for STR Investors", id: "income-tax-rates" },
      { type: "table", headers: ["Taxable Income (Single)", "California Rate", "Cumulative Rate with Federal (37% bracket)"],
        rows: [
          ["$0–$10,099", "1%", "Up to 38%"],
          ["$10,099–$23,942", "2%", "Up to 39%"],
          ["$23,942–$37,788", "4%", "Up to 41%"],
          ["$37,788–$52,455", "6%", "Up to 43%"],
          ["$52,455–$66,295", "8%", "Up to 45%"],
          ["$66,295–$338,639", "9.3%", "Up to 46.3%"],
          ["$338,639–$406,364", "10.3%", "Up to 47.3%"],
          ["$406,364–$677,275", "11.3%", "Up to 48.3%"],
          ["$677,275–$1,000,000", "12.3%", "Up to 49.3%"],
          ["Over $1,000,000", "13.3%", "Up to 50.3%"],
        ]
      },
      { type: "heading", level: 2, text: "California STR Markets and Investment Considerations", id: "ca-markets" },
      { type: "paragraph", text: "<strong>Palm Springs / Coachella Valley:</strong> One of the premier desert STR markets, with high occupancy and premium ADR. Strong personal property ratios (pools, outdoor entertainment are standard). Despite the California tax complexity, high property values make cost seg worthwhile." },
      { type: "paragraph", text: "<strong>Lake Tahoe (El Dorado, Placer, Nevada counties):</strong> Cross-border market where properties in Nevada counties benefit from Nevada's no-income-tax environment. El Dorado County properties on the California side face California's full tax regime including non-conforming bonus depreciation." },
      { type: "paragraph", text: "<strong>Big Bear Lake:</strong> Popular Southern California mountain market. High-demand, relatively accessible property prices compared to Palm Springs. Subject to San Bernardino County STR regulations." },
      { type: "callout", variant: "info", title: "California Strategy: Still Worth It", text: "Despite non-conformity, cost segregation still generates significant federal savings for California STR investors. A $120,000 federal deduction at 37% is $44,400 in federal savings, even if the California benefit is reduced. The net combined benefit is still typically 4–6× the study cost." },
      { type: "faq", question: "Does California have a separate state depreciation schedule I need to track?", answer: "Yes. California investors maintain two separate depreciation schedules: one for federal (with bonus depreciation) and one for California (without bonus, using regular MACRS). This creates 'temporary differences' that your CPA tracks via Form FTB 3885A. Over the life of the asset, total depreciation is the same; it's just when you take it that differs." },
      { type: "cta", title: "California STR Investors: Get Your Numbers", text: "The California complexity is manageable. A qualified cost seg study and CPA can optimize both your federal and CA returns. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Arizona ──────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-arizona",
    title: "Short-Term Rental Taxes in Arizona: Scottsdale, Sedona, and the Desert Market",
    description: "Arizona has a 2.5% flat state income tax (among the lowest in the U.S.) and conforms to federal bonus depreciation. With Scottsdale, Sedona, and Phoenix, Arizona is a top-tier STR investment state.",
    publishedAt: "2026-02-26",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Arizona", "Scottsdale", "Sedona", "Phoenix", "desert rental", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "7 min read",
    heroImage: "/images/blog/str-taxes-arizona.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Arizona 2025: Scottsdale, Sedona Guide | Abode",
      description: "Arizona's 2.5% flat income tax and full federal depreciation conformity make it one of the best states for STR investing. Here's the complete AZ guide for Scottsdale, Sedona, and Phoenix.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-arizona",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is Arizona's income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Arizona has a flat 2.5% state income tax rate on all taxable income, including rental income (as of 2023). This is among the lowest flat rates in the country. Arizona conforms to federal depreciation including bonus depreciation." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Arizona STR Tax Summary", text: "2.5% flat state income tax (one of lowest in U.S.) | Conforms to federal bonus depreciation | Strong markets in Scottsdale, Sedona, Phoenix, Flagstaff | Transaction privilege tax 5.5% + local rates" },
      { type: "paragraph", text: "Arizona passed Proposition 208 (2020) and SB 1828 (2021), ultimately landing on a flat 2.5% income tax rate for all taxpayers — one of the lowest flat income tax rates in the nation. Combined with Arizona's full conformity to federal bonus depreciation and strong, diverse STR markets (desert luxury, spiritual retreat, college town, and mountain), Arizona is one of the best states in the country for STR investing from a tax perspective." },
      { type: "heading", level: 2, text: "Arizona's 2.5% Flat Income Tax", id: "flat-income-tax" },
      { type: "paragraph", text: "Arizona's 2.5% flat income tax applies to all net taxable income including rental income. For a high-income investor, this is dramatically lower than California (up to 13.3%) or even states like Oregon (up to 9.9%) or New York (up to 10.9%). The combined federal + state marginal rate for a top-bracket Arizona investor is approximately 39.5% — vs. 50.3% in California." },
      { type: "paragraph", text: "Arizona conforms to federal depreciation including 100% bonus depreciation. Cost segregation deductions reduce both federal and Arizona taxable income proportionally. A $150,000 bonus depreciation deduction saves 37% federally ($55,500) and 2.5% at the Arizona level ($3,750) — total of $59,250 in first-year combined tax savings." },
      { type: "heading", level: 2, text: "Arizona Transaction Privilege Tax on STRs", id: "tpt" },
      { type: "paragraph", text: "Arizona's version of a sales tax is the Transaction Privilege Tax (TPT). For STR rentals, the state TPT rate is 5.5%. Additional city TPT rates apply in most markets. STR operators must register for TPT with the Arizona Department of Revenue and collect and remit the tax." },
      { type: "table", headers: ["Market", "State TPT", "City TPT", "Total Rate"],
        rows: [
          ["Scottsdale", "5.5%", "1.75%", "7.25%"],
          ["Sedona (City of Sedona)", "5.5%", "3%", "8.5%"],
          ["Phoenix", "5.5%", "2.3%", "7.8%"],
          ["Tempe", "5.5%", "1.8%", "7.3%"],
          ["Flagstaff", "5.5%", "2.281%", "7.78%"],
          ["Tucson", "5.5%", "2%", "7.5%"],
          ["Cave Creek", "5.5%", "3%", "8.5%"],
        ]
      },
      { type: "heading", level: 2, text: "Top Arizona STR Markets", id: "az-markets" },
      { type: "paragraph", text: "<strong>Scottsdale:</strong> Premier desert luxury STR market. High-end homes with pools, outdoor kitchens, and resort-style amenities command premium nightly rates. High personal property ratios for cost seg — pool, outdoor entertainment areas, and premium interior furnishings are standard." },
      { type: "paragraph", text: "<strong>Sedona:</strong> Spiritual retreat and red rock tourism destination. Very high ADR relative to property values, making Sedona STRs among the best yield-per-dollar markets in the West. Sedona adopted a strict STR ordinance; ensure properties are in compliant zones." },
      { type: "paragraph", text: "<strong>Flagstaff:</strong> Mountain market offering respite from Phoenix summer heat. Northern Arizona University drives year-round demand. Cooler climate, pine forest setting — different amenity profile from desert properties." },
      { type: "faq", question: "Does Arizona require a state license for STR operators?", answer: "Arizona does not have a statewide STR license, but requires TPT registration. Individual cities (Sedona, Scottsdale, Phoenix) have their own registration or permit requirements. Arizona preempts some local STR regulations under state law, but local licensing requirements still apply in many jurisdictions." },
      { type: "cta", title: "Maximize Your Arizona STR Tax Strategy", text: "Arizona's 2.5% income tax + full federal bonus depreciation = exceptional STR returns. Get your free estimate for your Scottsdale or Sedona property.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── South Carolina ───────────────────────────────────────────────────────
  {
    slug: "str-taxes-south-carolina",
    title: "Short-Term Rental Taxes in South Carolina: Charleston, Hilton Head, and Myrtle Beach",
    description: "South Carolina has a 6.4% top income tax rate and strong STR markets in Charleston, Hilton Head, and Myrtle Beach. Here's the complete SC STR tax and investment guide.",
    publishedAt: "2026-02-27",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "South Carolina", "Charleston", "Hilton Head", "Myrtle Beach", "state taxes", "cost segregation"],
    readTime: "7 min read",
    heroImage: "/images/blog/str-taxes-south-carolina.jpg",
    seo: {
      title: "Short-Term Rental Taxes in South Carolina 2025: Charleston & Myrtle Beach | Abode",
      description: "South Carolina's STR tax guide: 6.4% top income tax, full federal depreciation conformity, and coastal markets in Charleston, Hilton Head, and Myrtle Beach.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-south-carolina",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is South Carolina's income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "South Carolina has a graduated income tax with a top rate of 6.4% (reduced from 7% under recent legislation, phasing down further). Rental income is taxed as ordinary income at these rates. South Carolina generally conforms to federal depreciation." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "South Carolina STR Tax Summary", text: "6.4% top income tax rate (phasing down) | Conforms to federal depreciation | Major coastal markets: Charleston, Hilton Head, Myrtle Beach | Accommodations taxes 2–11% by county/city" },
      { type: "paragraph", text: "South Carolina's coastal markets — the colonial history of Charleston, the private-resort luxury of Hilton Head Island, and the family vacation scale of Myrtle Beach — represent three very different STR investment profiles. SC's top income tax rate is currently 6.4% (reduced from 7%, with further reductions scheduled), and the state generally conforms to federal depreciation methods." },
      { type: "heading", level: 2, text: "South Carolina Income Tax", id: "income-tax" },
      { type: "paragraph", text: "South Carolina has a graduated income tax with a top marginal rate of 6.4% on income over approximately $17,000. This applies to net rental income after all deductions. SC's recent tax reform is phasing this rate down to 6% over several years. South Carolina generally conforms to federal depreciation, meaning cost segregation deductions reduce both federal and SC taxable income." },
      { type: "heading", level: 2, text: "SC Accommodations Taxes", id: "accommodations-taxes" },
      { type: "table", headers: ["Market / County", "SC Accommodations Tax", "Local Add-On", "Total"],
        rows: [
          ["Charleston (City + Charleston County)", "7%", "1.5–3%", "~10%"],
          ["Hilton Head Island (Beaufort County)", "7%", "1.5%", "~8.5%"],
          ["Myrtle Beach (Horry County)", "7%", "1.5%", "~8.5%"],
          ["Isle of Palms (Charleston County)", "7%", "1.5%", "~8.5%"],
          ["Kiawah Island (Charleston County)", "7%", "1.5%", "~8.5%"],
          ["Folly Beach (Charleston County)", "7%", "1.5%", "~8.5%"],
        ]
      },
      { type: "heading", level: 2, text: "South Carolina's Top STR Markets", id: "sc-markets" },
      { type: "paragraph", text: "<strong>Charleston:</strong> Historic city with strong year-round tourism demand. Mix of downtown carriage houses, downtown condos, and suburban homes catering to event tourism (weddings, corporate events, historical tourism). Short average stays typical. The city has active STR regulation discussion; verify current permit requirements." },
      { type: "paragraph", text: "<strong>Hilton Head Island:</strong> Private resort island with strong seasonal demand and premium ADRs. Properties often include resort amenities (golf access, beach access, pools). High personal property content in resort-style properties makes cost segregation valuable." },
      { type: "paragraph", text: "<strong>Myrtle Beach:</strong> Scale vacation rental market with properties ranging from oceanfront high-rises to golf course communities. High volume, lower ADR than Hilton Head — but significant portfolio-building opportunity at lower entry prices than coastal markets in Florida or the Carolinas further north." },
      { type: "faq", question: "Does South Carolina require STR registration?", answer: "South Carolina does not have a unified statewide STR registration program, but individual municipalities have their own requirements. Charleston has permit requirements; verify with the City of Charleston. Hilton Head and the Sea Pines community have HOA-level regulations as well." },
      { type: "cta", title: "Estimate Your SC STR Tax Savings", text: "Get a free cost segregation estimate for your South Carolina coastal property.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── New York ─────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-new-york",
    title: "Short-Term Rental Taxes in New York: The Hamptons, Catskills, and NYC Rules",
    description: "New York has a top income tax rate of 10.9% plus NYC tax. The Hamptons, Catskills, and Hudson Valley are top STR markets. Here's the complete New York STR tax guide.",
    publishedAt: "2026-02-28",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "New York", "Hamptons", "Catskills", "Hudson Valley", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-new-york.jpg",
    seo: {
      title: "Short-Term Rental Taxes in New York 2025: Hamptons, Catskills Guide | Abode",
      description: "New York's 10.9% top income tax, local hotel taxes, and NYC STR restrictions make NY one of the more complex states for STR investing. Here's what investors need to know.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-new-york",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is New York's income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "New York State has a top income tax rate of 10.9% on income over $25 million. For most high-income investors, the applicable rate is 9.65–10.3%. New York City residents add a city income tax of up to 3.876%. New York does not fully conform to federal bonus depreciation." } },
          { "@type": "Question", name: "Does New York conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "New York does not conform to federal bonus depreciation. Similar to California, New York requires taxpayers to add back the excess of bonus depreciation over regular MACRS depreciation, then allows a recovery of that amount over subsequent years. This creates a timing difference but not a permanent difference." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "warning", title: "New York Bonus Depreciation: Non-Conforming", text: "Like California, New York does not conform to federal bonus depreciation. You must add back the excess bonus depreciation on your NY return in year one, then recover it over subsequent years. The federal benefit is fully preserved; the NY state benefit is deferred." },
      { type: "paragraph", text: "New York is home to some of the most valuable and sought-after STR markets in the Northeast: the Hamptons (one of the highest ADR markets in the country), the Catskills (resurgent mountain market driven by NYC weekend escape demand), the Hudson Valley, and the Finger Lakes wine country. Despite New York's high income tax rates and non-conformity with bonus depreciation, these markets can generate exceptional returns for well-positioned STR investors." },
      { type: "heading", level: 2, text: "New York State Income Tax Rates", id: "income-tax-rates" },
      { type: "table", headers: ["Filing Status / Income", "NY State Rate"],
        rows: [
          ["Single, $0–$17,150", "4%"],
          ["Single, $17,150–$23,600", "4.5%"],
          ["Single, $23,600–$27,900", "5.25%"],
          ["Single, $27,900–$161,550", "5.85%"],
          ["Single, $161,550–$323,200", "6.25%"],
          ["Single, $323,200–$2,155,350", "6.85%"],
          ["Single, $2,155,350–$5M", "9.65%"],
          ["Single, $5M–$25M", "10.3%"],
          ["Single, over $25M", "10.9%"],
        ]
      },
      { type: "heading", level: 2, text: "New York Bonus Depreciation Addback", id: "bonus-depreciation-addback" },
      { type: "paragraph", text: "New York requires taxpayers to add back the difference between federal bonus depreciation and what regular MACRS depreciation would have been. If you take $120,000 in federal bonus depreciation and regular MACRS would have been $24,000, you add back $96,000 on your NY return. Over subsequent years, you can recover this $96,000 — typically 1/5 per year — as a NY deduction." },
      { type: "paragraph", text: "The practical impact: you lose the timing advantage of bonus depreciation at the New York state level, but you don't permanently lose the deduction. Total lifetime New York depreciation equals total federal depreciation — it's just spread over more years." },
      { type: "heading", level: 2, text: "Top New York STR Markets", id: "ny-markets" },
      { type: "paragraph", text: "<strong>The Hamptons (Suffolk County):</strong> The highest ADR STR market in the Northeast, with peak summer weekly rates of $5,000–$50,000+ for premium properties. Very high property values (many properties $3M–$20M) mean cost segregation studies generate exceptional absolute dollar amounts. Suffolk County hotel tax applies." },
      { type: "paragraph", text: "<strong>Catskills (Delaware, Sullivan, Ulster Counties):</strong> The NYC weekend escape market has exploded since 2020. Properties in towns like Woodstock, Hudson, and Livingston Manor have seen significant appreciation. More accessible entry prices than the Hamptons with strong yield-to-price ratios." },
      { type: "paragraph", text: "<strong>Hudson Valley (Dutchess, Orange Counties):</strong> Year-round tourism driven by historic estates, vineyards, and arts culture. Properties in Rhinebeck, Millbrook, and the Hudson area command premium rates from NYC travelers." },
      { type: "heading", level: 2, text: "NYC Short-Term Rental Rules", id: "nyc-rules" },
      { type: "paragraph", text: "New York City has among the most restrictive STR regulations in the country. Local Law 18 (effective September 2023) effectively bans most STRs in NYC — hosts must register, be present during stays, and can host a maximum of 2 guests at once. This has essentially eliminated Airbnb-style non-hosted rentals in the five boroughs. Investors targeting NYC STR income should be aware that NYC is functionally closed to traditional STR operation." },
      { type: "faq", question: "Should I invest in NY STRs given the high tax rates and non-conformity?", answer: "For the right property in the right market (especially Hamptons and Catskills), the revenue potential can justify the higher tax burden. The key is to work with a NY-experienced CPA to optimize the state return, use the addback recovery mechanism efficiently, and ensure the federal cost seg benefit is fully captured even when the state benefit is deferred." },
      { type: "cta", title: "Navigate NY STR Taxes with Confidence", text: "Even with NY's complexity, cost segregation generates significant federal savings. Get your free estimate for your Hamptons or Catskills property.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Hawaii ───────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-hawaii",
    title: "Short-Term Rental Taxes in Hawaii: Maui, Oahu, and the Unique Hawaii Tax Structure",
    description: "Hawaii has one of the most complex STR tax structures in the country: general excise tax, transient accommodations tax, and high income tax rates. Here's what Hawaii STR investors need to know.",
    publishedAt: "2026-03-01",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Hawaii", "Maui", "Oahu", "Kauai", "general excise tax", "state taxes", "cost segregation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-hawaii.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Hawaii 2025: Maui, Oahu, Kauai Guide | Abode",
      description: "Hawaii's STR tax structure includes general excise tax (4%), transient accommodations tax (10.25%), and high income tax rates. Here's the complete guide for Maui, Oahu, and Kauai STR investors.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-hawaii",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What taxes do Hawaii STR operators pay?", acceptedAnswer: { "@type": "Answer", text: "Hawaii STR operators pay: (1) Hawaii General Excise Tax (GET) of 4% (4.5% in Honolulu county) on gross rental revenue; (2) Transient Accommodations Tax (TAT) of 10.25% on gross rental revenue; (3) County surcharges (Maui County adds 3%, Oahu adds 3%); (4) Hawaii state income tax on net rental income (up to 11%)." } },
          { "@type": "Question", name: "Does Hawaii conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Hawaii does not conform to federal bonus depreciation. Hawaii uses its own depreciation rules, which generally follow pre-TCJA federal law without the bonus depreciation provisions. Investors must track separate federal and Hawaii depreciation schedules." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "warning", title: "Hawaii STR Tax Complexity", text: "Hawaii is one of the most tax-complex states for STR investors. Non-conformity with bonus depreciation, a unique General Excise Tax (GET), high income tax rates, and county surcharges make Hawaii a high-compliance, high-tax environment — but high property values still make cost segregation highly valuable." },
      { type: "paragraph", text: "Hawaii's STR market is driven by world-class tourism demand — Maui, Oahu (Waikiki and North Shore), Kauai, and the Big Island attract millions of visitors annually and command some of the highest ADR in the world. Property values in desirable areas are extraordinary. Cost segregation studies on Hawaii STR properties can generate $300,000+ in first-year federal deductions on premium properties." },
      { type: "heading", level: 2, text: "Hawaii's Layered Tax System for STRs", id: "layered-taxes" },
      { type: "paragraph", text: "Hawaii's STR tax structure has multiple layers that don't exist in most other states:" },
      { type: "list", style: "bulleted", items: [
        "<strong>General Excise Tax (GET):</strong> 4% (4.5% in Honolulu County) on gross rental revenue — this is passed to guests on top of rent but is technically the landlord's tax obligation",
        "<strong>Transient Accommodations Tax (TAT):</strong> 10.25% on gross rental revenue for stays under 180 days",
        "<strong>County TAT Surcharge:</strong> Maui County adds 3%, Honolulu adds 3% — these are on top of the state TAT",
        "<strong>State Income Tax:</strong> Hawaii income tax rates range from 1.4% to 11% on net taxable income",
      ]},
      { type: "table", headers: ["Island / County", "GET", "State TAT", "County TAT", "Total Pass-Through"],
        rows: [
          ["Honolulu (Oahu)", "4.5%", "10.25%", "3%", "~17.75%"],
          ["Maui County", "4%", "10.25%", "3%", "~17.25%"],
          ["Hawaii County (Big Island)", "4%", "10.25%", "3%", "~17.25%"],
          ["Kauai County", "4%", "10.25%", "3%", "~17.25%"],
        ]
      },
      { type: "heading", level: 2, text: "Hawaii Income Tax on Rental Income", id: "income-tax" },
      { type: "paragraph", text: "Hawaii's individual income tax is one of the highest in the country, with a top rate of 11% on taxable income over $400,000. The combination of Hawaii income tax (up to 11%), federal income tax (up to 37%), and the 3.8% NIIT can result in marginal rates approaching 52% for the highest-income Hawaii investors." },
      { type: "paragraph", text: "Hawaii's non-conformity with federal bonus depreciation means cost segregation's year-one impact is significantly reduced at the state level. Federal savings remain fully intact." },
      { type: "heading", level: 2, text: "Cost Segregation in Hawaii: Still Worthwhile", id: "cost-seg-hawaii" },
      { type: "paragraph", text: "Despite the complexity, cost segregation is highly valuable for Hawaii STR investors because of the extraordinary property values. A $3M Maui beachfront home might generate $600,000–$900,000 in federal bonus depreciation via cost seg. At 37% federal, that's $222,000–$333,000 in first-year federal tax savings — which more than justifies the state-level complexity and the study fee." },
      { type: "heading", level: 2, text: "Hawaii STR Regulations", id: "str-regulations" },
      { type: "paragraph", text: "Hawaii has dramatically restricted STRs in recent years, particularly in residential zones. Maui County has effectively banned non-hosted STRs (TVRs — Transient Vacation Rentals) in most residential areas, limiting them to properties with prior nonconforming status or resort/hotel zones. Oahu similarly restricts non-hosted rentals in residential areas. Kauai and the Big Island have their own permitting systems." },
      { type: "faq", question: "Can I still do STR investing in Hawaii given the restrictions?", answer: "Yes, but property selection is critical. Properties in resort zones (Wailea, Ka'anapali, Kaanapali, Ko Olina, Waikiki resort corridors, Princeville) are specifically designated for vacation rental use and face fewer restrictions. These properties command premium prices but also premium rental rates." },
      { type: "cta", title: "Hawaii STR Tax Strategy", text: "Hawaii's complexity is manageable with the right team. Get your free cost segregation estimate and see your federal savings potential.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

];
