// State STR tax guides — South region
// States: Georgia, Virginia, Alabama, Mississippi, Arkansas, Oklahoma, Kentucky, West Virginia, Louisiana
// URL pattern: /learn/str-taxes-[state]

export const stateArticlesSouth = [

  // ─── Georgia ──────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-georgia",
    title: "Short-Term Rental Taxes in Georgia: What Investors Need to Know in 2025",
    description: "Georgia STR investors face a 5.75% flat state income tax and a critical bonus depreciation non-conformity that surprises many investors. Here's the complete Georgia STR tax guide for Blue Ridge, Savannah, and beyond.",
    publishedAt: "2026-03-10",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Georgia", "Blue Ridge", "Savannah", "state taxes", "cost segregation", "bonus depreciation", "Fannin County"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-georgia.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Georgia 2025: Blue Ridge, Savannah & More | Abode",
      description: "Georgia does NOT conform to federal bonus depreciation — a critical issue for STR investors. Here's what Georgia STR investors pay, how the bonus dep decoupling works, and how to plan around it.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-georgia",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Georgia conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "No. Georgia decouples from federal bonus depreciation almost entirely. On your Georgia state return, you must add back the federal bonus depreciation deduction and then use 150% declining balance depreciation over the asset's normal MACRS life. First-year Georgia deductions are far smaller than federal deductions — a critical planning issue for Georgia STR investors." } },
          { "@type": "Question", name: "What is Georgia's state income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Georgia has a 5.75% flat state income tax rate (with a phased reduction to 5.39% beginning in 2024 under HB 1437, subject to revenue triggers). All net rental income is subject to this rate. Combined with federal taxes, Georgia STR investors face a meaningful total tax burden that makes cost segregation planning — including the state decoupling issue — especially important." } },
          { "@type": "Question", name: "What lodging taxes apply to Blue Ridge, Georgia STR rentals?", acceptedAnswer: { "@type": "Answer", text: "Blue Ridge is in Fannin County. Fannin County charges an 8% excise tax on lodging on STR rentals. The state collects sales tax on accommodations at 4%, and counties add their own rates. Total lodging tax in Fannin County is typically around 12% (4% state sales tax + 8% county excise)." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "warning", title: "Georgia Bonus Depreciation Alert", text: "Georgia does NOT conform to federal bonus depreciation. You must add back federal bonus dep on your GA return and use 150% DB depreciation instead. This is one of the most important state tax issues for Georgia STR investors — plan accordingly with a Georgia CPA." },
      { type: "paragraph", text: "Georgia is home to some of the Southeast's most popular STR markets — Blue Ridge and Fannin County mountain cabins, Savannah's historic districts, Tybee Island beaches, and Helen's Bavarian village. The state has a 5.75% flat income tax and a unique, often-overlooked issue: Georgia does not conform to federal bonus depreciation. Investors who take large first-year deductions on their federal return must make a significant Georgia-specific adjustment." },
      { type: "heading", level: 2, text: "Georgia State Income Tax on Rental Income", id: "state-income-tax" },
      { type: "paragraph", text: "Georgia taxes individuals at a 5.75% flat rate on net income, including net rental income reported on Schedule E. Under HB 1437, this rate was set to phase down to 5.39% by 2024, subject to revenue triggers — verify the current rate with a Georgia tax professional. Regardless of the exact rate, Georgia's income tax represents a meaningful additional burden on top of federal taxes. For a $300,000 net rental income, the Georgia tax alone approaches $17,250." },
      { type: "heading", level: 2, text: "The Critical Issue: Georgia Bonus Depreciation Non-Conformity", id: "bonus-dep-nonconformity" },
      { type: "paragraph", text: "Georgia is one of a handful of states that decouples from federal bonus depreciation. Here is how it works: when you take federal bonus depreciation (say, $150,000 on 5-year assets in year one), you must add that entire amount back to your Georgia income. You then replace it with 150% declining balance depreciation calculated over the asset's normal MACRS life." },
      { type: "paragraph", text: "For a $150,000 federal bonus depreciation deduction, the Georgia replacement deduction in year one might be roughly $30,000–$50,000 — meaning you are paying Georgia income tax on an extra $100,000+ of income in year one. At 5.75%, that is an additional $5,750–$7,500 in Georgia taxes. You will recover those deductions over subsequent years as the 150% DB depreciation runs its course, but the timing mismatch is a real cash flow consideration." },
      { type: "callout", variant: "info", title: "Planning Around the Georgia Decoupling", text: "Work with a CPA who understands both federal STR strategy and Georgia's addback rules. The federal benefit of cost segregation is still very real — the Georgia impact is a reduction of state timing benefit, not elimination of federal deductions. Most Georgia STR investors find the federal savings still significantly exceed the Georgia timing penalty." },
      { type: "heading", level: 2, text: "Georgia Lodging and Sales Taxes by Market", id: "lodging-taxes" },
      { type: "table", headers: ["Market / County", "State Sales Tax", "County Lodging Tax", "Estimated Total"],
        rows: [
          ["Fannin County (Blue Ridge)", "4%", "8%", "~12%"],
          ["Chatham County (Savannah)", "4%", "6%", "~10%"],
          ["Chatham County (Tybee Island)", "4%", "6%", "~10%"],
          ["White County (Helen)", "4%", "5%", "~9%"],
          ["Hall County (Lake Lanier area)", "4%", "5%", "~9%"],
          ["Rabun County (Clayton / Tallulah area)", "4%", "5%", "~9%"],
        ]
      },
      { type: "heading", level: 2, text: "Top Georgia STR Markets", id: "top-markets" },
      { type: "paragraph", text: "<strong>Blue Ridge / Fannin County:</strong> Georgia's premier mountain cabin market. Blue Ridge draws Atlanta-area visitors (roughly 2 hours away) for weekend cabin getaways featuring mountain views, hot tubs, fire pits, and game rooms — amenity profiles similar to Smoky Mountains cabins. The 8% county lodging tax is the highest in Georgia. Strong year-round demand includes fall leaf-peeping and holiday escapes." },
      { type: "paragraph", text: "<strong>Savannah:</strong> Georgia's most popular city tourism destination. The STR market is concentrated in the historic district and Victorian homes. Average stays of 2–4 nights are well within STR loophole territory. The historic character of properties means renovation costs and building components can carry distinct values for cost segregation purposes." },
      { type: "paragraph", text: "<strong>Tybee Island:</strong> Georgia's primary beach STR market, located 18 miles east of Savannah. A seasonal market with very strong summer occupancy and meaningful shoulder season demand. Properties range from cottages to larger beach houses." },
      { type: "paragraph", text: "<strong>Helen:</strong> A quirky Bavarian-themed alpine village in the Blue Ridge Mountains. Helen draws visitors for Oktoberfest, tubing on the Chattahoochee River, and mountain scenery. Lower property prices than Blue Ridge proper with year-round appeal." },
      { type: "heading", level: 2, text: "Cost Segregation in Georgia: Still Powerful Despite Decoupling", id: "cost-seg-georgia" },
      { type: "paragraph", text: "Despite the Georgia bonus depreciation decoupling, cost segregation remains highly valuable for Georgia STR investors. The federal deductions are unchanged — 100% bonus depreciation on 5-year and 15-year assets under the OBBBA applies fully on your federal return. For a $500,000 Blue Ridge cabin with $160,000 in cost seg deductions at a 37% federal bracket, the federal savings are approximately $59,200 — largely unaffected by the Georgia state timing issue." },
      { type: "paragraph", text: "The Georgia impact is a temporary timing difference, not a permanent loss of deductions. Over the full depreciation period, Georgia investors recover the same total deductions — just more slowly. The net present value cost of the timing difference is typically $3,000–$8,000 for a typical Georgia STR property, small relative to the $40,000–$80,000+ federal benefit." },
      { type: "faq", question: "Do Airbnb and VRBO collect Georgia lodging taxes automatically?", answer: "Airbnb acts as a marketplace facilitator in Georgia and collects and remits state sales tax on bookings. For county lodging and excise taxes, coverage varies — some Georgia counties have agreements with Airbnb, others do not. VRBO has similar arrangements. Verify with your specific county tax authority and confirm with your platform's tax help center for your county." },
      { type: "cta", title: "Get Your Georgia STR Cost Segregation Estimate", text: "Even with Georgia's bonus depreciation decoupling, federal cost seg savings are substantial. Get your free estimate to see your year-one federal and state net benefit.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Virginia ─────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-virginia",
    title: "Short-Term Rental Taxes in Virginia: What Investors Need to Know in 2025",
    description: "Virginia STR investors face a 2–5.75% graduated income tax and partial bonus depreciation conformity — only 20% in year one, with the rest spread over 5 years. Here's the complete Virginia STR tax guide.",
    publishedAt: "2026-03-11",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Virginia", "Virginia Beach", "Shenandoah Valley", "state taxes", "cost segregation", "bonus depreciation", "transient occupancy tax"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-virginia.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Virginia 2025: Virginia Beach, Shenandoah & More | Abode",
      description: "Virginia allows only 20% of bonus depreciation in year one — the rest is spread over 5 years. Here's what Virginia STR investors pay, transient occupancy taxes by market, and how to plan your deductions.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-virginia",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Virginia conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Virginia partially conforms. Virginia allows only 20% of the federal bonus depreciation deduction in year one. The remaining 80% is deducted ratably over the next 5 tax years (20% per year). Virginia investors get a slower state deduction schedule than the federal 100% first-year treatment, though they ultimately recover the full amount." } },
          { "@type": "Question", name: "What is Virginia's state income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Virginia has a graduated income tax with rates from 2% to 5.75%. The top 5.75% rate applies to taxable income over $17,000 — a very low threshold. Most STR investors with meaningful rental income will be at or near the 5.75% top rate. Virginia taxable income begins with federal AGI with Virginia-specific modifications." } },
          { "@type": "Question", name: "What transient occupancy taxes apply in Virginia?", acceptedAnswer: { "@type": "Answer", text: "Virginia does not have a statewide lodging tax, but localities impose transient occupancy taxes (TOT) ranging from 2% to 8%. Virginia Beach charges 8%. Loudoun County (wine country) charges 7%. Arlington County charges 7.25%. Total rates vary significantly by locality." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Virginia STR Tax Summary", text: "2–5.75% graduated income tax (top rate reached at just $17K of income) | Partial bonus dep: 20% year 1, then 20%/year for years 2–5 | No statewide lodging tax — locality TOT rates 2–8% | Markets: Virginia Beach, Shenandoah Valley, Charlottesville, Chincoteague" },
      { type: "paragraph", text: "Virginia is a diverse STR state with coastal markets on the Atlantic (Virginia Beach, Chincoteague), mountain and wine country retreats (Shenandoah Valley, Charlottesville), and popular historic and college town markets. The state has a graduated income tax and a partial bonus depreciation conformity rule that requires careful planning for STR investors deploying cost segregation." },
      { type: "heading", level: 2, text: "Virginia State Income Tax on Rental Income", id: "state-income-tax" },
      { type: "paragraph", text: "Virginia's graduated income tax tops out at 5.75% — and it reaches that top rate at just $17,000 of taxable income. This means virtually every STR investor with meaningful net rental income in Virginia pays at the 5.75% rate on nearly all of it. Virginia starts with federal AGI and makes Virginia-specific additions and subtractions." },
      { type: "heading", level: 2, text: "Virginia's Partial Bonus Depreciation Conformity", id: "bonus-dep-virginia" },
      { type: "paragraph", text: "Virginia's approach to bonus depreciation is a middle-ground between full decoupling (as Georgia does) and full conformity (as Tennessee and Texas do). Virginia allows 20% of the federal bonus depreciation deduction in the year it is taken, then deducts the remaining 80% ratably over the following 5 tax years — 20% per year for years 2 through 5." },
      { type: "paragraph", text: "In practice, for a $100,000 federal bonus depreciation deduction: Virginia allows $20,000 in year one, then $20,000 in each of years 2 through 5. Unlike Georgia, Virginia investors recover the full deduction — just on a spread schedule. The economic cost is the time value of money on the deferred state deductions." },
      { type: "callout", variant: "info", title: "Virginia Bonus Dep Spread Example", text: "Federal: $150,000 bonus dep in year 1. Virginia: $30,000 in year 1, then $30,000/year for years 2–5. Total over 5 years = $150,000 (same total, different timing). Additional Virginia tax in year 1 vs. full deduction: ~$6,900 at 5.75% on the $120,000 Virginia addback." },
      { type: "heading", level: 2, text: "Transient Occupancy Taxes by Virginia Market", id: "transient-occupancy-tax" },
      { type: "table", headers: ["Locality / Market", "Transient Occupancy Tax Rate", "Notes"],
        rows: [
          ["Virginia Beach (City)", "8%", "Highest rate in VA; plus state sales tax"],
          ["Charlottesville / Albemarle County", "5–7%", "City and county rates differ"],
          ["Loudoun County (wine country / NoVA)", "7%", "Growing STR market near DC"],
          ["Fairfax County", "2%", "Northern VA suburbs; lower rate"],
          ["Page County (Luray / Shenandoah)", "4–5%", "Shenandoah Valley access point"],
          ["Shenandoah County", "4%", "Mountain / valley market"],
          ["Accomack County (Chincoteague Island)", "5.5%", "Beach / wildlife refuge market"],
          ["Northampton County (Eastern Shore)", "5%", "Cape Charles and coastal towns"],
        ]
      },
      { type: "heading", level: 2, text: "Top Virginia STR Markets", id: "top-markets" },
      { type: "paragraph", text: "<strong>Virginia Beach:</strong> The largest coastal city in the country by land area. Virginia Beach's STR market is concentrated around the oceanfront resort area and the Sandbridge neighborhood. Average stays of 3–7 nights during peak season support the STR loophole. The 8% transient occupancy tax is Virginia's highest but in line with national coastal market averages." },
      { type: "paragraph", text: "<strong>Shenandoah Valley:</strong> Virginia's wine and mountain country, stretching along the Appalachian range. Markets in Luray (home to Luray Caverns, one of the East Coast's top tourist attractions), Harrisonburg, Front Royal, and the vineyard towns attract heavy weekend traffic from the DC metro area. Properties tend to be farmhouses, cabins, and rural retreats with high amenity ratios for cost segregation." },
      { type: "paragraph", text: "<strong>Charlottesville:</strong> Home to the University of Virginia and surrounded by Piedmont wine country. Strong STR demand from graduation weekends, football season, wine tourism, and the appeal of the Blue Ridge foothills. A college town with consistent year-round demand and strong average nightly rates." },
      { type: "paragraph", text: "<strong>Chincoteague Island:</strong> Virginia's premier beach island market on the Eastern Shore, adjacent to the Assateague National Seashore and famous for the wild Chincoteague ponies. A seasonal market with very strong summer occupancy and shoulder season wildlife tourism." },
      { type: "heading", level: 2, text: "Cost Segregation in Virginia: Federal Benefits Still Strong", id: "cost-seg-virginia" },
      { type: "paragraph", text: "Virginia's partial conformity rule creates a timing difference, not a permanent loss of deductions. The full 100% federal bonus depreciation benefit applies on your federal return unchanged. For a $500,000 Virginia Beach property with $150,000 in cost seg deductions, federal first-year savings of $55,500 (at 37%) are fully available. The Virginia timing cost is approximately $6,900 in additional year-one state taxes — recovered over the following 4 years." },
      { type: "faq", question: "Do Virginia STR operators need a state license?", answer: "Virginia does not have a statewide STR licensing requirement, but many localities do. Virginia Beach requires STR registration permits. Many Northern Virginia localities have adopted their own ordinances. Check with the specific locality where your property is located for registration, permit, and zoning requirements before operating." },
      { type: "cta", title: "Estimate Your Virginia STR Tax Savings", text: "Virginia's partial bonus dep conformity creates a timing difference, not a permanent loss. See your full federal and state net benefit with a free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Alabama ──────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-alabama",
    title: "Short-Term Rental Taxes in Alabama: What Investors Need to Know in 2025",
    description: "Alabama STR investors enjoy full federal bonus depreciation conformity and a 2–5% graduated income tax. Gulf Shores and Orange Beach dominate the Alabama STR landscape with strong summer demand.",
    publishedAt: "2026-03-11",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Alabama", "Gulf Shores", "Orange Beach", "state taxes", "cost segregation", "bonus depreciation", "beach rental"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-alabama.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Alabama 2025: Gulf Shores & Orange Beach Guide | Abode",
      description: "Alabama conforms to federal bonus depreciation and has a 2–5% graduated income tax. Here's what Alabama STR investors pay, Gulf Shores lodging taxes, and how to maximize cost segregation deductions.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-alabama",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Alabama conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. Alabama conforms to federal bonus depreciation rules, including 100% bonus depreciation under the OBBBA. Alabama STR investors can take the full first-year bonus depreciation deduction on both their federal and Alabama state returns simultaneously." } },
          { "@type": "Question", name: "What is Alabama's state income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Alabama has a graduated income tax with rates of 2% on the first $500 (single) or $1,000 (married), 4% on the next $2,500 (single) or $5,000 (married), and 5% on income above $3,000 (single) or $6,000 (married). Most STR investors with meaningful rental income will be at the 5% top rate." } },
          { "@type": "Question", name: "What lodging taxes apply to Gulf Shores STR rentals?", acceptedAnswer: { "@type": "Answer", text: "Gulf Shores and Orange Beach operators face: Alabama state sales tax (4%), Baldwin County sales/lodging tax (approximately 3%), and Gulf Shores city lodging tax (approximately 7%). Total rates in Gulf Shores typically run 14–15% of rental revenue. Orange Beach has a similar combined total." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Alabama STR Tax Summary", text: "2–5% graduated income tax (top rate 5%) | Conforms to federal bonus depreciation | ~14–15% total lodging tax in Gulf Shores | 4% state sales tax on rentals | Strong Gulf Coast market: Gulf Shores, Orange Beach, Gulf State Park area" },
      { type: "paragraph", text: "Alabama's STR market is heavily concentrated along the Gulf Coast — specifically Gulf Shores and Orange Beach in Baldwin County, which together form one of the Southeast's premier beach vacation destinations. The state's income tax tops out at a modest 5% and fully conforms to federal bonus depreciation, making Alabama a relatively straightforward state for STR tax planning with meaningful combined benefits from cost segregation." },
      { type: "heading", level: 2, text: "Alabama State Income Tax on Rental Income", id: "state-income-tax" },
      { type: "paragraph", text: "Alabama's income tax reaches its top rate of 5% at very modest income levels. Most STR investors will effectively pay 5% on nearly all their net rental income. Alabama starts with federal AGI and makes Alabama-specific modifications. The full benefit of cost segregation flows to the Alabama state return — there is no Alabama bonus depreciation addback requirement." },
      { type: "heading", level: 2, text: "Alabama Bonus Depreciation Conformity: A Key Advantage", id: "bonus-dep-alabama" },
      { type: "paragraph", text: "Alabama's conformity to federal bonus depreciation is a meaningful advantage compared to neighboring Georgia, which decouples entirely. If you take $200,000 in federal bonus depreciation on an Alabama STR property, you take the same $200,000 deduction on your Alabama return. Cost segregation studies on Alabama properties generate both immediate federal and state tax savings." },
      { type: "heading", level: 2, text: "Gulf Coast Lodging Taxes", id: "lodging-taxes" },
      { type: "table", headers: ["Market / Jurisdiction", "State Sales Tax", "County Tax", "City Tax", "Estimated Total"],
        rows: [
          ["Gulf Shores (Baldwin County)", "4%", "~3%", "~7%", "~14%"],
          ["Orange Beach (Baldwin County)", "4%", "~3%", "~7%", "~14%"],
          ["Gulf State Park area", "4%", "~3%", "varies", "~12–15%"],
          ["Mobile (Mobile County)", "4%", "~2%", "~5%", "~11%"],
          ["Huntsville (Madison County)", "4%", "~2%", "~5%", "~11%"],
        ]
      },
      { type: "heading", level: 2, text: "The Gulf Shores and Orange Beach STR Market", id: "gulf-shores-market" },
      { type: "paragraph", text: "Gulf Shores and Orange Beach together form Alabama's dominant STR market and one of the Southeast's most popular beach destinations. The Gulf State Park area — with pristine white sand beaches, the Gulf State Park Lodge, and an extensive trail system — anchors a market drawing families, groups, and couples from Alabama, Georgia, Tennessee, and the broader Southeast." },
      { type: "paragraph", text: "This is an intensely seasonal market: peak season runs Memorial Day through Labor Day, with strong shoulder demand in spring and fall. Winter occupancy drops significantly. Properties range from modest beach condos ($200,000–$400,000) to large beachfront homes ($800,000–$3M+). Beachfront and gulf-view properties can generate $80,000–$200,000+ in annual gross revenue during strong years." },
      { type: "paragraph", text: "The typical high personal property ratio in Gulf Coast vacation homes — furnished interiors, outdoor amenities, recreation equipment — supports cost segregation ratios of 20–30% of purchase price in short-lived assets eligible for bonus depreciation." },
      { type: "heading", level: 2, text: "Alabama STR Licensing Requirements", id: "licensing" },
      { type: "paragraph", text: "Alabama requires STR operators to register with the Alabama Department of Revenue for sales tax collection. Baldwin County has its own licensing and registration requirements for STRs. Both Gulf Shores and Orange Beach require local business licenses for STR operators. Properties in or near Gulf State Park have additional permit requirements through the Alabama State Park system." },
      { type: "heading", level: 2, text: "Cost Segregation on Alabama Gulf Coast Properties", id: "cost-seg-alabama" },
      { type: "paragraph", text: "A $500,000 Gulf Shores beach house with a cost segregation study might identify 22–28% of purchase price in 5-year and 15-year assets — roughly $110,000–$140,000 in bonus-eligible deductions. At a 32% federal bracket, that is $35,200–$44,800 in first-year federal savings. At a 37% bracket, it is $40,700–$51,800. Alabama's 5% conforming state benefit adds another $5,500–$7,000 in year-one state tax savings." },
      { type: "faq", question: "Do Airbnb and VRBO collect Alabama lodging taxes automatically?", answer: "Airbnb collects and remits Alabama state sales tax as a marketplace facilitator. Baldwin County and city lodging taxes in Gulf Shores and Orange Beach are largely collected by platforms as well under marketplace facilitator agreements. Confirm current coverage with Airbnb and VRBO's tax help centers for your specific jurisdiction before assuming full platform coverage." },
      { type: "cta", title: "Estimate Your Alabama STR Tax Savings", text: "Alabama's full bonus depreciation conformity means maximum first-year deductions at both the federal and state level. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Mississippi ──────────────────────────────────────────────────────────
  {
    slug: "str-taxes-mississippi",
    title: "Short-Term Rental Taxes in Mississippi: What Investors Need to Know in 2025",
    description: "Mississippi has a 5% flat income tax, conforms to federal bonus depreciation, and a growing Gulf Coast STR market. Here's the complete Mississippi STR tax guide for Biloxi, Gulfport, and Oxford.",
    publishedAt: "2026-03-12",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Mississippi", "Biloxi", "Gulf Coast", "Oxford", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-mississippi.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Mississippi 2025: Gulf Coast & Oxford Guide | Abode",
      description: "Mississippi has a 5% flat income tax and conforms to federal bonus depreciation. Here's what Mississippi STR investors pay, Gulf Coast lodging taxes, and how cost segregation works.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-mississippi",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is Mississippi's state income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Mississippi has a 5% flat income tax rate on taxable income. Rental income reported on Schedule E flows to Mississippi taxable income. Mississippi conforms to federal depreciation methods including bonus depreciation, so cost segregation benefits apply on both federal and Mississippi state returns." } },
          { "@type": "Question", name: "Does Mississippi conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. Mississippi conforms to federal bonus depreciation. STR investors can take 100% bonus depreciation on eligible short-lived assets identified in a cost segregation study, reducing both federal and Mississippi state taxable income in year one." } },
          { "@type": "Question", name: "What taxes do Mississippi STR operators collect?", acceptedAnswer: { "@type": "Answer", text: "Mississippi STR operators are subject to the 7% state sales tax on short-term rental revenue, plus any local municipal lodging taxes. The Biloxi/Gulf Coast area has the most active STR market, with total effective rates of approximately 10–12% depending on the specific municipality." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Mississippi STR Tax Summary", text: "5% flat state income tax | Conforms to federal bonus depreciation | 7% state sales tax on rentals | Primary markets: Gulf Coast (Biloxi, Gulfport, Ocean Springs) and Oxford (Ole Miss football demand) | Combined federal + state cost seg benefits available" },
      { type: "paragraph", text: "Mississippi's STR market is smaller and more concentrated than most Southern states, with activity primarily on the Gulf Coast (Biloxi, Gulfport, Ocean Springs) and in Oxford (home to the University of Mississippi). The state has a 5% flat income tax and full conformity to federal bonus depreciation — meaning Mississippi STR investors benefit from cost segregation on both their federal and state returns in year one." },
      { type: "heading", level: 2, text: "Mississippi State Income Tax", id: "state-income-tax" },
      { type: "paragraph", text: "Mississippi's 5% flat income tax applies to net rental income after all deductions. Mississippi begins with federal taxable income and makes state-specific adjustments. Because Mississippi conforms to federal depreciation methods — including bonus depreciation — the same depreciation deductions on your federal Schedule E also reduce your Mississippi taxable income. Cost segregation is particularly efficient in Mississippi since federal and state benefits accrue simultaneously." },
      { type: "heading", level: 2, text: "Mississippi Sales Tax on STR Rentals", id: "sales-tax" },
      { type: "paragraph", text: "Mississippi imposes a 7% state sales tax on short-term rental accommodations (stays under 30 days). With one of the higher state sales tax rates in the country, STR operators must register with the Mississippi Department of Revenue to collect and remit. Airbnb acts as a marketplace facilitator in Mississippi for state sales tax collection on its platform bookings." },
      { type: "heading", level: 2, text: "Mississippi Lodging Tax Overview", id: "lodging-taxes" },
      { type: "table", headers: ["Market / Jurisdiction", "State Sales Tax", "Local/City Tax", "Estimated Total"],
        rows: [
          ["Biloxi (Harrison County)", "7%", "3–5%", "~10–12%"],
          ["Gulfport (Harrison County)", "7%", "3–4%", "~10–11%"],
          ["Ocean Springs (Jackson County)", "7%", "2–3%", "~9–10%"],
          ["Oxford (Lafayette County)", "7%", "2%", "~9%"],
          ["Hattiesburg (Forrest County)", "7%", "2%", "~9%"],
          ["Bay St. Louis (Hancock County)", "7%", "2%", "~9%"],
        ]
      },
      { type: "heading", level: 2, text: "The Gulf Coast STR Market", id: "gulf-coast-market" },
      { type: "paragraph", text: "Mississippi's Gulf Coast stretches from Bay St. Louis to Pascagoula, with Biloxi and Gulfport as the principal population centers. Biloxi has a significant casino and entertainment industry that drives substantial visitor volume. Ocean Springs, directly east of Biloxi, is an arts-focused community with a walkable downtown that has developed a boutique STR market attracting coastal tourism and festival visitors." },
      { type: "paragraph", text: "The Gulf Coast STR market competes with Mobile, Alabama and the Florida Panhandle. Property values on Mississippi's Gulf Coast are generally lower than comparable Alabama or Florida Gulf properties, which can create attractive gross yield ratios for cost-conscious investors willing to accept more modest absolute revenue numbers." },
      { type: "heading", level: 2, text: "Oxford: The College Town STR Market", id: "oxford-market" },
      { type: "paragraph", text: "Oxford is home to the University of Mississippi — and Ole Miss football drives intense demand during 7–8 home game weekends per year. Game weekend STR rates in Oxford routinely run 5–10x normal nightly rates for the biggest games against rivals like Alabama, LSU, and Tennessee. The challenge is that Oxford's STR market is intensely seasonal and event-driven. Strong football weekends compensate for relatively quiet off-season periods." },
      { type: "heading", level: 2, text: "Cost Segregation in Mississippi", id: "cost-seg-mississippi" },
      { type: "paragraph", text: "Mississippi's full bonus depreciation conformity and 5% flat tax means every dollar of cost segregation deductions reduces both federal and state taxes simultaneously. For a $400,000 Gulf Coast property with $90,000 in cost seg deductions, the combined first-year benefit is approximately $33,300 federal (at 37%) + $4,500 state = $37,800 total, against a typical study cost of $4,000–$7,000." },
      { type: "faq", question: "Are there STR-specific regulations in Biloxi?", answer: "Mississippi municipalities have varying STR regulations. Biloxi and other Gulf Coast cities may require business licenses and sales tax registration. Unlike some larger metros, Mississippi's municipalities have generally not adopted stringent STR permit or cap systems — though HOA rules and local zoning can restrict STR use in newer residential developments. Always verify local requirements before acquiring an STR investment property in Mississippi." },
      { type: "cta", title: "Estimate Your Mississippi STR Tax Savings", text: "Mississippi's full bonus dep conformity means federal and state deductions stack together in year one. Get your free cost segregation estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Arkansas ─────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-arkansas",
    title: "Short-Term Rental Taxes in Arkansas: What Investors Need to Know in 2025",
    description: "Arkansas STR investors benefit from full federal bonus depreciation conformity and a top income tax rate of 4.9%. Hot Springs, Eureka Springs, and the Ozarks are the top STR markets.",
    publishedAt: "2026-03-12",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Arkansas", "Eureka Springs", "Hot Springs", "Ozarks", "Bentonville", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-arkansas.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Arkansas 2025: Ozarks, Hot Springs & More | Abode",
      description: "Arkansas conforms to federal bonus depreciation and has a top income tax rate of 4.9%. Here's the complete guide for Arkansas STR investors in the Ozarks, Hot Springs, Eureka Springs, and Bentonville.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-arkansas",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Arkansas conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. Arkansas conforms to federal bonus depreciation. STR investors in Arkansas can take 100% bonus depreciation on eligible assets identified in a cost segregation study on both their federal and Arkansas state returns in year one." } },
          { "@type": "Question", name: "What is Arkansas's state income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Arkansas has a graduated income tax ranging from 2% to 4.9%. The top 4.9% rate applies to income over approximately $87,000. Arkansas has been reducing its top rate in recent years as part of ongoing tax reform. Most STR investors with meaningful rental income will be near the 4.9% top rate." } },
          { "@type": "Question", name: "What sales and tourism taxes apply to Arkansas STR rentals?", acceptedAnswer: { "@type": "Answer", text: "Arkansas imposes a 6.5% state sales tax on short-term rental accommodations. Cities and counties add tourism and lodging taxes on top. Eureka Springs has an additional city tourism development tax. Total rates typically run 9–13% depending on the specific location." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Arkansas STR Tax Summary", text: "2–4.9% graduated income tax (top rate at ~$87K) | Conforms to federal bonus depreciation | 6.5% state sales tax on rentals | Top markets: Ozark Mountains, Hot Springs, Eureka Springs, Bentonville, Buffalo National River corridor" },
      { type: "paragraph", text: "Arkansas is an underappreciated STR market with strong fundamentals in outdoor recreation, hot springs, and mountain regions. The Ozark Mountains, Buffalo National River corridor, and the resort town of Hot Springs anchor a diverse STR landscape. The state's conformity to federal bonus depreciation and a modest 4.9% top income tax rate create a favorable tax environment for Arkansas STR investors." },
      { type: "heading", level: 2, text: "Arkansas State Income Tax", id: "state-income-tax" },
      { type: "paragraph", text: "Arkansas has a graduated income tax structure that has been reduced in recent years, with the top rate now at 4.9% — applying to income over approximately $87,000. Arkansas conforms to federal tax definitions, meaning net rental income from Schedule E flows into Arkansas taxable income after the same deductions — including federal bonus depreciation — are applied." },
      { type: "heading", level: 2, text: "Arkansas Sales and Tourism Taxes on STRs", id: "sales-tourism-taxes" },
      { type: "table", headers: ["Market / Jurisdiction", "State Sales Tax", "Local/Tourism Tax", "Estimated Total"],
        rows: [
          ["Hot Springs (Garland County)", "6.5%", "3–4%", "~9.5–10.5%"],
          ["Eureka Springs (Carroll County)", "6.5%", "4–5%", "~10.5–11.5%"],
          ["Fayetteville (Washington County)", "6.5%", "2–3%", "~8.5–9.5%"],
          ["Bentonville (Benton County)", "6.5%", "2%", "~8.5%"],
          ["Mountain Home (Baxter County)", "6.5%", "2%", "~8.5%"],
          ["Jasper / Newton County (Buffalo River)", "6.5%", "1–2%", "~7.5–8.5%"],
        ]
      },
      { type: "heading", level: 2, text: "Top Arkansas STR Markets", id: "top-markets" },
      { type: "paragraph", text: "<strong>Hot Springs:</strong> Arkansas's original resort town, built around the thermal springs of Hot Springs National Park. Hot Springs draws visitors for the national park, Bathhouse Row (historic spa district), horse racing at Oaklawn Park, and Lake Hamilton water recreation. Properties range from historic cottages to lakefront homes on Lake Hamilton. A year-round market with diverse demand drivers." },
      { type: "paragraph", text: "<strong>Eureka Springs:</strong> A Victorian-era mountain town in the Ozarks that has reinvented itself as an arts, entertainment, and weekend getaway destination. The city is compact and walkable, with strong STR demand from couples and groups visiting for music venues, craft breweries, and a distinctive Victorian character. Historic architecture creates interesting cost segregation dynamics for renovated properties." },
      { type: "paragraph", text: "<strong>Northwest Arkansas (Bentonville / Fayetteville):</strong> Bentonville, home to Walmart's global headquarters, generates corporate travel and executive relocation demand for furnished rentals. The Crystal Bridges Museum of American Art and the region's world-class mountain biking trail system (Oz Trails) draw significant leisure visitors. Fayetteville has University of Arkansas football weekend demand comparable to Oxford's Ole Miss pattern." },
      { type: "paragraph", text: "<strong>Buffalo National River Corridor:</strong> The Ozark Mountain wilderness along the Buffalo National River — America's first national river — draws outdoor recreationists, kayakers, and hikers. Rustic cabins along the river corridor can command premium rates during peak floating season (April–June)." },
      { type: "heading", level: 2, text: "Cost Segregation in Arkansas", id: "cost-seg-arkansas" },
      { type: "paragraph", text: "Arkansas STR properties in mountain and lakefront settings tend to have strong personal property ratios. Ozark Mountain cabins with hot tubs, decks, fire pits, and recreational amenities typically yield 20–30% of purchase price in 5-year and 15-year assets. At the 4.9% top Arkansas rate combined with federal savings at 32–37%, cost segregation generates compelling returns. A $400,000 Hot Springs lakefront property with $100,000 in cost seg deductions could yield $37,000–$41,900 in combined first-year savings." },
      { type: "faq", question: "Is Airbnb popular in the Ozarks and Hot Springs?", answer: "Yes. Airbnb and VRBO both have significant presence in Hot Springs, Eureka Springs, and the Ozark Mountain corridor. Both platforms act as marketplace facilitators for Arkansas state sales tax collection. Local tourism and lodging taxes may or may not be collected by platforms depending on specific local agreements — verify with your county tax authority." },
      { type: "cta", title: "Estimate Your Arkansas STR Tax Savings", text: "Arkansas's full bonus dep conformity and 4.9% top rate create an attractive combined federal and state tax picture. Get your free cost seg estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Oklahoma ─────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-oklahoma",
    title: "Short-Term Rental Taxes in Oklahoma: What Investors Need to Know in 2025",
    description: "Oklahoma STR investors benefit from full federal bonus depreciation conformity and a top income tax rate of 4.75%. Broken Bow/Hochatown is the fastest-growing cabin market in the South.",
    publishedAt: "2026-03-13",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Oklahoma", "Broken Bow", "Hochatown", "Grand Lake", "state taxes", "cost segregation", "bonus depreciation", "cabin rental"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-oklahoma.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Oklahoma 2025: Broken Bow, Hochatown & More | Abode",
      description: "Oklahoma conforms to federal bonus depreciation and has a top income tax rate of 4.75%. Broken Bow/Hochatown is the fastest-growing cabin STR market in the South. Here's the complete Oklahoma investor guide.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-oklahoma",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Oklahoma conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. Oklahoma conforms to federal bonus depreciation, including 100% bonus depreciation under the OBBBA. Oklahoma STR investors can take the full bonus depreciation deduction on both federal and Oklahoma state returns in year one." } },
          { "@type": "Question", name: "Why is Broken Bow/Hochatown considered the fastest-growing cabin STR market in the South?", acceptedAnswer: { "@type": "Answer", text: "The Broken Bow/Hochatown area in McCurtain County, Oklahoma has seen explosive growth over the past 5–7 years. The combination of dense pine forests (unique in Oklahoma), Beavers Bend State Park, and proximity to the DFW metro (3.5 hour drive) has made it a premier weekend retreat. New luxury cabin construction has been rapid, with well-positioned properties generating $60,000–$150,000+ annually." } },
          { "@type": "Question", name: "What taxes do Oklahoma STR operators collect?", acceptedAnswer: { "@type": "Answer", text: "Oklahoma STR operators collect: 4.5% state sales tax on rental revenue, plus city and county sales taxes that vary by location. McCurtain County (Broken Bow/Hochatown) has additional lodging taxes. Total effective rates in the Broken Bow area run approximately 10–13% of rental revenue." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Oklahoma STR Tax Summary", text: "0.25–4.75% graduated income tax (top rate 4.75%) | Conforms to federal bonus depreciation | 4.5% state sales tax + local taxes | Broken Bow/Hochatown = fastest-growing cabin STR market in the South | Grand Lake and Lake Eufaula also active markets" },
      { type: "paragraph", text: "Oklahoma is home to one of the most compelling STR market stories in the country: the Broken Bow/Hochatown cabin market in McCurtain County. Driven by proximity to the Dallas-Fort Worth metropolitan area, the dense Ouachita National Forest setting, and Beavers Bend State Park, this market has seen explosive growth that consistently outpaces supply. Oklahoma's full conformity to federal bonus depreciation and a top income tax rate of 4.75% make the state's STR tax environment among the most favorable in the South." },
      { type: "heading", level: 2, text: "Oklahoma State Income Tax", id: "state-income-tax" },
      { type: "paragraph", text: "Oklahoma's graduated income tax ranges from 0.25% to 4.75%, with the top rate applying to taxable income over approximately $12,200 for single filers and $15,000 for joint filers. Most STR investors will reach the 4.75% top rate quickly. Oklahoma conforms to federal tax treatment of rental income, and the full benefit of cost segregation deductions — including bonus depreciation — reduces Oklahoma taxable income dollar-for-dollar." },
      { type: "heading", level: 2, text: "Oklahoma Sales Tax on STR Rentals", id: "sales-tax" },
      { type: "table", headers: ["Market / Jurisdiction", "State Sales Tax", "County/City Tax", "Estimated Total"],
        rows: [
          ["Broken Bow / Hochatown (McCurtain County)", "4.5%", "5.5–8%", "~10–12.5%"],
          ["Grand Lake (Mayes/Delaware/Ottawa County)", "4.5%", "3–5%", "~7.5–9.5%"],
          ["Lake Eufaula (McIntosh County)", "4.5%", "3–4%", "~7.5–8.5%"],
          ["Oklahoma City (Oklahoma County)", "4.5%", "4.375%", "~8.875%"],
          ["Tulsa (Tulsa County)", "4.5%", "4.017%", "~8.5%"],
          ["Medicine Park (Comanche County)", "4.5%", "3%", "~7.5%"],
        ]
      },
      { type: "heading", level: 2, text: "Broken Bow / Hochatown: Oklahoma's STR Phenomenon", id: "broken-bow-market" },
      { type: "paragraph", text: "No discussion of Oklahoma STR investing is complete without highlighting Broken Bow and Hochatown. Located in the pine forest foothills of the Ouachita Mountains in far southeastern Oklahoma, this area has become one of the most talked-about cabin markets in the country. The combination of factors that drove explosive growth is instructive for any investor evaluating the market:" },
      { type: "list", style: "bulleted", items: [
        "<strong>Proximity to DFW:</strong> Broken Bow is approximately 3.5 hours from Dallas — ideal for a long weekend escape from one of America's largest metro areas",
        "<strong>Unique pine forest setting:</strong> The dense Ouachita pine forests look nothing like typical Oklahoma topography — the foggy, misty aesthetic photographs beautifully and differentiates the market",
        "<strong>Beavers Bend State Park:</strong> State park with river activities, hiking, miniature golf, and a nature center anchors the recreation infrastructure",
        "<strong>Luxury cabin supply:</strong> Developers built high-end A-frame and modern cabins with hot tubs, fire pits, and designer interiors that photograph perfectly for listing platforms",
        "<strong>Year-round demand:</strong> Summer camping, fall foliage, holiday escapes, and winter cozy retreats maintain consistent occupancy across seasons",
      ]},
      { type: "paragraph", text: "Revenue figures in Broken Bow/Hochatown are impressive: well-positioned 2-bedroom luxury cabins routinely generate $70,000–$120,000 annually. Larger premium properties with multiple bedrooms, outdoor amenities, and designer interiors can generate $150,000–$250,000+. New cabin construction has been rapid, but demand has largely kept pace in the highest-quality segments of the market." },
      { type: "heading", level: 2, text: "Grand Lake and Lake Eufaula", id: "other-markets" },
      { type: "paragraph", text: "Grand Lake O' the Cherokees in northeastern Oklahoma is the state's premier lake STR market, drawing boaters, fishermen, and water sports enthusiasts from the Tulsa metro. Lake Eufaula — one of the largest man-made lakes in the U.S. — offers similar lakefront STR opportunities at generally lower property prices. Both are more seasonal than Broken Bow, with peak demand concentrated in summer." },
      { type: "heading", level: 2, text: "Cost Segregation in Oklahoma: Broken Bow Cabins", id: "cost-seg-oklahoma" },
      { type: "paragraph", text: "Broken Bow's luxury A-frame cabins are excellent cost segregation candidates. High-design interiors (premium furniture, designer lighting, hot tub decks, fire pit terraces, outdoor kitchens) create above-average personal property ratios. A typical $500,000 Hochatown cabin might have 28–35% of its value in 5-year and 15-year property — $140,000–$175,000 in bonus-eligible deductions. At 37% federal + 4.75% Oklahoma state, first-year combined savings could reach $58,800–$73,500." },
      { type: "faq", question: "Are there restrictions on new STR cabin development near Broken Bow?", answer: "McCurtain County has seen significant new cabin development, and local authorities have been examining zoning and regulation as the market matures. Some specific areas around Broken Bow and Hochatown have adopted short-term rental regulations or are under review. Before acquiring or developing a cabin in this market, verify current zoning, permit requirements, and any deed restrictions." },
      { type: "cta", title: "Get Your Oklahoma STR Cost Segregation Estimate", text: "Broken Bow luxury cabins often yield 28–35% personal property ratios — among the highest in the country. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Kentucky ─────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-kentucky",
    title: "Short-Term Rental Taxes in Kentucky: What Investors Need to Know in 2025",
    description: "Kentucky has a 4% flat income tax and full federal bonus depreciation conformity. Red River Gorge, Lake Cumberland, and Louisville's Derby season are the primary STR demand drivers.",
    publishedAt: "2026-03-13",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Kentucky", "Red River Gorge", "Lake Cumberland", "Louisville", "Kentucky Derby", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-kentucky.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Kentucky 2025: Red River Gorge, Lake Cumberland & More | Abode",
      description: "Kentucky has a 4% flat income tax and fully conforms to federal bonus depreciation. Here's what Kentucky STR investors pay, transient room tax rates by county, and how cost segregation works.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-kentucky",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Kentucky conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. Kentucky conforms to federal bonus depreciation. STR investors can take 100% bonus depreciation on short-lived assets identified in a cost segregation study, reducing both federal and Kentucky state taxable income in year one." } },
          { "@type": "Question", name: "What is Kentucky's state income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Kentucky has a 4% flat income tax rate on net rental income. Kentucky transitioned from a graduated rate structure to a flat 4% rate effective 2023, with planned reductions in subsequent years depending on revenue triggers. Verify the current applicable rate with a Kentucky tax professional." } },
          { "@type": "Question", name: "What transient room taxes apply in Kentucky?", acceptedAnswer: { "@type": "Answer", text: "Kentucky has a statewide transient room tax of 1% on lodging. Counties and cities add their own transient room taxes ranging from 1–7.5%, depending on the jurisdiction. The total varies by location but typically runs 2–8.5% in popular STR markets. Louisville has the highest combined rates in the state." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Kentucky STR Tax Summary", text: "4% flat income tax (with planned further reductions) | Conforms to federal bonus depreciation | 1% state transient room tax + local taxes (1–7.5%) | Top markets: Red River Gorge, Lake Cumberland, Louisville | Derby season creates extreme short-term demand spikes in Louisville" },
      { type: "paragraph", text: "Kentucky offers a straightforward and investor-friendly state tax environment for STR operators: a flat 4% income tax that has been on a downward trajectory, full conformity to federal bonus depreciation, and relatively low transient room taxes in most markets. The primary STR markets are split between outdoor recreation (Red River Gorge, Lake Cumberland, Daniel Boone National Forest) and urban event demand (Louisville, particularly around the Kentucky Derby)." },
      { type: "heading", level: 2, text: "Kentucky State Income Tax", id: "state-income-tax" },
      { type: "paragraph", text: "Kentucky simplified its tax structure by adopting a 4% flat income tax effective 2023, down from a graduated structure with a prior top rate of 5%. Kentucky has further reductions written into law contingent on revenue triggers. The flat rate structure means all net rental income is taxed at the same rate, simplifying planning. Kentucky conforms to federal depreciation definitions — cost segregation deductions reduce both federal and Kentucky taxable income in year one." },
      { type: "heading", level: 2, text: "Kentucky Transient Room Taxes by Market", id: "transient-room-taxes" },
      { type: "table", headers: ["Market / County", "State Tax (1%)", "County/City Tax", "Estimated Total"],
        rows: [
          ["Louisville (Jefferson County)", "1%", "4.5–7.5%", "~5.5–8.5%"],
          ["Lexington (Fayette County)", "1%", "4%", "~5%"],
          ["Stanton/Powell County (Red River Gorge gateway)", "1%", "2%", "~3%"],
          ["Lake Cumberland (Russell/Wayne County)", "1%", "1–2%", "~2–3%"],
          ["Mammoth Cave area (Edmonson County)", "1%", "1–2%", "~2–3%"],
          ["Bowling Green (Warren County)", "1%", "3%", "~4%"],
        ]
      },
      { type: "heading", level: 2, text: "Red River Gorge: Kentucky's Top Outdoor STR Market", id: "red-river-gorge" },
      { type: "paragraph", text: "The Red River Gorge Geological Area in Powell, Wolfe, and Menifee counties is one of the most spectacular rock climbing and hiking destinations east of the Mississippi. The Daniel Boone National Forest setting — with over 100 miles of hiking trails, the Natural Bridge State Resort Park, and world-renowned climbing routes — draws outdoor enthusiasts year-round. STR demand is driven by climbers, hikers, backpackers, and couples seeking secluded mountain retreats." },
      { type: "paragraph", text: "Red River Gorge STR properties tend to be rustic cabins and cottages accessible to trailheads. Property values are modest compared to national markets — $150,000–$350,000 for typical cabins — with solid gross revenue potential of $30,000–$80,000 annually for well-positioned properties. The outdoor amenity components (decks, hot tubs, fire pits) support meaningful cost segregation benefits relative to purchase price." },
      { type: "heading", level: 2, text: "Lake Cumberland: Kentucky's Lakefront Market", id: "lake-cumberland" },
      { type: "paragraph", text: "Lake Cumberland in south-central Kentucky is known as the 'Houseboat Capital of the World' — and houseboat rentals are a unique STR category here alongside traditional lakefront cabin STRs. The lake draws water sports enthusiasts, boaters, and fishing tourists. Peak season is Memorial Day through Labor Day, with strong shoulder demand in spring and fall for fishing." },
      { type: "heading", level: 2, text: "Louisville: Derby Season Demand", id: "louisville-market" },
      { type: "paragraph", text: "Louisville's STR market is highly event-driven, with the Kentucky Derby (first Saturday in May) creating extreme demand spikes. Churchill Downs and the surrounding Highlands and NuLu neighborhoods are prime STR locations. Derby weekend properties routinely command 10–15x normal nightly rates, with many bookings confirmed a year in advance. Louisville also has consistent demand from bourbon trail tourism, conventions, and University of Louisville events." },
      { type: "heading", level: 2, text: "Cost Segregation in Kentucky", id: "cost-seg-kentucky" },
      { type: "paragraph", text: "Kentucky's full bonus depreciation conformity and 4% flat tax create clean math for cost segregation ROI. Red River Gorge and Lake Cumberland properties with high outdoor amenity ratios typically yield 20–28% personal property ratios. A $300,000 gorge cabin with $75,000 in cost seg deductions saves approximately $27,750 federal (at 37%) + $3,000 Kentucky (at 4%) = $30,750 in year one, against a study cost of $3,500–$6,000." },
      { type: "faq", question: "Does Kentucky have a state STR licensing requirement?", answer: "Kentucky does not have a statewide STR licensing requirement. Local jurisdictions handle registration and permitting. Louisville and Lexington have STR registration programs. Rural counties typically have minimal regulation. Always verify local requirements for your specific property location before operating an STR in Kentucky." },
      { type: "cta", title: "Estimate Your Kentucky STR Tax Savings", text: "Kentucky's 4% flat tax + full bonus dep conformity = clean, predictable tax savings. Get your free cost segregation estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── West Virginia ────────────────────────────────────────────────────────
  {
    slug: "str-taxes-west-virginia",
    title: "Short-Term Rental Taxes in West Virginia: What Investors Need to Know in 2025",
    description: "West Virginia has a 3–6.5% graduated income tax and full federal bonus depreciation conformity. Snowshoe Mountain, New River Gorge, and Canaan Valley are the premier STR markets.",
    publishedAt: "2026-03-14",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "West Virginia", "Snowshoe Mountain", "New River Gorge", "Canaan Valley", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-west-virginia.jpg",
    seo: {
      title: "Short-Term Rental Taxes in West Virginia 2025: Snowshoe, New River Gorge & More | Abode",
      description: "West Virginia conforms to federal bonus depreciation and has a 3–6.5% graduated income tax. Here's what WV STR investors pay in Snowshoe Mountain, New River Gorge, and Canaan Valley.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-west-virginia",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does West Virginia conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. West Virginia conforms to federal bonus depreciation. STR investors can take 100% bonus depreciation on eligible assets identified in a cost segregation study on both their federal and West Virginia state returns." } },
          { "@type": "Question", name: "What is West Virginia's state income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "West Virginia has a graduated income tax ranging from 3% (on income up to $10,000) to 6.5% (on income over $60,000). Most STR investors with meaningful rental income will be at or near the 6.5% top rate. West Virginia has been discussing income tax reform in recent sessions — verify the current applicable rates with a WV tax professional." } },
          { "@type": "Question", name: "What sales taxes apply to West Virginia STR rentals?", acceptedAnswer: { "@type": "Answer", text: "West Virginia has a 6% state sales tax that applies to short-term rental accommodations. Local counties may add hotel/motel taxes on top. Total transient tax rates in popular STR markets like Snowshoe and Fayetteville (New River Gorge gateway) typically run 7–10% depending on specific location." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "West Virginia STR Tax Summary", text: "3–6.5% graduated income tax (top rate at $60K) | Conforms to federal bonus depreciation | 6% state sales tax on rentals | Top markets: Snowshoe Mountain (ski/summer), New River Gorge National Park, Canaan Valley | Proximity to DC, Charlotte, Pittsburgh metro areas drives demand" },
      { type: "paragraph", text: "West Virginia's STR market is anchored by three premier outdoor recreation destinations: Snowshoe Mountain Resort (the Mid-Atlantic's largest ski resort), New River Gorge National Park (designated as a national park in 2020), and Canaan Valley (skiing, mountain biking, and hiking). The state's conformity to federal bonus depreciation is a meaningful advantage, though its 6.5% top income tax rate is the highest in this South region guide." },
      { type: "heading", level: 2, text: "West Virginia State Income Tax", id: "state-income-tax" },
      { type: "paragraph", text: "West Virginia's graduated income tax ranges from 3% on the first $10,000 to 6.5% on income over $60,000. At the top rate, West Virginia is on the higher end for the states in this region. However, West Virginia's full conformity to federal bonus depreciation means cost segregation delivers simultaneous federal and state deductions, partially offsetting the higher rate. Note that West Virginia has been actively discussing income tax reform — verify current applicable rates." },
      { type: "heading", level: 2, text: "West Virginia Sales Tax on STR Rentals", id: "sales-tax" },
      { type: "paragraph", text: "West Virginia imposes a 6% sales tax on short-term rental accommodations. Counties may add additional hotel/motel excise taxes. Total transient tax rates in popular STR markets typically run 7–10%. STR operators must register with the West Virginia State Tax Department for sales tax collection purposes." },
      { type: "heading", level: 2, text: "Top West Virginia STR Markets", id: "top-markets" },
      { type: "table", headers: ["Market", "County", "Primary Season", "Notes"],
        rows: [
          ["Snowshoe Mountain", "Pocahontas County", "Winter ski + summer", "WV's largest ski resort; year-round resort operations"],
          ["New River Gorge", "Fayette County", "Spring–fall", "National Park designation (2020) boosted tourism significantly"],
          ["Canaan Valley", "Tucker County", "Winter + summer", "Ski + mountain biking; Blackwater Falls nearby"],
          ["Harpers Ferry", "Jefferson County", "Year-round", "Civil War history; Appalachian Trail; near DC metro"],
          ["Seneca Rocks", "Pendleton County", "Spring–fall", "Rock climbing; Spruce Knob wilderness area"],
          ["Summersville Lake", "Nicholas County", "Summer", "Scuba diving; white water rafting; cliff jumping"],
        ]
      },
      { type: "heading", level: 2, text: "Snowshoe Mountain: The Mid-Atlantic Ski STR Market", id: "snowshoe-market" },
      { type: "paragraph", text: "Snowshoe Mountain Resort in Pocahontas County is the largest ski resort in the Mid-Atlantic and Southeast regions. It draws skiers and snowboarders from the DC metro, Charlotte, and Pittsburgh during winter, and mountain bikers, hikers, and summer festival-goers in the warmer months. The resort operates year-round with strong shoulder season programming." },
      { type: "paragraph", text: "Snowshoe's STR market consists primarily of ski-in/ski-out or slope-adjacent condos and mountain homes. Slopeside properties command significant premiums during ski season. The resort's year-round operations differentiate it from purely seasonal ski markets. Properties in Snowshoe Village carry high furniture, fixture, and outdoor amenity components — supporting above-average cost segregation personal property ratios." },
      { type: "heading", level: 2, text: "New River Gorge: The Newest National Park Market", id: "new-river-gorge" },
      { type: "paragraph", text: "New River Gorge National Park and Preserve, designated a national park in December 2020, has seen a significant increase in tourism since its elevation in status. The New River Gorge Bridge — the longest single-arch steel bridge in the Western Hemisphere — hosts the annual Bridge Day festival (October) that draws 100,000+ visitors. Rock climbing, white water rafting, and hiking anchor year-round outdoor recreation demand." },
      { type: "paragraph", text: "Fayetteville and surrounding communities serve as the gateway. STR demand is driven by climbers, rafters, hikers, and the general national park tourism boom. Property values in the area remain accessible compared to more established resort markets, creating opportunities for yield-focused investors." },
      { type: "heading", level: 2, text: "Cost Segregation in West Virginia", id: "cost-seg-wv" },
      { type: "paragraph", text: "West Virginia's mountain and ski properties typically have strong personal property ratios. Snowshoe ski cabins and New River Gorge retreat properties with hot tubs, decks, and outdoor amenities can yield 22–30% in bonus-eligible assets. At 6.5% WV rate + 37% federal, a $400,000 Snowshoe property with $100,000 in cost seg deductions delivers approximately $43,500 combined first-year tax savings." },
      { type: "faq", question: "Are there special regulations for STRs near New River Gorge National Park?", answer: "Properties within the national park boundary are subject to NPS regulations that restrict commercial activity. However, most STR activity occurs in adjacent communities (Fayetteville, Oak Hill, Ansted) on private land outside park boundaries, regulated by local WV county and municipal ordinances. Always verify the regulatory status of any specific property before acquiring it as a potential STR." },
      { type: "cta", title: "Estimate Your West Virginia STR Tax Savings", text: "Snowshoe Mountain and New River Gorge properties can generate strong cost seg deductions. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Louisiana ────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-louisiana",
    title: "Short-Term Rental Taxes in Louisiana: What Investors Need to Know in 2025",
    description: "Louisiana's recently-reformed 1.85–4.25% income tax and full bonus depreciation conformity create a favorable state tax environment. But New Orleans has some of the most complex STR regulations in the country.",
    publishedAt: "2026-03-14",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Louisiana", "New Orleans", "Lafayette", "state taxes", "cost segregation", "bonus depreciation", "occupancy tax"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-louisiana.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Louisiana 2025: New Orleans, Lafayette & More | Abode",
      description: "Louisiana recently reformed its income tax to 1.85–4.25% and conforms to federal bonus depreciation. New Orleans has some of the most complex STR regulations in the U.S. Here's the complete Louisiana guide.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-louisiana",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is Louisiana's income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Louisiana overhauled its income tax structure effective 2025. The new rates are 1.85% on the first $12,500 of net income (single filers), rising to a top rate of 4.25% on income above approximately $50,000. This represents a significant reduction from prior rates and makes Louisiana one of the lower-rate income tax states in the country for STR investors." } },
          { "@type": "Question", name: "Does Louisiana conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. Louisiana conforms to federal bonus depreciation. STR investors can take 100% bonus depreciation on eligible assets on both their federal and Louisiana state returns in year one." } },
          { "@type": "Question", name: "How complex are New Orleans STR regulations?", acceptedAnswer: { "@type": "Answer", text: "New Orleans has some of the most restrictive STR regulations in the country. The city prohibits non-owner-occupied STRs in most residential zoning districts — only owner-occupied properties or commercially-zoned properties can operate as STRs. Additionally, New Orleans' total lodging tax burden can reach approximately 15.75% of rental revenue when all state, city, and special district taxes are combined." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Louisiana STR Tax Summary", text: "1.85–4.25% reformed income tax (effective 2025) | Conforms to federal bonus depreciation | New Orleans total lodging tax ~15.75% | Non-owner-occupied STRs prohibited in most New Orleans residential zones | Other markets: Lafayette, Natchitoches, Gulf Coast" },
      { type: "paragraph", text: "Louisiana presents a split picture for STR investors. The state's recently reformed income tax (now among the lower rates in the South) and full conformity to federal bonus depreciation create a favorable state tax environment. However, the primary tourism market — New Orleans — has adopted some of the most restrictive STR regulations in the country, significantly limiting investment opportunities for non-owner-occupied properties in the city." },
      { type: "heading", level: 2, text: "Louisiana's Reformed Income Tax Structure", id: "income-tax" },
      { type: "paragraph", text: "Louisiana overhauled its income tax system effective 2025, significantly reducing rates. The new individual income tax structure features rates starting at 1.85% on the first $12,500 of net income (single filers), rising to a top rate of 4.25% on income above approximately $50,000. This reform makes Louisiana one of the lower-rate income tax states in the country for STR investors — a meaningful improvement over the prior structure that had a top rate of over 6%." },
      { type: "heading", level: 2, text: "New Orleans: Complex Regulations and High Lodging Taxes", id: "new-orleans-regs" },
      { type: "paragraph", text: "New Orleans is Louisiana's dominant tourist market and one of the most regulated STR markets in the country. Following a 2019 ordinance revision, New Orleans distinguishes between 'Residential STRs' (owner-occupied, with limits on permitted nights) and 'Commercial STRs' (non-owner-occupied, requiring a commercial license). Non-owner-occupied STRs are prohibited in most residential zoning districts." },
      { type: "callout", variant: "warning", title: "New Orleans STR Warning for Investors", text: "If you are considering purchasing a non-owner-occupied STR property in New Orleans, the regulatory landscape is extremely restrictive. Commercial STR licenses are only available in commercially-zoned areas or specific overlay districts. Verify current zoning and permit availability with the City of New Orleans before making any purchase." },
      { type: "heading", level: 2, text: "New Orleans Lodging Tax Structure", id: "lodging-taxes" },
      { type: "table", headers: ["Tax Component", "Rate", "Authority"],
        rows: [
          ["Louisiana state sales tax (hospitality rate)", "4.45%", "State of Louisiana"],
          ["New Orleans city hotel tax", "4.75%", "City of New Orleans"],
          ["Orleans Parish tourism/convention tax", "1.75%", "New Orleans & Company"],
          ["New Orleans Tourism Marketing District", "1.25%", "NOTMD"],
          ["Louisiana Convention District tax (where applicable)", "~3.5%", "Various special districts"],
          ["Estimated Total (typical commercial zone)", "~15.75%", "Combined all layers"],
        ]
      },
      { type: "heading", level: 2, text: "Louisiana STR Markets Beyond New Orleans", id: "other-markets" },
      { type: "paragraph", text: "<strong>Lafayette:</strong> The hub of Cajun country, Lafayette draws culinary and cultural tourists from across the country. The city's STR regulations are less restrictive than New Orleans, and the market is growing as Cajun food and culture tourism expands. Properties in Lafayette's historic Garden District and Freetown neighborhoods appeal to travelers seeking authentic Louisiana experiences." },
      { type: "paragraph", text: "<strong>Natchitoches:</strong> Louisiana's oldest permanent European settlement, Natchitoches (pronounced 'NACK-uh-tish') is a National Historic Landmark district with charming brick streets, the scenic Cane River waterway, and year-round festivals including a famous Christmas Festival in December that draws enormous crowds. A small but distinctive STR market." },
      { type: "paragraph", text: "<strong>Gulf Coast (Grand Isle, Lake Charles):</strong> Louisiana's Gulf Coast has a smaller STR market than Alabama or Florida but serves fishing, hunting, and water sports tourists. Grand Isle is the state's primary beach destination. Lake Charles has grown as a destination for regional gaming and entertainment tourism." },
      { type: "heading", level: 2, text: "Cost Segregation in Louisiana", id: "cost-seg-louisiana" },
      { type: "paragraph", text: "For Louisiana STR properties outside New Orleans, cost segregation works cleanly with full federal and state deduction alignment. At Louisiana's new top rate of 4.25%, the state benefit is more modest but still real. For New Orleans commercial zone STR properties — typically higher-value historic buildings — cost segregation can be particularly valuable given the significant renovation and improvement investments often required." },
      { type: "paragraph", text: "Historic renovation properties in New Orleans may also qualify for federal Historic Tax Credits (HTC), which can compound the first-year tax benefits significantly. If investing in a historic New Orleans commercial zone property, engage both a cost segregation specialist and a historic tax credit consultant." },
      { type: "faq", question: "Can Airbnb bookings happen legally in New Orleans?", answer: "Airbnb and VRBO operate in New Orleans but only for legally permitted properties. The City of New Orleans has actively worked with platforms to remove unpermitted listings. Any New Orleans STR must have a valid city STR license. Non-owner-occupied properties in residential zones face extreme difficulty obtaining commercial STR licenses under the current ordinance." },
      { type: "cta", title: "Estimate Your Louisiana STR Tax Savings", text: "Louisiana's reformed income tax + full bonus dep conformity creates compelling net returns on permitted STR properties. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

];
