// State STR tax guides — West region
// States: Nevada, Utah, Oregon, Washington, Montana, Idaho, Wyoming, New Mexico, Alaska
// URL pattern: /learn/str-taxes-[state]

export const stateArticlesWest = [

  // ─── Nevada ───────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-nevada",
    title: "Short-Term Rental Taxes in Nevada: No Income Tax, Las Vegas, Lake Tahoe Guide",
    description: "Nevada has NO state income tax and is one of the top tax-advantaged states for STR investors. Here's the complete Nevada STR tax guide covering Las Vegas, Lake Tahoe, and more.",
    publishedAt: "2026-03-20",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Nevada", "Las Vegas", "Lake Tahoe", "Incline Village", "no income tax", "cost segregation", "bonus depreciation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-nevada.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Nevada 2025: No Income Tax, Las Vegas & Tahoe | Abode",
      description: "Nevada has no state income tax — a major benefit for STR investors. Here's the complete guide covering Las Vegas STR regulations, Lake Tahoe's NV side, and cost segregation strategy.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-nevada",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Nevada have a state income tax on rental income?", acceptedAnswer: { "@type": "Answer", text: "No. Nevada has no state personal income tax. STR rental income is only taxed at the federal level. This is one of Nevada's most significant advantages for STR investors — all cost segregation deductions and STR loophole benefits flow entirely to your federal return with no state income tax offset." } },
          { "@type": "Question", name: "What taxes do Nevada STR investors pay on rental revenue?", acceptedAnswer: { "@type": "Answer", text: "Nevada STR operators pay state and local lodging taxes on rental revenue. In Clark County (Las Vegas), the transient lodging tax is approximately 12–13% of gross rental revenue. In Washoe County (Reno/Lake Tahoe area), rates are approximately 13.5%. No state income tax applies to the rental profits themselves." } },
          { "@type": "Question", name: "Are short-term rentals regulated in Las Vegas?", acceptedAnswer: { "@type": "Answer", text: "Yes. Clark County and the City of Las Vegas have adopted STR regulations. Properties near the Las Vegas Strip and in certain residential zones face significant restrictions. Clark County requires STR licenses and prohibits STRs within certain distances of resort corridor hotels. Residential neighborhoods away from the Strip — Henderson, Summerlin, North Las Vegas — have active and increasingly regulated STR markets." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Nevada STR Tax Summary", text: "NO state income tax | Full federal bonus depreciation benefit — no state offset | Clark County (Las Vegas) lodging tax ~12–13% | Washoe County (Reno/Tahoe) ~13.5% | STR regulations vary significantly by jurisdiction — especially near the Strip | Top markets: Las Vegas residential, Henderson, Lake Tahoe NV side (Incline Village)" },
      { type: "paragraph", text: "Nevada's most powerful tax advantage is simple: no state income tax. For STR investors, this means every dollar of federal cost segregation deductions and every dollar of STR loophole benefit is captured entirely at the federal level — there is no Nevada state tax bill to offset. Combined with Nevada's status as a major domestic tourism destination (Las Vegas draws 40+ million visitors annually; Lake Tahoe's Nevada side is a pristine alpine resort market), the investment fundamentals are compelling." },
      { type: "heading", level: 2, text: "No Nevada State Income Tax: Maximum Cost Seg Benefit", id: "no-income-tax" },
      { type: "paragraph", text: "Nevada's constitutional prohibition on income taxes is one of the most investor-friendly tax policies in the United States. For STR investors using cost segregation, this means: the full 37% federal rate applies to every dollar of bonus depreciation deduction, with zero state income tax to complicate the calculation. Compare this to California (13.3% state rate, plus bonus depreciation non-conformity) — the difference in after-tax returns for comparable properties can be extraordinary." },
      { type: "heading", level: 2, text: "Nevada Lodging Taxes by Market", id: "nevada-lodging-taxes" },
      { type: "table", headers: ["County / Market", "State Lodging Tax", "County/Local Tax", "Approximate Total"],
        rows: [
          ["Clark County (Las Vegas/Henderson)", "~6.5%", "~6%", "~12–13%"],
          ["Washoe County (Reno/Sparks)", "~6.5%", "~7%", "~13.5%"],
          ["Douglas County (Stateline/South Lake Tahoe NV)", "~6.5%", "~5%", "~11.5%"],
          ["Carson City", "~6.5%", "~3%", "~9.5%"],
          ["Churchill County (Fallon area)", "~6.5%", "~2%", "~8.5%"],
          ["Elko County", "~6.5%", "~2%", "~8.5%"],
        ]
      },
      { type: "heading", level: 2, text: "Las Vegas STR Market: Residential Neighborhoods vs. Strip", id: "las-vegas-market" },
      { type: "paragraph", text: "The Las Vegas Strip itself is dominated by mega-resort hotels — STR competition there is minimal and heavily regulated. But the broader Las Vegas metro area (Clark County) has a large and active STR market in residential neighborhoods. Henderson, Summerlin, Spring Valley, and North Las Vegas all have significant STR activity driven by: convention attendees seeking more space than a hotel room, group travel for bachelor/bachelorette parties, sports event visitors (Raiders, Golden Knights, Formula 1, major boxing), and entertainment seekers." },
      { type: "paragraph", text: "Clark County has adopted a tiered licensing system for STRs. Properties within 2,500 feet of resort corridor hotels face the most stringent restrictions or outright prohibition. Properties in residential zones require a Short-Term Rental License and compliance with occupancy, parking, and noise rules. The regulatory environment has tightened since 2021 — verify current Clark County and city-specific rules for your target property before acquisition." },
      { type: "heading", level: 2, text: "Lake Tahoe Nevada Side: Incline Village and Crystal Bay", id: "lake-tahoe-nevada" },
      { type: "paragraph", text: "The Nevada side of Lake Tahoe — primarily Incline Village and Crystal Bay in Washoe County — offers one of the West's most desirable alpine STR markets. Properties here benefit from the no-income-tax advantage of Nevada while sitting on the shore of one of the most beautiful lakes in the world. Incline Village properties routinely command $600–$2,000+/night in peak ski season (January–March) and summer (July–August). Demand is driven by San Francisco Bay Area and Sacramento visitors who can access Tahoe in 2–4 hours." },
      { type: "paragraph", text: "Incline Village has its own STR permit program with annual caps on permits and strict compliance requirements. Properties that hold valid permits command a premium in resale value given the limited permit availability." },
      { type: "heading", level: 2, text: "Cost Segregation in Nevada", id: "cost-seg-nevada" },
      { type: "paragraph", text: "Nevada's no-income-tax environment makes cost segregation maximally efficient. Las Vegas residential STR properties have moderate personal property ratios (15–22%) — furnished interiors, appliances, outdoor pools and spas. Lake Tahoe Nevada-side properties have higher ratios due to ski storage areas, outdoor decks, hot tubs, and lake-access infrastructure. A $900,000 Incline Village property might generate $180,000–$250,000 in bonus-eligible deductions, generating $66,600–$92,500 in federal first-year tax savings at 37%, with zero Nevada state income tax impact." },
      { type: "faq", question: "Does Nevada have a gross receipts or business tax on STR income?", answer: "Nevada does not have a gross receipts tax on STR rental income. Nevada does have a Commerce Tax on businesses with revenues over $4 million, but individual STR investors operating below this threshold are not subject to it. The Modified Business Tax applies to payroll, not rental income. Individual STR investors operating a few properties face no Nevada entity-level tax on rental revenue beyond the lodging taxes collected from guests." },
      { type: "cta", title: "Estimate Your Nevada STR Tax Savings", text: "No state income tax + full federal bonus depreciation = Nevada's STR investors keep maximum returns. Get your free cost segregation estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Utah ─────────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-utah",
    title: "Short-Term Rental Taxes in Utah: Park City, Moab, and What STR Investors Need to Know",
    description: "Utah has a 4.65% flat income tax, conforms to federal bonus depreciation, and features Park City and Moab — two of the West's top STR markets. Here's the complete Utah STR tax guide.",
    publishedAt: "2026-03-20",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Utah", "Park City", "Moab", "St. George", "ski rental", "national parks", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "9 min read",
    heroImage: "/images/blog/str-taxes-utah.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Utah 2025: Park City, Moab Investor Guide | Abode",
      description: "Utah's 4.65% flat income tax, full bonus depreciation conformity, and elite STR markets in Park City and Moab make it one of the West's top STR states. Here's the complete guide.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-utah",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is Utah's income tax rate on STR rental income?", acceptedAnswer: { "@type": "Answer", text: "Utah has a flat 4.65% state income tax rate on all taxable income, including net rental income. Utah conforms to federal bonus depreciation, so a cost segregation study produces the same first-year deduction on your Utah TC-40 as on your federal return. The flat rate structure makes tax planning straightforward for Utah STR investors." } },
          { "@type": "Question", name: "Does Utah conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. Utah conforms to federal bonus depreciation. There is no Utah bonus depreciation addback or limitation. Cost segregation deductions are fully recognized on your Utah state return at the same amounts as your federal return — unlike California, Oregon, or some other western states that limit bonus depreciation." } },
          { "@type": "Question", name: "What are the lodging taxes in Park City, Utah?", acceptedAnswer: { "@type": "Answer", text: "Park City STR operators pay a combined lodging tax of approximately 12.1% on gross rental revenue, including Utah state sales tax (6.1% in Summit County), county transient room tax, and Park City municipal tax. Grand County (Moab) total taxes are approximately 12.35% of rental revenue." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Utah STR Tax Summary", text: "4.65% flat state income tax | Conforms to federal bonus depreciation | Park City total lodging tax ~12.1% | Moab (Grand County) ~12.35% | Top markets: Park City (ski/Sundance), Moab (Arches/Canyonlands), St. George, Brian Head | Some of the highest STR property values in the West" },
      { type: "paragraph", text: "Utah has emerged as one of the West's premier STR investment destinations, driven by world-class ski resorts in Park City (home to the Sundance Film Festival, Park City Mountain, and Deer Valley), the dramatic red rock landscapes around Moab and Arches National Park, and the warm-weather golf and recreation market in St. George. The tax environment is straightforward and investor-friendly: a moderate flat rate and full federal bonus depreciation conformity." },
      { type: "heading", level: 2, text: "Utah State Income Tax", id: "utah-income-tax" },
      { type: "paragraph", text: "Utah's 4.65% flat income tax applies to all taxable income, including net rental income. The flat rate structure means every dollar of rental income is taxed at the same rate — no bracket planning is needed. Utah's flat 4.65% is lower than California (up to 13.3%), Oregon (up to 9.9%), and comparable to Colorado (4.4%). Combined with full bonus depreciation conformity, Utah presents a clean and favorable tax picture for STR investors." },
      { type: "heading", level: 2, text: "Utah Lodging Taxes by Market", id: "utah-lodging-taxes" },
      { type: "table", headers: ["County / Market", "State Sales Tax", "County/Local Tax", "Approximate Total"],
        rows: [
          ["Summit County (Park City)", "6.1%", "~6%", "~12.1%"],
          ["Grand County (Moab)", "6.1%", "~6.25%", "~12.35%"],
          ["Washington County (St. George)", "6.1%", "~4%", "~10.1%"],
          ["Iron County (Brian Head)", "6.1%", "~4%", "~10.1%"],
          ["Utah County (Provo/Sundance area)", "6.1%", "~3%", "~9.1%"],
          ["Salt Lake County (Salt Lake City)", "6.1%", "~4%", "~10.1%"],
          ["Garfield County (Bryce Canyon area)", "6.1%", "~4%", "~10.1%"],
          ["Kane County (Kanab/Zion gateway)", "6.1%", "~4%", "~10.1%"],
        ]
      },
      { type: "heading", level: 2, text: "Park City: Utah's Highest-Value STR Market", id: "park-city-market" },
      { type: "paragraph", text: "Park City is one of the most valuable STR markets in the entire United States. Properties range from $800,000 ski condos to $5M+ luxury mountain homes, and the rental market supports extraordinary rates: $500–$2,500+/night in ski season (December–March), with strong shoulder seasons driven by fall foliage, mountain biking, and the Sundance Film Festival in January. Park City Mountain Resort and Deer Valley (recently expanded and now opened to snowboarders) drive some of the highest ADRs of any ski market in the country." },
      { type: "paragraph", text: "Park City has adopted a permit system for STRs with annual caps. Permits can be difficult to obtain in some areas, and they affect property value — permitted STR properties command a premium at sale. Summit County has also adopted regulations for unincorporated county properties. Verify permit availability for any specific property before acquisition." },
      { type: "heading", level: 2, text: "Moab: National Parks Gateway Market", id: "moab-market" },
      { type: "paragraph", text: "Moab sits at the gateway to both Arches National Park and Canyonlands National Park — two of the most visually stunning parks in the U.S. STR demand in Moab is driven by outdoor recreation: hiking, mountain biking, jeep tours, and river rafting. The market is intensely seasonal (spring and fall are peak; summer can be very hot; winter is mild but slower) with average stays typically 2–4 nights — well within STR loophole parameters." },
      { type: "paragraph", text: "Moab STR properties tend to have strong outdoor amenity ratios. Desert landscaping, patios with red rock views, hot tubs, and unique architectural features designed to capture views are all 5-year or 15-year assets for cost segregation purposes. A $600,000 Moab property with dramatic views might yield 22–28% of value in short-life assets." },
      { type: "heading", level: 2, text: "Cost Segregation in Utah: High-Value Properties, Strong Returns", id: "cost-seg-utah" },
      { type: "paragraph", text: "Utah's high property values in Park City — where $1M–$3M is the norm for quality STR-ready properties — make cost segregation particularly impactful. A $1.5M Park City ski property with $375,000 in bonus-eligible deductions (25% ratio) generates $138,750 in federal first-year tax savings at 37%, plus $17,438 in Utah state savings at 4.65% — a combined $156,188 first-year benefit from cost segregation alone." },
      { type: "paragraph", text: "Utah's full bonus depreciation conformity means there's no complex state addback calculation. What you claim federally, you claim in Utah. The combination of high property values, strong rental income, and clean state tax rules makes Utah — particularly Park City — one of the most compelling cost segregation markets in the country." },
      { type: "faq", question: "Do Airbnb and VRBO collect Utah lodging taxes on bookings?", answer: "Yes. Both Airbnb and VRBO act as marketplace facilitators in Utah and collect and remit state sales tax and applicable county transient room taxes on bookings made through their platforms. Direct bookings require independent collection and remittance. Verify with each platform that local municipal taxes (Park City city tax, for example) are included in what they collect." },
      { type: "cta", title: "Estimate Your Utah STR Tax Savings", text: "Park City's extraordinary property values + full bonus depreciation conformity = some of the largest cost seg deductions in the country. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Oregon ───────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-oregon",
    title: "Short-Term Rental Taxes in Oregon: High Rates, Bonus Dep Non-Conformity, and Bend/Coast Guide",
    description: "Oregon has income taxes up to 9.9% and does not conform to federal bonus depreciation — two significant issues for STR investors in Bend, the Oregon Coast, and Hood River.",
    publishedAt: "2026-03-20",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Oregon", "Bend", "Oregon Coast", "Hood River", "Cannon Beach", "state taxes", "bonus depreciation decoupling", "cost segregation"],
    readTime: "9 min read",
    heroImage: "/images/blog/str-taxes-oregon.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Oregon 2025: Bend, Coast, Bonus Dep Issues | Abode",
      description: "Oregon's income tax tops at 9.9% and the state does not conform to federal bonus depreciation. Here's the complete guide for Bend, Oregon Coast, and Hood River STR investors.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-oregon",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Oregon conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "No. Oregon does not conform to federal bonus depreciation. When you take bonus depreciation on your federal return via a cost segregation study, you must add back the excess depreciation on your Oregon OR-40 return. Oregon uses its own depreciation schedule that does not allow accelerated 100% first-year bonus depreciation. This is a significant planning consideration given Oregon's high income tax rates (up to 9.9%)." } },
          { "@type": "Question", name: "What is Oregon's income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Oregon has graduated income tax rates: 4.75% on income up to $18,400 (single); 6.75% on $18,400–$46,200; 8.75% on $46,200–$250,000; and 9.9% on income over $250,000. Most high-income STR investors will pay 8.75% or 9.9% on their net rental income — among the highest rates in the West." } },
          { "@type": "Question", name: "Does Oregon have a state sales tax?", acceptedAnswer: { "@type": "Answer", text: "No. Oregon has no state sales tax — a unique distinction among western states. However, Oregon does impose a transient lodging tax (TLT) of 1.8% at the state level, and local jurisdictions add their own lodging taxes. Portland adds up to 13.5% locally, making the combined Portland lodging tax among the highest in the country." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Oregon STR Tax Summary", text: "4.75–9.9% graduated state income tax (high) | Oregon does NOT conform to federal bonus depreciation | No state sales tax, but 1.8% state transient lodging tax + local lodging taxes | Portland total lodging tax up to ~15% | Top markets: Bend, Oregon Coast (Cannon Beach, Lincoln City), Hood River, Crater Lake area | Work with an Oregon CPA on depreciation planning" },
      { type: "paragraph", text: "Oregon presents a mixed picture for STR investors. On the positive side, no state sales tax simplifies guest-facing tax collection, and the STR markets are excellent — Bend's outdoor recreation economy, the dramatic Oregon Coast, Hood River's windsurfing and Columbia Gorge beauty, and the proximity to Portland's affluent traveler base. On the negative side, Oregon has high income tax rates (up to 9.9%) and does not conform to federal bonus depreciation — a combination that requires careful tax planning." },
      { type: "heading", level: 2, text: "Oregon State Income Tax: High Rates", id: "oregon-income-tax" },
      { type: "paragraph", text: "Oregon's top marginal income tax rate of 9.9% is the fourth-highest in the United States and the highest in the Pacific Northwest. Most STR investors with significant rental income will be in the 8.75% or 9.9% bracket. Oregon also imposes an additional 1% income tax (the Corporate Activity Tax) on certain business activities, and Portland has its own metro-area income taxes. For high-income investors, combined federal + Oregon rates can approach 50% on ordinary income." },
      { type: "heading", level: 2, text: "CRITICAL: Oregon's Bonus Depreciation Non-Conformity", id: "bonus-depreciation" },
      { type: "paragraph", text: "Oregon does not conform to federal bonus depreciation. When you claim 100% bonus depreciation on 5-year and 15-year assets via cost segregation, Oregon requires you to add back the excess depreciation on your OR-40 and use Oregon's own depreciation schedule. Your Oregon taxable income in Year 1 will be significantly higher than your federal taxable income." },
      { type: "paragraph", text: "With Oregon's 8.75–9.9% top rates, this addback can be costly in Year 1. However — as with all bonus depreciation non-conformity states — this is a timing difference, not a permanent loss. Over the full asset life, Oregon allows the same total depreciation as federal. The net present value of cost segregation is still strongly positive given the federal savings at 37%. Work with an Oregon CPA to model the multi-year state tax cash flow and ensure the addback is properly calculated." },
      { type: "heading", level: 2, text: "Oregon Transient Lodging Tax by Market", id: "oregon-lodging-taxes" },
      { type: "paragraph", text: "Oregon has no state sales tax, but the state-level transient lodging tax (TLT) and local lodging taxes can be substantial — especially in Portland." },
      { type: "table", headers: ["County / Market", "State TLT", "Local Lodging Tax", "Approximate Total"],
        rows: [
          ["Portland (Multnomah County)", "1.8%", "~13.5%", "~15.3%"],
          ["Deschutes County (Bend)", "1.8%", "~9.5%", "~11.3%"],
          ["Clatsop County (Cannon Beach/Seaside)", "1.8%", "~8%", "~9.8%"],
          ["Hood River County", "1.8%", "~10%", "~11.8%"],
          ["Lincoln County (Lincoln City/Newport)", "1.8%", "~9.5%", "~11.3%"],
          ["Jackson County (Ashland/Medford)", "1.8%", "~6%", "~7.8%"],
          ["Lane County (Eugene/Florence coast)", "1.8%", "~5%", "~6.8%"],
          ["Klamath County (Crater Lake area)", "1.8%", "~5%", "~6.8%"],
        ]
      },
      { type: "heading", level: 2, text: "Top Oregon STR Markets", id: "top-markets" },
      { type: "list", style: "bulleted", items: [
        "<strong>Bend (Deschutes County):</strong> Oregon's fastest-growing STR market; outdoor recreation capital with skiing (Mt. Bachelor), hiking, mountain biking, and kayaking; year-round demand; vibrant food and craft beer scene; strong convention and corporate retreat market",
        "<strong>Oregon Coast (Cannon Beach, Lincoln City, Newport):</strong> Iconic dramatic coastline; Cannon Beach (Haystack Rock) is one of Oregon's most recognized images; storm watching in winter is a genuine shoulder-season driver; strong Portland/Willamette Valley demand",
        "<strong>Hood River / Columbia River Gorge:</strong> World-class windsurfing and kiteboarding; orchards and wine country; gateway to Mt. Hood; year-round demand with distinct seasonal peaks; high property values relative to market size",
        "<strong>Ashland (Jackson County):</strong> Oregon Shakespeare Festival drives exceptional cultural tourism (April–October); unique niche but extremely loyal visitor base",
        "<strong>Southern Oregon Coast (Brookings, Gold Beach):</strong> Warmer, sunnier coast; lower property prices than northern coast; growing remote-worker/long-stay market",
      ]},
      { type: "faq", question: "Is cost segregation worth it in Oregon given the high income tax and non-conformity?", answer: "Yes. The federal savings from cost segregation are unaffected by Oregon's rules. A $150,000 federal deduction at 37% saves $55,500 in federal taxes regardless of Oregon's treatment. The Oregon addback might cost $13,000–$15,000 in additional Oregon tax in Year 1, but that excess Oregon tax will be fully recovered in subsequent years as you claim lower Oregon depreciation. The net present value of cost segregation is still strongly positive. With Oregon's high 9.9% rate, in the long run you actually save more in Oregon state taxes over the depreciation life than you pay in Year 1 — because the deductions in subsequent years compound against high Oregon rates." },
      { type: "cta", title: "Estimate Your Oregon STR Tax Savings", text: "Oregon's high state rates make the federal savings from cost segregation even more powerful in relative terms. Get your free estimate for your Bend or coastal property.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Washington ───────────────────────────────────────────────────────────
  {
    slug: "str-taxes-washington",
    title: "Short-Term Rental Taxes in Washington State: No Income Tax, B&O Tax, and STR Guide",
    description: "Washington State has no income tax but does have a Business & Occupation (B&O) tax on rental revenue. Here's the complete guide for Leavenworth, San Juan Islands, and Lake Chelan STR investors.",
    publishedAt: "2026-03-21",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Washington State", "Leavenworth", "San Juan Islands", "Lake Chelan", "no income tax", "B&O tax", "cost segregation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-washington.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Washington State 2025: No Income Tax Guide | Abode",
      description: "Washington has no income tax but charges B&O tax (~1.75%) on rental revenue. Here's the guide for WA STR investors in Leavenworth, San Juan Islands, Chelan, and beyond.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-washington",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Washington State have an income tax on rental income?", acceptedAnswer: { "@type": "Answer", text: "No. Washington State has no personal income tax. STR rental income is not subject to state income tax in Washington. However, Washington does impose a Business & Occupation (B&O) tax on gross rental revenues — typically at the service and other activities rate of approximately 1.75%. This applies to gross revenue before expenses, unlike income taxes which apply to net profit." } },
          { "@type": "Question", name: "What is Washington's Business & Occupation (B&O) tax on STR rentals?", acceptedAnswer: { "@type": "Answer", text: "Washington's B&O tax is applied to gross rental revenue (not net income) at the service and other activities rate of approximately 1.75%. For a property generating $100,000 in gross annual rental revenue, the B&O tax would be approximately $1,750. This is significantly less burdensome than a 5–10% income tax on net profits." } },
          { "@type": "Question", name: "What lodging taxes apply in Washington State?", acceptedAnswer: { "@type": "Answer", text: "Washington STR operators collect and remit state retail sales tax (6.5%) plus local lodging/tourism taxes that vary by jurisdiction. Total rates range from approximately 10% in most areas to 14%+ in Seattle. Chelan County (Lake Chelan) is approximately 10–11%. Leavenworth/Chelan County is approximately 10%. San Juan County is approximately 10%." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Washington State STR Tax Summary", text: "NO state income tax | B&O tax ~1.75% on GROSS rental revenue (not net profit) | 6.5% state sales tax + local lodging taxes | Full federal bonus depreciation benefit — no state income tax offset | Top markets: Leavenworth, San Juan Islands, Lake Chelan, Whidbey Island, Olympic Peninsula" },
      { type: "paragraph", text: "Washington State's tax picture for STR investors is unique: no income tax (a significant benefit), but a Business & Occupation (B&O) tax that applies to gross rental revenues rather than net profits. The B&O tax is relatively modest (approximately 1.75% of gross revenue), making Washington's overall tax burden on STR investors quite low compared to states like Oregon or California. Combined with Washington's spectacular STR markets — from the Bavarian-themed village of Leavenworth to the island paradise of the San Juan Islands — Washington is a compelling STR investment state." },
      { type: "heading", level: 2, text: "Washington's Unique Tax Structure: No Income Tax, B&O Tax", id: "washington-taxes" },
      { type: "paragraph", text: "Washington has no personal income tax, but the state raises revenue through the Business & Occupation (B&O) tax on business gross receipts. For STR rental activities, the applicable B&O rate is the service and other activities rate of approximately 1.75% on gross rental revenue. This is a tax on gross revenue — not net profit — which means you pay it even in years when your property has a net loss from depreciation and expenses." },
      { type: "paragraph", text: "For perspective: if your Washington STR generates $120,000 in gross annual rental revenue, the B&O tax is approximately $2,100 — substantially less than even a 5% income tax on modest net profits. For most profitable STR properties, the B&O tax is a manageable cost well below what comparable income tax states would charge." },
      { type: "heading", level: 2, text: "Washington Lodging Taxes by Market", id: "washington-lodging-taxes" },
      { type: "table", headers: ["County / Market", "State Sales Tax", "Local Lodging Tax", "Approximate Total"],
        rows: [
          ["King County (Seattle)", "6.5%", "~7.5%", "~14%"],
          ["Chelan County (Leavenworth/Lake Chelan)", "6.5%", "~3–4%", "~10–10.5%"],
          ["San Juan County (San Juan Islands)", "6.5%", "~3–4%", "~10%"],
          ["Island County (Whidbey Island)", "6.5%", "~4%", "~10.5%"],
          ["Jefferson County (Olympic Peninsula/Port Townsend)", "6.5%", "~4%", "~10.5%"],
          ["Whatcom County (Bellingham/Mt. Baker)", "6.5%", "~3%", "~9.5%"],
          ["Skamania County (Columbia River Gorge WA)", "6.5%", "~4%", "~10.5%"],
          ["Okanogan County (Methow Valley/Winthrop)", "6.5%", "~4%", "~10.5%"],
        ]
      },
      { type: "heading", level: 2, text: "Top Washington State STR Markets", id: "top-markets" },
      { type: "list", style: "bulleted", items: [
        "<strong>Leavenworth (Chelan County):</strong> Bavarian-themed village in the Cascades; one of Washington's most visited tourist destinations; Christmas Lighting Festival (November–January) drives extraordinary off-season demand; skiing at Mission Ridge; apple orchards and wine country; charming aesthetic drives premium photography and listing appeal",
        "<strong>San Juan Islands (San Juan County):</strong> Remote and spectacular archipelago accessible only by ferry or seaplane; Friday Harbor and Orcas Island are primary STR markets; whale watching, kayaking, and cycling draw high-income visitors; premium property values; very limited STR supply creates strong occupancy",
        "<strong>Lake Chelan (Chelan County):</strong> Washington's deep-water lake resort; scenic 50-mile lake surrounded by desert hills and orchard country; strong summer boating and resort demand; a 2.5-hour drive from Seattle",
        "<strong>Whidbey Island (Island County):</strong> Long island in Puget Sound; accessible from Seattle metro by ferry or bridge; farms, art galleries, beaches, and navy base community; year-round demand from Seattle residents",
        "<strong>Methow Valley/Winthrop (Okanogan County):</strong> Wild West-themed town; best Nordic skiing in the Northwest; remote beauty with growing STR market",
      ]},
      { type: "heading", level: 2, text: "Cost Segregation in Washington: Federal Benefits Without State Income Tax", id: "cost-seg-washington" },
      { type: "paragraph", text: "Washington's no-income-tax environment makes cost segregation highly efficient — every dollar of federal deduction at 37% is pure federal savings with no state income tax offset. Washington San Juan Islands and Lake Chelan properties have strong cost segregation profiles: dock and waterfront infrastructure (15-year), boat lifts, outdoor recreation amenities, and premium furnished interiors. A $1.2M San Juan Islands waterfront property might generate $270,000–$360,000 in bonus-eligible deductions — $99,900–$133,200 in first-year federal tax savings." },
      { type: "faq", question: "Do I need to register my Washington STR for B&O tax purposes?", answer: "Yes. Washington STR operators must register with the Washington Department of Revenue for both B&O tax and retail sales tax collection purposes. Airbnb and VRBO collect and remit Washington state sales tax on platform bookings as marketplace facilitators. However, B&O tax is your responsibility to remit based on your gross rental revenue. Most individual STR operators file B&O tax quarterly with the WA DOR." },
      { type: "cta", title: "Estimate Your Washington State STR Tax Savings", text: "Washington's no income tax + full federal bonus depreciation = excellent after-tax returns. Get your free cost segregation estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Montana ──────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-montana",
    title: "Short-Term Rental Taxes in Montana: Whitefish, Big Sky, and What STR Investors Need to Know",
    description: "Montana has a 5.9% flat income tax, conforms to federal bonus depreciation, and hosts Whitefish and Big Sky — two of the fastest-growing luxury cabin markets in the Northwest.",
    publishedAt: "2026-03-21",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Montana", "Whitefish", "Big Sky", "Glacier National Park", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-montana.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Montana 2025: Whitefish, Big Sky Investor Guide | Abode",
      description: "Montana's 5.9% flat income tax and full bonus depreciation conformity make it favorable for Whitefish and Big Sky STR investors. Here's the complete Montana STR tax guide.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-montana",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is Montana's income tax rate on STR rental income?", acceptedAnswer: { "@type": "Answer", text: "Montana has a flat 5.9% income tax rate (reduced from the previous 6.9% rate). This applies to all taxable income, including net rental income from short-term rentals. Montana conforms to federal bonus depreciation, making cost segregation deductions fully effective at both the federal and state levels." } },
          { "@type": "Question", name: "Does Montana conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. Montana conforms to federal bonus depreciation. A cost segregation study generates the same first-year deduction on your Montana MT-40 as on your federal return. No addback or limitation is required on the Montana state return." } },
          { "@type": "Question", name: "What lodging taxes apply to Montana STR rentals?", acceptedAnswer: { "@type": "Answer", text: "Montana imposes a 4% lodging facility use tax on STR rentals. Many resort communities add a local resort tax on top of the state rate. Whitefish charges a 3% resort tax (total ~7%). Big Sky charges a resort tax as well. Montana has no state sales tax, which simplifies compliance slightly." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Montana STR Tax Summary", text: "5.9% flat state income tax (reduced from 6.9%) | Conforms to federal bonus depreciation | 4% state lodging facility use tax + local resort taxes | No state sales tax | Top markets: Whitefish/Glacier NP (fastest-growing luxury cabin market in Northwest), Big Sky, Bozeman | Rapidly appreciating property values" },
      { type: "paragraph", text: "Montana has experienced extraordinary growth in STR investing over the past five years. The Whitefish/Glacier National Park corridor has emerged as one of the premier luxury cabin markets in the entire Northwest. Big Sky — near Yellowstone's western approaches — has seen property values double since 2020. Bozeman's tech industry growth has created a hybrid market blending adventure tourism with corporate short-stay demand. Montana's tax environment is straightforward: a recently reduced flat rate, full bonus depreciation conformity, and no state sales tax." },
      { type: "heading", level: 2, text: "Montana State Income Tax", id: "montana-income-tax" },
      { type: "paragraph", text: "Montana recently reduced its income tax to a flat 5.9% from the previous higher graduated structure. This rate applies to all taxable income, including net rental income. While 5.9% is higher than Wyoming (no income tax) or Idaho (5.8%), the full bonus depreciation conformity and Montana's rapidly appreciating STR property values make the state highly attractive. Montana also has no state sales tax, which simplifies the tax compliance picture for STR operators." },
      { type: "heading", level: 2, text: "Montana Lodging and Resort Taxes by Market", id: "montana-lodging-taxes" },
      { type: "table", headers: ["County / Market", "State Lodging Tax", "Local Resort Tax", "Approximate Total"],
        rows: [
          ["Flathead County (Whitefish/Kalispell)", "4%", "3% (Whitefish resort tax)", "~7%"],
          ["Gallatin County (Big Sky/Bozeman)", "4%", "3% (Big Sky resort tax)", "~7%"],
          ["Missoula County", "4%", "0–2%", "~4–6%"],
          ["Lewis and Clark County (Helena)", "4%", "0%", "~4%"],
          ["Cascade County (Great Falls)", "4%", "0%", "~4%"],
          ["Glacier County (East Glacier/Blackfeet)", "4%", "0%", "~4%"],
          ["Park County (Gardiner/Yellowstone north)", "4%", "2%", "~6%"],
        ]
      },
      { type: "heading", level: 2, text: "Whitefish: Montana's Premier STR Market", id: "whitefish-market" },
      { type: "paragraph", text: "Whitefish is the gateway to Glacier National Park (one of America's most spectacular parks, drawing 3M+ annual visitors) and home to Whitefish Mountain Resort — a ski mountain with 3,000 feet of vertical and a loyal destination skier base. The STR market in Whitefish has exploded: luxury cabin properties that sold for $600,000 in 2019 now trade at $1.2M–$2M+. Short-stay rental rates of $400–$1,200/night are common for quality properties." },
      { type: "paragraph", text: "Whitefish has adopted a permit system for STRs with some zoning restrictions. Properties in approved zones with valid permits command a premium. The city has limited STR permits in certain residential areas to preserve neighborhood character. Verify permit availability for specific target addresses before acquisition." },
      { type: "heading", level: 2, text: "Big Sky and Bozeman Markets", id: "big-sky-bozeman" },
      { type: "paragraph", text: "Big Sky Resort — near the western entrance to Yellowstone and bordering the Lone Mountain ski area — has become one of Montana's most valuable real estate markets. STR properties in the Big Sky base area and nearby Moonlight Basin can achieve $800–$3,000+/night in peak ski season. Summer demand is fueled by Yellowstone tourists, hikers, and fly fishing enthusiasts." },
      { type: "paragraph", text: "Bozeman is Montana's fastest-growing city, driven by tech migration from California and the Pacific Northwest. The STR market here blends shorter-stay tech traveler demand with adventure tourism from nearby Bridger Bowl ski area and Yellowstone access. Bozeman has adopted STR regulations with permit requirements." },
      { type: "heading", level: 2, text: "Cost Segregation in Montana: Luxury Cabin Profiles", id: "cost-seg-montana" },
      { type: "paragraph", text: "Montana luxury cabin and mountain home properties have excellent cost segregation profiles. Log cabin construction has significant 5-year personal property components; outdoor hot tubs, decks, fire pits, and ski storage areas are 15-year land improvements; and high-end furnishings for luxury properties are 5-year assets. Whitefish and Big Sky properties typically achieve 22–32% of purchase price in short-life assets." },
      { type: "paragraph", text: "A $1.4M Whitefish luxury cabin with $360,000 in bonus-eligible deductions (26% ratio) generates $133,200 in federal first-year tax savings at 37%, plus $21,240 in Montana state savings at 5.9% — a combined $154,440 first-year benefit from cost segregation. Montana's full bonus depreciation conformity means no addback calculation is needed." },
      { type: "faq", question: "Does Montana have statewide STR regulations?", answer: "Montana does not have a comprehensive statewide STR licensing law. Regulation is primarily local. Whitefish, Bozeman, and some Gallatin County areas have adopted permit systems. Rural Montana counties generally have minimal regulation. The Montana Department of Revenue requires STR operators to register for lodging facility use tax collection purposes." },
      { type: "cta", title: "Estimate Your Montana STR Tax Savings", text: "Whitefish and Big Sky's rapidly appreciating properties + full bonus depreciation conformity = exceptional cost seg results. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Idaho ────────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-idaho",
    title: "Short-Term Rental Taxes in Idaho: Coeur d'Alene, Sun Valley, and Complete STR Guide",
    description: "Idaho has a 5.8% flat income tax, conforms to federal bonus depreciation, and features Coeur d'Alene and Sun Valley among the Northwest's top STR markets. Here's the complete Idaho guide.",
    publishedAt: "2026-03-21",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Idaho", "Coeur d'Alene", "Sun Valley", "McCall", "Boise", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-idaho.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Idaho 2025: Coeur d'Alene, Sun Valley Guide | Abode",
      description: "Idaho's 5.8% flat income tax and full bonus depreciation conformity make it favorable for Coeur d'Alene and Sun Valley STR investors. Here's the complete Idaho STR tax guide.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-idaho",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is Idaho's income tax rate on STR rental income?", acceptedAnswer: { "@type": "Answer", text: "Idaho has a flat 5.8% income tax rate on all taxable income, including net rental income from short-term rentals. Idaho conforms to federal bonus depreciation, so cost segregation deductions are fully recognized on your Idaho state return at the same amounts as your federal return." } },
          { "@type": "Question", name: "Does Idaho conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. Idaho conforms to federal bonus depreciation. There is no Idaho bonus depreciation addback or limitation. Cost segregation deductions flow through directly to your Idaho state return at the full federal bonus depreciation amounts." } },
          { "@type": "Question", name: "What lodging taxes apply to Idaho STR rentals?", acceptedAnswer: { "@type": "Answer", text: "Idaho imposes a 6% state sales tax on transient accommodations. Many counties and cities add local lodging taxes. Total rates in Coeur d'Alene (Kootenai County) are approximately 8–9%. Sun Valley (Blaine County) is approximately 8–9%. McCall (Valley County) is approximately 8%. Boise is approximately 8–9%." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Idaho STR Tax Summary", text: "5.8% flat state income tax | Conforms to federal bonus depreciation | 6% state sales tax + local lodging taxes (~8–9% total) | Top markets: Coeur d'Alene (lake/resort), Sun Valley/Ketchum (ski), McCall (lake/ski), Boise | Strong property appreciation market" },
      { type: "paragraph", text: "Idaho has quietly emerged as one of the Pacific Northwest's top STR investment destinations. Coeur d'Alene's stunning alpine lake draws Pacific Northwest and California tourists in enormous numbers. Sun Valley is one of America's premiere ski and outdoor recreation communities — birthplace of destination skiing in the U.S. McCall offers lakefront and ski access in one of Idaho's most scenic settings. Boise is one of the fastest-growing metro areas in the country. Idaho's tax structure is clean and investor-friendly." },
      { type: "heading", level: 2, text: "Idaho State Income Tax", id: "idaho-income-tax" },
      { type: "paragraph", text: "Idaho recently simplified its income tax to a flat 5.8% rate. This applies uniformly to all taxable income including net rental income. The flat structure is clean for tax planning purposes — no bracket management needed. At 5.8%, Idaho's rate is virtually identical to Montana (5.9%) and comparable to Utah (4.65%). The full bonus depreciation conformity means cost segregation deductions are fully recognized at the state level." },
      { type: "heading", level: 2, text: "Idaho Lodging Taxes by Market", id: "idaho-lodging-taxes" },
      { type: "table", headers: ["County / Market", "State Sales Tax", "Local Lodging Tax", "Approximate Total"],
        rows: [
          ["Kootenai County (Coeur d'Alene)", "6%", "2–3%", "~8–9%"],
          ["Blaine County (Sun Valley/Ketchum/Hailey)", "6%", "3%", "~9%"],
          ["Valley County (McCall)", "6%", "2%", "~8%"],
          ["Ada County (Boise)", "6%", "2%", "~8%"],
          ["Bonner County (Sandpoint/Lake Pend Oreille)", "6%", "2%", "~8%"],
          ["Teton County (Driggs/Victor — near Jackson Hole)", "6%", "3%", "~9%"],
          ["Custer County (Stanley/Sawtooth area)", "6%", "1%", "~7%"],
        ]
      },
      { type: "heading", level: 2, text: "Coeur d'Alene: The Gem of the Northwest", id: "coeur-dalene-market" },
      { type: "paragraph", text: "Coeur d'Alene sits on the southern shore of Lake Coeur d'Alene — a 25-mile-long glacially carved lake surrounded by forested mountains in the Idaho Panhandle. The market draws heavily from Spokane, WA (35 miles west), Seattle (5-hour drive), and increasingly from California transplants who have relocated to North Idaho. The STR market is strong year-round: summer lake recreation (boating, paddleboarding, swimming), fall foliage, Silverwood Theme Park (nearby), and winter snow activities all contribute to demand." },
      { type: "heading", level: 2, text: "Sun Valley: America's Original Ski Resort", id: "sun-valley-market" },
      { type: "paragraph", text: "Sun Valley, established in 1936, is America's first destination ski resort. The Blaine County market (Sun Valley, Ketchum, Hailey) features luxury mountain homes, condos, and cabins that command premium rates in ski season ($400–$2,500+/night for quality properties) and strong summer demand driven by hiking, mountain biking, and the Sun Valley Festival of Arts. Property values have appreciated significantly, with many properties now trading in the $1M–$5M+ range." },
      { type: "heading", level: 2, text: "Cost Segregation in Idaho", id: "cost-seg-idaho" },
      { type: "paragraph", text: "Idaho STR properties — particularly in Sun Valley and Coeur d'Alene — have good cost segregation profiles. Ski storage and equipment areas (15-year), outdoor hot tubs and decks, lake-access infrastructure (boat docks, lifts), and luxury furnishings all contribute to short-life asset percentages of 20–28% for well-equipped properties. A $800,000 Sun Valley ski property with $200,000 in bonus-eligible deductions generates $74,000 in federal first-year savings at 37%, plus $11,600 in Idaho state savings at 5.8% — a combined $85,600 first-year benefit." },
      { type: "faq", question: "Does Idaho have statewide STR regulations?", answer: "Idaho does not have comprehensive statewide STR regulations. Local jurisdictions vary significantly. Boise has adopted STR permit requirements. Sun Valley/Ketchum has regulations. Coeur d'Alene has registration requirements. McCall has regulations that limit STRs in certain areas. Rural Idaho counties generally have minimal regulation. Always verify local rules for your target property before acquisition." },
      { type: "cta", title: "Estimate Your Idaho STR Tax Savings", text: "Idaho's growing STR markets + full bonus depreciation conformity = strong investment returns. Get your free cost segregation estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Wyoming ──────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-wyoming",
    title: "Short-Term Rental Taxes in Wyoming: No Income Tax, Jackson Hole, and the Ultimate STR Guide",
    description: "Wyoming has NO state income tax — making Jackson Hole one of the most tax-advantaged luxury STR markets in the United States. Here's the complete Wyoming STR tax guide.",
    publishedAt: "2026-03-22",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Wyoming", "Jackson Hole", "Grand Teton", "Yellowstone", "no income tax", "cost segregation", "luxury STR"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-wyoming.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Wyoming 2025: No Income Tax, Jackson Hole | Abode",
      description: "Wyoming has no state income tax, making Jackson Hole one of the most tax-advantaged luxury STR markets in the U.S. Here's the complete Wyoming STR guide with cost segregation strategy.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-wyoming",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Wyoming have a state income tax on rental income?", acceptedAnswer: { "@type": "Answer", text: "No. Wyoming has no state personal income tax. Wyoming is one of the most tax-favorable states in the United States for investors of any kind. STR rental income is only subject to federal income tax — there is no Wyoming state income tax return for individuals. Combined with the extraordinary Jackson Hole market, Wyoming offers some of the best after-tax STR returns available anywhere in the country." } },
          { "@type": "Question", name: "What taxes do Wyoming STR operators collect?", acceptedAnswer: { "@type": "Answer", text: "Wyoming STR operators collect and remit a 4% state lodging tax plus applicable county lodging taxes. In Teton County (Jackson Hole), total lodging taxes are approximately 8% of gross rental revenue. The absence of state income tax means the lodging taxes collected from guests are the primary tax compliance obligation for Wyoming STR operators." } },
          { "@type": "Question", name: "What are the typical STR property values in Jackson Hole?", acceptedAnswer: { "@type": "Answer", text: "Jackson Hole (Teton County, WY) has some of the highest STR property values in the United States. Entry-level properties start around $800,000–$1.2M for modest condos. Quality stand-alone homes and luxury properties typically range from $2M to $10M+. The combination of extreme scarcity (most land is federal — Grand Teton National Park, National Forest), no income tax, and extraordinary destination demand drives both high property values and exceptional rental rates." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Wyoming STR Tax Summary", text: "NO state income tax | Full federal bonus depreciation benefit — no state offset | 4% state lodging tax + county taxes (~8% total in Teton County) | Jackson Hole is one of the highest-end STR markets in the U.S. ($1M–$10M+ properties) | No state income tax return to file" },
      { type: "paragraph", text: "Wyoming stands alongside Florida, Texas, Nevada, and South Dakota as one of the most tax-advantaged states in the country for STR investors. The absence of state income tax is straightforward and absolute — there is simply no Wyoming individual income tax. For Jackson Hole STR investors — where properties routinely trade at $2M–$10M+ — the absence of state income tax on rental profits represents enormous savings compared to investing in comparable-quality markets in California or Oregon." },
      { type: "heading", level: 2, text: "No Wyoming Income Tax: The Foundation of Exceptional Returns", id: "no-income-tax" },
      { type: "paragraph", text: "Wyoming's constitutional prohibition on income taxes applies to all income: wages, rental income, investment income, and business income. For a Jackson Hole STR investor generating $300,000 in annual net rental income, the absence of Wyoming state income tax saves $15,000–$30,000 annually compared to the same investment in Colorado (4.4%), Idaho (5.8%), or Utah (4.65%). Over a 10-year hold, that's $150,000–$300,000 in cumulative state income tax savings — before considering property appreciation." },
      { type: "paragraph", text: "Combined with 100% federal bonus depreciation and the STR loophole, Wyoming's no-income-tax status means every dollar of cost segregation deductions translates directly to federal tax savings with zero state offset." },
      { type: "heading", level: 2, text: "Wyoming Lodging Taxes by Market", id: "wyoming-lodging-taxes" },
      { type: "table", headers: ["County / Market", "State Lodging Tax", "County Lodging Tax", "Approximate Total"],
        rows: [
          ["Teton County (Jackson Hole)", "4%", "~4%", "~8%"],
          ["Park County (Cody/Yellowstone east)", "4%", "~2%", "~6%"],
          ["Sublette County (Pinedale/Wind River)", "4%", "~2%", "~6%"],
          ["Natrona County (Casper)", "4%", "~2%", "~6%"],
          ["Laramie County (Cheyenne)", "4%", "~2%", "~6%"],
          ["Lincoln County (Afton/Star Valley)", "4%", "~2%", "~6%"],
        ]
      },
      { type: "heading", level: 2, text: "Jackson Hole: America's Premier Luxury STR Market", id: "jackson-hole-market" },
      { type: "paragraph", text: "Jackson Hole (Teton County, Wyoming) is widely considered the most exclusive ski and outdoor recreation destination in the United States. The combination of extreme natural scarcity (over 97% of Teton County land is federal — Grand Teton National Park, Bridger-Teton National Forest, and National Elk Refuge), world-class skiing at Jackson Hole Mountain Resort, proximity to Yellowstone National Park (50 miles north), and the Wyoming tax advantage creates a market with extraordinary supply constraints and exceptional demand." },
      { type: "paragraph", text: "STR properties in Jackson Hole command extraordinary rates: $800–$5,000+/night for quality properties in peak ski season (December–March) and strong summer rates driven by Grand Teton and Yellowstone tourism (June–August). Annual gross revenue of $200,000–$800,000+ is achievable for well-positioned luxury properties." },
      { type: "heading", level: 2, text: "Jackson Hole STR Regulations", id: "jackson-hole-regulations" },
      { type: "paragraph", text: "Teton County has adopted a permit system for STRs with regulations that vary by zoning district. The Town of Jackson (the municipality) and unincorporated Teton County have different rules. The county has periodically imposed moratoriums on new STR permits in certain zones. Properties with existing valid permits command a significant premium. Due diligence on permit status and transferability is absolutely critical before any Jackson Hole STR acquisition." },
      { type: "heading", level: 2, text: "Cost Segregation in Wyoming: Maximum Impact", id: "cost-seg-wyoming" },
      { type: "paragraph", text: "Wyoming's no-income-tax environment makes cost segregation maximally effective. Jackson Hole luxury properties have excellent personal property ratios: high-end furnishings and artwork in luxury mountain homes, outdoor hot tubs, ski gear storage, heated driveways, and premium appliances can represent 20–28% of very high property values. A $3M Jackson Hole property with $750,000 in bonus-eligible deductions (25% ratio) generates $277,500 in first-year federal tax savings at 37% — with zero Wyoming state income tax impact. This is one of the largest cost segregation deductions available anywhere in the country." },
      { type: "faq", question: "Is Wyoming's lack of income tax permanent?", answer: "Wyoming's prohibition on income taxes is constitutional — it would require a constitutional amendment and popular vote to impose a state income tax. Wyoming has maintained this constitutional prohibition since statehood in 1890. As a practical matter, Wyoming's income-tax-free status is as secure as any state tax policy can be." },
      { type: "cta", title: "Estimate Your Wyoming STR Tax Savings", text: "No state income tax + Jackson Hole's extraordinary property values = some of the largest cost seg deductions in the country. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── New Mexico ───────────────────────────────────────────────────────────
  {
    slug: "str-taxes-new-mexico",
    title: "Short-Term Rental Taxes in New Mexico: Taos, Santa Fe, and Complete STR Guide",
    description: "New Mexico has a 1.7–5.9% graduated income tax, conforms to federal bonus depreciation, and features Taos and Santa Fe among the Southwest's most distinctive STR markets.",
    publishedAt: "2026-03-22",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "New Mexico", "Taos", "Santa Fe", "Ruidoso", "state taxes", "cost segregation", "bonus depreciation", "gross receipts tax"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-new-mexico.jpg",
    seo: {
      title: "Short-Term Rental Taxes in New Mexico 2025: Taos, Santa Fe Investor Guide | Abode",
      description: "New Mexico's income tax tops at 5.9% and the state conforms to federal bonus depreciation. Here's the complete guide for Taos, Santa Fe, and Ruidoso STR investors.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-new-mexico",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is New Mexico's income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "New Mexico has graduated income tax rates from 1.7% to 5.9%. The top rate of 5.9% applies to income over $210,000 (single). New Mexico conforms to federal bonus depreciation, so cost segregation deductions are fully recognized at the state level." } },
          { "@type": "Question", name: "What is New Mexico's Gross Receipts Tax and does it apply to STRs?", acceptedAnswer: { "@type": "Answer", text: "New Mexico imposes a Gross Receipts Tax (GRT) instead of a traditional sales tax. The GRT applies to rental receipts from short-term rentals. The state GRT rate is 5.125%, and localities add additional rates. Total effective GRT on STR rentals in Taos is approximately 8.4375%, in Santa Fe approximately 8.4375%, and in Albuquerque approximately 7.875%. This tax is similar in function to a sales tax and is collected from guests." } },
          { "@type": "Question", name: "Does New Mexico conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. New Mexico conforms to federal bonus depreciation. A cost segregation study on a New Mexico STR property generates the same first-year deduction on your New Mexico PIT-1 return as on your federal return. No bonus depreciation addback is required." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "New Mexico STR Tax Summary", text: "1.7–5.9% graduated state income tax | Conforms to federal bonus depreciation | Gross Receipts Tax (GRT) ~8–9% on STR rental revenue (similar to sales tax) | Top markets: Taos (ski/art colony), Santa Fe (arts/culture), Ruidoso (cabin/ski), White Sands area | Unique adobe architecture drives premium positioning" },
      { type: "paragraph", text: "New Mexico offers a distinctive STR investment proposition. Taos combines world-class high-altitude skiing (Taos Ski Valley) with one of America's most celebrated art colonies and a deeply rooted Indigenous and Hispanic cultural heritage. Santa Fe is consistently ranked among the top art destinations in the United States, driving year-round cultural tourism. Ruidoso in Lincoln County offers mountain cabin rentals in an accessible format. New Mexico's tax environment is moderate and straightforward." },
      { type: "heading", level: 2, text: "New Mexico State Income Tax", id: "nm-income-tax" },
      { type: "paragraph", text: "New Mexico's graduated income tax ranges from 1.7% to 5.9%, with the 5.9% top rate applying to income over $210,000 (single filers). Most STR investors with profitable portfolios will be in the 4.9% or 5.9% bracket. New Mexico residents file Form PIT-1; non-resident owners of New Mexico STR properties file PIT-1 and pay tax on New Mexico-source income. New Mexico conforms to federal bonus depreciation, making cost segregation calculations straightforward at the state level." },
      { type: "heading", level: 2, text: "New Mexico's Gross Receipts Tax: Understanding the STR Impact", id: "gross-receipts-tax" },
      { type: "paragraph", text: "New Mexico uses a Gross Receipts Tax (GRT) rather than a traditional sales tax. The GRT applies to rental receipts from STRs, functioning similarly to a sales tax in that it is collected from guests and remitted to the state and local jurisdictions. The combined GRT rate varies by location:" },
      { type: "table", headers: ["County / Market", "State GRT", "Local GRT", "Approximate Total"],
        rows: [
          ["Taos County (Taos/Taos Ski Valley)", "5.125%", "~3.3125%", "~8.4375%"],
          ["Santa Fe County (Santa Fe city)", "5.125%", "~3.3125%", "~8.4375%"],
          ["Lincoln County (Ruidoso)", "5.125%", "~2.75%", "~7.875%"],
          ["Bernalillo County (Albuquerque)", "5.125%", "~2.75%", "~7.875%"],
          ["Otero County (Cloudcroft/Alamogordo)", "5.125%", "~2.5%", "~7.625%"],
          ["Sierra County (Truth or Consequences)", "5.125%", "~2%", "~7.125%"],
        ]
      },
      { type: "heading", level: 2, text: "Taos: Ski and Art Colony STR Market", id: "taos-market" },
      { type: "paragraph", text: "Taos is one of the most distinctive STR markets in the United States — a combination that doesn't exist elsewhere: ski-in/ski-out or ski-adjacent properties at Taos Ski Valley (America's most challenging major ski resort by vertical and terrain variety) combined with the cultural magnetism of the Taos art colony, historic Taos Pueblo, and the unique adobe architecture of the Southwest. The demand base is educated, high-income, and loyal — visitors to Taos return year after year." },
      { type: "paragraph", text: "Taos STR properties feature unique architectural elements — kiva fireplaces, exposed vigas (log ceiling beams), saltillo tile floors, and adobe construction — that appeal strongly to the cultural tourism market and distinguish Taos rentals from cookie-cutter vacation properties. These distinctive features also have excellent cost segregation value." },
      { type: "heading", level: 2, text: "Santa Fe: Arts and Culture Year-Round Demand", id: "santa-fe-market" },
      { type: "paragraph", text: "Santa Fe is one of America's top cultural tourism destinations — home to more museums per capita than any other U.S. city, the Santa Fe Opera (one of the country's premier opera companies), gallery row on Canyon Road, and the historic Plaza. STR demand in Santa Fe is remarkably year-round, driven by arts, culinary tourism, and the city's designation as a UNESCO Creative City. Properties in the historic downtown core command exceptional rates." },
      { type: "heading", level: 2, text: "Cost Segregation in New Mexico", id: "cost-seg-nm" },
      { type: "paragraph", text: "New Mexico STR properties — particularly in Taos and Santa Fe — have unique cost segregation profiles driven by their architectural character. Adobe fireplaces, custom tile work, exposed wood elements, and culturally distinctive furnishing packages contribute to 5-year personal property totals. Taos Ski Valley properties add ski storage, outdoor hot tubs, and mountain decks. Properties in both markets typically achieve 20–28% of purchase price in short-life assets. Full bonus depreciation conformity means the federal and state deductions are aligned." },
      { type: "faq", question: "Are there New Mexico STR permit requirements?", answer: "New Mexico does not have a comprehensive statewide STR licensing law. Regulation is local. Santa Fe and Taos municipalities have adopted STR permit requirements with registration, compliance, and sometimes density caps. Taos Ski Valley (an unincorporated area of Taos County) has its own specific rules. Ruidoso has STR regulations. Always verify local permit requirements before operating." },
      { type: "cta", title: "Estimate Your New Mexico STR Tax Savings", text: "Taos and Santa Fe's distinctive properties + full bonus depreciation conformity = compelling cost seg results. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Alaska ───────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-alaska",
    title: "Short-Term Rental Taxes in Alaska: No Income Tax, No Sales Tax, and Unique STR Markets",
    description: "Alaska has no state income tax and no state sales tax — making it one of the most tax-favorable states for STR investors. Here's the complete Alaska STR guide for Anchorage, Juneau, and Homer.",
    publishedAt: "2026-03-22",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Alaska", "Anchorage", "Juneau", "Homer", "Kenai", "Denali", "no income tax", "no sales tax", "cost segregation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-alaska.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Alaska 2025: No Income Tax, No Sales Tax Guide | Abode",
      description: "Alaska has no state income tax AND no state sales tax — the most tax-favorable combination in the U.S. Here's the complete Alaska STR guide for investors in Anchorage, Juneau, and Homer.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-alaska",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Alaska have a state income tax on rental income?", acceptedAnswer: { "@type": "Answer", text: "No. Alaska has no state personal income tax. Alaska is the only state with neither a state income tax nor a state sales tax. For STR investors, this means rental income is taxed only at the federal level, and there is no state sales tax to collect on rental revenue (though municipalities may have their own taxes). Alaska's tax environment is the most favorable of any state for STR investors from a pure income tax perspective." } },
          { "@type": "Question", name: "Does Alaska have a state sales tax on STR rentals?", acceptedAnswer: { "@type": "Answer", text: "No. Alaska has no statewide sales tax. However, Alaskan municipalities (cities and boroughs) are permitted to levy their own local sales and bed taxes. Anchorage does not have a municipal sales tax but has a bed tax. Juneau has a 5% sales tax plus a bed tax. Homer has local sales taxes. Sitka, Ketchikan, and other Southeast Alaska cities have local sales taxes. Total local tax rates on STR revenue range from 0% in unincorporated Alaska to 12%+ in some cities." } },
          { "@type": "Question", name: "What is the STR market like in Alaska?", acceptedAnswer: { "@type": "Answer", text: "Alaska's STR market is highly seasonal, concentrated primarily in the May–September window. The market is driven by summer cruise passengers who extend their trips, adventure and wilderness tourism (bear viewing, fishing, hiking), and the midnight sun experience. Properties in gateway cities (Anchorage, Juneau, Fairbanks), coastal destinations (Homer, Sitka, Ketchikan), and near Denali National Park all have active STR markets during peak season." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Alaska STR Tax Summary", text: "NO state income tax | NO state sales tax — unique among all 50 states | Local municipality taxes vary (0–12%) | Highly seasonal market: May–September peak | Top markets: Anchorage, Juneau, Homer/Kenai Peninsula, Denali area, Sitka | Full federal bonus depreciation benefit with no state offset" },
      { type: "paragraph", text: "Alaska stands alone among all 50 U.S. states: it has neither a state income tax nor a state sales tax. For STR investors, this represents the maximum possible state tax advantage — rental profits are taxed only at the federal level, and guests are not charged a statewide transient tax (though local taxes may apply). The trade-off is Alaska's unique market dynamics: intense seasonality, remote property locations, and operational complexity. For investors willing to navigate these factors, Alaska offers extraordinary federal tax efficiency." },
      { type: "heading", level: 2, text: "No Alaska Income Tax AND No State Sales Tax", id: "no-alaska-taxes" },
      { type: "paragraph", text: "Alaska's dual no-tax status is constitutionally and legislatively embedded. Alaska has had no state income tax since 1980 (when it was repealed, funded by oil revenues) and no state sales tax ever. For STR investors, this means:" },
      { type: "list", style: "bulleted", items: [
        "All net rental income is taxed only at the federal rate — zero state income tax",
        "No state sales tax to collect and remit on rental revenue",
        "No state income tax return to file for Alaska",
        "Full 100% federal bonus depreciation benefit flows directly to the investor with no state offset",
        "Alaska Permanent Fund Dividend (PFD) available to residents — Alaska actually pays residents each year from oil revenues",
      ]},
      { type: "heading", level: 2, text: "Local Municipality Taxes in Alaska", id: "alaska-local-taxes" },
      { type: "paragraph", text: "While Alaska has no state-level income or sales tax, individual municipalities are authorized to levy their own local taxes. STR investors need to understand the specific tax rules for their municipality." },
      { type: "table", headers: ["Municipality / Market", "Local Sales Tax", "Local Bed/Accommodation Tax", "Approximate Total on STR Revenue"],
        rows: [
          ["Anchorage (Municipality of Anchorage)", "None", "12%", "~12%"],
          ["Juneau (City and Borough of Juneau)", "5%", "7%", "~12%"],
          ["Fairbanks (City of Fairbanks)", "0%", "8%", "~8%"],
          ["Homer (City of Homer)", "7.5%", "0%", "~7.5%"],
          ["Sitka (City and Borough of Sitka)", "5%", "6%", "~11%"],
          ["Ketchikan (City of Ketchikan)", "5%", "6%", "~11%"],
          ["Kenai (City of Kenai)", "3%", "0%", "~3%"],
          ["Unincorporated Borough areas", "0%", "0%", "0%"],
        ]
      },
      { type: "heading", level: 2, text: "Alaska STR Market Overview: Seasonal Dynamics", id: "alaska-market-overview" },
      { type: "paragraph", text: "Alaska's STR market operates on a dramatically different seasonal pattern than the Lower 48. The core season runs May through September, when Alaska's extraordinary summer conditions (long days, mild temperatures, accessible wilderness) drive massive tourism. Peak season — mid-June through mid-August — sees extraordinary ADRs as cruise passengers, fishing enthusiasts, and adventure travelers flood destinations across the state. This concentration of demand into 4–5 months can produce annual revenues competitive with year-round markets in other states." },
      { type: "paragraph", text: "Winter (October–April) is significantly slower in most markets. However, Fairbanks has emerged as a Northern Lights tourism destination, creating a unique winter demand driver. Anchorage maintains some year-round demand from business and government travel." },
      { type: "heading", level: 2, text: "Top Alaska STR Markets", id: "alaska-top-markets" },
      { type: "list", style: "bulleted", items: [
        "<strong>Anchorage:</strong> Alaska's largest city and main gateway; year-round demand from business, government, and tourism; strong summer peak; properties in the Hillside area with Denali views command premium rates",
        "<strong>Juneau (Southeast Alaska):</strong> State capital; accessible only by sea or air; summer cruise season (May–September) brings enormous visitor volume; excellent ADR during peak months; glacier and wilderness tourism",
        "<strong>Homer (Kenai Peninsula):</strong> The 'Cosmic Hamlet by the Sea'; world-class halibut fishing; arts community; End of the Road appeal; Homer Spit STRs with spectacular bay views",
        "<strong>Denali area (Talkeetna/Healy):</strong> Gateway to Denali National Park — the highest peak in North America; intense summer season; iconic Alaska wilderness experience",
        "<strong>Sitka/Ketchikan (Southeast Alaska):</strong> Cruise ship destinations; Tongass National Forest; unique rainforest setting; concentrated summer season with very high short-stay ADRs during cruise season",
      ]},
      { type: "heading", level: 2, text: "Cost Segregation in Alaska: Federal Benefits Maximized", id: "cost-seg-alaska" },
      { type: "paragraph", text: "Alaska's zero-income-tax status makes cost segregation maximally efficient. Every dollar of federal bonus depreciation deduction translates to pure federal tax savings at 37% with no state offset. Alaska STR properties have varied cost segregation profiles: waterfront properties in Homer and Juneau have dock and marine infrastructure; Denali-area properties have outdoor amenities; Anchorage properties tend toward urban/suburban profiles with moderate personal property ratios." },
      { type: "paragraph", text: "One consideration: Alaska's remote location and seasonal operation means STR properties often have significant equipment and infrastructure investments — generators, heating systems, water systems — that may be depreciable assets. A thorough cost segregation study should capture all relevant components. A $600,000 Homer waterfront property might generate $120,000–$150,000 in bonus-eligible deductions — $44,400–$55,500 in first-year federal savings with zero Alaska state income tax impact." },
      { type: "faq", question: "Is STR investing in Alaska practical given the remoteness?", answer: "Remote property management in Alaska requires planning but is absolutely done by active STR investors. Professional property managers in Anchorage, Juneau, Homer, and the Kenai Peninsula are available. The key operational considerations are: seasonal opening and closing (winterization), reliable maintenance contractors given the harsh climate, and the logistics of guest arrival (most properties require vehicle or boat access). Many Alaska STR operators are remote landlords who work through local management companies." },
      { type: "cta", title: "Estimate Your Alaska STR Tax Savings", text: "No income tax + no sales tax + full federal bonus depreciation = Alaska's unmatched tax efficiency for STR investors. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

];
