// State STR tax guides — Midwest region
// States: Illinois, Indiana, Ohio, Michigan, Wisconsin, Minnesota, Missouri, Iowa, Kansas, Nebraska, North Dakota, South Dakota
// URL pattern: /learn/str-taxes-[state]

export const stateArticlesMidwest = [

  // ─── Illinois ─────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-illinois",
    title: "Short-Term Rental Taxes in Illinois: What STR Investors Need to Know in 2025",
    description: "Illinois has a 4.95% flat income tax and decouples from federal bonus depreciation — a critical issue for STR investors. Here's the complete Illinois STR tax guide covering Chicago, Galena, and more.",
    publishedAt: "2026-03-15",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Illinois", "Chicago", "Galena", "state taxes", "bonus depreciation", "cost segregation", "Illinois decoupling"],
    readTime: "9 min read",
    heroImage: "/images/blog/str-taxes-illinois.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Illinois 2025: Bonus Dep Decoupling, Chicago Rules | Abode",
      description: "Illinois decouples from federal bonus depreciation — a major issue for STR investors. Here's what IL STR investors pay, the Chicago hotel tax breakdown, and how cost segregation still works.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-illinois",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Illinois conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "No. Illinois decouples from federal bonus depreciation. On your Illinois state income tax return, you cannot claim the accelerated bonus depreciation that reduces your federal taxable income. Instead, Illinois requires you to use regular MACRS depreciation schedules. This means a cost segregation study still produces large federal deductions, but those deductions are added back on the Illinois return and depreciated over the regular asset lives for state purposes. Working with a CPA experienced in Illinois tax is essential." } },
          { "@type": "Question", name: "What is Illinois's state income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Illinois has a flat 4.95% state income tax rate on all taxable income, including net rental income. Unlike states with graduated rates, every dollar of net rental income is taxed at the same 4.95% — but the bonus depreciation decoupling means your Illinois taxable income will be higher than your federal taxable income in the year you claim bonus depreciation." } },
          { "@type": "Question", name: "What are Chicago's STR taxes?", acceptedAnswer: { "@type": "Answer", text: "Chicago has one of the highest combined hotel/STR tax rates in the United States. The combined tax on STR rentals in Chicago is approximately 17.4%, including Chicago's Home Sharing tax, city hotel accommodation tax, Illinois sales tax, and other surcharges. STR operators in Chicago also must register with the city and comply with strict licensing requirements." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Illinois STR Tax Summary", text: "4.95% flat state income tax | Illinois DOES NOT conform to federal bonus depreciation (major impact) | Chicago hotel/STR tax ~17.4% (one of highest in U.S.) | Chicago STR requires city permit | Top markets: Chicago, Galena, Starved Rock area" },
      { type: "paragraph", text: "Illinois is home to world-class STR markets — Chicago's vibrant neighborhoods, the historic lead-mining town of Galena in the northwest corner, and the natural beauty around Starved Rock State Park. But Illinois also presents one of the most important state-level tax complications in the Midwest: it decouples from federal bonus depreciation. For STR investors planning to use cost segregation, this state-level difference is critical to understand before filing." },
      { type: "heading", level: 2, text: "Illinois State Income Tax", id: "illinois-income-tax" },
      { type: "paragraph", text: "Illinois taxes all personal income at a flat 4.95%. This applies uniformly to rental income — there are no lower brackets or income thresholds. For an STR investor generating $80,000 in net rental income in Illinois, the state income tax bill is $3,960 regardless of other income. This is lower than Minnesota or Wisconsin's top rates, but the bonus depreciation decoupling issue significantly complicates the picture." },
      { type: "heading", level: 2, text: "CRITICAL: Illinois Does Not Conform to Federal Bonus Depreciation", id: "bonus-depreciation-decoupling" },
      { type: "paragraph", text: "This is the most important tax issue for Illinois STR investors. When the federal government allows 100% bonus depreciation on 5-year and 15-year assets identified in a cost segregation study, Illinois does not follow suit. Instead, Illinois requires those same assets to be depreciated on their regular MACRS schedules — 5-year assets over 5 years, 15-year assets over 15 years." },
      { type: "paragraph", text: "The practical effect: if a cost segregation study on your Illinois STR generates $150,000 in federal first-year bonus depreciation, you will need to add back the excess depreciation on your Illinois IL-1040 and use the regular MACRS amounts instead. Your Illinois taxable income will be significantly higher than your federal taxable income in Year 1. Over the full asset life, the total depreciation taken is the same — Illinois just doesn't allow the front-loading. Work with a CPA experienced in Illinois state tax to handle the addback correctly." },
      { type: "paragraph", text: "The federal benefit is still 100% real and valuable. A $150,000 federal deduction at 37% saves $55,500 in federal taxes. The Illinois impact (adding back perhaps $120,000 at 4.95%) costs approximately $5,940 more in state tax in Year 1 — a net benefit of $49,560. Cost segregation is still highly profitable in Illinois; just don't expect to eliminate your Illinois tax bill the same way you can in Tennessee or Texas." },
      { type: "heading", level: 2, text: "Illinois Sales and Lodging Taxes", id: "illinois-lodging-taxes" },
      { type: "table", headers: ["Market / Jurisdiction", "State/Local Taxes", "Approximate Total Rate"],
        rows: [
          ["Chicago (city limits)", "Chicago Home Sharing tax + accommodation tax + state", "~17.4%"],
          ["Chicago suburbs (Cook County)", "Cook County + state taxes", "~12–14%"],
          ["Galena (Jo Daviess County)", "State sales tax + county", "~8–9%"],
          ["Starved Rock area (LaSalle County)", "State sales tax + county", "~8–9%"],
          ["Bloomington-Normal", "State sales tax + city", "~9–10%"],
          ["Springfield", "State sales tax + city", "~9–10%"],
        ]
      },
      { type: "heading", level: 2, text: "Chicago STR Regulations: A Complex Market", id: "chicago-str-regulations" },
      { type: "paragraph", text: "Chicago has one of the most heavily regulated STR environments in the Midwest. The city requires all STR operators to obtain a Shared Housing Unit license or a Vacation Rental license, depending on the property type. The licensing process involves registration with the city and ongoing compliance reporting. Chicago prohibits STRs in certain building types and zoning districts. The high combined tax rate (~17.4%) is among the highest in the United States — comparable to New York City. Despite the regulatory burden, Chicago STRs in approved areas (River North, Lincoln Park, Wicker Park, the Loop) can generate excellent revenue driven by convention traffic, tourism, and corporate demand." },
      { type: "heading", level: 2, text: "Top Illinois STR Markets", id: "top-markets" },
      { type: "list", style: "bulleted", items: [
        "<strong>Chicago:</strong> High-volume market; heavily regulated; high tax rates; excellent revenue potential in approved zones; permits required before operation",
        "<strong>Galena:</strong> Historic mining town in northwest Illinois; weekend getaway from Chicago; antique shops, vineyards, rolling hills; cabin and B&B-style properties do well; much simpler regulatory environment than Chicago",
        "<strong>Starved Rock / Utica area:</strong> Illinois's most-visited state park drives year-round cabin demand; smaller market but strong occupancy during fall foliage and spring",
        "<strong>Chain o' Lakes (Lake County):</strong> Chicago-area lake market; waterfront properties with strong summer demand; limited supply relative to proximity to Chicago",
      ]},
      { type: "heading", level: 2, text: "Cost Segregation in Illinois: Still Worth It", id: "cost-seg-illinois" },
      { type: "paragraph", text: "Despite the bonus depreciation decoupling, cost segregation studies are highly beneficial for Illinois STR investors — you just need to plan around the state-level addback. The federal savings typically dwarf the state impact. A $500,000 Chicago or Galena property with $130,000 in first-year federal bonus depreciation saves approximately $48,100 federally (at 37%). The Illinois addback increases state tax by roughly $5,600 — still a net $42,500 benefit. Galena and Starved Rock properties tend to have higher personal property ratios than urban Chicago apartments, often achieving 25–35% of purchase price in short-life assets." },
      { type: "faq", question: "Do Airbnb and VRBO collect Chicago's home sharing tax?", answer: "Yes. Airbnb and VRBO both have marketplace facilitator agreements covering Chicago's state and local taxes, including the home sharing accommodation tax. Direct bookings require you to collect and remit independently, which involves registering with both the Illinois Department of Revenue and the City of Chicago." },
      { type: "faq", question: "Should I form an LLC for my Illinois STR?", answer: "An LLC is generally recommended for liability protection. Illinois LLCs pay a $75 annual fee plus the Illinois Personal Property Replacement Tax (1.5% of net income for LLCs). Consult with an Illinois attorney and CPA to determine the optimal structure for your situation, especially given the bonus depreciation addback complexity." },
      { type: "cta", title: "Estimate Your Illinois STR Tax Savings", text: "Even with Illinois's bonus depreciation decoupling, cost segregation generates significant federal savings. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Indiana ──────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-indiana",
    title: "Short-Term Rental Taxes in Indiana: Complete Guide for STR Investors",
    description: "Indiana has a 3.23% flat state income tax, county income taxes, and conforms to federal bonus depreciation. Here's the complete Indiana STR tax guide for Brown County, Indiana Dunes, and other markets.",
    publishedAt: "2026-03-15",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Indiana", "Brown County", "Indiana Dunes", "state taxes", "cost segregation", "bonus depreciation", "county innkeeper tax"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-indiana.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Indiana 2025: Brown County, Indiana Dunes Guide | Abode",
      description: "Indiana's 3.23% flat tax + county income taxes apply to STR income. Indiana conforms to federal bonus depreciation. Here's the full guide for IN STR investors.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-indiana",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is Indiana's state income tax rate for STR rental income?", acceptedAnswer: { "@type": "Answer", text: "Indiana has a flat 3.23% state income tax rate on all taxable income, including net rental income. Indiana residents also pay county income tax, which ranges from 0.5% to 3.38% depending on your county of residence (not the county where the STR is located). Total Indiana state + county income tax ranges from roughly 3.73% to 6.61%." } },
          { "@type": "Question", name: "Does Indiana conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. Indiana conforms to federal bonus depreciation, including 100% bonus depreciation under the One Big Beautiful Budget Act (OBBBA). A cost segregation study on an Indiana STR property produces the same first-year deduction on both your federal and Indiana state returns, maximizing the combined benefit." } },
          { "@type": "Question", name: "What is the innkeeper's tax in Indiana?", acceptedAnswer: { "@type": "Answer", text: "Indiana counties can impose a local innkeeper's tax on STR and hotel rentals. The rate varies by county — typically 3% to 10% of gross rental revenue. Brown County (Nashville, IN) charges 5%, Porter County (Indiana Dunes) charges 5%, and Monroe County (Bloomington) charges 5%. Marion County (Indianapolis) charges 10%. These taxes are collected from guests and remitted to the county." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Indiana STR Tax Summary", text: "3.23% flat state income tax + county income tax (0.5–3.38%) | Conforms to federal bonus depreciation | County innkeeper's tax 3–10% by county | Top markets: Brown County, Indiana Dunes, Bloomington, South Bend | STR regulations vary by municipality" },
      { type: "paragraph", text: "Indiana offers a relatively investor-friendly tax environment for STR operators: a low flat income tax rate, full conformity with federal bonus depreciation, and a range of STR markets from the artsy hills of Brown County to the Lake Michigan shoreline at Indiana Dunes. The main complexity comes from the layered county income tax and the county-by-county innkeeper's tax — both of which require local knowledge to navigate." },
      { type: "heading", level: 2, text: "Indiana State and County Income Tax", id: "indiana-income-tax" },
      { type: "paragraph", text: "Indiana's 3.23% flat income tax is one of the lower state income tax rates in the Midwest. However, Indiana also levies a county income tax that applies to Indiana residents — the county where you live (not where your STR is located). County tax rates range from 0.5% (several counties) to 3.38% (Pulaski County). Most populated Indiana counties fall in the 1–2% range, giving most Indiana STR investors a combined state + county rate of approximately 4.5–5.5%. Out-of-state investors who own an Indiana STR but don't live in Indiana pay only the 3.23% state rate with no county add-on." },
      { type: "heading", level: 2, text: "Indiana Innkeeper's Tax by County", id: "innkeepers-tax" },
      { type: "table", headers: ["County / Market", "Innkeeper's Tax Rate", "Notes"],
        rows: [
          ["Brown County (Nashville, IN)", "5%", "Art colony market; strong fall demand"],
          ["Porter County (Indiana Dunes)", "5%", "National park designation; growing market"],
          ["Monroe County (Bloomington)", "5%", "Indiana University drives demand"],
          ["Marion County (Indianapolis)", "10%", "Highest rate in state"],
          ["St. Joseph County (South Bend)", "5%", "Notre Dame drives demand"],
          ["LaPorte County (Michigan City)", "5%", "Lake Michigan resort market"],
          ["Dearborn County (Lawrenceburg)", "5%", "Cincinnati-adjacent market"],
          ["Vigo County (Terre Haute)", "5%", ""],
        ]
      },
      { type: "heading", level: 2, text: "Federal Bonus Depreciation in Indiana: Full Conformity", id: "bonus-depreciation" },
      { type: "paragraph", text: "Indiana fully conforms to federal bonus depreciation. When you commission a cost segregation study and take 100% bonus depreciation on 5-year and 15-year assets, Indiana allows the same deduction on your Indiana IT-40 return. There's no addback, no limitation, and no separate calculation — what's deductible federally is deductible in Indiana. This is a significant advantage over neighboring Illinois and Wisconsin, both of which decouple from federal bonus depreciation." },
      { type: "heading", level: 2, text: "Top Indiana STR Markets", id: "top-markets" },
      { type: "list", style: "bulleted", items: [
        "<strong>Brown County / Nashville, IN:</strong> Indiana's premier nature tourism destination; 200,000+ acres of state forest; famous for fall foliage (October is peak); art galleries, boutique shops, and cabin rentals; the quintessential Indiana STR market",
        "<strong>Indiana Dunes (Porter/LaPorte Counties):</strong> Recently elevated to National Park status, driving significant visitor growth; Lake Michigan shoreline; proximity to Chicago (60 miles) gives strong weekend demand",
        "<strong>Bloomington / Monroe Lake:</strong> Indiana University college town; strong demand for graduation weekends, football games, and year-round tourism; Lake Monroe waterfront properties",
        "<strong>Indianapolis:</strong> Urban market driven by sporting events (Indy 500, Brickyard 400, Big Ten events), conventions, and tourism; highly regulated in some areas; 10% innkeeper's tax",
        "<strong>South Bend:</strong> Notre Dame football drives extraordinary demand on home game weekends; university-adjacent STRs can generate exceptional short-burst revenue",
      ]},
      { type: "heading", level: 2, text: "Cost Segregation in Indiana", id: "cost-seg-indiana" },
      { type: "paragraph", text: "Indiana STR properties — particularly the cabin and resort-style properties in Brown County and the lake homes on Indiana Dunes — have solid cost segregation profiles. Brown County cabins with decks, hot tubs, outdoor fire pits, and rustic furnishings typically generate 20–30% of purchase price in short-life assets. A $350,000 Brown County cabin might yield $70,000–$105,000 in bonus-eligible deductions. Indiana's full bonus depreciation conformity means the federal and state deductions are perfectly aligned — a $90,000 deduction saves approximately $33,300 federally (at 37%) plus $2,907 in Indiana state tax (at 3.23%), for a combined $36,207 first-year benefit." },
      { type: "faq", question: "Do Airbnb and VRBO collect Indiana innkeeper's tax?", answer: "Airbnb and VRBO act as marketplace facilitators in Indiana and typically collect and remit both state sales tax and county innkeeper's taxes on bookings made through their platforms. However, coverage varies by county. Verify with your specific county treasurer's office and confirm with each platform what they collect for your location. Direct bookings always require you to collect and remit independently." },
      { type: "cta", title: "Estimate Your Indiana STR Tax Savings", text: "Indiana's full bonus depreciation conformity means cost segregation works cleanly at both the federal and state level. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Ohio ─────────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-ohio",
    title: "Short-Term Rental Taxes in Ohio: STR Investor's Complete 2025 Guide",
    description: "Ohio has low graduated state income taxes (0–3.75%), conforms to federal bonus depreciation, and features strong STR markets in Hocking Hills, Put-in-Bay, and Lake Erie. Here's the full Ohio STR tax guide.",
    publishedAt: "2026-03-16",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Ohio", "Hocking Hills", "Put-in-Bay", "Lake Erie", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-ohio.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Ohio 2025: Hocking Hills, Put-in-Bay Guide | Abode",
      description: "Ohio has low state income taxes (max 3.75%), conforms to federal bonus depreciation, and features Hocking Hills cabins and Lake Erie island STRs. Here's the complete Ohio STR tax guide.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-ohio",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is Ohio's state income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Ohio has a graduated income tax with rates from 0% to 3.75%. The lowest bracket (0%) applies to income under $26,050. The maximum rate of 3.75% applies to income over $115,300. This is one of the lower state income tax burdens in the Midwest, making Ohio a tax-efficient state for STR investors." } },
          { "@type": "Question", name: "Does Ohio conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. Ohio conforms to federal MACRS depreciation and bonus depreciation. A cost segregation study generates the same first-year deduction on your Ohio IT-1040 as on your federal return. Ohio does not require an addback or recalculation for bonus depreciation — unlike Illinois, Wisconsin, or Minnesota." } },
          { "@type": "Question", name: "What lodging taxes apply to Ohio STRs?", acceptedAnswer: { "@type": "Answer", text: "Ohio STR operators collect 5.75% state sales tax on transient accommodations, plus county lodging taxes that vary by county (typically 3–6% additional). In Hocking County (Hocking Hills), total taxes are approximately 9.75%. In Ottawa County (Put-in-Bay/Lake Erie), total taxes are approximately 10.75%." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Ohio STR Tax Summary", text: "0–3.75% graduated state income tax (low) | Conforms to federal bonus depreciation | 5.75% state sales tax + county lodging tax | Top markets: Hocking Hills, Put-in-Bay, Lake Erie islands, Columbus, Amish Country | Investor-friendly tax environment" },
      { type: "paragraph", text: "Ohio is an underrated destination for STR investing, offering a combination of affordable property prices, low state income taxes, full bonus depreciation conformity, and markets with genuine demand drivers. Hocking Hills — with its iconic rock formations and waterfalls — is one of the Midwest's top cabin rental markets. Put-in-Bay and South Bass Island on Lake Erie offer a unique island STR experience. Columbus, the Amish Country, and the Lake Erie wine region round out a diversified Ohio STR landscape." },
      { type: "heading", level: 2, text: "Ohio State Income Tax: One of the Lowest in the Midwest", id: "ohio-income-tax" },
      { type: "paragraph", text: "Ohio's maximum state income tax rate is 3.75% — among the lowest in the Midwest. The graduated structure means lower-income investors pay even less. Ohio also has no municipal income tax on rental income from properties located in most rural markets (municipal income taxes apply in cities like Columbus, Cleveland, and Cincinnati, but primarily to wages earned there). For most cabin investors in rural Ohio, the effective state tax rate on rental profits will be 2.5–3.75%." },
      { type: "heading", level: 2, text: "Ohio Lodging and Sales Taxes by Market", id: "lodging-taxes" },
      { type: "table", headers: ["County / Market", "State Sales Tax", "County Lodging Tax", "Approximate Total"],
        rows: [
          ["Hocking County (Hocking Hills)", "5.75%", "4%", "9.75%"],
          ["Ottawa County (Put-in-Bay)", "5.75%", "5%", "10.75%"],
          ["Erie County (Sandusky/Cedar Point area)", "5.75%", "4.5%", "10.25%"],
          ["Franklin County (Columbus)", "5.75%", "4%", "9.75%"],
          ["Cuyahoga County (Cleveland)", "5.75%", "4%", "9.75%"],
          ["Wayne County (Amish Country)", "5.75%", "3%", "8.75%"],
          ["Lake County (Lake Erie wine region)", "5.75%", "3.5%", "9.25%"],
          ["Butler County (Cincinnati north)", "5.75%", "3%", "8.75%"],
        ]
      },
      { type: "heading", level: 2, text: "Hocking Hills: Ohio's Premier STR Market", id: "hocking-hills-market" },
      { type: "paragraph", text: "Hocking Hills State Park — famous for Ash Cave, Old Man's Cave, Cedar Falls, and Conkle's Hollow — draws over 4 million visitors annually and sits within a 2-hour drive of Columbus, Cleveland, and Cincinnati. The STR market here is overwhelmingly cabin-based, with properties ranging from basic one-bedroom retreats to luxury 6-bedroom lodges with private pools and hot tubs." },
      { type: "paragraph", text: "Hocking Hills STR properties have excellent cost segregation profiles. Outdoor amenities (hot tubs, fire pits, decks with forest views, covered porches) are standard and often represent 25–30% of property value. A $400,000 Hocking Hills cabin might generate $100,000–$130,000 in bonus-eligible deductions." },
      { type: "heading", level: 2, text: "Put-in-Bay and Lake Erie Islands", id: "put-in-bay-market" },
      { type: "paragraph", text: "Put-in-Bay on South Bass Island is one of Ohio's most unique STR markets. The island is accessible only by ferry from Port Clinton and Sandusky, creating natural demand concentration. Summer (June–August) is intense with boaters, day-trippers, and weekend visitors. The season is shorter than mainland markets, but peak-season ADRs can be exceptional. Average stays are typically 1–3 nights, well within STR loophole parameters." },
      { type: "heading", level: 2, text: "Ohio STR Licensing", id: "ohio-licensing" },
      { type: "paragraph", text: "Ohio does not have a statewide STR licensing program, but local jurisdictions vary. Most rural markets like Hocking Hills require simple registration with the county auditor for lodging tax purposes. Columbus requires a short-term rental license. Put-in-Bay and South Bass Island have local island-specific regulations. Check with your specific township and county before operating." },
      { type: "faq", question: "Does Ohio tax STR income differently than W-2 income?", answer: "No — net rental income from Schedule E flows through to your Ohio IT-1040 at the same graduated rates as other income. Rental losses generated by cost segregation and the STR loophole can offset other Ohio taxable income, subject to the same passive activity and material participation rules as federal." },
      { type: "cta", title: "Calculate Your Ohio STR Tax Savings", text: "Ohio's low income tax + full bonus depreciation conformity = excellent after-tax returns. Get your free cost segregation estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Michigan ─────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-michigan",
    title: "Short-Term Rental Taxes in Michigan: Complete Guide for STR Investors",
    description: "Michigan has a 4.25% flat income tax, conforms to federal bonus depreciation, and features premier STR markets on the Great Lakes shoreline. Here's the complete Michigan STR tax guide.",
    publishedAt: "2026-03-16",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Michigan", "Traverse City", "Sleeping Bear Dunes", "Lake Michigan", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-michigan.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Michigan 2025: Traverse City, Great Lakes Guide | Abode",
      description: "Michigan's 4.25% flat income tax applies to STR rental income. Michigan conforms to federal bonus depreciation, making cost segregation highly effective for lakefront cabin investors.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-michigan",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is Michigan's income tax rate on STR rental income?", acceptedAnswer: { "@type": "Answer", text: "Michigan has a flat 4.25% state income tax on all taxable income, including net rental income from short-term rentals. Michigan does not have a graduated rate structure — every dollar of net rental income is taxed at 4.25%. Some Michigan cities impose a city income tax of 1–2.4%, but this typically applies only to city residents and businesses operating within city limits." } },
          { "@type": "Question", name: "Does Michigan conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. Michigan conforms to federal bonus depreciation. A cost segregation study produces the same first-year deduction on both your federal 1040 and Michigan MI-1040. There is no Michigan bonus depreciation addback requirement, unlike the situation in Illinois, Wisconsin, or Minnesota." } },
          { "@type": "Question", name: "What taxes apply to Michigan STR rentals?", acceptedAnswer: { "@type": "Answer", text: "Michigan imposes a 6% use tax on transient accommodations (rentals under 30 days). Many Michigan counties and municipalities add a local accommodations or lodging tax. Total rates typically range from 9–12% depending on location. Airbnb and VRBO collect and remit state use tax on their platform bookings in Michigan." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Michigan STR Tax Summary", text: "4.25% flat state income tax | Conforms to federal bonus depreciation | 6% state use tax on accommodations + local lodging taxes | Top markets: Traverse City, Sleeping Bear Dunes, South Haven, Mackinac Island, Petoskey | Strong lakefront cabin cost seg profiles" },
      { type: "paragraph", text: "Michigan has quietly become one of the Midwest's top STR investment destinations. The Great Lakes shoreline offers hundreds of miles of lakefront properties, from the wine country around Traverse City to the sandy shores of South Haven and St. Joseph. The Upper Peninsula adds adventure tourism around Pictured Rocks and the Keweenaw Peninsula. Michigan's tax environment — moderate flat rate, full bonus depreciation conformity — is straightforward and investor-friendly." },
      { type: "heading", level: 2, text: "Michigan State Income Tax", id: "michigan-income-tax" },
      { type: "paragraph", text: "Michigan's 4.25% flat income tax applies uniformly to all taxable income. For STR investors, net rental income (after expenses including depreciation) is taxed at this flat rate. Michigan's flat structure means there's no advantage to income spreading from a rate perspective. The simplicity is a benefit for investors with complex rental portfolios, and the moderate rate means cost segregation deductions have a clear quantifiable state tax benefit." },
      { type: "heading", level: 2, text: "Michigan STR Use Tax and Local Lodging Taxes", id: "michigan-lodging-taxes" },
      { type: "table", headers: ["County / Market", "State Use Tax", "Local Lodging Tax", "Approximate Total"],
        rows: [
          ["Grand Traverse County (Traverse City)", "6%", "5%", "~11%"],
          ["Leelanau County (Sleeping Bear Dunes)", "6%", "3%", "~9%"],
          ["Benzie County (Crystal Lake, Frankfort)", "6%", "3%", "~9%"],
          ["Allegan County (Saugatuck/Douglas)", "6%", "5%", "~11%"],
          ["Van Buren County (South Haven)", "6%", "3%", "~9%"],
          ["Mackinac County (Mackinac Island)", "6%", "5%", "~11%"],
          ["Ottawa County (Holland/Grand Haven)", "6%", "3%", "~9%"],
          ["Emmet County (Petoskey/Harbor Springs)", "6%", "5%", "~11%"],
        ]
      },
      { type: "heading", level: 2, text: "Traverse City: Michigan's STR Crown Jewel", id: "traverse-city-market" },
      { type: "paragraph", text: "Traverse City sits at the tip of the Old Mission Peninsula on Grand Traverse Bay — one of the most picturesque settings in the Midwest. The market is driven by the Traverse City wine country (200+ wineries in the Leelanau and Old Mission appellations), cherry orchards, Sleeping Bear Dunes National Lakeshore (20 minutes away), and the National Cherry Festival in July. Properties command premium rates: lakefront homes and wine country retreats regularly achieve $400–$900+/night in peak season." },
      { type: "heading", level: 2, text: "Other Premier Michigan STR Markets", id: "other-markets" },
      { type: "list", style: "bulleted", items: [
        "<strong>Sleeping Bear Dunes National Lakeshore (Leelanau/Benzie Counties):</strong> One of the most beautiful stretches of Great Lakes coastline; limited lodging supply relative to demand; strong occupancy for summer and fall color season",
        "<strong>South Haven / St. Joseph (Van Buren County):</strong> Lake Michigan beachfront market; 2 hours from Chicago; excellent summer demand; accessible price points relative to Traverse City",
        "<strong>Saugatuck/Douglas (Allegan County):</strong> Art colony meets beach town; popular with Chicago and Detroit weekend travelers; boutique feel with strong year-round demand",
        "<strong>Mackinac Island:</strong> Car-free island accessible by ferry; unique seasonal market; higher regulatory complexity; niche but highly recognizable brand that commands premium rates",
        "<strong>Petoskey/Harbor Springs (Emmet County):</strong> Upscale resort community; affluent Chicago families; Bay Harbor Golf Club drives premium demand",
      ]},
      { type: "heading", level: 2, text: "Cost Segregation in Michigan: The Lakefront Profile", id: "cost-seg-michigan" },
      { type: "paragraph", text: "Michigan lakefront STR properties have compelling cost segregation profiles. Dock and pier infrastructure (15-year land improvement), lakefront landscaping and seawalls (15-year), boat lifts, outdoor entertainment areas, and furnished interior packages all contribute to short-life asset percentages. Lake Michigan shoreline properties frequently achieve 20–30% of purchase price in 5-year and 15-year assets. With Michigan's full bonus depreciation conformity, a $600,000 Traverse City home with $150,000 in bonus-eligible deductions saves approximately $55,500 federally (at 37%) plus $6,375 in Michigan state tax (at 4.25%) — a combined first-year benefit of nearly $62,000." },
      { type: "faq", question: "Does Michigan have any STR-specific protections for investors?", answer: "Yes. Michigan passed Public Act 113 of 2023, which significantly restricted local governments' ability to ban short-term rentals outright. While local municipalities can still regulate STRs (permits, inspections, nuisance rules), they generally cannot prohibit them entirely in residential zones. This has made Michigan more STR-friendly than many other states from a regulatory standpoint — a significant investor protection." },
      { type: "cta", title: "Estimate Your Michigan STR Tax Savings", text: "Michigan lakefront properties + full bonus depreciation conformity = powerful cost segregation results. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Wisconsin ────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-wisconsin",
    title: "Short-Term Rental Taxes in Wisconsin: What STR Investors Must Know About Bonus Depreciation",
    description: "Wisconsin has graduated income taxes (3.54–7.65%) and limits federal bonus depreciation conformity — a critical issue for Door County, Lake Geneva, and Wisconsin Dells investors.",
    publishedAt: "2026-03-17",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Wisconsin", "Door County", "Lake Geneva", "Wisconsin Dells", "state taxes", "cost segregation", "bonus depreciation decoupling"],
    readTime: "9 min read",
    heroImage: "/images/blog/str-taxes-wisconsin.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Wisconsin 2025: Bonus Dep Limits, Door County | Abode",
      description: "Wisconsin does not fully conform to federal bonus depreciation, which affects STR investors in Door County, Lake Geneva, and Wisconsin Dells. Here's the full Wisconsin STR tax guide.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-wisconsin",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Wisconsin conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "No. Wisconsin does not conform to federal bonus depreciation. Wisconsin has its own depreciation rules that do not allow the 100% first-year bonus depreciation available on federal returns. Wisconsin uses its own modified ACRS system, which spreads depreciation deductions over longer periods. This means your Wisconsin taxable income will be higher than your federal taxable income in years when you claim bonus depreciation. STR investors in Wisconsin should work with a Wisconsin-experienced CPA to navigate the state addback requirements." } },
          { "@type": "Question", name: "What is Wisconsin's income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Wisconsin has graduated income tax rates from 3.54% to 7.65%. The rates are: 3.54% on income up to $13,810 (single); 4.65% on income $13,810–$27,630; 5.3% on income $27,630–$304,170; 7.65% on income over $304,170. Most profitable STR investors will be in the 5.3% or 7.65% bracket for their Wisconsin rental income." } },
          { "@type": "Question", name: "What room taxes apply to Wisconsin STR rentals?", acceptedAnswer: { "@type": "Answer", text: "Wisconsin has a 5% state sales tax on short-term accommodations. Counties and municipalities may add a room tax of 2–8% on top of the state rate. Door County charges an 8% county room tax (total ~13%). Lake Geneva/Walworth County charges approximately 5.5% (total ~10.5%). Wisconsin Dells area is approximately 10% total." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Wisconsin STR Tax Summary", text: "3.54–7.65% graduated state income tax | Wisconsin does NOT conform to federal bonus depreciation | 5% state sales tax + county room tax | Top markets: Door County, Lake Geneva, Wisconsin Dells, Apostle Islands | Work with a WI CPA on depreciation planning" },
      { type: "paragraph", text: "Wisconsin offers some of the Midwest's most desirable vacation property markets: the dramatic limestone cliffs and cherry orchards of Door County, the elegant resort community of Lake Geneva (Chicago's classic summer escape), the water parks and family entertainment of Wisconsin Dells, and the remote wilderness of the Apostle Islands on Lake Superior. For STR investors, Wisconsin presents a moderate-to-high tax burden with one important complication — limited bonus depreciation conformity — that requires careful planning." },
      { type: "heading", level: 2, text: "Wisconsin State Income Tax on STR Rental Income", id: "wisconsin-income-tax" },
      { type: "paragraph", text: "Wisconsin's graduated income tax tops out at 7.65% for income over $304,170 — making it one of the higher state income tax environments in the Midwest. Most STR investors with significant rental income will find themselves in the 5.3% or 7.65% bracket. Wisconsin does not have a special rate for investment income; all income is taxed at ordinary rates. Non-resident owners of Wisconsin STR properties file Wisconsin Form 1NPR and pay Wisconsin income tax on Wisconsin-source income at the same rates." },
      { type: "heading", level: 2, text: "IMPORTANT: Wisconsin's Limited Bonus Depreciation Conformity", id: "bonus-depreciation-limits" },
      { type: "paragraph", text: "Wisconsin maintains its own depreciation system, based on pre-TCJA (2017 Tax Cuts and Jobs Act) federal rules. Wisconsin generally does not allow the enhanced 100% bonus depreciation that applies federally. Instead, Wisconsin requires assets to be depreciated over their regular useful lives under Wisconsin's modified ACRS rules." },
      { type: "paragraph", text: "The practical impact: in the year you claim large bonus depreciation deductions on your federal return via cost segregation, you must add back the excess depreciation on your Wisconsin Form 1 and recalculate using Wisconsin's depreciation rules. Your Wisconsin taxable income can be substantially higher than federal in the first year, followed by lower Wisconsin income in subsequent years as the Wisconsin depreciation catches up. This is a timing difference, not a permanent loss — over the full asset life, total Wisconsin depreciation equals total federal depreciation. Work with a CPA who understands Wisconsin's depreciation regime to properly model the multi-year Wisconsin tax impact." },
      { type: "heading", level: 2, text: "Wisconsin Room Tax by Market", id: "room-tax" },
      { type: "table", headers: ["County / Market", "State Sales Tax", "County/Local Room Tax", "Approximate Total"],
        rows: [
          ["Door County", "5%", "8%", "~13%"],
          ["Walworth County (Lake Geneva)", "5%", "5.5%", "~10.5%"],
          ["Columbia County (Wisconsin Dells)", "5%", "5%", "~10%"],
          ["Dane County (Madison)", "5%", "8%", "~13%"],
          ["Milwaukee County", "5%", "5.5%", "~10.5%"],
          ["Vilas County (Eagle River area)", "5%", "4%", "~9%"],
          ["Bayfield County (Apostle Islands)", "5%", "4%", "~9%"],
          ["Ashland County (Apostle Islands)", "5%", "3%", "~8%"],
        ]
      },
      { type: "heading", level: 2, text: "Top Wisconsin STR Markets", id: "top-markets" },
      { type: "list", style: "bulleted", items: [
        "<strong>Door County:</strong> The 'Cape Cod of the Midwest'; 300 miles of shoreline on Green Bay and Lake Michigan; cherry orchards, lighthouses, and waterfront dining; strong Chicago and Milwaukee weekend market; high room tax at ~13% but strong ADR in peak season",
        "<strong>Lake Geneva (Walworth County):</strong> Chicago's classic lake resort community; old-money summer culture transitioning to STR market; high property values; proximity to Chicago (90 minutes) drives consistent demand",
        "<strong>Wisconsin Dells (Columbia County):</strong> World's largest concentration of waterparks; family-oriented; strong summer demand; year-round indoor waterpark activity keeps off-season occupancy surprisingly strong",
        "<strong>Apostle Islands (Bayfield/Ashland County):</strong> Remote Lake Superior archipelago; National Lakeshore designation; kayaking, sea caves, sailing; niche but growing adventure tourism market",
        "<strong>Elkhart Lake / Sheboygan County:</strong> Road America racing circuit drives unique demand peaks; scenic lake community with Chicago proximity",
      ]},
      { type: "faq", question: "Is cost segregation worth it for Wisconsin STR investors given the bonus depreciation limitation?", answer: "Yes, absolutely. The federal tax savings from cost segregation are unaffected by Wisconsin's rules. A $150,000 federal deduction at 37% saves $55,500 in federal taxes regardless of Wisconsin's treatment. The Wisconsin limitation might increase Wisconsin tax by $5,000–$8,000 in Year 1, but that additional Wisconsin tax will be recouped in subsequent years as you have lower Wisconsin depreciation to claim. The net Wisconsin impact over the full asset life is zero — it's purely a timing difference. The net present value of cost segregation remains strongly positive for Wisconsin investors." },
      { type: "cta", title: "Estimate Your Wisconsin STR Tax Savings", text: "Wisconsin's bonus depreciation limits don't change the federal picture. Get your free cost segregation estimate for your Door County or Lake Geneva property.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Minnesota ────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-minnesota",
    title: "Short-Term Rental Taxes in Minnesota: High Rates, No Bonus Dep, and What STR Investors Must Know",
    description: "Minnesota has graduated income taxes up to 9.85% and does not conform to federal bonus depreciation. Here's what Boundary Waters, Brainerd Lakes, and North Shore STR investors need to know.",
    publishedAt: "2026-03-17",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Minnesota", "Boundary Waters", "Brainerd Lakes", "North Shore", "state taxes", "cost segregation", "bonus depreciation decoupling"],
    readTime: "9 min read",
    heroImage: "/images/blog/str-taxes-minnesota.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Minnesota 2025: High Rates, Bonus Dep Issues | Abode",
      description: "Minnesota's top income tax rate is 9.85% and the state does not conform to federal bonus depreciation. Here's the complete guide for MN STR investors in Brainerd, BWCA, and Duluth.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-minnesota",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Minnesota conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "No. Minnesota does not conform to federal bonus depreciation. Minnesota requires depreciation to be calculated on its own schedule, generally following pre-TCJA rules. When you claim bonus depreciation on your federal return via a cost segregation study, you must add back the excess on your Minnesota M1 return. This increases Minnesota taxable income in Year 1 but reduces it in later years as you claim Minnesota depreciation. With Minnesota's high top rate of 9.85%, this addback can be significant — working with a Minnesota CPA is essential." } },
          { "@type": "Question", name: "What is Minnesota's income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Minnesota has four income tax brackets: 5.35% on the first $30,070 (single); 6.8% on $30,070–$98,760; 7.85% on $98,760–$183,340; and 9.85% on income over $183,340. Most high-income STR investors will pay 7.85% or 9.85% on their rental income, making Minnesota's income tax burden among the highest in the Midwest." } },
          { "@type": "Question", name: "What lodging taxes apply to Minnesota STR rentals?", acceptedAnswer: { "@type": "Answer", text: "Minnesota imposes a 6.875% state sales tax on short-term accommodations. Many counties and cities add lodging taxes. Hennepin County (Minneapolis) adds additional taxes. Greater Minnesota counties typically add 1–3%, bringing totals to 8–10%. Some resort areas have special lodging taxes." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Minnesota STR Tax Summary", text: "5.35–9.85% graduated state income tax (high top rate) | Minnesota does NOT conform to federal bonus depreciation | 6.875% state sales tax + local lodging taxes | Top markets: Brainerd Lakes, Boundary Waters/Ely, North Shore/Duluth | Work with a Minnesota CPA on depreciation planning" },
      { type: "paragraph", text: "Minnesota's 10,000 lakes are more than a slogan — they're the foundation of one of the Midwest's largest vacation property markets. The Brainerd Lakes area, the Boundary Waters Canoe Area Wilderness, the North Shore of Lake Superior, and the Twin Cities all offer distinct STR opportunities. However, Minnesota presents the most challenging state income tax environment in the Midwest: high graduated rates, no conformity to federal bonus depreciation, and complex state tax rules that require professional guidance." },
      { type: "heading", level: 2, text: "Minnesota State Income Tax: The Highest in the Midwest", id: "minnesota-income-tax" },
      { type: "paragraph", text: "Minnesota's top marginal income tax rate of 9.85% is the third-highest in the United States and the highest in the Midwest. For STR investors with substantial rental income, this high rate makes tax planning essential. At 9.85%, every $10,000 in net rental income costs $985 in state tax — before federal. Combined federal + Minnesota rates for high-income investors can exceed 50% on ordinary income. This makes cost segregation and the STR loophole particularly valuable tools for reducing taxable income." },
      { type: "heading", level: 2, text: "Minnesota's Bonus Depreciation Non-Conformity: What It Means", id: "bonus-depreciation" },
      { type: "paragraph", text: "Like Wisconsin and Illinois, Minnesota does not conform to federal bonus depreciation. Minnesota requires assets to be depreciated using Minnesota's own schedules, which do not include 100% first-year bonus depreciation. The practical impact:" },
      { type: "list", style: "bulleted", items: [
        "Your federal return shows large first-year bonus depreciation deductions from your cost segregation study",
        "Your Minnesota M1 return requires an addback of excess depreciation, resulting in higher Minnesota taxable income in Year 1",
        "In subsequent years, you claim Minnesota depreciation on those same assets, resulting in lower Minnesota taxable income",
        "Over the full asset life, the total depreciation taken is identical — it is a timing difference, not a permanent loss",
        "With Minnesota's 9.85% top rate, the Year 1 addback can cost $10,000–$15,000+ in additional state tax — plan accordingly",
      ]},
      { type: "heading", level: 2, text: "Minnesota Lodging Tax by Market", id: "lodging-taxes" },
      { type: "table", headers: ["County / Market", "State Sales Tax", "Local Lodging Tax", "Approximate Total"],
        rows: [
          ["Crow Wing County (Brainerd Lakes)", "6.875%", "3%", "~9.875%"],
          ["St. Louis County (Duluth/North Shore)", "6.875%", "3%", "~9.875%"],
          ["Cook County (Grand Marais/BWCA gateway)", "6.875%", "3%", "~9.875%"],
          ["Hennepin County (Minneapolis)", "6.875%", "3%", "~9.875%"],
          ["Itasca County (Grand Rapids area)", "6.875%", "1%", "~7.875%"],
          ["Otter Tail County (Detroit Lakes area)", "6.875%", "1%", "~7.875%"],
          ["Beltrami County (Bemidji area)", "6.875%", "1%", "~7.875%"],
        ]
      },
      { type: "heading", level: 2, text: "Top Minnesota STR Markets", id: "top-markets" },
      { type: "list", style: "bulleted", items: [
        "<strong>Brainerd Lakes Area:</strong> Minnesota's most popular lake district; hundreds of named lakes; family cabins and luxury lake homes; strong summer demand with growing shoulder-season activity; Gull Lake, Mille Lacs, and Whitefish Chain are premium addresses",
        "<strong>Boundary Waters / Ely Area:</strong> Gateway to the BWCA — one of America's most pristine wilderness areas; outfitter lodges and lakefront cabins; unique niche market with adventure and eco-tourism focus; intense but short season (July–September)",
        "<strong>Duluth / North Shore:</strong> Lake Superior's dramatic north shore; Duluth experiencing rapid STR growth; scenic Highway 61 from Duluth to the Canadian border; waterfalls, state parks, and fall foliage drive year-round demand",
        "<strong>Twin Cities Area:</strong> Urban STR market; Minneapolis requires STR permits; strong conference and sports event demand; year-round urban tourism",
        "<strong>Detroit Lakes (Otter Tail County):</strong> Regional lake resort area popular with North Dakotan and western MN visitors; affordable entry points with solid summer returns",
      ]},
      { type: "heading", level: 2, text: "Cost Segregation in Minnesota: Planning Around the Addback", id: "cost-seg-minnesota" },
      { type: "paragraph", text: "Despite the bonus depreciation non-conformity, cost segregation is particularly valuable for Minnesota STR investors precisely because of the high state tax rate. The federal savings are 100% intact. The Minnesota impact is a timing issue — you pay more Minnesota tax now and less later. In net present value terms, you're still ahead because the federal deferral at 37% is more valuable than the Minnesota timing impact at 9.85%." },
      { type: "paragraph", text: "Minnesota lake cabin properties typically achieve 20–28% of purchase price in short-life assets — dock systems (15-year), boat houses, recreational equipment, outdoor amenities, and premium furnishings all contribute. A $550,000 Brainerd Lakes cabin with $130,000 in bonus-eligible deductions saves $48,100 federally in Year 1, while the Minnesota addback increases Year 1 MN tax by approximately $12,800 at 9.85% — still a net $35,300 Year 1 benefit, with the Minnesota tax being recovered in subsequent years." },
      { type: "faq", question: "Can I still use the STR loophole in Minnesota to offset non-passive income?", answer: "Yes. The STR loophole (average stay under 7 days + material participation) is a federal concept that applies regardless of state tax rules. If you qualify for the loophole, your rental losses offset your federal W-2 or business income. The Minnesota bonus depreciation addback affects Minnesota taxable income, but the federal benefit of the STR loophole is fully intact and can dramatically reduce your federal tax bill regardless of what Minnesota does with the depreciation." },
      { type: "cta", title: "Estimate Your Minnesota STR Tax Savings", text: "Minnesota's high rates make the federal savings from cost segregation even more valuable in relative terms. Get your free estimate for your lake property.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Missouri ─────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-missouri",
    title: "Short-Term Rental Taxes in Missouri: Branson, Lake of the Ozarks, and Complete 2025 Guide",
    description: "Missouri has a graduated income tax up to 4.95%, conforms to federal bonus depreciation, and hosts major STR markets in Branson and Lake of the Ozarks. Here's the complete Missouri STR tax guide.",
    publishedAt: "2026-03-17",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Missouri", "Branson", "Lake of the Ozarks", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-missouri.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Missouri 2025: Branson, Lake of the Ozarks Guide | Abode",
      description: "Missouri's income tax tops at 4.95%, conforms to federal bonus depreciation, and features Branson and Lake of the Ozarks STR markets. Here's the complete Missouri STR investor guide.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-missouri",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is Missouri's state income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Missouri has a graduated income tax with rates from 2% to 4.95%. The top rate of 4.95% applies to income over $9,072 (a very low threshold), meaning most STR investors effectively pay close to 4.95% on their rental income. Missouri conforms to federal bonus depreciation, so cost segregation deductions reduce Missouri taxable income on the same basis as federal." } },
          { "@type": "Question", name: "Does Missouri conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. Missouri conforms to federal bonus depreciation rules. A cost segregation study that generates 100% first-year bonus depreciation on 5-year and 15-year assets produces the same deduction on your Missouri MO-1040 as on your federal return. This is a significant advantage over neighboring Illinois, which decouples from federal bonus depreciation." } },
          { "@type": "Question", name: "What taxes apply to Branson STR rentals?", acceptedAnswer: { "@type": "Answer", text: "Branson STR operators pay Missouri state sales tax of 4.225%, plus Taney County taxes and Branson city taxes. Total transient taxes in Branson are approximately 8.475% of gross rental revenue. Branson also requires STR registration and compliance with city ordinances." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Missouri STR Tax Summary", text: "2–4.95% graduated state income tax (effectively 4.95% for most investors) | Conforms to federal bonus depreciation | ~4.225% state sales tax + local taxes | Branson total tourism tax ~8.475% | Top markets: Branson, Lake of the Ozarks, Kansas City, St. Louis" },
      { type: "paragraph", text: "Missouri offers STR investors a favorable combination: a moderate income tax rate (effectively 4.95% for most investors), full federal bonus depreciation conformity, and two of the Midwest's most distinctive vacation markets. Branson is America's live entertainment capital — a Midwest equivalent of Nashville's show scene, drawing 10+ million visitors annually. Lake of the Ozarks offers 1,150 miles of shoreline and a lake culture that rivals any inland water recreation destination in the country. Both markets produce strong STR returns." },
      { type: "heading", level: 2, text: "Missouri State Income Tax", id: "missouri-income-tax" },
      { type: "paragraph", text: "Missouri's income tax technically has rates from 2% to 4.95%, but the brackets are very narrow — income over $9,072 hits the 4.95% top rate. In practice, the vast majority of STR investors' rental income is taxed at 4.95%. This is a mid-range rate among Midwest states — lower than Minnesota (9.85%) or Wisconsin (7.65%), comparable to Iowa, and slightly higher than Indiana (3.23%) or Ohio (3.75%)." },
      { type: "paragraph", text: "Missouri also allows a deduction for federal income taxes paid on the Missouri return, which reduces the effective Missouri tax rate somewhat. Non-residents who own Missouri STR properties file Form MO-1040NR and pay Missouri income tax on Missouri-source income at the same rates." },
      { type: "heading", level: 2, text: "Missouri Sales Tax and Tourism Taxes by Market", id: "missouri-taxes" },
      { type: "table", headers: ["Market / County", "State Sales Tax", "Local/Tourism Tax", "Approximate Total"],
        rows: [
          ["Branson (Taney County)", "4.225%", "~4.25%", "~8.475%"],
          ["Lake of the Ozarks — Camden County", "4.225%", "~2–3%", "~6.5–7.5%"],
          ["Lake of the Ozarks — Miller County", "4.225%", "~2–3%", "~6.5–7.5%"],
          ["Kansas City (Jackson County)", "4.225%", "~7–8%", "~11.5–12%"],
          ["St. Louis (city)", "4.225%", "~7%", "~11.5%"],
          ["Springfield (Greene County)", "4.225%", "~3%", "~7.5%"],
          ["Columbia (Boone County)", "4.225%", "~3%", "~7.5%"],
        ]
      },
      { type: "heading", level: 2, text: "Branson: Live Entertainment Capital STR Market", id: "branson-market" },
      { type: "paragraph", text: "Branson attracts over 10 million visitors per year with its unique concentration of live music theaters, comedy shows, magic acts, and country music legends. Unlike traditional resort towns, Branson's entertainment is the primary draw — Table Rock Lake, just south of Branson, adds a water-recreation dimension. Properties on Table Rock Lake with boat docks and water views command premium rates and have excellent cost segregation profiles — dock systems and waterfront amenities are primarily 15-year assets. Branson demand patterns produce average stays well under 7 days, supporting the STR loophole cleanly." },
      { type: "heading", level: 2, text: "Lake of the Ozarks: America's Boating Lake", id: "lake-of-the-ozarks-market" },
      { type: "paragraph", text: "Lake of the Ozarks is one of the largest man-made reservoirs in the U.S., stretching across Camden, Miller, Morgan, and Benton counties. Memorial Day through Labor Day brings intense boating and recreation activity that generates extraordinary STR demand. Lakefront properties with boat docks are the premium asset class — deep water dockage commands the highest prices and rental rates. Lake of the Ozarks is a particularly strong market for cost segregation: lakefront land improvements (docks, seawalls, boat lifts), outdoor entertainment areas, and vacation furnishing packages all contribute to high personal property ratios of 25–30%." },
      { type: "heading", level: 2, text: "Cost Segregation in Missouri: Full Federal Conformity", id: "cost-seg-missouri" },
      { type: "paragraph", text: "Missouri's full federal bonus depreciation conformity means cost segregation works cleanly at both levels. A $500,000 Branson or Lake of the Ozarks property with $125,000 in bonus-eligible deductions saves $46,250 federally (at 37%) plus $6,188 in Missouri state taxes (at 4.95%) — a combined first-year benefit of over $52,000." },
      { type: "faq", question: "Does Missouri have any STR-specific state regulations?", answer: "Missouri does not have a comprehensive statewide STR regulation law. Regulation is primarily at the local level. Branson has specific STR registration requirements. Kansas City has adopted a rental property inspection and licensing program. Most rural markets (Lake of the Ozarks, Branson area outside city limits) have relatively light regulatory requirements. Always verify with your specific county and municipality before operating." },
      { type: "cta", title: "Estimate Your Missouri STR Tax Savings", text: "Missouri's Branson and Lake of the Ozarks markets + full bonus depreciation conformity = excellent investment math. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Iowa ─────────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-iowa",
    title: "Short-Term Rental Taxes in Iowa: What STR Investors Need to Know",
    description: "Iowa's income tax is transitioning to a 3.9% flat rate, the state conforms to federal bonus depreciation, and STR markets center on the Iowa Great Lakes. Here's the complete Iowa STR guide.",
    publishedAt: "2026-03-18",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Iowa", "Iowa Great Lakes", "Okoboji", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "7 min read",
    heroImage: "/images/blog/str-taxes-iowa.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Iowa 2025: Great Lakes, Okoboji STR Guide | Abode",
      description: "Iowa's income tax is phasing to a flat 3.9%, it conforms to federal bonus depreciation, and the Iowa Great Lakes are the state's top STR market. Here's the complete Iowa STR investor guide.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-iowa",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is Iowa's income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Iowa is undergoing significant income tax reform. For 2025–2026, Iowa's income tax is approximately 4.4–6% (graduated rates). Iowa's legislature has enacted a phased reduction to a flat 3.9% rate fully effective by 2026. This declining rate trend is favorable for Iowa STR investors." } },
          { "@type": "Question", name: "Does Iowa conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. Iowa conforms to federal bonus depreciation. A cost segregation study generates the same first-year deduction on your Iowa IA-1040 as on your federal return. Iowa does not require the bonus depreciation addback that Illinois, Wisconsin, and Minnesota require." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Iowa STR Tax Summary", text: "Income tax phasing to 3.9% flat by 2026 (declining rate trend) | Conforms to federal bonus depreciation | 5% state sales tax + local hotel/motel taxes | Top STR markets: Iowa Great Lakes (Okoboji/Spirit Lake), Des Moines area | Improving tax environment" },
      { type: "paragraph", text: "Iowa is not typically the first state that comes to mind for STR investing, but it offers a favorable tax environment that is actively improving: a declining income tax rate trending to a flat 3.9%, full federal bonus depreciation conformity, and the iconic Iowa Great Lakes region around Spirit Lake and Lake Okoboji — a genuine vacation destination that has served Iowa, South Dakota, and Nebraska families for generations." },
      { type: "heading", level: 2, text: "Iowa's Declining Income Tax Rate", id: "iowa-income-tax" },
      { type: "paragraph", text: "Iowa enacted comprehensive income tax reform phasing the state to a flat 3.9% rate. The top rate has fallen dramatically from a previous 8.98% high. For STR investors, this trajectory is favorable — locking in cost segregation deductions at current rates offsets income that will be taxed at lower rates in future years, maximizing the net present value of the federal and state tax savings." },
      { type: "heading", level: 2, text: "Iowa Hotel and Motel Taxes", id: "iowa-lodging-taxes" },
      { type: "table", headers: ["County / Market", "State Sales Tax", "Local Hotel Tax", "Approximate Total"],
        rows: [
          ["Dickinson County (Iowa Great Lakes/Okoboji)", "5%", "7%", "~12%"],
          ["Spirit Lake / Arnold's Park", "5%", "7%", "~12%"],
          ["Polk County (Des Moines)", "5%", "7%", "~12%"],
          ["Johnson County (Iowa City)", "5%", "7%", "~12%"],
          ["Linn County (Cedar Rapids)", "5%", "7%", "~12%"],
          ["Story County (Ames/Iowa State)", "5%", "5%", "~10%"],
          ["Scott County (Davenport/Quad Cities)", "5%", "7%", "~12%"],
        ]
      },
      { type: "heading", level: 2, text: "Iowa Great Lakes: The State's Premier STR Market", id: "iowa-great-lakes" },
      { type: "paragraph", text: "The Iowa Great Lakes region — centered on Spirit Lake, Lake Okoboji (West Okoboji and East Okoboji), and surrounding smaller lakes in Dickinson County — is the most concentrated STR market in Iowa. These glacially formed lakes draw visitors from across Iowa, South Dakota, Nebraska, and Minnesota. The Arnold's Park Amusement Park, marinas, lakefront restaurants, and summer festivals anchor the seasonal tourism economy." },
      { type: "paragraph", text: "West Lake Okoboji is the crown jewel — one of only three natural blue-water lakes in the world (alongside Lake Tahoe and Geneva in Switzerland). Lakefront properties on West Okoboji command premium prices and strong rental rates. The season is concentrated May–September, with July 4th and Labor Day weekend being peak demand periods." },
      { type: "heading", level: 2, text: "Cost Segregation in Iowa", id: "cost-seg-iowa" },
      { type: "paragraph", text: "Iowa lakefront properties have solid cost segregation profiles. Dock systems, boat storage structures, outdoor entertainment areas, and vacation furnishings contribute to short-life asset totals of 18–25% of purchase price. Iowa's full bonus depreciation conformity means the federal and state deductions are aligned. A $400,000 lake cottage with $80,000 in bonus-eligible deductions saves $29,600 federally plus approximately $3,120 in Iowa state tax — a combined $32,720 first-year benefit against a study cost of $4,000–$7,000." },
      { type: "faq", question: "Are Iowa STR regulations burdensome?", answer: "Iowa does not have a comprehensive statewide STR licensing law. Most regulation occurs at the county and city level. Dickinson County (Iowa Great Lakes area) has registration requirements for vacation rentals. Des Moines and Iowa City have adopted local STR ordinances. The regulatory environment is generally less complex than urban markets like Minneapolis or Chicago." },
      { type: "cta", title: "Estimate Your Iowa STR Tax Savings", text: "Iowa's declining tax rates and full bonus depreciation conformity make cost segregation an excellent investment. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Kansas ───────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-kansas",
    title: "Short-Term Rental Taxes in Kansas: What STR Investors Need to Know",
    description: "Kansas has a 3.1–5.7% graduated income tax, conforms to federal bonus depreciation, and has limited but growing STR markets. Here's the complete Kansas STR tax guide.",
    publishedAt: "2026-03-18",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Kansas", "Kansas City", "Wichita", "Lawrence", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "7 min read",
    heroImage: "/images/blog/str-taxes-kansas.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Kansas 2025: Complete STR Investor Guide | Abode",
      description: "Kansas has a 3.1–5.7% graduated income tax and conforms to federal bonus depreciation. Limited STR markets but clear rules. Here's the Kansas STR tax guide.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-kansas",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is Kansas's income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Kansas has a two-bracket graduated income tax: 3.1% on income up to $15,000 (single), and 5.7% on income over $30,000. Most STR investors with profitable rental portfolios effectively pay 5.7% on their net rental income. Kansas conforms to federal bonus depreciation, so cost segregation deductions flow through to the Kansas K-40 return at the same amounts." } },
          { "@type": "Question", name: "Does Kansas conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. Kansas conforms to federal bonus depreciation. A cost segregation study on a Kansas STR property produces the same first-year deduction on your Kansas K-40 as on your federal return. No bonus depreciation addback is required on the Kansas state return." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Kansas STR Tax Summary", text: "3.1–5.7% graduated income tax | Conforms to federal bonus depreciation | 6.5% state sales tax + local transient room taxes | Limited STR markets concentrated near Kansas City metro, Wichita, and Lawrence | Straightforward tax compliance" },
      { type: "paragraph", text: "Kansas is not a major STR destination market, but STR investing does exist in the state — primarily in the Kansas City metro area, around Wichita for sports and conference demand, in college-town Lawrence, and in recreation areas like Cheney Reservoir and Milford Lake. For Kansas STR investors, the tax environment is clean and investor-friendly: moderate rates, full bonus depreciation conformity, and clear sales tax rules." },
      { type: "heading", level: 2, text: "Kansas State Income Tax", id: "kansas-income-tax" },
      { type: "paragraph", text: "Kansas taxes income at 3.1% on the first $15,000 (single filers) and 5.7% on income above $30,000. The brackets are narrow, so most investors with meaningful rental income pay the 5.7% top rate on the majority of their rental profits. This is a mid-range rate — lower than Minnesota or Wisconsin but comparable to Nebraska or Missouri. Kansas conforms to federal depreciation, making state-level cost segregation calculations straightforward." },
      { type: "heading", level: 2, text: "Kansas Sales Tax and Transient Room Tax", id: "kansas-taxes" },
      { type: "table", headers: ["County / Market", "State Sales Tax", "Local Transient Tax", "Approximate Total"],
        rows: [
          ["Johnson County (Overland Park/Shawnee)", "6.5%", "2–5%", "~8.5–11.5%"],
          ["Wyandotte County (Kansas City, KS)", "6.5%", "2%", "~8.5%"],
          ["Sedgwick County (Wichita)", "6.5%", "7%", "~13.5%"],
          ["Shawnee County (Topeka)", "6.5%", "2%", "~8.5%"],
          ["Douglas County (Lawrence)", "6.5%", "2%", "~8.5%"],
          ["Rural counties (lakes, recreation areas)", "6.5%", "0–2%", "~6.5–8.5%"],
        ]
      },
      { type: "heading", level: 2, text: "Kansas STR Markets", id: "kansas-markets" },
      { type: "paragraph", text: "Kansas's STR market is primarily driven by: (1) Kansas City metro area demand from the Kansas side — conferences, Chiefs and Royals games, arts and entertainment; (2) Wichita — aviation industry hub with significant business travel and events; (3) Lawrence — University of Kansas drives consistent demand for graduation weekends, football games, and basketball season; (4) Flint Hills and rural recreation areas around Milford Lake, Cheney Reservoir, and Kanopolis Lake." },
      { type: "heading", level: 2, text: "Cost Segregation in Kansas", id: "cost-seg-kansas" },
      { type: "paragraph", text: "Kansas STR properties tend to have lower personal property ratios than cabin/resort markets in other states. However, any furnished vacation rental will have 5-year assets (furniture, appliances, electronics) and potentially outdoor improvements. For Kansas STR investors with property values above $350,000, a cost segregation study can still generate meaningful federal savings. Full bonus depreciation conformity means the state deduction is aligned with the federal deduction." },
      { type: "faq", question: "Does Kansas have statewide STR regulations?", answer: "Kansas does not have a comprehensive statewide STR law. Regulation is left to municipalities. Wichita, Lawrence, and Overland Park have adopted local STR ordinances requiring permits. Most rural counties have minimal regulation. Always verify local requirements for your specific property address before operating." },
      { type: "cta", title: "Estimate Your Kansas STR Tax Savings", text: "Even in smaller markets, cost segregation can generate meaningful federal and state tax savings. Get your free Kansas estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Nebraska ─────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-nebraska",
    title: "Short-Term Rental Taxes in Nebraska: Complete STR Investor Guide",
    description: "Nebraska has a 2.46–6.64% graduated income tax, conforms to federal bonus depreciation, and has growing STR markets in Omaha and around Lake McConaughy. Here's the complete Nebraska STR guide.",
    publishedAt: "2026-03-18",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Nebraska", "Omaha", "Lake McConaughy", "Lincoln", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "7 min read",
    heroImage: "/images/blog/str-taxes-nebraska.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Nebraska 2025: Complete STR Investor Guide | Abode",
      description: "Nebraska's income tax tops at 6.64%, conforms to federal bonus depreciation, and features Omaha and Lake McConaughy STR markets. Here's the full Nebraska STR tax guide.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-nebraska",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is Nebraska's income tax rate on STR rental income?", acceptedAnswer: { "@type": "Answer", text: "Nebraska has graduated income tax rates from 2.46% to 6.64%. The top rate of 6.64% applies to income over approximately $33,180 (single). Nebraska is also in the process of phased income tax reductions toward a lower flat rate. For most STR investors, the effective rate on rental income is close to the 6.64% top rate." } },
          { "@type": "Question", name: "Does Nebraska conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. Nebraska conforms to federal bonus depreciation. Cost segregation deductions are allowed in full on your Nebraska state return at the same amounts as your federal return. No addback is required, making the state-level calculation straightforward." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Nebraska STR Tax Summary", text: "2.46–6.64% graduated income tax (phased reductions underway) | Conforms to federal bonus depreciation | 5.5% state sales tax + local occupation taxes | Top markets: Omaha (Berkshire Hathaway week, College World Series), Lincoln, Lake McConaughy | Declining tax rate trend favors acting now on cost segregation" },
      { type: "paragraph", text: "Nebraska is not a major vacation rental destination, but the state has meaningful STR activity driven by Omaha (a major conference city with unique demand events), Lincoln (University of Nebraska, Husker football), and outdoor recreation around Lake McConaughy in the Sandhills. Nebraska's tax rules are investor-friendly — full bonus depreciation conformity and a declining income tax rate trend." },
      { type: "heading", level: 2, text: "Nebraska State Income Tax", id: "nebraska-income-tax" },
      { type: "paragraph", text: "Nebraska's top income tax rate is 6.64% — one of the higher rates in the Midwest. However, Nebraska has enacted phased reductions bringing the rate down toward a flat rate over coming years. For STR investors, cost segregation deductions that reduce current-year Nebraska income are particularly valuable when locking in savings at today's higher rate before reductions take effect — the state tax savings per dollar of deduction are greatest now." },
      { type: "heading", level: 2, text: "Nebraska Sales Tax and Lodging Taxes", id: "nebraska-taxes" },
      { type: "table", headers: ["County / Market", "State Sales Tax", "Local Occupation Tax", "Approximate Total"],
        rows: [
          ["Douglas County (Omaha)", "5.5%", "2.5%", "~8%"],
          ["Lancaster County (Lincoln)", "5.5%", "1.75%", "~7.25%"],
          ["Keith County (Lake McConaughy / Ogallala)", "5.5%", "1%", "~6.5%"],
          ["Hall County (Grand Island)", "5.5%", "1.5%", "~7%"],
          ["Scotts Bluff County (Scottsbluff)", "5.5%", "1.5%", "~7%"],
          ["Rural counties", "5.5%", "0–1%", "~5.5–6.5%"],
        ]
      },
      { type: "heading", level: 2, text: "Nebraska STR Markets", id: "nebraska-markets" },
      { type: "paragraph", text: "Omaha is Nebraska's most compelling STR market. The Berkshire Hathaway Annual Meeting each May draws 40,000+ shareholders, creating a massive 2–3 day demand spike with extraordinary ADRs across all accommodation types. The College World Series (NCAA baseball) each June brings sustained multi-week demand. Year-round conference and event business at the CHI Health Center keeps baseline occupancy healthy." },
      { type: "paragraph", text: "Lake McConaughy — Nebraska's largest reservoir — is the state's primary water recreation attraction near Ogallala. The lake attracts boaters, campers, and outdoor enthusiasts from across Nebraska and neighboring states. STR cabins and lakefront properties are limited in supply but see strong summer demand. Lake McConaughy properties have the best cost segregation profiles in the state due to dock infrastructure and outdoor amenity packages." },
      { type: "heading", level: 2, text: "Cost Segregation for Nebraska STR Investors", id: "cost-seg-nebraska" },
      { type: "paragraph", text: "Nebraska's full bonus depreciation conformity means cost segregation deductions are fully recognized at both federal and state levels. Nebraska's declining tax rate also means acting sooner rather than later on cost segregation maximizes the state-level benefit at current higher rates. For urban Omaha properties, personal property ratios tend to be 15–20%, but the dollar value justifies studies for properties above $400,000. For Lake McConaughy vacation properties, outdoor amenities push ratios to 20–25%." },
      { type: "faq", question: "Do Airbnb and VRBO collect Nebraska sales tax on bookings?", answer: "Yes. Both platforms have marketplace facilitator agreements with Nebraska and collect and remit state sales tax on Nebraska bookings. Local occupation taxes (city/county level) may or may not be fully covered depending on the jurisdiction. Verify the specific coverage for your location and ensure any gap in local tax remittance is covered." },
      { type: "cta", title: "Estimate Your Nebraska STR Tax Savings", text: "Nebraska's full bonus depreciation conformity and declining tax rates favor acting now on cost segregation. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── North Dakota ──────────────────────────────────────────────────────────
  {
    slug: "str-taxes-north-dakota",
    title: "Short-Term Rental Taxes in North Dakota: Low Rates, Full Bonus Dep, Complete STR Guide",
    description: "North Dakota has very low income taxes (1.1–2.9%), conforms to federal bonus depreciation, and STR markets center on the Badlands and Theodore Roosevelt National Park. Here's the complete ND guide.",
    publishedAt: "2026-03-19",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "North Dakota", "Badlands", "Theodore Roosevelt National Park", "Medora", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "7 min read",
    heroImage: "/images/blog/str-taxes-north-dakota.jpg",
    seo: {
      title: "Short-Term Rental Taxes in North Dakota 2025: Badlands, Low Rate Guide | Abode",
      description: "North Dakota has the lowest income tax rate in the Midwest (max 2.9%) and conforms to federal bonus depreciation. Here's the ND STR tax guide for Medora, Bismarck, and Fargo investors.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-north-dakota",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "What is North Dakota's income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "North Dakota has the lowest income tax rate in the Midwest: 1.1% on income up to $44,725 (single) and 2.9% on income over $44,725. This is one of the lowest state income tax burdens in the country. North Dakota conforms to federal bonus depreciation, so cost segregation deductions fully apply at the state level as well." } },
          { "@type": "Question", name: "Does North Dakota conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. North Dakota conforms to federal bonus depreciation. There is no bonus depreciation addback required on the North Dakota ND-1 state return. This is a significant advantage for STR investors using cost segregation." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "North Dakota STR Tax Summary", text: "1.1–2.9% income tax — lowest in the Midwest | Conforms to federal bonus depreciation | 5% state sales tax + local lodging taxes | Main STR markets: Medora/Badlands, Bismarck, Fargo | Very low state income tax burden maximizes net returns" },
      { type: "paragraph", text: "North Dakota is not a major STR destination state, but it offers the most investor-favorable income tax environment in the entire Midwest. With income tax rates topping at just 2.9%, North Dakota STR investors keep a greater share of their rental profits than investors in any other Midwestern state. The state also fully conforms to federal bonus depreciation, giving cost segregation its full double benefit." },
      { type: "heading", level: 2, text: "North Dakota State Income Tax: The Lowest in the Midwest", id: "nd-income-tax" },
      { type: "paragraph", text: "North Dakota's top income tax rate is 2.9% — dramatically lower than Minnesota (9.85%), Wisconsin (7.65%), or even Iowa (declining to 3.9%). For STR investors, this means state income taxes on rental profits are minimal. The low rate makes cost segregation's state-level savings modest in absolute terms, but the federal savings remain fully intact and the low combined tax burden means investors build wealth substantially faster than in neighboring high-tax states." },
      { type: "heading", level: 2, text: "North Dakota Sales Tax and Lodging Taxes", id: "nd-taxes" },
      { type: "table", headers: ["County / Market", "State Sales Tax", "Local Lodging Tax", "Approximate Total"],
        rows: [
          ["Billings County (Medora/Theodore Roosevelt NP)", "5%", "3%", "~8%"],
          ["Burleigh County (Bismarck)", "5%", "2%", "~7%"],
          ["Cass County (Fargo)", "5%", "2%", "~7%"],
          ["Grand Forks County", "5%", "2%", "~7%"],
          ["Morton County (Mandan)", "5%", "2%", "~7%"],
          ["McKenzie County (Williston area)", "5%", "1%", "~6%"],
        ]
      },
      { type: "heading", level: 2, text: "North Dakota STR Markets", id: "nd-markets" },
      { type: "paragraph", text: "North Dakota's primary STR draw is Theodore Roosevelt National Park and the nearby town of Medora — a historic cowboy town that serves as the park's western gateway. The park attracts 700,000+ visitors annually, with summer (June–August) and fall being peak seasons. Medora's historic charm, the Medora Musical outdoor show, and the dramatic Badlands scenery create a unique destination. Cabin rentals in and around Medora and Belfield are a small but growing market." },
      { type: "paragraph", text: "Bismarck and Fargo offer urban STR markets driven by conferences, sports events (NDSU Bison football is a regional draw), and oil industry corporate travel in the western part of the state. Properties in these cities can achieve reasonable occupancy, though ADRs are lower than resort markets." },
      { type: "heading", level: 2, text: "Cost Segregation in North Dakota", id: "cost-seg-nd" },
      { type: "paragraph", text: "North Dakota's full bonus depreciation conformity makes cost segregation calculations straightforward. While the state tax savings are modest given the low 2.9% rate, the federal savings are identical to those in any other state. For a $400,000 Medora or Bismarck STR property, cost segregation might identify $80,000 in bonus-eligible assets — generating $29,600 in federal tax savings at 37% plus $2,320 in North Dakota state savings. The study cost is recovered many times over from federal savings alone." },
      { type: "faq", question: "Does North Dakota have any unique STR licensing requirements?", answer: "North Dakota does not have a comprehensive statewide STR licensing law. Most regulation is at the city and county level. Bismarck and Fargo have adopted local short-term rental ordinances. Medora and rural Badlands areas have minimal regulation. STR operators must register with the ND Tax Commissioner for accommodation tax collection purposes." },
      { type: "cta", title: "Estimate Your North Dakota STR Tax Savings", text: "North Dakota's ultra-low income tax and full bonus depreciation conformity mean you keep more of your federal tax savings. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── South Dakota ─────────────────────────────────────────────────────────
  {
    slug: "str-taxes-south-dakota",
    title: "Short-Term Rental Taxes in South Dakota: No Income Tax, Black Hills, and Cost Seg Benefits",
    description: "South Dakota has NO state income tax — one of the best tax environments for STR investors. Here's the complete guide for Black Hills, Rapid City, Deadwood, and Custer State Park markets.",
    publishedAt: "2026-03-19",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "South Dakota", "Black Hills", "Rapid City", "Deadwood", "no income tax", "cost segregation", "Sturgis"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-south-dakota.jpg",
    seo: {
      title: "Short-Term Rental Taxes in South Dakota 2025: No Income Tax, Black Hills Guide | Abode",
      description: "South Dakota has no state income tax — a major benefit for STR investors. Here's the complete guide for Black Hills, Rapid City, Deadwood, and Mount Rushmore STR markets.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-south-dakota",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does South Dakota have a state income tax?", acceptedAnswer: { "@type": "Answer", text: "No. South Dakota has no state personal income tax. This is one of only nine states in the U.S. without a state income tax, making South Dakota one of the most tax-favorable states for STR investors. All rental income is taxed only at the federal level — there is no South Dakota individual income tax return to file." } },
          { "@type": "Question", name: "What taxes do South Dakota STR investors pay on rental revenue?", acceptedAnswer: { "@type": "Answer", text: "South Dakota STR operators collect and remit a 4.5% state sales tax on rental revenue, plus applicable municipal sales tax (typically 2% in most cities) and a tourism tax in qualifying tourism areas. Total transient taxes in Rapid City are approximately 9%, in Deadwood approximately 9–10%, and in rural Black Hills counties approximately 6–7%." } },
          { "@type": "Question", name: "Does South Dakota conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "South Dakota has no income tax, so there is no state-level depreciation issue. Federal bonus depreciation flows 100% to your benefit without any South Dakota state adjustment. You benefit fully from cost segregation at the federal level with zero state offset or complexity." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "South Dakota STR Tax Summary", text: "NO state income tax | Full federal bonus depreciation benefit — no state offset | 4.5% state sales tax + local taxes (~9% total in most markets) | Top markets: Black Hills (Rapid City, Deadwood, Mount Rushmore area), Custer State Park, Sturgis area | Excellent tax environment for STR investing" },
      { type: "paragraph", text: "South Dakota joins a small group of states — including Florida, Texas, Nevada, and Wyoming — with no state personal income tax, giving it an exceptional tax environment for STR investors. The Black Hills region in western South Dakota is a legitimate national tourism destination: Mount Rushmore, Crazy Horse Memorial, Custer State Park, Badlands National Park, and the historic gambling town of Deadwood draw millions of visitors annually. The annual Sturgis Motorcycle Rally creates one of the single largest concentrated STR demand events anywhere in the Midwest." },
      { type: "heading", level: 2, text: "No South Dakota Income Tax: A Major STR Advantage", id: "no-income-tax" },
      { type: "paragraph", text: "South Dakota's constitutional prohibition on income taxes is one of the most investor-friendly tax policies in the country. For STR investors, this means: (1) 100% of net rental income is only subject to federal taxes; (2) Cost segregation deductions flow entirely to the federal return with no state-level complexity; (3) The STR loophole produces federal loss deductions with no state offset required; (4) There is no South Dakota individual income tax return to file." },
      { type: "paragraph", text: "Compare this to neighboring states: Minnesota charges up to 9.85% and doesn't conform to bonus depreciation. North Dakota charges 2.9% (low, but still present). Iowa is trending to 3.9%. South Dakota investors simply pay federal taxes — and keep the full federal benefit of every dollar of cost segregation deductions." },
      { type: "heading", level: 2, text: "South Dakota Sales Tax on STR Rentals", id: "sd-sales-tax" },
      { type: "table", headers: ["County / Market", "State Sales Tax", "Local/Municipal Sales Tax", "Approximate Total"],
        rows: [
          ["Rapid City / Pennington County", "4.5%", "2% + tourism tax", "~9%"],
          ["Deadwood (Lawrence County)", "4.5%", "2%", "~9–10%"],
          ["Custer (Custer County)", "4.5%", "2%", "~7–8%"],
          ["Hot Springs (Fall River County)", "4.5%", "2%", "~7%"],
          ["Hill City (Pennington County)", "4.5%", "2%", "~7.5%"],
          ["Rural Black Hills (unincorporated)", "4.5%", "0–1%", "~5–6%"],
          ["Sioux Falls (Minnehaha County)", "4.5%", "2%", "~7%"],
          ["Sturgis (Meade County)", "4.5%", "2%", "~7%"],
        ]
      },
      { type: "heading", level: 2, text: "The Black Hills: South Dakota's STR Powerhouse", id: "black-hills-market" },
      { type: "list", style: "bulleted", items: [
        "<strong>Mount Rushmore / Keystone:</strong> 2–3 million annual visitors; family-oriented; strong summer demand; July 4th is one of the most intense demand days in the entire Midwest for STR properties",
        "<strong>Deadwood:</strong> Historic gold rush town with legalized gambling; adult-oriented; year-round demand from casino visitors; unique regulated environment with specific STR rules",
        "<strong>Custer State Park:</strong> 71,000 acres of spectacular Black Hills scenery; free-roaming bison herds; game drives and wildlife viewing; very limited lodging supply relative to demand — cabin rentals near the park command premium rates",
        "<strong>Sturgis Motorcycle Rally:</strong> 700,000+ attendees each August; creates the single most intense 10-day STR demand event in the entire Midwest; properties within 30 miles of Sturgis can generate months of revenue in one Rally week",
        "<strong>Badlands National Park:</strong> 1M+ annual visitors; limited nearby lodging; Wall Drug tourism complex on the eastern approach; STR demand is strong in the Rapid City-to-Wall corridor",
      ]},
      { type: "heading", level: 2, text: "Sturgis Rally: The Annual Revenue Windfall", id: "sturgis-rally" },
      { type: "paragraph", text: "The Sturgis Motorcycle Rally in early August deserves special mention. Properties within 30–50 miles of Sturgis — including Rapid City, Deadwood, and throughout the Black Hills — see nightly rates increase 5–10x during the Rally's 10-day run. A property that normally rents for $200/night can command $800–$2,000/night during Sturgis. This annual revenue spike is a unique financial advantage of Black Hills STR ownership that investors should factor heavily into purchase economics." },
      { type: "heading", level: 2, text: "Cost Segregation in South Dakota", id: "cost-seg-sd" },
      { type: "paragraph", text: "South Dakota's no-income-tax environment makes cost segregation maximally effective. Every dollar of federal deduction benefits the investor at their full federal rate (37% for high-income investors) with zero state offset. Black Hills cabin properties have good cost segregation profiles — rustic amenities (fireplaces, decks, hot tubs, outdoor seating areas), pine log construction details, and vacation furnishing packages contribute to personal property ratios of 20–30%. A $500,000 Black Hills cabin with $125,000 in bonus-eligible deductions generates $46,250 in first-year federal tax savings — with no South Dakota state income tax on rental income to worry about." },
      { type: "faq", question: "Are there STR regulations in the Black Hills / Rapid City area?", answer: "STR regulation in the Black Hills varies by jurisdiction. Rapid City has adopted a short-term rental licensing and registration ordinance. Deadwood has specific regulations tied to its historic character designation. Many rural Pennington and Custer County areas have minimal regulation. The Sturgis area has addressed STR activity particularly around Rally week. Always verify the specific rules for your property's township and county before operating." },
      { type: "cta", title: "Estimate Your South Dakota STR Tax Savings", text: "No income tax + full federal bonus depreciation + a booming Black Hills market. Get your free cost segregation estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

];
