// State STR tax guides — Northeast region
// States: Pennsylvania, New Jersey, Massachusetts, Connecticut, Rhode Island, Vermont, New Hampshire, Maine, Maryland, Delaware
// URL pattern: /learn/str-taxes-[state]

export const stateArticlesNortheast = [

  // ─── Pennsylvania ─────────────────────────────────────────────────────────
  {
    slug: "str-taxes-pennsylvania",
    title: "Short-Term Rental Taxes in Pennsylvania: What Investors Need to Know in 2025",
    description: "Pennsylvania has a 3.07% flat income tax but does NOT conform to federal bonus depreciation — a critical planning issue for Pocono Mountains and Philadelphia STR investors.",
    publishedAt: "2026-03-10",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Pennsylvania", "Pocono Mountains", "Philadelphia", "state taxes", "cost segregation", "bonus depreciation", "hotel tax"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-pennsylvania.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Pennsylvania 2025: Poconos, Philadelphia & More | Abode",
      description: "Pennsylvania does NOT conform to federal bonus depreciation — using straight-line instead. Here's what PA STR investors pay, Pocono hotel taxes, and how to maximize deductions despite the decoupling.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-pennsylvania",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Pennsylvania conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "No. Pennsylvania does not conform to federal bonus depreciation. PA requires investors to use straight-line depreciation on their state returns regardless of the federal method. This means the large first-year bonus depreciation deduction on your federal return is not available on your PA state return — you must add it back and use straight-line over the asset's normal life." } },
          { "@type": "Question", name: "What is Pennsylvania's state income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Pennsylvania has a flat 3.07% personal income tax rate on net rental income. While the rate is relatively low, the non-conformity to bonus depreciation means PA investors get smaller first-year state deductions than federal deductions." } },
          { "@type": "Question", name: "What hotel taxes apply to Pocono Mountains STR rentals?", acceptedAnswer: { "@type": "Answer", text: "Pennsylvania has a 6% state hotel occupancy tax. Individual counties add their own hotel taxes on top. Monroe County (Poconos core) adds an additional 1.5–2%, bringing total rates to approximately 7.5–8%. Pike County (Delaware Water Gap) has similar combined rates. Verify exact rates with the specific county tax office." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "warning", title: "Pennsylvania Bonus Depreciation Alert", text: "Pennsylvania does NOT conform to federal bonus depreciation. PA requires straight-line depreciation on state returns. Your federal bonus dep deduction must be added back on your PA return and replaced with straight-line depreciation over the asset's MACRS life. Work with a PA CPA to model the state impact." },
      { type: "paragraph", text: "Pennsylvania is home to the Pocono Mountains — one of the most established STR cabin markets in the Northeast — as well as urban STR activity in Philadelphia and Pittsburgh. The state has a relatively low 3.07% flat income tax but decouples entirely from federal bonus depreciation, requiring straight-line depreciation on Pennsylvania state returns. This is a critical planning issue for PA investors using cost segregation." },
      { type: "heading", level: 2, text: "Pennsylvania State Income Tax on Rental Income", id: "state-income-tax" },
      { type: "paragraph", text: "Pennsylvania's 3.07% flat personal income tax applies to net rental income. While the rate is lower than most Northeast states, the non-conformity to federal depreciation methods means the effective Pennsylvania tax burden is higher than the headline rate suggests for investors who rely on first-year bonus depreciation to reduce federal taxable income." },
      { type: "heading", level: 2, text: "Pennsylvania's Bonus Depreciation Non-Conformity", id: "bonus-dep-pa" },
      { type: "paragraph", text: "Pennsylvania requires investors to use straight-line depreciation on their state returns, regardless of the federal method elected. When you take 100% bonus depreciation on $120,000 of 5-year assets under MACRS on your federal return, you must add back that entire deduction on your PA return and instead deduct straight-line amounts — roughly $24,000/year for 5-year property over 5 years, or $20,000/year for 5-year property over 6 years depending on the convention used." },
      { type: "paragraph", text: "The result is that in year one, your PA taxable income is significantly higher than your federal taxable income. Over the full asset life, you recover the same total deductions — but the timing disadvantage is most pronounced in the year of acquisition. At 3.07%, the additional PA tax in year one on a typical cost seg study might be $3,000–$5,000 — recovered over subsequent years through larger PA deductions than federal deductions." },
      { type: "heading", level: 2, text: "Pennsylvania Hotel Taxes by Market", id: "hotel-taxes" },
      { type: "table", headers: ["Market / County", "State Hotel Tax (6%)", "County Hotel Tax", "Estimated Total"],
        rows: [
          ["Monroe County (Pocono core: Stroudsburg, Mt. Pocono)", "6%", "1.5–2%", "~7.5–8%"],
          ["Pike County (Milford, Delaware Water Gap)", "6%", "1.5%", "~7.5%"],
          ["Wayne County (Lake Wallenpaupack area)", "6%", "1.5%", "~7.5%"],
          ["Philadelphia (Philadelphia County)", "6%", "8.5% city", "~14.5%"],
          ["Allegheny County (Pittsburgh)", "6%", "7%", "~13%"],
          ["Lancaster County (PA Dutch Country)", "6%", "1.5%", "~7.5%"],
        ]
      },
      { type: "heading", level: 2, text: "The Pocono Mountains STR Market", id: "pocono-market" },
      { type: "paragraph", text: "The Pocono Mountains of northeastern Pennsylvania represent the closest major mountain vacation destination to the New York City metro area (90–120 minutes). The Poconos' STR market includes lakefront cabins, ski resort properties (Camelback, Big Boulder, Jack Frost Mountain), and year-round resort communities. Demand is driven primarily by New York City, Northern New Jersey, and Philadelphia-area travelers." },
      { type: "paragraph", text: "Pocono properties range from modest lake cottages ($150,000–$300,000) to premium lakefront homes and ski-in properties ($500,000–$1.5M+). The market is genuinely four-season — skiing in winter, lake activities in summer, foliage in fall, and resort and outdoor recreation in spring. Properties with lake access or ski proximity command the strongest revenue." },
      { type: "heading", level: 2, text: "Philadelphia and Pittsburgh: Urban STR Markets", id: "urban-markets" },
      { type: "paragraph", text: "Philadelphia's STR market is event-driven, with strong demand around sports events, concerts, conventions, and historic tourism (Independence Hall, the Liberty Bell, the Philadelphia Museum of Art). Philadelphia's hotel tax is among the highest in Pennsylvania at approximately 14.5% combined, but this is borne by guests, not investors. Pittsburgh's urban STR market is smaller but growing, anchored by Carnegie Mellon University, UPMC, and the city's revitalized neighborhoods." },
      { type: "heading", level: 2, text: "Cost Segregation in Pennsylvania: Federal Benefits Intact", id: "cost-seg-pa" },
      { type: "paragraph", text: "Despite the Pennsylvania straight-line requirement, cost segregation remains powerful for PA investors because the full federal benefit is unchanged. A $500,000 Pocono lakefront property with $130,000 in cost seg deductions at 37% federal generates $48,100 in year-one federal savings. The PA timing cost at 3.07% — paying tax on deferred PA deductions — is roughly $3,500–$4,500 in year one, recovered over the asset lives." },
      { type: "faq", question: "Does Pennsylvania require STR registration?", answer: "Pennsylvania does not have a statewide STR registration requirement. Individual municipalities and counties handle STR regulation. Monroe County (Poconos) and some municipalities have adopted registration and licensing requirements. Philadelphia requires short-term rental licenses. Pittsburgh has regulations for certain STR types. Always check with the specific municipality for your property location." },
      { type: "cta", title: "Estimate Your Pennsylvania STR Tax Savings", text: "PA's bonus dep non-conformity affects timing, not the full federal benefit. Get your free estimate to see your year-one net combined savings.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── New Jersey ───────────────────────────────────────────────────────────
  {
    slug: "str-taxes-new-jersey",
    title: "Short-Term Rental Taxes in New Jersey: What Investors Need to Know in 2025",
    description: "New Jersey has one of the highest state income taxes in the country (up to 10.75%) and does NOT conform to federal bonus depreciation. Here's the complete NJ STR tax guide for Jersey Shore investors.",
    publishedAt: "2026-03-11",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "New Jersey", "Jersey Shore", "Cape May", "Asbury Park", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-new-jersey.jpg",
    seo: {
      title: "Short-Term Rental Taxes in New Jersey 2025: Jersey Shore, Cape May & More | Abode",
      description: "New Jersey has a top income tax rate of 10.75% and does NOT conform to federal bonus depreciation. Here's what NJ STR investors pay, Jersey Shore sales taxes, and how to navigate the high-tax environment.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-new-jersey",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does New Jersey conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "No. New Jersey does not conform to federal bonus depreciation. NJ requires investors to add back the federal bonus depreciation deduction and use standard MACRS depreciation on their state returns. This is especially significant given NJ's high income tax rates — the state opportunity cost of non-conformity is among the highest in the country." } },
          { "@type": "Question", name: "What is New Jersey's income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "New Jersey has a highly graduated income tax with rates from 1.4% to 10.75%. The top 10.75% rate applies to taxable income over $1 million. However, New Jersey also has a 6.37% rate on income over $500,000 and a 5.525% rate on income over $75,000. High-income STR investors can face combined state + federal marginal rates exceeding 47%." } },
          { "@type": "Question", name: "What taxes apply to Jersey Shore STR rentals?", acceptedAnswer: { "@type": "Answer", text: "New Jersey charges 6.625% state sales tax on short-term rentals (accommodations under 90 days). The state also has a 5% state occupancy fee on hotel/motel rentals. Some municipalities add local lodging taxes. Owners of STR properties in Jersey Shore communities should verify current sales tax obligations with the NJ Division of Taxation." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "warning", title: "New Jersey Tax Alert for STR Investors", text: "New Jersey has a top income tax rate of 10.75% AND does not conform to federal bonus depreciation. For high-income NJ investors, the combination creates a significant state tax burden. Planning with a NJ CPA familiar with STR and depreciation rules is essential." },
      { type: "paragraph", text: "New Jersey's STR market is dominated by the Jersey Shore — a 127-mile coastline that draws tens of millions of visitors annually to beach towns from Sandy Hook to Cape May. The state's STR tax environment is challenging: one of the country's highest income tax rates, non-conformity to federal bonus depreciation, and a 6.625% sales tax on short-term rentals. Despite these hurdles, the Shore's strong revenue potential makes STR investing viable — especially with strategic tax planning." },
      { type: "heading", level: 2, text: "New Jersey State Income Tax on Rental Income", id: "state-income-tax" },
      { type: "paragraph", text: "New Jersey has one of the most progressive income tax structures in the country. Rates range from 1.4% at the lowest income levels to 10.75% on income over $1 million. Most STR investors with meaningful rental income will face NJ rates in the 5.525%–6.37% range (applicable to income over $75,000 and $500,000, respectively). At these rates, the non-conformity to bonus depreciation is particularly costly." },
      { type: "heading", level: 2, text: "New Jersey Bonus Depreciation Non-Conformity", id: "bonus-dep-nj" },
      { type: "paragraph", text: "New Jersey does not allow federal bonus depreciation. On your NJ state return, you must add back any federal bonus depreciation deduction and compute depreciation using standard MACRS methods. This means a $200,000 federal bonus dep deduction generates approximately $0 in year-one NJ deductions (instead, NJ deductions are spread over the asset's MACRS life — 5 years for personal property, 39 years for building)." },
      { type: "paragraph", text: "At a 6% NJ effective rate, $200,000 of disallowed first-year deductions means an extra $12,000 in NJ state taxes in year one. Those deductions are recovered over subsequent years, but the time value cost is real and significant — especially for high-income investors in the 10.75% bracket." },
      { type: "heading", level: 2, text: "New Jersey Sales Tax on STR Rentals", id: "sales-tax" },
      { type: "table", headers: ["Market / Region", "NJ Sales Tax", "State Occupancy Fee", "Estimated Total"],
        rows: [
          ["Cape May (Cape May County)", "6.625%", "5% (hotels)", "~6.625% (STR sales tax only)"],
          ["Long Beach Island (Ocean County)", "6.625%", "varies", "~6.625%+"],
          ["Asbury Park (Monmouth County)", "6.625%", "varies", "~6.625%+"],
          ["Wildwood (Cape May County)", "6.625%", "varies", "~6.625%+"],
          ["Delaware Water Gap (Warren County)", "6.625%", "varies", "~6.625%+"],
          ["Hoboken/Jersey City (Hudson County)", "6.625%", "varies", "~6.625%+"],
        ]
      },
      { type: "heading", level: 2, text: "Jersey Shore: New Jersey's Premier STR Market", id: "jersey-shore-market" },
      { type: "paragraph", text: "The Jersey Shore is one of the most heavily visited coastal destinations on the East Coast, drawing primarily from the New York City and Philadelphia metro areas. The 127-mile coastline is dotted with distinct communities: Cape May (Victorian architecture, upscale tourism), Cape May Court House, Wildwood (family amusement parks), Ocean City (family-friendly, alcohol-free), Long Beach Island (LBI), Spring Lake, Asbury Park (arts and music scene), and Point Pleasant Beach, among many others." },
      { type: "paragraph", text: "Jersey Shore STR properties range from small beach cottages to large multi-family homes that accommodate extended families and groups. The market is intensely seasonal — peak season runs mid-June through Labor Day, with strong Memorial Day and Fourth of July weeks. Weekly rentals are the dominant booking pattern in many shore towns, which can interact with the 7-day average stay STR loophole requirement in interesting ways." },
      { type: "heading", level: 2, text: "Delaware Water Gap: NJ's Mountain STR Market", id: "delaware-water-gap" },
      { type: "paragraph", text: "The Delaware Water Gap National Recreation Area in Warren and Sussex counties draws hikers, kayakers, and outdoor recreationists from the New York and Philadelphia metros. This is a smaller, less developed STR market than the Shore but offers more accessible entry prices and year-round potential for outdoor recreation tourism." },
      { type: "heading", level: 2, text: "Cost Segregation in New Jersey: Federal Benefits Still Significant", id: "cost-seg-nj" },
      { type: "paragraph", text: "Despite New Jersey's unfavorable bonus dep treatment, cost segregation remains one of the most powerful tools available to NJ STR investors because the full federal deduction is intact. A $600,000 Jersey Shore property with $150,000 in cost seg deductions at 37% federal generates $55,500 in year-one federal savings. The NJ timing penalty at a 6% effective rate is approximately $9,000 — recovered over the following 4–5 years. Net first-year benefit: still $46,500+." },
      { type: "faq", question: "Does New Jersey have specific STR licensing requirements?", answer: "New Jersey does not have a statewide STR licensing requirement. Many Jersey Shore municipalities have adopted their own rental property registration and inspection requirements. Beach towns like Ocean City, Cape May, and Long Beach Island have local rental registration programs. Verify current requirements with your specific municipality before operating." },
      { type: "cta", title: "Estimate Your New Jersey STR Tax Savings", text: "NJ's high rates make the federal cost seg benefit even more important as an offset. Get your free estimate to see your year-one combined net savings.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Massachusetts ────────────────────────────────────────────────────────
  {
    slug: "str-taxes-massachusetts",
    title: "Short-Term Rental Taxes in Massachusetts: What Investors Need to Know in 2025",
    description: "Massachusetts has a 5% flat income tax, does NOT conform to federal bonus depreciation, and has significant STR markets on Cape Cod, Martha's Vineyard, Nantucket, and the Berkshires.",
    publishedAt: "2026-03-12",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Massachusetts", "Cape Cod", "Martha's Vineyard", "Nantucket", "Berkshires", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-massachusetts.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Massachusetts 2025: Cape Cod, Martha's Vineyard & More | Abode",
      description: "Massachusetts does NOT conform to federal bonus depreciation and has a 5% flat income tax plus rooms excise taxes of up to 11.7%. Here's the complete MA STR tax guide for Cape Cod and island investors.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-massachusetts",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Massachusetts conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "No. Massachusetts does not conform to 100% federal bonus depreciation. Massachusetts requires investors to add back the federal bonus depreciation deduction and use standard MACRS depreciation on their state returns. This is a material issue given Massachusetts' 5% income tax rate and high property values in premier markets like Cape Cod, Martha's Vineyard, and Nantucket." } },
          { "@type": "Question", name: "What is Massachusetts's rooms excise tax on STR rentals?", acceptedAnswer: { "@type": "Answer", text: "Massachusetts charges a 5.7% state rooms excise tax on short-term rentals. Municipalities can add a local option rooms excise of up to 6%, bringing total rates to as high as 11.7% in some communities. Additionally, a 3% Community Impact Fee applies in some situations. Cape Cod and island towns often apply the full local option." } },
          { "@type": "Question", name: "Are Martha's Vineyard and Nantucket subject to STR taxes?", acceptedAnswer: { "@type": "Answer", text: "Yes. Martha's Vineyard and Nantucket properties are subject to the same Massachusetts rooms excise tax structure as the mainland — 5.7% state + local option up to 6%. Both island communities generally apply the maximum local option rates given the high tourism intensity. Total rates on Martha's Vineyard and Nantucket typically run 11.7%." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "warning", title: "Massachusetts Bonus Depreciation Alert", text: "Massachusetts does NOT conform to federal bonus depreciation. You must add back federal bonus dep on your MA return and use standard MACRS depreciation. With high property values in Cape Cod, Martha's Vineyard, and Nantucket, the cost of the non-conformity is amplified. Plan with a MA CPA." },
      { type: "paragraph", text: "Massachusetts is home to some of the most valuable and consistently-performing STR markets in the Northeast: Cape Cod, Martha's Vineyard, Nantucket, the Berkshires, and the North Shore beach communities. The state has a 5% flat income tax, does not conform to federal bonus depreciation, and applies a layered rooms excise tax structure that reaches up to 11.7% of rental revenue in many markets." },
      { type: "heading", level: 2, text: "Massachusetts State Income Tax on Rental Income", id: "state-income-tax" },
      { type: "paragraph", text: "Massachusetts has a 5% flat income tax on most income, including net rental income. Massachusetts voters approved a 4% surtax on income over $1 million beginning in 2023 (the 'Millionaires Tax'), making the effective top rate 9% for high earners. For most STR investors, the applicable rate is 5%. Massachusetts begins with federal AGI and makes Massachusetts-specific modifications, including the depreciation addback." },
      { type: "heading", level: 2, text: "Massachusetts Rooms Excise Tax Structure", id: "rooms-excise-tax" },
      { type: "table", headers: ["Market / Region", "State Excise (5.7%)", "Local Option (up to 6%)", "Community Impact Fee", "Estimated Total"],
        rows: [
          ["Cape Cod (Barnstable County towns)", "5.7%", "Up to 6%", "Up to 3%", "~11.7%+"],
          ["Martha's Vineyard (Dukes County)", "5.7%", "Up to 6%", "Up to 3%", "~11.7%+"],
          ["Nantucket", "5.7%", "6%", "Up to 3%", "~11.7%+"],
          ["Berkshires (Lenox, Stockbridge area)", "5.7%", "4–6%", "varies", "~9.7–11.7%"],
          ["Boston", "5.7%", "6%", "varies", "~11.7%+"],
          ["North Shore (Gloucester, Rockport)", "5.7%", "4–6%", "varies", "~9.7–11.7%"],
        ]
      },
      { type: "heading", level: 2, text: "Top Massachusetts STR Markets", id: "top-markets" },
      { type: "paragraph", text: "<strong>Cape Cod:</strong> One of the most established seasonal vacation markets in the country. The 70-mile Cape attracts millions of summer visitors, with peak season running mid-June through Labor Day. Properties on the Cape range from modest cottages in Falmouth or Bourne to premium waterfront homes on Chatham or Wellfleet. The Cape Cod National Seashore and 560 miles of coastline sustain near-impossible occupancy rates in peak season." },
      { type: "paragraph", text: "<strong>Martha's Vineyard:</strong> An island accessible by ferry from Woods Hole or Hyannis. Martha's Vineyard has a national celebrity clientele and among the highest average nightly rates in Massachusetts. Property values on the Vineyard are extreme — multimillion-dollar estates are common. Cost segregation on a $2M+ property with $400,000 in bonus-eligible assets can generate $148,000+ in federal year-one savings." },
      { type: "paragraph", text: "<strong>Nantucket:</strong> The most premium of Massachusetts' island STR markets. Nantucket properties routinely command $1,000–$5,000+/night in peak season. Property values start at $1M+ for modest properties. The island's strict zoning and building regulations create a naturally supply-constrained market that supports strong ADRs." },
      { type: "paragraph", text: "<strong>Berkshires:</strong> Western Massachusetts' cultural and outdoor recreation destination. Tanglewood (summer home of the Boston Symphony Orchestra), MASS MoCA, and the natural scenery draw a mix of cultural tourism and outdoor recreationists. A more evenly-distributed year-round market than the Cape or islands, with fall foliage season a particular peak period." },
      { type: "heading", level: 2, text: "Cost Segregation in Massachusetts: High-Value Properties", id: "cost-seg-ma" },
      { type: "paragraph", text: "Massachusetts' combination of high property values and non-conformity to bonus depreciation creates a situation where the federal cost seg benefit is very large in absolute terms, while the state timing penalty is also meaningful. A $1.5M Vineyard property with $350,000 in cost seg deductions generates $129,500 in federal first-year savings (at 37%) — against a MA state timing penalty of approximately $17,500 (at 5%) in year one, which is recovered over the following 5 years." },
      { type: "faq", question: "Does Massachusetts require STR registration?", answer: "Yes. Massachusetts implemented a statewide short-term rental registration requirement in 2019 (Chapter 337). All STR operators must register with the state, obtain liability insurance with minimum $1 million coverage per occurrence, and collect and remit the rooms excise tax. Failure to register can result in penalties." },
      { type: "cta", title: "Estimate Your Massachusetts STR Tax Savings", text: "High MA property values amplify cost seg federal savings. The state timing penalty is real but dwarfed by the federal benefit. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Connecticut ──────────────────────────────────────────────────────────
  {
    slug: "str-taxes-connecticut",
    title: "Short-Term Rental Taxes in Connecticut: What Investors Need to Know in 2025",
    description: "Connecticut has a 3–6.99% graduated income tax, does NOT conform to federal bonus depreciation, and has a 15% room occupancy tax on short-term rentals. Here's the complete CT STR tax guide.",
    publishedAt: "2026-03-12",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Connecticut", "Mystic", "Litchfield Hills", "state taxes", "cost segregation", "bonus depreciation", "room occupancy tax"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-connecticut.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Connecticut 2025: Mystic, Litchfield Hills & More | Abode",
      description: "Connecticut has a 15% room occupancy tax on STRs, a top income tax rate of 6.99%, and does not conform to federal bonus depreciation. Here's what CT STR investors pay and how to plan deductions.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-connecticut",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Connecticut conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "No. Connecticut does not conform to federal bonus depreciation. CT has its own depreciation method that differs from federal MACRS with bonus depreciation. Investors must add back federal bonus depreciation and use Connecticut's alternative depreciation schedule on state returns." } },
          { "@type": "Question", name: "What is Connecticut's room occupancy tax rate?", acceptedAnswer: { "@type": "Answer", text: "Connecticut charges a 15% room occupancy tax on short-term rentals (accommodations under 30 days). This is among the highest statewide lodging tax rates in the country. The tax applies to the full rental charge including cleaning fees in some interpretations. STR operators must register with the Connecticut Department of Revenue Services." } },
          { "@type": "Question", name: "What is Connecticut's income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Connecticut has a graduated income tax ranging from 3% (on income up to $10,000 for single filers) to 6.99% (on income over $500,000). Most STR investors with meaningful rental income will be in the 5–6.99% range. Connecticut's top rate is one of the higher rates in New England." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "warning", title: "Connecticut Room Occupancy Tax Alert", text: "Connecticut's 15% room occupancy tax is among the highest statewide lodging tax rates in the country. Combined with Connecticut's non-conformity to federal bonus depreciation and a top income tax rate of 6.99%, CT presents a challenging state tax environment for STR investors." },
      { type: "paragraph", text: "Connecticut's STR market is more modest than neighboring Massachusetts or the Jersey Shore, but the state has distinct STR destinations: Mystic (maritime history and Mystic Seaport), the Litchfield Hills (rural villages, wineries, and weekend retreats), and the Connecticut shoreline towns. Connecticut's 15% room occupancy tax is one of the highest statewide rates in the country, and the state's non-conformity to federal bonus depreciation adds planning complexity." },
      { type: "heading", level: 2, text: "Connecticut State Income Tax on Rental Income", id: "state-income-tax" },
      { type: "paragraph", text: "Connecticut has a graduated income tax with rates from 3% to 6.99%. The 6.99% top rate applies to income over $500,000 ($600,000 for joint filers). Most active STR investors with meaningful rental income will face CT rates in the 5–6.99% range. Connecticut begins with federal AGI and makes state-specific modifications, including adding back federal bonus depreciation." },
      { type: "heading", level: 2, text: "Connecticut's 15% Room Occupancy Tax", id: "room-occupancy-tax" },
      { type: "paragraph", text: "Connecticut's 15% room occupancy tax on short-term rentals is a standout in the national landscape — one of the highest statewide lodging tax rates in the country. This tax applies to accommodations under 30 days and is collected from guests. STR operators must register with the Connecticut Department of Revenue Services (CT DRS) as room operators to collect and remit this tax." },
      { type: "paragraph", text: "From an investor's perspective, the 15% rate is passed through to guests and does not directly reduce net income — but it can affect competitiveness and pricing relative to lower-tax neighboring states. Properties near the Massachusetts border compete with lower-tax alternatives; pricing strategy matters." },
      { type: "heading", level: 2, text: "Connecticut Bonus Depreciation Non-Conformity", id: "bonus-dep-ct" },
      { type: "paragraph", text: "Connecticut does not conform to federal bonus depreciation and has its own depreciation method that differs from standard MACRS with bonus. Investors must add back any federal bonus depreciation deduction on their CT returns and use Connecticut's alternative depreciation schedule. At a top CT rate of 6.99%, the first-year state tax impact of the disallowed bonus deduction can be substantial for investors in higher brackets." },
      { type: "heading", level: 2, text: "Top Connecticut STR Markets", id: "top-markets" },
      { type: "paragraph", text: "<strong>Mystic:</strong> Connecticut's most visited tourist attraction (Mystic Seaport, Mystic Aquarium) anchors a strong STR market in southeastern CT. The maritime heritage, charming village character, and proximity to Providence and New London drive year-round demand. Mystic STR properties tend to be historic New England homes and cottages." },
      { type: "paragraph", text: "<strong>Litchfield Hills:</strong> The rolling hills of northwestern Connecticut draw weekend travelers from New York City (2–2.5 hours) seeking New England village charm, farm-to-table dining, and antique shopping. Litchfield, Kent, Washington, and Salisbury are the primary towns. The region has a compact but quality STR market with a premium demographic." },
      { type: "paragraph", text: "<strong>Connecticut Shoreline:</strong> The towns along Long Island Sound — Old Saybrook, Essex, Madison, Guilford — offer coastal STR opportunities with proximity to both New York and Boston. The shoreline market is seasonal but produces strong summer revenue." },
      { type: "heading", level: 2, text: "Cost Segregation in Connecticut", id: "cost-seg-ct" },
      { type: "paragraph", text: "Despite Connecticut's challenging state tax environment, federal cost segregation benefits are fully preserved. A $500,000 Litchfield Hills property with $120,000 in cost seg deductions at 37% federal generates $44,400 in year-one federal savings. The CT state timing penalty at a 6% effective rate is approximately $7,200 in year one — a meaningful but temporary cost relative to the federal benefit." },
      { type: "faq", question: "Do Airbnb and VRBO collect Connecticut room occupancy tax?", answer: "Airbnb acts as a marketplace facilitator for Connecticut's room occupancy tax, collecting and remitting on behalf of hosts on bookings through its platform. VRBO has similar arrangements. STR operators must still register with CT DRS as room operators. For direct bookings not through platforms, the operator is responsible for collection and remittance." },
      { type: "cta", title: "Estimate Your Connecticut STR Tax Savings", text: "CT's 15% room occupancy tax and bonus dep non-conformity are real challenges — but federal cost seg benefits still deliver strong net returns. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Rhode Island ─────────────────────────────────────────────────────────
  {
    slug: "str-taxes-rhode-island",
    title: "Short-Term Rental Taxes in Rhode Island: What Investors Need to Know in 2025",
    description: "Rhode Island has a 3.75–5.99% income tax, partial bonus depreciation conformity (50%), a 6% hotel tax, and STR activity centered on Newport and the coastal communities.",
    publishedAt: "2026-03-13",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Rhode Island", "Newport", "state taxes", "cost segregation", "bonus depreciation", "hotel tax"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-rhode-island.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Rhode Island 2025: Newport & Coastal Markets | Abode",
      description: "Rhode Island limits bonus depreciation to 50% on state returns and has a 3.75–5.99% income tax. Here's what Rhode Island STR investors pay, Newport hotel taxes, and how cost segregation works.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-rhode-island",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Rhode Island conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Rhode Island partially conforms to federal bonus depreciation, limiting the deduction to 50% of the federal amount in year one. The remaining 50% is recovered over the asset's normal MACRS life on subsequent Rhode Island returns. This partial conformity reduces but does not eliminate the state benefit of cost segregation." } },
          { "@type": "Question", name: "What is Rhode Island's income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Rhode Island has a graduated income tax ranging from 3.75% to 5.99%. The top 5.99% rate applies to taxable income over $166,950 (approximately). Most STR investors with meaningful rental income will be at or near the top rate." } },
          { "@type": "Question", name: "What hotel and hospitality taxes apply to Rhode Island STRs?", acceptedAnswer: { "@type": "Answer", text: "Rhode Island charges a 6% state hotel tax on short-term rentals. Local municipalities may add hospitality taxes. Newport and many coastal communities also charge local hospitality taxes of 1–2%, bringing total rates to 7–8% in popular STR areas." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Rhode Island STR Tax Summary", text: "3.75–5.99% graduated income tax | Partial bonus dep conformity (50% in year 1, rest over MACRS life) | 6% state hotel tax + local hospitality taxes | Newport is the premier RI STR market | Coastal communities: Watch Hill, Narragansett, Block Island" },
      { type: "paragraph", text: "Rhode Island — the nation's smallest state — has a concentrated STR market centered on Newport (luxury coastal and sailing culture), the South County beaches, and Block Island (an island accessible by ferry). The state's partial bonus depreciation conformity (limiting the first-year deduction to 50% of the federal amount) is a middle-ground approach that provides partial state benefit while deferring the remainder." },
      { type: "heading", level: 2, text: "Rhode Island State Income Tax", id: "state-income-tax" },
      { type: "paragraph", text: "Rhode Island's graduated income tax tops out at 5.99% on income above approximately $166,950. Most STR investors with meaningful rental income will be at or near this top rate. Rhode Island begins with federal AGI and makes RI-specific adjustments. The partial bonus depreciation conformity (see below) affects how first-year depreciation deductions flow to the RI return." },
      { type: "heading", level: 2, text: "Rhode Island's 50% Bonus Depreciation Partial Conformity", id: "bonus-dep-ri" },
      { type: "paragraph", text: "Rhode Island allows 50% of the federal bonus depreciation deduction in year one — better than states that allow nothing (like PA or NJ), but worse than full conformity. For a $100,000 federal bonus depreciation deduction, Rhode Island allows $50,000 in year one and then deducts the remaining $50,000 over the asset's normal MACRS life in subsequent years." },
      { type: "paragraph", text: "At the 5.99% top rate, the year-one impact is approximately $3,000 in additional RI taxes compared to full federal conformity (tax on the $50,000 addback). This is a relatively modest timing penalty compared to states that disallow all bonus depreciation." },
      { type: "heading", level: 2, text: "Rhode Island Hotel and Hospitality Taxes", id: "hotel-taxes" },
      { type: "table", headers: ["Market / Jurisdiction", "State Hotel Tax (6%)", "Local Hospitality Tax", "Estimated Total"],
        rows: [
          ["Newport (Newport County)", "6%", "1–2%", "~7–8%"],
          ["South County / Narragansett", "6%", "1%", "~7%"],
          ["Watch Hill (Westerly)", "6%", "1%", "~7%"],
          ["Block Island (New Shoreham)", "6%", "1%", "~7%"],
          ["Providence", "6%", "1%", "~7%"],
          ["Bristol / Warren", "6%", "1%", "~7%"],
        ]
      },
      { type: "heading", level: 2, text: "Newport: Rhode Island's Premier STR Market", id: "newport-market" },
      { type: "paragraph", text: "Newport is Rhode Island's dominant STR market, anchored by its Gilded Age mansion heritage (The Breakers, Marble House, Rosecliff), the Newport Sailing Museum, the Newport Jazz and Folk Festivals, and a thriving waterfront restaurant and bar scene. Newport draws a premium demographic and commands some of the highest nightly rates in New England outside of Nantucket and Martha's Vineyard." },
      { type: "paragraph", text: "Newport properties range from charming historic colonial homes in the Point neighborhood to large waterfront estates on Bellevue Avenue. The market has year-round appeal — sailing tourism in summer, mansion tours and festivals in fall, and the Gilded Age Christmas events in December keep occupancy relatively strong outside peak summer." },
      { type: "heading", level: 2, text: "Block Island: Rhode Island's Island STR Market", id: "block-island" },
      { type: "paragraph", text: "Block Island, accessible by ferry from Point Judith (one hour) or New London, CT, is Rhode Island's island escape. With no traffic lights and over 40% of land protected as nature reserves, Block Island draws visitors seeking a quieter alternative to the Vineyard or Nantucket. The ferry-access model creates a natural supply constraint that supports strong ADRs in peak season." },
      { type: "heading", level: 2, text: "Cost Segregation in Rhode Island", id: "cost-seg-ri" },
      { type: "paragraph", text: "Rhode Island's partial conformity means cost segregation delivers roughly 50% of the potential state benefit in year one — better than non-conforming states. For a $600,000 Newport property with $140,000 in cost seg deductions, the combined first-year benefit is $51,800 federal (37%) + $4,193 RI state (5.99% on the $70,000 allowed in year 1) = $55,993 combined. The remaining $70,000 in RI deductions are recovered over the asset lives." },
      { type: "faq", question: "Does Rhode Island require STR registration?", answer: "Rhode Island has STR registration requirements administered through the Division of Taxation. Operators must register as hotel operators for purposes of the hotel tax, collect the 6% state hotel tax, and remit to the RI Division of Taxation. Some municipalities have additional registration requirements. Newport has specific local STR regulations." },
      { type: "cta", title: "Estimate Your Rhode Island STR Tax Savings", text: "Rhode Island's 50% partial conformity means real state savings alongside the full federal benefit. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Vermont ──────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-vermont",
    title: "Short-Term Rental Taxes in Vermont: What Investors Need to Know in 2025",
    description: "Vermont has a 3.35–8.75% graduated income tax, does NOT conform to federal bonus depreciation, and charges a 9% meals and rooms tax. Stowe, Killington, and the Mad River Valley are the top STR markets.",
    publishedAt: "2026-03-13",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Vermont", "Stowe", "Killington", "ski rental", "state taxes", "cost segregation", "bonus depreciation", "meals and rooms tax"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-vermont.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Vermont 2025: Stowe, Killington & Ski Markets | Abode",
      description: "Vermont does NOT conform to federal bonus depreciation and has a top income tax rate of 8.75% plus a 9% meals and rooms tax. Here's what Vermont ski country STR investors need to know.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-vermont",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Vermont conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "No. Vermont does not conform to federal bonus depreciation. VT requires investors to add back the federal bonus depreciation deduction and use standard MACRS depreciation on their state returns. Given Vermont's high top income tax rate of 8.75%, the state cost of non-conformity can be quite significant for large cost seg deductions." } },
          { "@type": "Question", name: "What is Vermont's meals and rooms tax on STR rentals?", acceptedAnswer: { "@type": "Answer", text: "Vermont charges a 9% meals and rooms tax on short-term rental accommodations. This applies to the rental charge and some additional fees. Vermont STR operators must register with the Vermont Department of Taxes to collect and remit this tax. Some municipalities add local option taxes on top of the 9% state rate." } },
          { "@type": "Question", name: "What is Vermont's income tax rate for STR investors?", acceptedAnswer: { "@type": "Answer", text: "Vermont has a highly graduated income tax with rates from 3.35% to 8.75%. The top 8.75% rate applies to taxable income over $213,150 (approximately, for single filers). Vermont's top rate is one of the highest in New England and nationally. The combination of high rates and non-conformity to bonus depreciation makes Vermont one of the more challenging state tax environments in this guide." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "warning", title: "Vermont Tax Alert for STR Investors", text: "Vermont does NOT conform to federal bonus depreciation AND has a top income tax rate of 8.75%. For high-income investors, the combination of non-conformity and high rates means a substantial year-one state tax penalty when taking large cost seg deductions. Plan carefully with a VT CPA." },
      { type: "paragraph", text: "Vermont's STR market is anchored by world-class ski resorts (Stowe, Killington, Mad River Glen, Sugarbush) and supplemented by fall foliage tourism and summer outdoor recreation. The state's tax environment is challenging for investors: a top income tax rate of 8.75%, non-conformity to federal bonus depreciation, and a 9% meals and rooms tax. However, the strength of Vermont's ski and foliage markets can still support compelling after-tax returns." },
      { type: "heading", level: 2, text: "Vermont State Income Tax on Rental Income", id: "state-income-tax" },
      { type: "paragraph", text: "Vermont has one of the most progressive income tax structures in the country, with rates from 3.35% to 8.75%. The top 8.75% rate applies to income over approximately $213,150 for single filers. Most STR investors with meaningful rental income from premium ski properties will reach upper Vermont brackets. Vermont's non-conformity to bonus depreciation means this high rate applies to the full year-one income without the benefit of large first-year depreciation deductions on the state return." },
      { type: "heading", level: 2, text: "Vermont's Meals and Rooms Tax", id: "meals-rooms-tax" },
      { type: "table", headers: ["Market / Area", "State M&R Tax (9%)", "Local Option", "Estimated Total"],
        rows: [
          ["Stowe (Lamoille County)", "9%", "1%", "~10%"],
          ["Killington (Rutland County)", "9%", "1%", "~10%"],
          ["Manchester / Bromley / Magic (Bennington County)", "9%", "1%", "~10%"],
          ["Woodstock / Quechee (Windsor County)", "9%", "1%", "~10%"],
          ["Burlington (Chittenden County)", "9%", "1%", "~10%"],
          ["Mad River Valley (Washington County)", "9%", "1%", "~10%"],
        ]
      },
      { type: "heading", level: 2, text: "Vermont Ski Country STR Markets", id: "ski-markets" },
      { type: "paragraph", text: "<strong>Stowe:</strong> Vermont's most iconic resort town and consistently ranked among the top ski destinations in the East. Stowe Mountain Resort (owned by Vail Resorts) features 485 acres of skiable terrain and a charming village. The Stowe STR market is competitive and highly seasonal — peak winter season commands extremely high nightly rates, but summer and fall bring their own demand from hikers, cyclists, and foliage seekers." },
      { type: "paragraph", text: "<strong>Killington:</strong> The largest ski resort in the East by skiable acreage, with 155 trails and 22 lifts. Killington draws a younger, more party-oriented crowd than Stowe and operates one of the longest ski seasons in the East (typically November through late April or May). The Killington STR market tends to offer more accessible property prices than Stowe, with competitive revenue potential." },
      { type: "paragraph", text: "<strong>Mad River Valley:</strong> Home to Sugarbush and Mad River Glen, the Mad River Valley attracts a more dedicated skier demographic. The Valley has a Vermont-authentic character and loyal following. STR properties here range from ski-in condos at Sugarbush to farmhouses and chalets in the surrounding hills." },
      { type: "heading", level: 2, text: "Vermont Foliage and Summer Tourism", id: "foliage-summer" },
      { type: "paragraph", text: "Vermont's fall foliage season (late September through mid-October) is a genuine second peak for the STR market — in some areas, foliage weekend demand rivals ski season. Nightly rates in October can approach or exceed peak ski season rates. Summer brings cycling (Kingdom Trails, VAST trail network), hiking, lake activities, and general rural escape tourism. Vermont's four-season appeal distributes revenue more evenly than one-season markets." },
      { type: "heading", level: 2, text: "Cost Segregation in Vermont: Federal Benefits Despite High State Tax", id: "cost-seg-vt" },
      { type: "paragraph", text: "Vermont's high state income tax and non-conformity to bonus depreciation create a scenario where the federal benefit is large but the state timing penalty is also larger than in most states. For a $700,000 Stowe ski property with $175,000 in cost seg deductions at 37% federal, the year-one federal savings are $64,750. The VT state timing penalty at an 8% effective rate on $175,000 of disallowed deductions is approximately $14,000 in year one — meaningful but recovered over subsequent years. Net year-one benefit: $50,750+." },
      { type: "faq", question: "Are there specific STR regulations in Stowe or Killington?", answer: "Vermont does not have a statewide STR licensing requirement. Municipalities regulate STRs independently. Stowe has adopted STR registration requirements. Killington and surrounding towns have varying levels of regulation. The Vermont Department of Taxes requires all STR operators to register for meals and rooms tax collection. Verify local requirements for your specific property location." },
      { type: "cta", title: "Estimate Your Vermont STR Tax Savings", text: "Vermont's premium ski markets generate strong revenue and large federal cost seg deductions despite the state timing penalty. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── New Hampshire ────────────────────────────────────────────────────────
  {
    slug: "str-taxes-new-hampshire",
    title: "Short-Term Rental Taxes in New Hampshire: What Investors Need to Know in 2025",
    description: "New Hampshire has NO state income tax on wages or rental income, making it one of the best Northeast states for STR investing. White Mountains, Lake Winnipesaukee, and ski resorts anchor the market.",
    publishedAt: "2026-03-14",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "New Hampshire", "White Mountains", "Lake Winnipesaukee", "North Conway", "state taxes", "cost segregation", "no income tax"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-new-hampshire.jpg",
    seo: {
      title: "Short-Term Rental Taxes in New Hampshire 2025: White Mountains & Lakes Region | Abode",
      description: "New Hampshire has NO state income tax on rental income — making it the most tax-favorable state in the Northeast for STR investors. Here's what NH investors pay and how to maximize cost seg benefits.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-new-hampshire",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does New Hampshire have a state income tax on rental income?", acceptedAnswer: { "@type": "Answer", text: "No. New Hampshire does not have a state personal income tax on wages, salaries, or rental income. The state's only individual income tax (the Interest and Dividends Tax on dividends and interest income) was fully phased out as of January 1, 2025. NH STR investors only pay federal income taxes on rental income." } },
          { "@type": "Question", name: "Does New Hampshire conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "New Hampshire has no personal income tax, so there is no state conformity issue for individual STR investors. The full 100% federal bonus depreciation benefit applies without any NH state adjustment, making New Hampshire uniquely advantageous in the Northeast region." } },
          { "@type": "Question", name: "What rooms and meals tax applies to New Hampshire STRs?", acceptedAnswer: { "@type": "Answer", text: "New Hampshire charges an 8.5% rooms and meals tax on short-term rental accommodations. This is the primary STR-related tax in NH. Unlike many states, there is no local option rooms tax in New Hampshire — the 8.5% rate is uniform statewide." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "success", title: "New Hampshire: Best State Tax Environment in the Northeast", text: "No state income tax on rental income. No bonus depreciation conformity issue. 8.5% rooms and meals tax (uniform statewide, no local add-ons). New Hampshire is the most tax-favorable state for STR investors in the entire Northeast region." },
      { type: "paragraph", text: "New Hampshire is the standout state tax environment for STR investing in the Northeast. With no state personal income tax on rental income and no local income tax, NH investors keep the full federal benefit of cost segregation without any state-level offset. The White Mountains, Lake Winnipesaukee, the ski resorts (Cannon, Loon, Bretton Woods, Wildcat), and Seacoast area anchor a four-season STR market." },
      { type: "heading", level: 2, text: "No New Hampshire State Income Tax: The Major Advantage", id: "no-income-tax" },
      { type: "paragraph", text: "New Hampshire is one of only nine states with no broad-based personal income tax. The state's Interest and Dividends Tax — which taxed investment income but not wages or rental income — was fully phased out effective January 1, 2025. As of 2025, New Hampshire individual residents pay zero state income tax on any form of income, including net rental income from STR properties." },
      { type: "paragraph", text: "This means NH STR investors benefit from 100% federal bonus depreciation with no state-level addback requirement. A $200,000 federal bonus depreciation deduction saves $74,000 in federal taxes at 37% — with zero state income tax impact. Compared to Vermont investors facing an 8.75% addback penalty, New Hampshire investors are approximately $17,500 better off on the same size cost seg deduction." },
      { type: "heading", level: 2, text: "New Hampshire Rooms and Meals Tax", id: "rooms-meals-tax" },
      { type: "paragraph", text: "New Hampshire's 8.5% rooms and meals tax is the primary transaction tax on STR rentals. Unlike most states, New Hampshire has no local option rooms tax — the 8.5% rate is the same statewide, from North Conway to Portsmouth to Laconia. This simplicity is an advantage for STR operators who don't need to navigate multiple jurisdictional rates." },
      { type: "table", headers: ["Market", "County", "NH Rooms & Meals Tax", "Local Tax", "Total"],
        rows: [
          ["North Conway", "Carroll County", "8.5%", "None", "8.5%"],
          ["Laconia / Lake Winnipesaukee", "Belknap County", "8.5%", "None", "8.5%"],
          ["Lincoln / Loon Mountain", "Grafton County", "8.5%", "None", "8.5%"],
          ["Bretton Woods / Mount Washington Hotel", "Coos County", "8.5%", "None", "8.5%"],
          ["Franconia / Cannon Mountain", "Grafton County", "8.5%", "None", "8.5%"],
          ["Hampton Beach", "Rockingham County", "8.5%", "None", "8.5%"],
        ]
      },
      { type: "heading", level: 2, text: "Top New Hampshire STR Markets", id: "top-markets" },
      { type: "paragraph", text: "<strong>North Conway / White Mountains:</strong> North Conway serves as the commercial hub for the White Mountains, home to skiing at Cranmore, Attitash, Wildcat, and a short drive to Cannon and Bretton Woods. The area draws hikers, leaf peepers, skiers, and outlet shoppers. Mount Washington — the highest peak in the Northeast — drives significant adventure tourism. STR demand is genuinely four-season." },
      { type: "paragraph", text: "<strong>Lake Winnipesaukee / Lakes Region:</strong> New Hampshire's Lakes Region, centered on Lake Winnipesaukee (the largest lake in the state), is a summer tourism stronghold. Boating, waterskiing, fishing, and the general lake escape draw families from the Boston metro area. Laconia, Wolfeboro, and Meredith are the primary lake towns. Lakefrontinvestment properties carry premium values and strong summer occupancy." },
      { type: "paragraph", text: "<strong>Hampton Beach / Seacoast:</strong> New Hampshire has only 18 miles of coastline, but Hampton Beach is a highly developed summer beach destination. STR demand is intensely seasonal (peak July–August) but very strong within season. Hampton Beach benefits from proximity to the Boston and Portland, ME metros." },
      { type: "heading", level: 2, text: "Cost Segregation in New Hampshire: Maximum Benefit", id: "cost-seg-nh" },
      { type: "paragraph", text: "New Hampshire offers the maximum possible cost segregation benefit in the Northeast because there is no state income tax offset. Every dollar of federal bonus depreciation deduction saves only federal taxes — and the savings are 100% retained. A $600,000 North Conway ski property with $160,000 in cost seg deductions at 37% federal generates $59,200 in year-one savings with no state-level dilution whatsoever." },
      { type: "faq", question: "Does New Hampshire require STR licensing?", answer: "New Hampshire does not have a statewide STR licensing requirement for individuals. However, STR operators must register with the NH Department of Revenue Administration to collect and remit the rooms and meals tax. Some municipalities (particularly North Conway and Hampton Beach area towns) have adopted local STR registration or zoning requirements. Always verify with your specific municipality before operating." },
      { type: "cta", title: "Estimate Your New Hampshire STR Tax Savings", text: "New Hampshire's no-income-tax environment delivers the full federal benefit with zero state offset. The best cost seg ROI in the Northeast. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Maine ────────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-maine",
    title: "Short-Term Rental Taxes in Maine: What Investors Need to Know in 2025",
    description: "Maine has a 5.8–7.15% graduated income tax, does NOT conform to federal bonus depreciation, and charges 9% sales tax on lodging. Bar Harbor, Kennebunkport, and Acadia National Park anchor the market.",
    publishedAt: "2026-03-14",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Maine", "Bar Harbor", "Acadia", "Kennebunkport", "Boothbay Harbor", "state taxes", "cost segregation", "bonus depreciation"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-maine.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Maine 2025: Bar Harbor, Acadia & Coastal Maine | Abode",
      description: "Maine does NOT conform to federal bonus depreciation and has a 5.8–7.15% income tax plus 9% sales tax on lodging. Here's what Maine STR investors pay in Bar Harbor and coastal Maine.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-maine",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Maine conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "No. Maine does not conform to federal bonus depreciation. Maine requires investors to add back the federal bonus depreciation deduction and use standard MACRS depreciation on state returns. Given Maine's top income tax rate of 7.15%, the state cost of the non-conformity is material for large cost seg deductions." } },
          { "@type": "Question", name: "What is Maine's income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Maine has a graduated income tax with rates from 5.8% to 7.15%. The top 7.15% rate applies to taxable income over approximately $53,150 for single filers and $106,350 for joint filers — a relatively low threshold that means most STR investors with meaningful rental income will pay at or near the top rate." } },
          { "@type": "Question", name: "What sales tax applies to Maine STR rentals?", acceptedAnswer: { "@type": "Answer", text: "Maine charges a 9% sales tax on short-term lodging accommodations — one of the highest lodging sales tax rates in New England. Maine does not have local option lodging taxes, so the 9% rate applies uniformly statewide, from Bar Harbor to Kennebunkport to Boothbay Harbor." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "warning", title: "Maine Bonus Depreciation Alert", text: "Maine does NOT conform to federal bonus depreciation. Maine requires investors to add back federal bonus dep and use standard MACRS depreciation on state returns. Maine's top income tax rate of 7.15% amplifies the state timing penalty. Plan with a Maine CPA who understands STR depreciation." },
      { type: "paragraph", text: "Maine's coastal STR market is one of the most distinctive in the Northeast, anchored by Acadia National Park and Bar Harbor, the Kennebunk/Kennebunkport resort area, Boothbay Harbor, and Old Orchard Beach. The state's tax environment is challenging: non-conformity to bonus depreciation, a top income tax rate of 7.15%, and a 9% sales tax on lodging. Yet Maine's unique market characteristics — the rugged coast, the national park, the authentic fishing village character — sustain premium STR demand." },
      { type: "heading", level: 2, text: "Maine State Income Tax on Rental Income", id: "state-income-tax" },
      { type: "paragraph", text: "Maine's graduated income tax reaches its top rate of 7.15% at relatively modest income levels (approximately $53,150 for single filers). This means nearly all STR investors with meaningful rental income pay at the top rate. Maine begins with federal AGI and makes Maine-specific modifications, including the depreciation addback for bonus depreciation." },
      { type: "heading", level: 2, text: "Maine's 9% Lodging Sales Tax", id: "sales-tax" },
      { type: "paragraph", text: "Maine's 9% sales tax on short-term lodging is one of the highest in New England (Connecticut is 15% room occupancy, but Maine's 9% is high for a sales tax rate). The tax applies uniformly statewide with no local option additions, simplifying compliance across Maine's many coastal and mountain STR locations. STR operators must register with the Maine Revenue Services to collect and remit." },
      { type: "heading", level: 2, text: "Top Maine STR Markets", id: "top-markets" },
      { type: "table", headers: ["Market", "County", "Primary Season", "Key Demand Driver"],
        rows: [
          ["Bar Harbor / Acadia National Park", "Hancock County", "Summer (peak), shoulder", "Acadia NP (3.5M annual visitors)"],
          ["Kennebunkport / Kennebunk", "York County", "Summer, some year-round", "Historic resort town, Bush compound fame"],
          ["Boothbay Harbor", "Lincoln County", "Summer", "Classic Maine fishing village, whale watching"],
          ["Old Orchard Beach", "York County", "Summer (peak)", "French-Canadian beach tourism, amusement pier"],
          ["Camden / Rockland", "Knox County", "Summer, fall foliage", "Windjammer cruises, art galleries"],
          ["Portland (city)", "Cumberland County", "Year-round growing", "James Beard dining scene, arts, Old Port"],
        ]
      },
      { type: "heading", level: 2, text: "Acadia National Park and Bar Harbor", id: "bar-harbor-market" },
      { type: "paragraph", text: "Acadia National Park draws approximately 3.5 million visitors annually, making Bar Harbor one of the most visited places in New England. The park encompasses most of Mount Desert Island, and Bar Harbor serves as the primary visitor services hub. The STR market here is intensely seasonal: the Park Loop Road officially opens for the season in spring, and the high season runs June through October, with fall foliage in early October a particular peak period." },
      { type: "paragraph", text: "Bar Harbor properties command premium rates during peak season — quality 3–4 bedroom homes can generate $150,000–$250,000 in annual gross revenue with strong occupancy during the June–October window. The challenge is the relatively short season; winter months see dramatically lower occupancy. Properties with distinctive coastal views or within walking distance of Bar Harbor's waterfront village command the strongest performance." },
      { type: "heading", level: 2, text: "Kennebunkport: Premium Coastal Maine", id: "kennebunkport-market" },
      { type: "paragraph", text: "Kennebunkport is Maine's most upscale traditional resort town, known for the Bush family compound, a charming historic village center (Dock Square), and pristine beaches. STR properties in Kennebunkport range from converted historic New England homes to modern oceanfront cottages. The market has a premium demographic and commands among the highest nightly rates in Maine outside of Bar Harbor." },
      { type: "heading", level: 2, text: "Cost Segregation in Maine: High-Season Revenue Markets", id: "cost-seg-maine" },
      { type: "paragraph", text: "Maine's non-conformity to bonus depreciation and 7.15% top rate create a material year-one state timing penalty. For a $600,000 Bar Harbor property with $145,000 in cost seg deductions at 37% federal, the year-one federal savings are $53,650. The Maine state timing penalty at 7.15% on the $145,000 addback is approximately $10,368 in year one — recovered over subsequent years as MACRS depreciation on state returns exceeds federal (since federal already took it all in year one). Net year-one benefit: $43,282." },
      { type: "faq", question: "Does Maine have STR regulations or licensing requirements?", answer: "Maine does not have a statewide STR licensing law for most residential properties. The Maine Revenue Services requires registration for rooms tax collection. Some municipalities have adopted STR regulations — Portland has STR licensing requirements, and Bar Harbor has been actively managing STR growth in response to housing concerns. Always verify local ordinances for your specific property location." },
      { type: "cta", title: "Estimate Your Maine STR Tax Savings", text: "Maine's premium coastal markets generate strong revenue. Even with state non-conformity, federal cost seg savings are substantial. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Maryland ─────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-maryland",
    title: "Short-Term Rental Taxes in Maryland: What Investors Need to Know in 2025",
    description: "Maryland has a 2–5.75% state income tax plus a county income tax (1.75–3.2%), and does NOT fully conform to federal bonus depreciation. Ocean City, Deep Creek Lake, and the Eastern Shore are the top STR markets.",
    publishedAt: "2026-03-15",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Maryland", "Ocean City", "Deep Creek Lake", "Eastern Shore", "state taxes", "cost segregation", "bonus depreciation", "county income tax"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-maryland.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Maryland 2025: Ocean City, Deep Creek Lake & More | Abode",
      description: "Maryland does NOT fully conform to federal bonus depreciation and has a combined state + county income tax that can reach nearly 9%. Here's the complete Maryland STR investor guide.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-maryland",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Maryland conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Maryland does not fully conform to federal bonus depreciation. Maryland requires investors to add back a portion of the federal bonus depreciation deduction on state returns, using an alternative depreciation schedule. The specifics have varied by year — consult a Maryland CPA for current year conformity rules." } },
          { "@type": "Question", name: "What is Maryland's combined income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Maryland has a state income tax of 2–5.75% (top rate at income over $250,000) PLUS a mandatory county income tax ranging from 1.75–3.2% depending on the county of residence. The combined state + county top rate can reach approximately 8.95% (5.75% state + 3.2% county maximum) for Montgomery County residents." } },
          { "@type": "Question", name: "What hotel taxes apply to Ocean City, Maryland STR rentals?", acceptedAnswer: { "@type": "Answer", text: "Worcester County (Ocean City) has one of Maryland's higher hotel tax structures. Ocean City charges approximately 6.5% in county hotel tax on top of Maryland's state sales tax on accommodations. Total effective lodging tax rates in Ocean City typically run 9–11% depending on how the various layers are applied." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "warning", title: "Maryland Bonus Depreciation and County Income Tax Alert", text: "Maryland does NOT fully conform to federal bonus depreciation. Additionally, Maryland imposes a mandatory county income tax (up to 3.2%) on top of the state income tax, creating combined marginal rates that can approach 9%. Work with a Maryland CPA to model the combined impact." },
      { type: "paragraph", text: "Maryland's STR market features Ocean City (the mid-Atlantic's largest beach resort), Deep Creek Lake (Maryland's only freshwater resort area), and the Eastern Shore communities along the Chesapeake Bay. The state's tax environment is complex: non-full conformity to bonus depreciation, a two-layer income tax structure (state + mandatory county income tax), and varied hotel tax rates across the state's 23 counties." },
      { type: "heading", level: 2, text: "Maryland's Two-Layer Income Tax Structure", id: "state-county-income-tax" },
      { type: "paragraph", text: "Maryland is unusual in that it imposes a mandatory county income tax on top of the state income tax, collected and remitted together on the Maryland state return. The state income tax is 2–5.75% (with the top 5.75% rate applying to income over $250,000 for joint filers). The county income tax is set by each county and ranges from 1.75% (several lower-tax counties) to 3.2% (Montgomery County and Prince George's County)." },
      { type: "paragraph", text: "For an investor residing in Montgomery County: combined state + county top rate = 5.75% + 3.2% = 8.95%. For Garrett County (Deep Creek Lake area): 5.75% + 2.65% = 8.40%. These combined rates are among the highest for a state without the 'brand name' reputation for high taxes." },
      { type: "heading", level: 2, text: "Maryland's Bonus Depreciation Non-Conformity", id: "bonus-dep-md" },
      { type: "paragraph", text: "Maryland does not fully conform to federal bonus depreciation. The state requires investors to add back a portion of the federal bonus depreciation deduction and use an alternative depreciation method on state returns. The specific current-year rules can change — consult a Maryland CPA for the applicable treatment in your tax year. At combined state + county rates that can approach 9%, the state timing cost of the addback is significant." },
      { type: "heading", level: 2, text: "Hotel Taxes by Maryland Market", id: "hotel-taxes" },
      { type: "table", headers: ["Market / County", "State Sales Tax", "County Hotel Tax", "Estimated Total"],
        rows: [
          ["Ocean City (Worcester County)", "6%", "6.5%", "~9–11%"],
          ["Deep Creek Lake (Garrett County)", "6%", "4%", "~10%"],
          ["Annapolis (Anne Arundel County)", "6%", "7%", "~13%"],
          ["Frederick / Middletown (Frederick County)", "6%", "5%", "~11%"],
          ["Eastern Shore (Talbot County — St. Michaels)", "6%", "5%", "~11%"],
          ["Assateague Island (Worcester County)", "6%", "6.5%", "~9–11%"],
        ]
      },
      { type: "heading", level: 2, text: "Top Maryland STR Markets", id: "top-markets" },
      { type: "paragraph", text: "<strong>Ocean City:</strong> Maryland's premier beach resort and one of the most visited beach destinations on the East Coast. Ocean City draws millions of visitors annually from the DC metro area, Baltimore, and the broader Mid-Atlantic region. The Boardwalk and beachfront are anchor attractions. STR properties range from modest Ocean City condos to large beach block homes. The market is intensely seasonal (peak June–August) but generates very high peak-season revenue." },
      { type: "paragraph", text: "<strong>Deep Creek Lake:</strong> Maryland's only significant freshwater resort area, located in Garrett County in the far western panhandle of the state. Deep Creek Lake draws visitors for boating, water sports, fishing, and winter skiing at Wisp Resort. An increasingly popular four-season market with growing STR supply. Properties with lakefront access command the highest rates and occupancy." },
      { type: "paragraph", text: "<strong>Eastern Shore (St. Michaels, Chestertown, Oxford):</strong> The Maryland Eastern Shore along the Chesapeake Bay offers a distinctive STR market featuring historic maritime towns, water views, crabbing culture, and proximity to the DC/Baltimore metros. St. Michaels and the surrounding Talbot County area have an established boutique STR market." },
      { type: "heading", level: 2, text: "Cost Segregation in Maryland: Important Despite State Complexity", id: "cost-seg-md" },
      { type: "paragraph", text: "Despite Maryland's complex state tax environment, federal cost segregation benefits are fully preserved and the state benefit, while timing-delayed, ultimately accrues. For a $550,000 Ocean City beach home with $130,000 in cost seg deductions at 37% federal, the year-one federal savings are $48,100. The Maryland state timing penalty at a combined 8.5% effective rate on the disallowed deductions is approximately $11,050 in year one — recovered as accelerated Maryland deductions in subsequent years." },
      { type: "faq", question: "Does Maryland require STR registration?", answer: "Maryland does not have a uniform statewide STR registration requirement. Regulations vary significantly by jurisdiction. Ocean City requires STR licensing and registration with Worcester County. Montgomery County and other major counties have their own STR ordinances. Always check the specific county and municipality requirements for your property." },
      { type: "cta", title: "Estimate Your Maryland STR Tax Savings", text: "Maryland's combined state + county income tax makes strategic cost seg planning especially important. Get your free estimate to see your year-one net benefit.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

  // ─── Delaware ─────────────────────────────────────────────────────────────
  {
    slug: "str-taxes-delaware",
    title: "Short-Term Rental Taxes in Delaware: What Investors Need to Know in 2025",
    description: "Delaware has NO state sales tax, conforms to federal bonus depreciation, and has a 2.2–6.6% income tax. Rehoboth Beach, Dewey Beach, and Bethany Beach anchor the Delaware STR market.",
    publishedAt: "2026-03-15",
    author: { name: "Abode Team", role: "Cost Segregation Specialists" },
    category: "STR Investors",
    tags: ["STR investors", "Delaware", "Rehoboth Beach", "Dewey Beach", "Bethany Beach", "state taxes", "cost segregation", "bonus depreciation", "no sales tax"],
    readTime: "8 min read",
    heroImage: "/images/blog/str-taxes-delaware.jpg",
    seo: {
      title: "Short-Term Rental Taxes in Delaware 2025: Rehoboth Beach & Coastal Delaware | Abode",
      description: "Delaware has no state sales tax and conforms to federal bonus depreciation. Here's what Delaware beach STR investors pay, lodging taxes by market, and how cost segregation works in the First State.",
      canonical: "https://www.abodecostseg.com/learn/str-taxes-delaware",
      structuredData: [
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
          { "@type": "Question", name: "Does Delaware have a state sales tax on STR rentals?", acceptedAnswer: { "@type": "Answer", text: "No. Delaware has no state sales tax, which is one of its most distinctive tax characteristics. There is no Delaware state sales tax on short-term rental revenue. However, Delaware does have a lodging tax of 8% administered at the state level on hotel and short-term rental accommodations." } },
          { "@type": "Question", name: "Does Delaware conform to federal bonus depreciation?", acceptedAnswer: { "@type": "Answer", text: "Yes. Delaware conforms to federal bonus depreciation. STR investors can take 100% bonus depreciation on eligible short-lived assets on both their federal and Delaware state returns in year one. This is a meaningful advantage compared to neighboring Maryland, New Jersey, and Pennsylvania, which do not conform." } },
          { "@type": "Question", name: "What is Delaware's income tax rate on rental income?", acceptedAnswer: { "@type": "Answer", text: "Delaware has a graduated income tax with rates from 2.2% to 6.6%. The top 6.6% rate applies to taxable income over $60,000. Most STR investors with meaningful rental income will be at or near the top rate. Delaware's conformity to federal bonus depreciation means cost segregation reduces both federal and Delaware state taxes in year one." } },
        ]},
      ],
    },
    content: [
      { type: "callout", variant: "highlight", title: "Delaware STR Tax Summary", text: "No state sales tax | Conforms to federal bonus depreciation | 2.2–6.6% graduated income tax (top at $60K) | 8% state lodging tax on STR rentals | Beach markets: Rehoboth Beach, Dewey Beach, Bethany Beach, Fenwick Island | Proximity to DC, Baltimore, Philadelphia metros" },
      { type: "paragraph", text: "Delaware occupies an unusual position in the Northeast STR landscape: no state sales tax, full conformity to federal bonus depreciation, and a premium coastal STR market at Rehoboth Beach and the surrounding Sussex County beach towns. While the state's income tax tops out at a moderate 6.6%, the combination of no sales tax and full bonus dep conformity makes Delaware one of the more investor-friendly states in the Northeast region." },
      { type: "heading", level: 2, text: "Delaware's No-Sales-Tax Advantage", id: "no-sales-tax" },
      { type: "paragraph", text: "Delaware is one of only five states with no state sales tax (alongside Montana, Oregon, New Hampshire, and Alaska). For STR investors, this means there is no additional layer of Delaware sales tax on rental revenue — unlike neighboring Maryland (6% state sales tax on lodging), New Jersey (6.625% sales tax), and Pennsylvania (6% hotel tax). Delaware does have a separate 8% lodging tax on short-term rentals, but the absence of a general sales tax layer simplifies the overall tax picture." },
      { type: "heading", level: 2, text: "Delaware Bonus Depreciation Conformity", id: "bonus-dep-de" },
      { type: "paragraph", text: "Delaware's conformity to federal bonus depreciation is a significant advantage compared to every other Northeast state covered in this guide except New Hampshire. When you take 100% bonus depreciation on cost segregation-identified assets on your federal return, the same deduction applies to your Delaware state return. This means cost segregation savings are stacked at both the federal and state level simultaneously." },
      { type: "heading", level: 2, text: "Delaware Lodging Tax and Income Tax", id: "lodging-income-tax" },
      { type: "table", headers: ["Tax Type", "Rate", "Notes"],
        rows: [
          ["Delaware lodging tax on STR rentals", "8%", "Statewide; applies to all short-term rentals"],
          ["Delaware state income tax (top rate)", "6.6%", "On income over $60,000"],
          ["Local county/city lodging taxes", "varies", "Some municipalities add local taxes on top"],
          ["Rehoboth Beach city realty transfer (on sale)", "varies", "Not a rental tax but relevant to acquisition"],
          ["No Delaware state sales tax", "0%", "No general sales tax in Delaware"],
        ]
      },
      { type: "heading", level: 2, text: "Delaware Beach STR Markets", id: "beach-markets" },
      { type: "paragraph", text: "<strong>Rehoboth Beach:</strong> Delaware's largest and most developed beach town, often called the 'Nation's Summer Capital' given its historical popularity with DC government workers and diplomats. Rehoboth Beach draws a diverse mix of families, couples, LGBTQ+ travelers, and weekend beach seekers from the DC, Baltimore, and Philadelphia metro areas. The combination of Rehoboth's 1-mile Boardwalk, excellent dining scene, and relatively easy access makes it one of the most consistently-performing Mid-Atlantic beach markets." },
      { type: "paragraph", text: "<strong>Dewey Beach:</strong> Immediately south of Rehoboth, Dewey Beach is known for a younger demographic, beach bars, and a more party-oriented atmosphere. Properties in Dewey Beach tend to be smaller (the peninsula is narrow) and highly seasonal. Very strong June–August occupancy, with a younger average guest than Rehoboth." },
      { type: "paragraph", text: "<strong>Bethany Beach and Fenwick Island:</strong> South of Dewey, Bethany Beach is known as the 'Quiet Resorts' — a more family-oriented, less commercial atmosphere than Rehoboth or Dewey. Properties here tend to be larger single-family beach homes attracting families and multi-generational groups. Fenwick Island shares a border with Ocean City, Maryland, capturing some of that market's overflow." },
      { type: "heading", level: 2, text: "Cost Segregation in Delaware: Combined Benefits", id: "cost-seg-de" },
      { type: "paragraph", text: "Delaware's full conformity to bonus depreciation combined with the 6.6% state income tax creates a clean combined benefit from cost segregation. For a $600,000 Rehoboth Beach property with $140,000 in cost seg deductions, the combined first-year benefit is: $51,800 federal (at 37%) + $9,240 Delaware state (at 6.6%) = $61,040 total first-year tax savings, against a study cost of $5,500–$8,500. The ROI on the cost segregation study itself is compelling in the year of purchase." },
      { type: "faq", question: "Does Delaware require STR registration or licensing?", answer: "Delaware does not have a statewide STR licensing requirement. Individual municipalities have their own ordinances. Rehoboth Beach has STR regulations and some reporting requirements. Sussex County has been actively managing STR growth given the significant beach market. Always verify current local requirements with the specific municipality and county for your property." },
      { type: "cta", title: "Estimate Your Delaware STR Tax Savings", text: "Delaware's no-sales-tax environment + full bonus dep conformity = strong combined cost seg ROI. Get your free estimate.", buttonText: "Get My Free Estimate", buttonHref: "/quiz" },
    ],
  },

];
